### ISSUE TITLE
`image` value from yaml gets expanded to fully qualified name, breaking local backend

### ISSUE THREAD

**Issue by thestr4ng3r** [woodpecker-ci/woodpecker#1003]
### Component

server

### Describe the bug

When parsing the `image` in a pipeline yaml, the given value is always expanded to a fully qualified docker image name very early:
https://github.com/woodpecker-ci/woodpecker/blob/3f73d5bf5338eacd3e91d937ed07a55e7398538d/pipeline/frontend/yaml/compiler/convert.go#L23

For example, if you have `image: alpine`, you will get `docker.io/library/alpine:latest`.

First, it is questionable whether this kind of expansion should be done on the server at all, as the docker or podman on the agent machine could figure this out themselves, as @6543 noted on matrix.

But second, this is a major problem for the local backend where the image value is not interpreted as a docker image, but as the name of the shell to run commands in.
Currently there is this hack in place, which tries to chop off the prefix and suffix again:
https://github.com/woodpecker-ci/woodpecker/blob/3f73d5bf5338eacd3e91d937ed07a55e7398538d/pipeline/backend/local/local.go#L65
So you pass `image: bash` and `proc.Image[18:len(proc.Image)-7]` will evaluate to `bash`. But this of course is only a very fragile workaround. For example it panics and crashes the agent as soon as you pass something like `image: /bin/bash`, which will not get anything added by the expansion.
This by itself could also be fixed by not reusing the `image` key for the shell and instead adding an additional one.

### System Info

```shell
3f73d5b
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by 6543** [comment]
:point_up: race condition :laughing:
