### ISSUE TITLE
Rename secrets to environment variables (use conceal flag)

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#1007]
WE currently have secrets and environment variables (can be set at server start). Instead I would suggest to rename secrets to environment variables and add an option to conceal environment variables which would be same to the current secrets.

This would allow us to have one way of managing those variables in ui, cli, pipeline parsing ...

**Comment by anbraten** [comment]
Would solve #362 as well

**Comment by lafriks** [comment]
But secrets are not really env variables, they are used quite differently

**Comment by anbraten** [comment]
They can be used by `from_secret`, are redacted from logs and what else?

**Comment by 6543** [comment]
they are env vars ... but with spesific propertys like sanitazed in logs before leaving the agent

**Comment by anbraten** [comment]
It would be a super hard and breaking job renaming it, but would only require one thing to maintain. But I am open for other suggestions.  

Would you just "copy" the UI / base logic from secrets?

**Comment by lafriks** [comment]
Env vars has one use case and secrets have other, only case where they use case overlaps is if they are specifically bound together in step definition. If we are talking about UI than yes they should have separate tab in settings and way more simple UI - just name and value that should be visible and editable not like secrets that you can just override with new value.

**Comment by EchedeyLR** [comment]
Could this be used to get environment variables at repository level for several pipelines instead that to pipeline level?

**Comment by anbraten** [comment]
Seems not to be wanted
