### ISSUE TITLE
How does WOODPECKER_GRPC_SECURE setting work?

### ISSUE THREAD

**Issue by alteriks** [woodpecker-ci/woodpecker#1015]
### Component

server, agent

### Describe the bug

I've been trying to run second agent with `WOODPECKER_GRPC_SECURE=true` so it could connect using TLS to server. Unfortunately I haven't found what settings should I enable on woodpecker-server.
As far as I tested - using `WOODPECKER_SERVER_CERT` and `WOODPECKER_SERVER_KEY` only forces server to use TLS for HTTP. I have verified that GRPC doesn't use those parameters.
```
openssl s_client -connect workstation:9000 -servername woodpecker-server
```
Woodpecker-agent returns in logs:
```
woodpecker-agent  | {"level":"error","error":"rpc error: code = Unavailable desc = connection error: desc = \"transport: authentication handshake failed: tls: first record does not look like a TLS handshake\"","time":"2022-07-06T19:07:11Z","message":"grpc error: done(): code: Unavailable: rpc error: code = Unavailable desc = connection error: desc = \"transport: authentication handshake failed: tls: first record does not look like a TLS handshake\""}
```

I've also tried using nginx as remote proxy for grpc with little success

```
server {

  listen              9444 ssl http2;
  server_name         woodpecker-server;
  ssl_certificate     ssl/woodpecker-server.crt;
  ssl_certificate_key ssl/woodpecker-server.key;
  ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers         HIGH:!aNULL:!MD5;
  keepalive_timeout   70;

  default_type  application/octet-stream;

  location / {
    grpc_pass grpc://woodpecker-grpc;
  }
}
upstream woodpecker-grpc {
  server 127.0.0.1:9000 fail_timeout=3;
}
```
After restarting agent with new setting `WOODPECKER_SERVER=woodpecker-server:9444` agent is being registered by server:
https://woodpecker-server/api/queue/info
```
{
    "pending": null,
    "waiting_on_deps": null,
    "running": null,
    "stats": {
        "worker_count": 2,
        "pending_count": 0,
        "waiting_on_deps_count": 0,
        "running_count": 0,
        "completed_count": 0
    },
    "Paused": false
}
```

Unfortunately even though agent doesn't give any errors. New jobs aren't started and all I get is `This step hasn't started yet.`

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"0.15.3"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by anbraten** [comment]
We added some hint for caddy: https://woodpecker-ci.org/docs/next/administration/proxy#caddy

In general you should be able to put the grpc port behind a reverse proxy and enable `WOODPECKER_GRPC_SECURE`.

**Comment by 6543** [comment]
@alteriks do you have a suggestion how to improve the docs to make this more clear?

https://woodpecker-ci.org/docs/next/administration/agent-config#woodpecker_grpc_secure
