### ISSUE TITLE
GitLab token expires now

### ISSUE THREAD

**Issue by dsanader** [woodpecker-ci/woodpecker#1019]
### Component

server

### Describe the bug

Hello,

You can't opt out from expiring tokens in GitLab on newer versions[^1].

Unfortunately, refreshing token seems not be supported in go-gitlab yet[^2].

The workaround for me now, is logging out regularly from woodpecker and pushing empty commits to trigger builds.

[^1]: https://docs.gitlab.com/ee/integration/oauth_provider.html#access-token-expiration
[^2]: https://github.com/xanzy/go-gitlab/issues/1172

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-313e72e5"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by 6543** [comment]
> Closing this issue due to no response.

upstream issue got closed ... 

from woodpecker side we just need to implement the Refresher interface for gitlab
https://github.com/woodpecker-ci/woodpecker/blob/42c745362b11f09d3e397c102b78c4bf0c664f3a/server/remote/remote.go#L96-L101

**Comment by dsanader** [comment]
Back from vacation.

Couldn't get it to work with the latest state of the feature branch.

Getting messages like these in the server logs :

```json
{"level":"error","error":"OAuthError: Refresh: no existing Token",
"caller":"/home/dsanader/code/6543-forks/woodpecker/server/router/middleware/token/token.go:59",
"message":"refresh oauth token of user 'dsanader' failed"}
```

Doesn't seem to be related to the token issue, but jobs aren't being picked up by the agents and stay in pending state.

**Comment by dsanader** [comment]
Hello,

After a bit of tinkering in `server/remote/gitlab/gitlab.go`, I found out that the token was indeed empty in the Refresher func. Injecting in the transport seems to improve the situation.

```diff
@@ -149,11 +151,14 @@ func (g *Gitlab) Refresh(ctx context.Context, user *model.User) (bool, error) {
        config := g.oauth2Config()
        config.RedirectURL = ""

-       trans := &oauth2.Transport{Config: config, Transport: &http.Transport{
+       trans := &oauth2.Transport{Config: config, Token: &oauth2.Token{AccessToken: user.Token, RefreshToken: user.Secret, Expiry: time.Unix(user.Expiry, 0)}, Transport: &http.Transport{
                TLSClientConfig: &tls.Config{InsecureSkipVerify: g.SkipVerify},
                Proxy:           http.ProxyFromEnvironment,
        }}
```

**Comment by 6543** [comment]
added your diff

**Comment by 6543** [comment]
@dsanader can you verify tag `pull_1031` does solve it?

**Comment by dsanader** [comment]
It almost completely fixes the GitLab token validity issues for me.

I had a few glitches in the context of merge requests events.

Git cloning was not authorized when merging to the main repo on the first run. Hitting the restart button was enough to trigger a successful build.

I haven't tracked it down yet, but I guess Refresh might not be called every time in some cases.

Will report back with more detailed info.
