### ISSUE TITLE
Improve Visibility of Errors on Invalid CI Config Yaml

### ISSUE THREAD

**Issue by benyanke** [woodpecker-ci/woodpecker#1045]
### Clear and concise description of the problem

I am using Woodpecker with Gitea using webhooks to trigger CI runs on every push/commit.

Currently, if a commit contains invalid CI yaml, it silently fails to run the CI job, unless you look at the webhook configuration (which may not be available to lower-privileged users) and is not obvious unless you know what you're looking for.

The following screenshot was taken from `https://gitea.example.com/[project]/[repo]/settings/hooks/[hook-id]`:

![image](https://user-images.githubusercontent.com/4274911/180655531-66687426-4cf6-4cf1-9c94-2ac66c0a82cf.png)

However, if you're not sure what you're looking for, it looks like Ci just silently failed.

### Suggested solution

I would propose that a far more self-evident solution would be creating a job entry in the CI jobs list, but marking it as failed, and also providing failed feedback to the git repo to turn the build red, etc. This fits far more closely in the mental model of how a developer would expect a CI system to interact: fail the build if it couldn't complete successfully due to bad files in the repo.

This is similar to how gitlab CI approaches the problem. Below is an example of one of my projects - the bottom entry is a normal successful run, and then I intentionally committed invalid yaml, which generated the top entry in CI run entries.

![image](https://user-images.githubusercontent.com/4274911/180655720-6b14f78c-f983-4c98-b25d-a4a23a84d351.png)

Similarly, it's treated like any other failed job, and marks the commit as having had CI not pass (instead of gitea's solution of not creating any CI runs in the interface).

![image](https://user-images.githubusercontent.com/4274911/180655778-29845948-4f1d-468f-8243-d35c5be4d7cb.png)

The run details has more specific information as well.

![image](https://user-images.githubusercontent.com/4274911/180655825-a3f0d37b-7d2c-4162-89b3-840a0636d5f4.png)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by anbraten** [comment]
linking #811 & #812

**Comment by anbraten** [comment]
I absolutely agree. I think it was working before some time ago and just has a bug which prevents the job from being created.
