### ISSUE TITLE
Fatal error during execution: unexpected signal 

### ISSUE THREAD

**Issue by ghost** [woodpecker-ci/woodpecker#1049]
### Component

server

### Describe the bug

After I start the server, it stays online sometime, but then it hangs with veeery long backtrace (applied here)
Probably not 'occasional', but rather when I authorize

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"0.15.3"}
```

No docker-compose, no kubernetes, just shell and systemd, u know

### Additional context

[logs.txt](https://github.com/woodpecker-ci/woodpecker/files/9207290/logs.txt)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by bobbyMilly** [comment]
to be honest, it is the only thing that is stopping me from using Woodpecker CI (can't guess of any other, except make my own)

**Comment by bobbyMilly** [comment]
nah, not it is not important. i dont have anything to host it on, loel

**Comment by 6543** [comment]
I thin it has to do how you start woodpecker.

It needs `export GODEBUG=netdns=go`

**Comment by 6543** [comment]
Well please comment if my sol. does not solve it and I'll reopen this issue
