### ISSUE TITLE
[Important] Limit secret access to plugins only

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#1071]
similar to the images filter for secrets, add a checkbox to only inject secret if step is exec as plugin.

this ensure only the intended entry-point do get the secrets to handle.

this does help if a plugin is not based from scratch image but do contain an shell that could be used.

---
bounty: 50$

**Comment by anbraten** [comment]
I don't see how this could protect secrets? You could just create a plugin (normal docker image) that leaks the secrets, couldn't you?

**Comment by lafriks** [comment]
this could be helpful in combination with trusted images ex. currently setting trusted image `woodpeckerci/plugin-git` you can still use:
```
image woodpeckerci/plugin-git
commands:
  - echo ${SECRET}
```

adding such option would prevent that

**Comment by 6543** [comment]
```
image: woodpeckerci/plugin-git
commands:
  - echo ${SECRET} | base58
  ```
-> it's a trusted image
-> secret is leaked

**Comment by 6543** [comment]
bounty: 50$
