### ISSUE TITLE
single sign on (SSO) / LDAP

### ISSUE THREAD

**Issue by KiaraGrouwstra** [woodpecker-ci/woodpecker#1074]
### Clear and concise description of the problem

it would be great if, as an organization, one could log users in to their Woodpecker CI instance using their existing tools for this.

### Suggested solution

this could including using LDAP or single sign on (SSO), think OIDC, SAML, OAuth2.

### Additional context

has anything been done in this direction?

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by anbraten** [comment]
As Woodpecker needs a forge (Github, Gitlab, ...) anyways it is using OAuth2 to authenticate against those forges. Most forges do support the methods you asked for, so this should already be possible.

**Comment by KiaraGrouwstra** [comment]
hm. allegedly OAuth is [vulnerable to an attack](https://en.wikipedia.org/wiki/OpenID#OpenID_Connect_(OIDC)) that OIDC resolves.
perhaps that might make OIDC relevant as an OAuth alternative for Woodpecker as well?

**Comment by anbraten** [comment]
I don't see how the login to Woodpecker is affected by this. 

For authentication steps with OIDC we started a discussion in https://github.com/woodpecker-ci/woodpecker/issues/1126
