### ISSUE TITLE
Customisable theming

### ISSUE THREAD

**Issue by tecosaur** [woodpecker-ci/woodpecker#1079]
### Clear and concise description of the problem

It could be rather nice to be able to switch out the theme used by Woodpecker.

### Suggested solution

It would be great if one could provide an alternative set of colours/styles (via a `theme.css` file) to be used.

### Additional context

This issue has been spun off from https://github.com/woodpecker-ci/woodpecker/issues/468#issuecomment-1207185270

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by silverwind** [comment]
All colors should be extracted to CSS variables on the `:root` node. This will make designing custom color themes a breeze.

**Comment by mvdkleijn** [comment]
I would also suggest that an index of sorts be made available for themes, similar to plugins.
