### ISSUE TITLE
Manually trigger pipeline on latest commit

### ISSUE THREAD

**Issue by theoparis** [woodpecker-ci/woodpecker#1092]
### Clear and concise description of the problem

After my server went offline and I made a new commit, it won't run the pipeline on the latest commit because It didn't receive the webhook. I need a way to manually re-trigger the webhook now and I can't find a feature that can do this...

### Suggested solution

**Trigger Pipeline** button with commit/branch id

### Alternative

Pushing a random commit just to get it to trigger (not a good idea)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by theoparis** [comment]
Oops, i think #83 means this  is a duplicate question.

**Comment by anbraten** [comment]
#93 will solve it. Its definitely often requested and still on the roadmap 😉
