### ISSUE TITLE
cli errors on exec tutorial example

### ISSUE THREAD

**Issue by KiaraGrouwstra** [woodpecker-ci/woodpecker#1099]
### Component

cli

### Describe the bug

- try the [tutorial](https://woodpecker-ci.org/docs/intro) with an abridged example:
```
# .woodpecker.yml
pipeline:
  build:
    image: debian
    commands:
      - echo "This is the build step"
```
- run `woodpecker-cli exec`
- find error:
```
8:13PM ??? github.com/woodpecker-ci/woodpecker/cli/common/zerologger.go:20 > LogLevel = trace
# .woodpecker.yml
8:13PM ERR github.com/woodpecker-ci/woodpecker/pipeline/backend/docker/docker.go:196 > could not kill container 'woodpecker_stage_0' error="Error response from daemon: Cannot kill container: woodpecker_step_0: Container 6535db335da05234705a4c39e4103dd8c6825c75925060953c87f31f617deec0 is not running"
```

### System Info

```shell
- woodpecker-cli version dev
- Docker version 20.10.17, build 100c70180f
- Arch Linux
```

### Additional context

fwiw `woodpecker-cli lint` passes with `✅ Config is valid`.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by KiaraGrouwstra** [comment]
fortunately i can no longer reproduce this :)

**Comment by 6543** [comment]
might got fixed along the way ;)
