### ISSUE TITLE
document API

### ISSUE THREAD

**Issue by KiaraGrouwstra** [woodpecker-ci/woodpecker#1101]
### Clear and concise description of the problem

it is currently hard to find how to use the REST API in the documentation

### Suggested solution

add documentation with a brief example of how to use the api

### Alternative

reopen #293

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by 6543** [comment]
duplicate of  #292
