### ISSUE TITLE
Translation automation to keep translations in sync

### ISSUE THREAD

**Issue by lafriks** [woodpecker-ci/woodpecker#1105]
### Clear and concise description of the problem

Currently when adding new localization strings they will become out of sync with translated strings in other languages

### Suggested solution

Use external tool for keeping translations in sync either using external provider or self-hosted.

My proposal would be to use open source software Weblate for this. They also provide free hosted option for libre projects:
https://weblate.org/en/hosting/
![attels](https://user-images.githubusercontent.com/165205/184532449-7659186f-5ebc-47b6-a049-b51905711f88.png)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by lafriks** [comment]
I tested Weblate on my company self-hosted instance and everything was detected automatically and current translations was imported without problems. Also it has built-in automations to add webhooks to github that will automatically fetch changes on push to master

**Comment by anbraten** [comment]
https://translate.woodpecker-ci.org/projects/woodpecker-ci/ui/

**Comment by lafriks** [comment]
Can't seem to register there (did not receive confirmation email)

**Comment by anbraten** [comment]
> Can't seem to register there (did not receive confirmation email)

Sorry, we haven't configured the email settings properly yet.

**Comment by lafriks** [comment]
Please set me reviewer rights for Latvian language when setup is done 😉

**Comment by anbraten** [comment]
@lafriks I configured the mail settings for weblate. You should be able to register now.

**Comment by lafriks** [comment]
thanks, registered
