### ISSUE TITLE
Allow user to set language

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#1109]
### Clear and concise description of the problem

As a user I may want to select a language in Woodpecker which isn't the language my Browser is set to.

### Suggested solution

Add some language selection in the user details screen `/user` (clicking on the user icon).

### Additional context

follow up of #258 

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by lexyd** [comment]
@anbraten I would love to work on this, is there a design file?

**Comment by anbraten** [comment]
We don't have any design files for this feature  yet (and in general 🙈). I would go with a simple dropdown. Or maybe with some flags you could click on 🤔

I would suggest, one option should be an automatic mode selected by default. This mode should be using the browsers language as it is currently the case.

**Comment by lexyd** [comment]
@anbraten I have designed a proposed nav bar with the language included. This component can be added where needed.

<img width="1527" alt="Updated Nav bar to show language" src="https://user-images.githubusercontent.com/17413130/185930349-c90b41a1-09bf-43b3-9a14-cc7358fc9eac.png">
.
