### ISSUE TITLE
Does woodpecker support builds based on files changeset

### ISSUE THREAD

**Issue by iamsudip** [woodpecker-ci/woodpecker#112]
Please refer to this: https://github.com/microadam/drone-config-changeset-conditional/issues/20

Is there any way I can enable it for our installation?

**Comment by laszlocph** [comment]
Hello @iamsudip 

The 0.8 line did not have that feature, nor it is currently available in Woodpecker.

Technically it is not too difficult to implement, as git has the changeset information for every commit. I created this issue to track this feature: https://github.com/laszlocph/woodpecker/issues/87

**Comment by iamsudip** [comment]
@laszlocph Can I expect a timeline? I see, you are a sole maintainer of this project, If you can't ensure a timeline, can you point me to the part of code where this can be implemented, I'll see if I can implement?

**Comment by laszlocph** [comment]
This is where the webhook from Github arrives: https://github.com/laszlocph/woodpecker/blob/bc80063ccb0dee901954893491a7635293497872/server/hook.go#L75

It's a change that has to trickle through many parts of the system. The internal representation of the build also needs to know about the changeset and not generate build steps according to this new condition:

https://github.com/laszlocph/woodpecker/blob/bc80063ccb0dee901954893491a7635293497872/server/hook.go#L255
https://github.com/laszlocph/woodpecker/blob/bc80063ccb0dee901954893491a7635293497872/server/hook.go#L255
https://github.com/laszlocph/woodpecker/blob/e2801e82737ccef0b771a194bfb5731e3f1a838d/cncd/pipeline/pipeline/frontend/yaml/constraint_test.go

I can't promise a timeline, just assure you that I want to have this feature too and it will arrive.

**Comment by sudip-moengage** [comment]
Can I do it through a plugin? I'm not proficient in go. Can you tell me how can I achieve this by writing a plugin in other language? @laszlocph

**Comment by laszlocph** [comment]
The problem is that when the plugin gets the control, the build has already started. You can fail the build based on git changeset at that point, but the build will show up as a failed build.

**Comment by anbraten** [comment]
General support for path conditions added by #174 and #235
