### ISSUE TITLE
Avatar image not shown in UI when connected to Github Enterpise

### ISSUE THREAD

**Issue by windsource** [woodpecker-ci/woodpecker#1132]
### Component

web-ui

### Describe the bug

I am using Woodpecker connected to Github Enterpise which works fine except that the avatar images in the UI are broken. The link seems to be OK but no cookie is passed which is probably required by our closed Github Enterpise instance. The link to the image looks like `https://ghe.example.com/avatars/u/34?` which works in another browser tab when logged on to Github Enterpise but opening that link in a private tab redirects to login.

![grafik](https://user-images.githubusercontent.com/13716595/186933508-68239c47-9734-40a3-8b8c-0e918aefeee3.png)

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"0.15.3"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by 6543** [comment]
solutions:
A. conntent proxy within woodpecker server
B. get sessin cookie from foreign site to work somehow?

**Comment by pat-s** [comment]
Likely stale, please re-open if still valid.
