### ISSUE TITLE
web UI elements not keyboard-navigatable

### ISSUE THREAD

**Issue by KiaraGrouwstra** [woodpecker-ci/woodpecker#1133]
### Component

web-ui

### Describe the bug

expanding on #1043:
there are a few web UI components that currently cannot be navigated by keyboard.
for example:

- tabs on settings page
- tabs on repo page
- cog on repo page

it would be nice if we could improve the accessibility of the UI components, similar to in #1044.

### System Info

```shell
0.15.3
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by KiaraGrouwstra** [comment]
hi there,

i still seem able to select by keyboard only part of the UI elements in woodpecker 0.15.5.
would it be possible to reopen this issue accordingly?
let me add a few illustrations using Vimium to highlight selectable elements. elements that don't have a letter appear not to be selectable by keyboard yet.

in the main view, i'm missing:

- dark toggle
- run sidebar
- repo buttons

![image](https://user-images.githubusercontent.com/3059397/196165854-bad9e2f3-13d3-4b79-886a-224e15167d45.png)

in repo view, aditionally missing:

- the cog menu
- the activity/branches tabs

![image](https://user-images.githubusercontent.com/3059397/196166342-dd9be7b1-7690-4e35-bc18-e18225c8d4ba.png)

in run view:

- the back button
- the tasks / config / changed files tabs
- the step buttons

![image](https://user-images.githubusercontent.com/3059397/196166878-41c65b91-bc2c-4136-bc0c-119fa19712c9.png)

in the settings -> secrets tab:

- the tabs
- the secret deletion buttons

![image](https://user-images.githubusercontent.com/3059397/196167270-77370092-b0c1-4031-8fab-97df3fd66ee7.png)

**Comment by anbraten** [comment]
@KiaraGrouwstra Thanks for this detailed tests. The recent changes we did will be released in 1.0 and are therefore sadly not included in 0.15.5. We would need to check it again for `next` to verify if there are still parts left. To track it, it would be awesome if you could create a new issues with your comment.

**Comment by KiaraGrouwstra** [comment]
@anbraten thanks for the quick response!
i've retested now using `next`, which appeared to yield similar results.
i've filed this now as #1280.
