### ISSUE TITLE
Allow to download pipline metadata via UI to replay with cli

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#1155]
I would be nice if I could download the metadata object via the UI as something like json to then use it to locally test with it (maybe adjusting some parts of it) via `cli exec`.

**Comment by 6543** [comment]
pipeline/frontend/metadata.go create the info from a pipeline (stored in db etc...)  and pipeline/frontend/metadata/* contains al types and is ready to be de-/serialized
