### ISSUE TITLE
Multiple spaces in logs are ignores by browsers

### ISSUE THREAD

**Issue by MarcelCoding** [woodpecker-ci/woodpecker#1161]
### Component

web-ui

### Describe the bug

If the log contains multiple spaces (e.g. pretty print table) those additional spaces are omitted by the browser.

### System Info

```shell
0.15.3
```

### Additional context

This would be solvable by wrapping the logs into an HTML `pre` tag, as it preserves additional spaces.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by anbraten** [comment]
We changed a few things related to the docs which should already solve this. You can try them by using `next` until they got officially released.

**Comment by 6543** [comment]
that's a `wontfix` for release v0.15 branch ...
... we are looking towards v1.0.0 more and more ;)
