### ISSUE TITLE
Very very minor UI nitpick: Secret events are sorted by last change instead of static order

### ISSUE THREAD

**Issue by UnlimitedCookies** [woodpecker-ci/woodpecker#1176]
### Component

web-ui

### Describe the bug

![image](https://user-images.githubusercontent.com/49200216/189342578-ce35dc36-aebf-4b70-8dae-6d7bff4bffbd.png)

In the picture, you can see that the labels are differently sorted, making it harder to compare in a highly complex setup (unlike mine). These should be sorted the same way as they are sorted in the settings menu. Maybe these could also get color-coded in the future.

### System Info

```shell
Using a relatively recent next version. So it's not relevant here.
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by 6543** [comment]
we could either sort via backend or via frontend ...
... I think we should do backend, as that would allso fix it for cli

**Comment by lafriks** [comment]
it should be sorted in backend imho. Question is should they be sorted by name or creation date? I would probably vote for name

**Comment by 6543** [comment]
just have to add an OrderBy() too
https://github.com/woodpecker-ci/woodpecker/blob/master/server/store/datastore/secret.go#L38

**Comment by UnlimitedCookies** [comment]
![image](https://user-images.githubusercontent.com/49200216/190705790-90e59ec0-0500-440a-913a-175fccd7ee6d.png)
Wouldn't it make sense to have the same order as here?

**Comment by UnlimitedCookies** [comment]
> just have to add an OrderBy() between Where() and Find() https://github.com/woodpecker-ci/woodpecker/blob/master/server/store/datastore/secret.go#L38

If I am not mistaken, `OrderBy()` is provided by xorm and would only add the `ORDER BY` to the SQL query. Which wouldn't help to sort the TEXT in the column `secret_events`, to get to the array that first needs to get interpreted by go and then sorted.

**Comment by lafriks** [comment]
> ![image](https://user-images.githubusercontent.com/49200216/190705790-90e59ec0-0500-440a-913a-175fccd7ee6d.png)
> Wouldn't it make sense to have the same order as here?

I think that would be quite obscure

**Comment by 6543** [comment]
well orderByName is the way to go ... and yes it will be forwarded to database so go dont need to sort it, its then already sorted

**Comment by 6543** [comment]
-> #1223
