### ISSUE TITLE
Autoset labels based on backend

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#1178]
auto add labels for `backend type` and `arch` and `os` (platform) to agent

... and document them all nicenly :)

to decide: should we only expose `arch&os` or only `platform` or both?

**Comment by 6543** [comment]
->  #708

**Comment by ambroisie** [comment]
Are you talking about the labels on the agent itself, or adding labels to the workflow?

**Comment by 6543** [comment]
the agent sets it, and you can filter(control) it via pipeline config
