### ISSUE TITLE
conditional step event failure aways triggered 

### ISSUE THREAD

**Issue by pchampio** [woodpecker-ci/woodpecker#1181]
### Component

server

### Describe the bug

conditional step event failure always triggered  even when there is no error

```yml
    when:
      status:
        - failure
```
is triggered even when no jobs fails

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-6433dfea"}
```

### Additional context

![image](https://user-images.githubusercontent.com/7476655/189774930-95e87e9d-497d-4d82-9101-4652b935050d.png)

![image](https://user-images.githubusercontent.com/7476655/189774989-ec542107-68a3-4785-af7b-7402ca8cc470.png)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by fcwoknhenuxdfiyv** [comment]
I'm a little confused... How exactly does #1219 address this issue? At first glance it seems to reinforce the problem.
