### ISSUE TITLE
Add option to specify healthcheck port for agent

### ISSUE THREAD

**Issue by tandav** [woodpecker-ci/woodpecker#1193]
### Clear and concise description of the problem

I see that now port 3000 is hardcoded for local agent:

https://github.com/woodpecker-ci/woodpecker/blob/531bdf5bd2d1bb0f6194011de2dce21a02991d70/cmd/agent/agent.go#L92

### Suggested solution

add option to specify port in `.env` file like this:

```
WOODPECKER_AGENT_PORT=3001
```

**Comment by anbraten** [comment]
Just for my interest: Why do you need to change that port of the healthcheck. Isn't the health-endpoint only used in container systems (docker, kubernetes) where you map the port internally?

**Comment by tandav** [comment]
I want to run local agent on a machine where port 3000 is already taken (by gitea in my case). 
When I run agent I get an error:

```sh
./woodpecker-agent
{"level":"error","time":"2022-09-17T20:02:01+03:00","message":"can not listen on port 3000: listen tcp :3000: bind: address already in use"}
```

**Comment by anbraten** [comment]
For local deployments you can just disable the healthcheck endpoint with `WOODPECKER_HEALTHCHECK=false`

**Comment by tandav** [comment]
thank you, I'll close the issue

**Comment by 6543** [comment]
I still think it should not be hardcoded
