### ISSUE TITLE
Status Icons are missaligned (Safari & Chrome on MacOS)

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#1198]
latest chrome macOS
Firefox displays fine. But the problem always exists in Chrome (not related to browser cache)

![image](https://user-images.githubusercontent.com/24977596/191000396-d438976e-7ed6-4c6c-94af-16e59e428819.png)

**Comment by wxiaoguang** [comment]
Adding a h-full can resolve the problem.

![image](https://user-images.githubusercontent.com/2114189/191000992-752382e5-dddc-470c-936f-a1b55a4f82cd.png)
