### ISSUE TITLE
Another UI nitpick: search bar text is not centered

### ISSUE THREAD

**Issue by UnlimitedCookies** [woodpecker-ci/woodpecker#1201]
![image](https://user-images.githubusercontent.com/49200216/191717883-e1e77001-ee54-411d-b810-36ed3762b057.png)

Env:
- Firefox 104.0.2-1 (ArchLinux Build)
- Woodpecker next-cf9305d3

**Comment by dvjn** [comment]
On what page(s) are you seeing this issue?

If possible, can you check if it is still an issue in #1290

**Comment by dvjn** [comment]
I couldn't see this kind of issue on any page :(

**Comment by UnlimitedCookies** [comment]
> I couldn't see this kind of issue on any page :(

Did you use firefox for testing? This is a firefox/gecko-only issue.

**Comment by dvjn** [comment]
I am using firefox

**Comment by UnlimitedCookies** [comment]
Okay, this might be a Linux-specific bug too. Github for example also has some misaligned icons: 
![image](https://user-images.githubusercontent.com/49200216/197413864-5065e10a-01d3-43c4-80f1-cc3cdf5af48c.png)
so I don't know if this is a general firefox bug. But it seems that other people are also having this issue, so it's not just on my machine. :D
(and it might be fixable on the woodpecker side by using a different alignment technique in the css)

**Comment by dvjn** [comment]
I'm with you on GitHub bug
![image](https://user-images.githubusercontent.com/62170586/197414377-e7c86462-bc5f-4c41-a501-6b62a1551895.png)

But my woodpecker search bars are aligned :(
![image](https://user-images.githubusercontent.com/62170586/197414423-cd45075f-0859-4753-a62d-20fde67c06dd.png)


BTW, I use Arch ;)

**Comment by UnlimitedCookies** [comment]
![image](https://user-images.githubusercontent.com/49200216/199749008-b047984f-8f06-4cdd-9262-c943f16f8764.png)

I think this is centered. So yeah, the UI redesign fixed this issue.
