### ISSUE TITLE
Document `when.ref`

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#1211]
```
    when:
      ref: "refs/tags/*-pre*"
```

**Comment by 6543** [comment]
did https://woodpecker-ci.org/docs/next/usage/pipeline-syntax#tag-1 ever worked ?!?

the tag filter is mentioned long ago but never where in any code snipped from https://github.com/woodpecker-ci/woodpecker/blob/release/v0.14/cncd/pipeline/pipeline/frontend/yaml/constraint.go to master!

**Comment by 6543** [comment]
while ref could be used as branch and tag filter ... it's just bit more complicated as you have to know what prefix to add

so should we add the tag filter mentioned in the docs?!? or just document ref instead and mention how to use ref for tag filter
