### ISSUE TITLE
Branch list is truncated for Gitea repository with many branches

### ISSUE THREAD

**Issue by mappu** [woodpecker-ci/woodpecker#1233]
### Component

server, web-ui

### Describe the bug

Hi, i have a Gitea repo with many branches (> 100). When listing the branches in Woodpecker, only 30 are shown. It seems like alphabetically the first 30 and then truncated after this.

This affects both the branch page, and also, the select dropdown when creating a custom build.

I think the Gitea API was changed to require pagination when listing branches, probably Woodpecker should make multiple API calls for pages of branches or request a larger pagination size,

### System Info

```shell
Running woodpecker-master from Docker Hub, today's build, digest: sha256:a8b4d6eccdb37e2207ff4b251ca8c88dccca476d76b502b84226107c7ccb074e
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by 6543** [comment]
closed by #1231
