### ISSUE TITLE
Missing required Service.spec.ports in Kubernetes

### ISSUE THREAD

**Issue by mmoya** [woodpecker-ci/woodpecker#1238]
### Component

agent

### Describe the bug

 `Service.spec.ports` is required and not being passed.

Same environment and pipeline of #1232. This time using agent version `next-3130a1c5`. The error is:

```
default/woodpecker-woodpecker-agent-56df456494-b62fg[woodpecker-agent]: {
  "level": "error",
  "error": "rpc error: code = Unknown desc = Proc finished with exitcode 1, Service \"wp-0-3996753301819885534-services-0\" is invalid: spec.ports: Required value",
  "time": "2022-10-07T21:27:22Z",
  "message": "grpc error: wait(): code: Unknown: rpc error: code = Unknown desc = Proc finished with exitcode 1, Service \"wp-0-3996753301819885534-services-0\" is invalid: spec.ports: Required value"
}
```

I see that [`kubernetes.Service`](https://github.com/woodpecker-ci/woodpecker/blob/master/pipeline/backend/kubernetes/service.go#L12) has a `ports` parameter but all calls are done with an empty array as its value.

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-3130a1c5"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by 6543** [comment]
might could solve the open todo of #552

**Comment by anbraten** [comment]
So you are trying to run a pipeline with this context (no ports defined)?:

```yml
services:
  docker:
    image: docker:22.06-rc-dind

pipeline:
  build:
    image: docker:22.06-rc-dind
    commands:
      - printenv | sort
```

I will try to debug it against a cluster again.

**Comment by mmoya** [comment]
> So you are trying to run a pipeline with this context (no ports defined)?:

Correct, no ports defined.

**Comment by zc-devs** [comment]
> no ports defined

> all calls are done with an empty array as its value

> Service.spec.ports is required and not being passed

> error: Service is invalid: spec.ports: Required value

@mmoya, what do you expect in that case?

**Comment by pat-s** [comment]
I am not sure this applies anymore given it's age. Also so much has changed in the helm chart lately and nobody else reported similar issues.

I'd vote to close and re-evaluate if something similar comes up again?

**Comment by mmoya** [comment]
I'm not actively using the CI these days. If I find time to test a more recent build I'll add a note with the results.

Although I second @pat-s's recommendation of closing this, I'll add an answer to @zc-devs for the record.

> @mmoya, what do you expect in that case?

**Expected behaviour**:

The `build` step runs and a sorted list of environment variables is printed to stdout.

**Actual behaviour**:

You get the following error  `"error": "rpc error: code = Unknown desc = Proc finished with exitcode 1, Service \"wp-0-3996753301819885534-services-0\" is invalid: spec.ports: Required value",`.

ci config:

```
services:
  docker:
    image: docker:22.06-rc-dind

pipeline:
  build:
    image: docker:22.06-rc-dind
    commands:
      - printenv | sort
```

**Comment by J-Ha** [comment]
this problem still exists.
this problem has nothing todo with the helm-chart.
it is more about the kubernetes backend and the service that should be created by a job

the service of the job awaits a port:
https://github.com/woodpecker-ci/woodpecker/blob/next-release/1.0.3/pipeline/backend/kubernetes/service.go#L26

but there is no option to pass a service port into this by the `.woodpecker.yml`
