### ISSUE TITLE
`CI_COMMIT_PULL_REQUEST` is only populated if the event is a pull request.

### ISSUE THREAD

**Issue by markopolo123** [woodpecker-ci/woodpecker#1250]
### Clear and concise description of the problem

Hi, `CI_COMMIT_PULL_REQUEST` is only populated if the event is a pull request. This means that subsequent pipelines triggered on a PR with events like `PUSH` won't be able to access this variable. 

My specific use case here is a Woodpecker plugin I've written to add comments onto a Pull Request, it needs the pull request index number to utilise the Gitea API.  It works when a PR is opened, however when triggered by any subsequent pushes it will fail as the variable is unavailable.

I can submit a PR for this issue.

### Suggested solution

Populating that value (when it's available) for other events would be very helpful

### Alternative

I've had a good search through the other CI_* variables and cannot find another way to get this value.

### Additional context

https://github.com/woodpecker-ci/woodpecker/blob/b4d89a1ccecbd0f6663947d7a320beb412f155c2/pipeline/frontend/metadata.go#L211

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by 6543** [comment]
if a push to a branch, that also is head of an pull, is exec, gitea create a push and pull webhook.

Sowe dont need to try to guess/calc/query pull index on push event, we have the pull event.

If the pull event did not got a pull index it's likely  gitea bug

**Comment by markopolo123** [comment]
Thanks, I'll test that's the case then close this/update accordingly

**Comment by markopolo123** [comment]
@6543 thanks, you are right! There are two `webhooks` fired and I was looking at the woodpecker pipeline triggered by push event (which doesn't have the index).
