### ISSUE TITLE
Check if repo exists before creating pipeline

### ISSUE THREAD

**Issue by qwerty287** [woodpecker-ci/woodpecker#1257]
https://github.com/woodpecker-ci/woodpecker/blob/master/server/store/datastore/build.go#L100

From https://github.com/woodpecker-ci/woodpecker/pull/796

**Comment by bitethecode** [comment]
Hello! Could you assign this to me please?

**Comment by 6543** [comment]
@bitethecode sure you got it :)

if you need help just chat with us via discord or matrix (links in readme)

**Comment by bitethecode** [comment]
I will start looking into it this weekend and I will let reach out to you for sure!
Thanks :)
