### ISSUE TITLE
tarball release: pnpm store js files outside the repo

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#1262]
cc @ennetech @lukashass

https://github.com/woodpecker-ci/woodpecker/blob/a94a3de4b56d16e2d1f7999d0a2cd2886fb0a752/Makefile#L227-L250

should produce a self contained source repo that dont need the internet to build woodpecker - bsd's do use this :)

**Comment by 6543** [comment]
pnpm just store symlinks and has a globa store, for ci pipeline we need to change that

**Comment by ennetech** [comment]
I see two possible solutions:
1. Package the tar having the reps installed with npm
2. Use cp -L, it should follow the links and Copy the files "web/node_modules web/pnode_modules && cp -L -r web/pnode_modules web/node_modules"

**Comment by silverwind** [comment]
`node_modules` are not portable across platforms unless they contain pure js modules only, but this is not the case with `esbuild` in the dependency tree.

**Comment by 6543** [comment]
hmm I cant find a official BSD package so I think we can rm it

**Comment by 6543** [comment]
There was no other complaint ... so yey just  need an pull to address it
