### ISSUE TITLE
certain web UI elements not yet keyboard-navigable

### ISSUE THREAD

**Issue by KiaraGrouwstra** [woodpecker-ci/woodpecker#1280]
### Clear and concise description of the problem

continuing from #1133:
there are a few web UI components that currently cannot be navigated by keyboard.

### Suggested solution

it would be nice if we could improve the accessibility of the UI components.

### Additional context

tested with version `next`.
i'll add a few illustrations using Vimium to highlight selectable elements. elements that don't have a letter appear not to be selectable by keyboard yet.

in the main view, i'm missing:

- dark toggle
- run sidebar
- repo buttons

![image](https://user-images.githubusercontent.com/3059397/196165854-bad9e2f3-13d3-4b79-886a-224e15167d45.png)

in repo view, aditionally missing:

- the cog menu
- the activity/branches tabs

![image](https://user-images.githubusercontent.com/3059397/196166342-dd9be7b1-7690-4e35-bc18-e18225c8d4ba.png)

in run view:

- the back button
- the tasks / config / changed files tabs
- the step buttons

![image](https://user-images.githubusercontent.com/3059397/196166878-41c65b91-bc2c-4136-bc0c-119fa19712c9.png)

in the settings -> secrets tab:

- the tabs
- the secret deletion buttons

![image](https://user-images.githubusercontent.com/3059397/196167270-77370092-b0c1-4031-8fab-97df3fd66ee7.png)

**Comment by lukashass** [comment]
@KiaraGrouwstra Are you sure you tested this on `next`? There are quite some changes that are not in your screenshots. E.g. it should say `next` below the logo.

**Comment by KiaraGrouwstra** [comment]
hi @lukashass.
i made the screenshots before trying `next`, was attended to the fact some changes were only in `next`, retried there to verify.
i found no changes there to my earlier findings, so left my screenshots as-is.
that said, feel free to try these on `next` yourself as well.

**Comment by lukashass** [comment]
@KiaraGrouwstra `next` looks very different though. Almost everything should be keyboard navigable. See for example:

![image](https://user-images.githubusercontent.com/32853499/197254376-e9f26e32-12ea-48b2-8e86-754afcc80e2b.png)

**Comment by 6543** [comment]
well dont forget to use the *latest* next ;) ... git pull / docker pull

**Comment by 6543** [comment]
in generall thanks for the effort ... to make it more accessible

**Comment by KiaraGrouwstra** [comment]
ahh, not sure what went wrong there on my end before.
thanks for all the improvements! i'll close this then. :pleading_face:

**Comment by 6543** [comment]
> @KiaraGrouwstra `next` looks very different though. Almost everything should be keyboard navigable. See for example:
> 
> ![image](https://user-images.githubusercontent.com/32853499/197254376-e9f26e32-12ea-48b2-8e86-754afcc80e2b.png)

What plugin can do this?

**Comment by lukashass** [comment]
https://vimium.github.io/ (press "f")
