### ISSUE TITLE
CLI: Failed to find system CA certs

### ISSUE THREAD

**Issue by MikiDi** [woodpecker-ci/woodpecker#1281]
### Component

cli

### Describe the bug

Running the CLI on my Fedora 34 system:
```
woodpecker repo ls
ERR ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/cli/internal/util.go:40 > failed to find system CA certs: <nil>
```
~~Given that the log says `nil` and [the sources expressing an intent only to log when nót nil](https://github.com/woodpecker-ci/woodpecker/blob/755d9d37e4c7615063ea1fa292cb4faad953e1d0/cli/internal/util.go#L40), I suspect this is a bug, rather than my system not having any certificates.~~
`master` [has a fix for this](https://github.com/woodpecker-ci/woodpecker/commit/1fb800329488de74c9db7cfc5dc43fb5a4efbad8), but it looks like this [didn't land in a release yet](https://github.com/woodpecker-ci/woodpecker/blob/328f10447acb38c0465eb969c42d365acdc57855/cli/internal/util.go#L40).

### System Info

Fedora 34
Woodpecker CLI `v0.15.5`

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by MikiDi** [comment]
See strike-through part of the description. I probably made the faulty assumption that a commit on `master` from january would be in the latest release (`0.15.5`).

**Comment by 6543** [comment]
well just backport :)
