### ISSUE TITLE
Rename `procs` and all other namings of it to `steps`

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#1288]
ref https://github.com/woodpecker-ci/woodpecker/issues/745

**Comment by Harikesh00** [comment]
Hi @anbraten, @6543 
I wanna work on this
can u plz give me more insight into what are all changes required to do in this issue?
and how will I verify the changes I'll make are not breaking?

**Comment by 6543** [comment]
You could just start with renaming variables and code comments in code, that way nothing break and we have that already corrected ...

... rename structFields and tables are a more intemce thing ...

**Comment by Harikesh00** [comment]
ok, thanks @6543 
I have started working on this
I'll raise a PR for review

**Comment by anbraten** [comment]
is mostly done so closing this
