### ISSUE TITLE
migrate more sql querys to xorm

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#1310]
migrate code like e.g. https://github.com/woodpecker-ci/woodpecker/pull/1296/files#diff-a3003b46215d34362e75d779f7e5b3fe234547af38afc3d21b7402f3a256636bL51-L61

to use the xorm builder or xorm instead

**Comment by 6543** [comment]
cc @bitethecode ?

**Comment by bitethecode** [comment]
@6543 Sure! 
@qwerty287 how can I find specific TODOs related to this work?

**Comment by 6543** [comment]
grep through code 😓 ... 

but it's basically only code in folder `server/store/datastore` and it's subfolders...

**Comment by bitethecode** [comment]
Okay thanks for the direction!
