### ISSUE TITLE
Locales dont have fallback

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#1313]
if you for example use "espaniol" witch is not fully translated strings are just hidden

I expect an english word in case the current locales do not provide the string 

followup of #912

**Comment by lafriks** [comment]
Yes you can customize JSON output, there should be checkbox remove empty keys

**Comment by 6543** [comment]
yes but I neither could find an option to remove them in weblate (witch indeed would fix it) nor could i found an option for vue-i28n to fallback on empty string

**Comment by 6543** [comment]
https://github.com/intlify/vue-i18n-next/issues/1206

I hope they can give us an answer ...

**Comment by lafriks** [comment]
@6543 you should add add-on "Remove blank strings", that should do the trick

**Comment by 6543** [comment]
@lafriks we do use **Weblate 4.13.1**

**Comment by 6543** [comment]
there was no addon-menu so i did alter the docker config:

but after a deploy witch ended up in an error: https://github.com/woodpecker-ci/infrastructure/pull/13#issuecomment-1287954668

I did deploy the old config.

the strange thing: the addon-menu stayed so now I was able to add mentioned plugin - works
