### ISSUE TITLE
different scroll areas for logview and workspace/step view [firefox]

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#1328]
logview does resize e.g. when you de-/collapse workspaces ...

**Comment by 6543** [comment]
<details>
 <summary>clarify it</summary>

atm:  
one scrowl zone:
![image](https://user-images.githubusercontent.com/24977596/197893575-555a8646-ab72-49bd-88d9-1af7efb11b0c.png)

want two zones:
- ![image](https://user-images.githubusercontent.com/24977596/197893634-f1ede2b1-da6f-43e8-8d64-5e417902f885.png)
- ![image](https://user-images.githubusercontent.com/24977596/197893663-ebd3d94a-646a-437b-9e17-544238e1eb5f.png)
</details>

**Comment by xoxys** [comment]
I guess this issue was fixed already?

**Comment by 6543** [comment]
yes 🎉
