### ISSUE TITLE
Use .woodpecker.yml as default pipeline config file

### ISSUE THREAD

**Issue by JensHeinrich** [woodpecker-ci/woodpecker#133]
As the current .drone.yml files are not supported by woodpecker, it seems to useful to switch to  supporting .woodpecker.yml as a default configuration source

**Comment by laszlocph** [comment]
Hi Jens,

This makes a lot of sense. Let me collect my thoughts and come back to you.

There are users having `.drone.yml` and using Woodpecker, so some backwards compatibility needs to be considered or a rollout plan.

Best regards,
Laszlo

**Comment by JensHeinrich** [comment]
I would suggest adding a second choice box 
"Fallback to .woodpecker.yml"  (there is already a one for .drone.yml) and enable it by default

**Comment by JensHeinrich** [comment]
This should then also be changed everywhere in the docs

**Comment by anbraten** [comment]
As multi-pipelines are somehow promoted in the docs already and are a very nifty feature IMO, I just had the idea that woodpecker could directly use them as default.
So the docs could be updated to mention multi-pipelines as the default way of creating pipeline files similar how github actions works. To support legacy installations `.drone.yml` should be kept as fallback as mentioned above maybe with a small hint in the docs that it is supported. So moving directly to `.woodpecker/` or `.ci/` could be an even more future-proof change.
