### ISSUE TITLE
Add initial Autoscaler support

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#1333]
Add an autoscaler into the server (optional, disabled by default)

TODOs:
 - API for agent to tell it should stop -> teardown before it pulls from next workflow
 - Server calc if it should spinn up or teardown agents (add some inactivity/wait perode before change something)
 - to start just a basic "autoscaler"

---
Bounty: 200$

**Comment by anbraten** [comment]
The first container image for the autoscaler currently only supporting Hetzner was just released: https://github.com/woodpecker-ci/autoscaler/pull/1

https://hub.docker.com/r/woodpeckerci/autoscaler
