### ISSUE TITLE
Allow non admin users to add Gitea repos

### ISSUE THREAD

**Issue by laszlocph** [woodpecker-ci/woodpecker#134]
I was able to enable repos (both user and org repos) as the Drone admin, but not with other users. I consider this a bug as the repo permissions are simply not set in the gitea integration: https://github.com/laszlocph/woodpecker/blob/master/remote/gitea/helper.go#L40 while it is set for github: https://github.com/laszlocph/woodpecker/blob/master/remote/github/convert.go#L97

Workaround is to enable repos with the DRONE_ADMIN user.

**Comment by anbraten** [comment]
I think this has been fixed by #226. At least I haven't had that bug anymore while testing.
