### ISSUE TITLE
Manuall Pipelines in gated repos still have to be approve

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#1340]
Just an UX thing ...

if you start a pipeline via "play cron" button or create a "manual pipeline" and the repo is gated,
you will get a blocked pipeline right now.

But since It's already manually triggered by persons who have the right to also approve, it should run directly 

_Originally posted by @6543 in https://github.com/woodpecker-ci/woodpecker/issues/1338#issuecomment-1291195303_

**Comment by xoxys** [comment]
Looks like this one was fixed already?
