### ISSUE TITLE
Allow to manually skip (waiting) workflows

### ISSUE THREAD

**Issue by qwerty287** [woodpecker-ci/woodpecker#1354]
Add a button to skip a workflow that is currently waiting for e.g. `depends_on` or agent capacities.

**Comment by bitethecode** [comment]
@qwerty287 Can I work on this?

**Comment by bitethecode** [comment]
Thanks! @qwerty287

**Comment by bitethecode** [comment]
@qwerty287 I'm stuck in terms of running the pipeline locally after UI local setup. Could I sync with you to be guided?

**Comment by bitethecode** [comment]
@qwerty287 I wasn't able to find you on Discord
