### ISSUE TITLE
OAuth support for Gitea

### ISSUE THREAD

**Issue by JensHeinrich** [woodpecker-ci/woodpecker#136]
It would be very nice to replace the current Auth flow with a "proper" one eg. https://oauth.net/2/pkce/.

This would eliminate the need for password entry for users already authenticated against their oauth provider and it would reduce attack surfaces

**Comment by laszlocph** [comment]
Which git provider are you on?

OAuth works for Github, not for Gitea, etc.

I can try enabling it for git providers that are in use.

**Comment by JensHeinrich** [comment]
I'm using gitea

**Comment by 6543** [comment]
port https://github.com/drone/drone/pull/2622 & https://github.com/drone/drone/pull/2684 ?
this parts are OpenSource if I did look correct ...

**Comment by anbraten** [comment]
closing as this seems to be resolved by #226 
Please feel free to re-open if needed.
