### ISSUE TITLE
Helm chart add RBAC / config section for Kubernetes backend

### ISSUE THREAD

**Issue by gapodo** [woodpecker-ci/woodpecker#1367]
### Clear and concise description of the problem

While testing #1032 I stumbled upon the Service Account not having the required permissions to use the Kubernetes backend.

This problem applies to any next, helm chart based setup with Kubernetes backend on a Kubernetes Cluster with active RBAC (which from a security perspective should be pretty much everywhere, all major enterprise K8s solutions rke2, okd, OpenShift, cloud providers, etc. have it active by default, many, more developer focused k8s-variants micro-k8s, minikube, etc., have options to enable it).

### Suggested solution

Add a role and roleBinding in the chart to allow agents with the Kubernetes backend to spawn the needed pods, collect logs, etc.

It might be an idea to take the Kubernetes backend config into its own values section, where all the Kubernetes backend settings can be added/configured, as well as deciding whether to deploy the service account with RBAC.

### Alternative

Write an additional section into the Kubernetes / Helm deployment docs outlining that a user should create the RBAC if RBAC is in use.
Also document which API-groups resources and verbs are required (which in effect is almost as much work as directly integrating it into the chart).

### Additional context

Was unsure whether this is considered a bug or feature request...

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by gapodo** [comment]
I'll have a look on implementing it, hit me up if you are quicker than I am...

**Comment by anbraten** [comment]
The helm chart already got improved several times since 0.15, but it only gets updated when released so all changes in master are not available yet. Maybe we should create a tagged pre-release or create helm pre-releases on master pushes.

**Comment by gapodo** [comment]
that would be my next feature request... But I've cloned master added a version to the Chart.yamls and deployed from source (./woodpecker-(agent|server), so I've tested against what would be the "next" version of the chart. I'll follow up as soon as I get in front of my PC (there is only one bug left, then I can open the fairly minimal pr for just the RBAC, and if thats something you (as in the team) are open to, follow up with some more possible improvements.

**Comment by anbraten** [comment]
Ahh perfect. Sounds great. Looking forward to your PR ❤️
