### ISSUE TITLE
Broken Cancel Pipeline in Web UI and CLI

### ISSUE THREAD

**Issue by dvjn** [woodpecker-ci/woodpecker#1369]
### Component

server, cli, web-ui

### Describe the bug

There is a breaking change in #1331 (deletion of line 88 in `server/router/api.go`)

![image](https://user-images.githubusercontent.com/62170586/198872699-6791548d-d8ff-4db3-b617-17a9b14ead22.png)

This endpoint is used by both the clients (web and cli), so they are breaking now.

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"dev"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by dvjn** [comment]
As per my understanding, the job parameter is redundant.

So we have 2 possible fixes:
- Revert the endpoint
- Update clients to use the `/pipelines/:number` endpoint

Or even both.

Happy to put a PR for this.

**Comment by dvjn** [comment]
@qwerty287 @6543 @anbraten

**Comment by anbraten** [comment]
If I understand it correctly we previously had that endpoint two times, but the `:job` parameter wasn't used so it got removed? I would change the cli & ui to use the new endpoint. In general we may should rename it to sth like `POST: /pipelines/:number/cancel` as it does not delete a pipeline but cancels it 🙈
