### ISSUE TITLE
Add storage requirements

### ISSUE THREAD

**Issue by JensHeinrich** [woodpecker-ci/woodpecker#137]
There seems to be no mention of storage requirements anywhere

How much working space should be planned for:
- persistent storage of the server (10Gi is used for kubernetes)
- the working directory of the agent (ran into storage problems here) [does the agent do cleanups ?]

**Comment by anbraten** [comment]
It s hard to say as it totally depends on your usage. Let me try:

# Woodpecker database
The Woodpecker server stores most / all of its data inside a database:
- pipeline metadata (pipeline configs, changed files, ...)
- pipeline logs
- users
- secrets / credentials for private registries
- projects (activated repos)
- misc data which is probably irrelevant in this aspect

# Workspace per pipeline execution
Intermediate data once per executed pipeline. If you are using multi-pipelines or matrix pipelines with will scale foreach combination.
This highly depends on your or your users pipelines. But lets assume some common usage. The following data will be stored on your system for the time the pipeline is running:
- container images defined by the pipeline
- cloned git repo (normally it only loads a single branch / tag)
- all data your user creates while building apps etc.
- maybe assets your user downloads from the internet inside the pipeline
