### ISSUE TITLE
Branches api endpoint returns 500 if user is not authenticated

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#1370]

**Comment by 6543** [comment]
well that's what tests are for, to make sure bugs are fixed once and for all :laughing:

**Comment by anbraten** [comment]
`{"level":"error","error":"Error #01: GET https://api.github.com/repos/woodpecker-ci/woodpecker/branches?page=1&per_page=50: 401 Bad credentials []\n","ip":"","latency":130.351425,"method":"GET","path":"/api/repos/woodpecker-ci/woodpecker/branches","status":500,"time":"2023-06-02T06:38:07Z","user-agent":"","time":"2023-06-02T06:38:07Z"}`
