### ISSUE TITLE
Show workflow state in UI

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#1371]
![image](https://user-images.githubusercontent.com/6918444/198873854-de531457-c688-4cb0-b4fb-6a32c3242a93.png)

We should show the state of a workflow similar to the state of a single step in front of the name.

In addition finished workflows (successful or failed) could be collapsed by default.

**Comment by dvjn** [comment]
There will be multiple steps in each workflow and they can have a mixture of states.
This opens up two options for the state indicator:

1. Combine the states into a single representative state with some logic like:
	- If any step is ['started', 'running'], then show blue
	- If any step is ['killed', 'error', 'failure', 'blocked', 'declined'], then show red
	- If all steps ['pending', 'skipped'], then show gray
	- Else show green
2. Get all the unique states (red, green, blue, gray) and show them in overlapping indicators
	![Screenshot 2022-11-01 at 00-48-47 Woodpecker(1)](https://user-images.githubusercontent.com/62170586/199092118-f9c217bc-499b-4bc8-88c6-b3a0d4017938.png)

Thoughts @anbraten ?

**Comment by anbraten** [comment]
I would go for the first with a logic like:
- If any step is ['killed', 'error', 'failure', 'blocked', 'declined'], then show red
- If all steps passed, then show green
- If any step is ['started', 'running'], then show blue
- else use gray

**Comment by dvjn** [comment]
`If all steps passed, then show green` will not work since some steps may be skipped while other passed.

How about this (my original logic with 1 and 2 swapped)?
- If any step is ['killed', 'error', 'failure', 'blocked', 'declined'], then show red
- If any step is ['started', 'running'] (inferred: no step has failed), then show blue
- If all steps ['pending', 'skipped'] (inferred: no step has failed or is running), then show gray
- Else (inferred: no step has failed or is running and not all are skipped/pending) show green

**Comment by anbraten** [comment]
Sounds fine.

**Comment by dvjn** [comment]
Sorry my bad, there was no need for this, each workflow already has a state.

Got confused by the name of the types in the code. A `Pipeline` contains `PipelineStep`s (i.e. `Workflow`) which contains again `PipelineStep`s (i.e. `WorkflowStep`)

**Comment by 6543** [comment]
@dvjn are you sure you do target latest master branch, as this name-confusions should be mostly solved ...
https://github.com/woodpecker-ci/woodpecker/issues/745

**Comment by 6543** [comment]
If you still find relicts, just rename them while you catch them please :)

**Comment by lafriks** [comment]
> `If all steps passed, then show green` will not work since some steps may be skipped while other passed, which should show success.
> 
> How about this (my original logic with 1 and 2 swapped)?
> 
>     * If any step is ['killed', 'error', 'failure', 'blocked', 'declined'], then show red
> 
>     * If any step is ['started', 'running'] (inferred: no step has failed), then show blue
> 
>     * If all steps ['pending', 'skipped'] (inferred: no step has failed or is running), then show gray
> 
>     * Else (inferred: no step has failed or is running and not all are skipped/pending) show green

Maybe last two steps could be changed:
* If any step is ['pending'] (inferred: no step has failed or is running), then show gray
* Else (inferred: no step has failed or is running or is pending) show green

This way if all steps are skipped would also mean that it is success as all is done, imho
