### ISSUE TITLE
Create a pre-release version of the helm chart based on next/master

### ISSUE THREAD

**Issue by gapodo** [woodpecker-ci/woodpecker#1374]
### Clear and concise description of the problem

As mentioned by @anbraten in #1367 it would be useful to have a built preview version of the helm chart, similar to the next builds.

### Suggested solution

Add a new pipeline / extend existing to allow for pre-release helm charts based on the master branch.

### Alternative

Not quite sure, not doing it or at least documenting how to install the master-branch version of the chart (there are a couple values that need to be overwritten in the Chart.yamls manually after pulling the master branch to allow helm to install without error)

### Additional context

This feature would become especially useful when we are reworking the chart more and more, since it would be an "as delivered" test not a "I've hacked a couple values, then installed and it's working for me™" test.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by gapodo** [comment]
Just to add I'm still fairly new to woodpecker and it's pipelines so this might be something for someone more experienced than I am (the existing pipelines are massive and I am not fully grasping them yet)

**Comment by 11mariom** [comment]
+1, would be easier to test unreleased features, like upcoming k8s backend.

**Comment by Nold360** [comment]
As far as i can see, there are two solutions:

1. Build a floating "master/next" version & keep the current tagging based pipeline
2. Or hardcode the version into the chart & update it separately
  a. And set the helmchart appversion based on branch/tag

IMHO no 2. would be a better solution, since there is the "appversion" flag already in the helm-chart. So the version of the Chart does not have to represent the version of woodpecker. And you shouldn't really use floating tags anyways...

Also it gives a way to introduce semver for the chart, when breaking changes occur.  

There should be a ci test if the version has been bumped, too.

**Comment by gapodo** [comment]
Having been working on the chart (towards #1375 and #1377) I've been toying with multiple ideas, I somewhat like the chart version being in a lockstep with the release (as all config is done via env, which can change and trying to keep the chart from breaking will be difficult / involve lots of add-on code just to manage the differences between versions), but I believe we may soon reach a point where we need to build in a bit more logic into the chart build (more than can be meaningfully be squeezed into the pipeline).

A potential idea I've been looking at may be to store a file with the "next" release SemVer and using it to build prerelease-charts according to the SemVer spec (x.y.z-PreReleaseNumber), but storing the running prerelease number may be a bit of a pain (reusing the pipeline run number would be possible, that's what I've done for a different project using GitHub workflows).

(Pre-)Release charts are also going to be more complicated once we've split common logic into its own library and have a meta chart for easy deployment of an "all in one" setup, which requires building charts with updated dependencies. One option would be to decouple the chart from the mono-repo and manage it stand alone, but triggering the Uploads to the Chart-Registry will be somewhat tricky / require wait loops as long as the CR is using a GitHub workflow for its release (using GitHub pages), one option may be to split the helm-chart out from the woodpecker-ci.org and have it on its own subdomain, which could be managed together with the split out chart (chart+pages for CR in one separate repo).

I'm currently thinking we may need to coordinate the chart (or Kubernetes in general) work better, potentially having its own channel in the Woodpecker-CI Discord/Matrix, and setup clear targets (and non targets).

**Comment by Nold360** [comment]
> I'm currently thinking we may need to coordinate the chart (or Kubernetes in general) work better, potentially having its own channel in the Woodpecker-CI Discord/Matrix, and setup clear targets (and non targets).

Sounds good to me! 

Having a own repo for the chart might be handy. Makes CI a lot easier I guess.

**Comment by pat-s** [comment]
Understanding the major differences of current HEAD vs 0.15.5 since using WP for a few days, I'd also welcome a rolling chart release on latest HEAD to give feedback on the new version.

Manual patching of (important) env vars and/or appVersion after applying an install via `helm-git` is not really practical in a team environment as it brings in too much confusion.

**Comment by Nold360** [comment]
I think what we basically want is to have a different release cycle from woodpecker itself. This way we can faster push out bugfixes & test features. 

To keep CI/CD simple, imho it would be best to create a separate helm-chart repository. 
Would you agree to create new git repo? @6543 @anbraten 

Then we can also discuss all helm related stuff over there. :)

**Comment by 6543** [comment]
+1 for dedicated helm-chart repo if there are enough maintainers who do contribute to it ... :)

**Comment by pat-s** [comment]
> +1 for dedicated helm-chart repo if there are enough maintainers who do contribute to it ... :)

To me the main points for a dedicated repo are

- easier permission handling of contributors (as people would not need write access to the main repo) 
- direct view of helm-chart only issues/PRs

For users it almost makes no difference from which URL they install or which repo they file issues to.

> +1 for dedicated helm-chart repo if there are enough maintainers who do contribute to it ... :)

This would not be an important decision point to me as I don't see a logic between the number of maintainers and splitting the repo. The repo is just "a click away" (and ofc linked in the main README) and might even simplify and increase contributions after it has been separated :)

Given the substantial differences between HEAD and 0.15.x (which would require some major refactoring AFAIK but I might be wrong), HEAD would probably live in a branch anyway as the default branch should follow the official release of course. Yet also this won't be an issue for people wanting to test the latest release *once* there is a compatible skeleton.

I can't promise any fixed time but I'd be interested to help (also helping to maintain the Gitea helm chart). Not sure who to tag besides @6543 @anbraten given the yearly elections but you might know best :)

**Comment by 6543** [comment]
-> https://github.com/woodpecker-ci/helm

**Comment by 6543** [comment]
so there is a dedicated helm repo now :)
