### ISSUE TITLE
Global pipeline `when` conditions indented at step-level

### ISSUE THREAD

**Issue by MikiDi** [woodpecker-ci/woodpecker#1386]
### Component

other

### Describe the bug

Hi!

The code snippets for `when` pipeline-syntax currently don't distinguish between
[pipeline step-level](https://woodpecker-ci.org/docs/next/usage/pipeline-syntax#when---conditional-execution) and [pipeline global-level](https://woodpecker-ci.org/docs/next/usage/pipeline-syntax#when---global-pipeline-conditions). Code snippets for both are indented at the step level, where as I'd expect the indentation for the global `when` condition to be at root level. This is confusing and probably not intended.

### System Info

```shell
`Next`-version docs
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by anbraten** [comment]
You are right. Thats a copy & paste error 🙈. Could you adjust those snippets?

**Comment by MikiDi** [comment]
I will. The `when` keyword is supposed to be at the same level as the `pipeline` keyword (no indentation), correct?

**Comment by anbraten** [comment]
Yes. Thanks.
