### ISSUE TITLE
Canceled pipelines/steps should have correct status

### ISSUE THREAD

**Issue by lafriks** [woodpecker-ci/woodpecker#1391]
### Component

server

### Describe the bug

When pipeline/step is canceled automatically it will result in failed state with error:
```
Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.41/containers/wp_0_8440940097353797125_clone_1/json": context canceled
```

Instead on this error step should be set to state canceled and so is pipeline

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-ee9269d6"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by 6543** [comment]
Duplicate ... need to find the index

**Comment by 6543** [comment]
-> #833
