### ISSUE TITLE
Help color blind people by changing dots to icons

### ISSUE THREAD

**Issue by gapodo** [woodpecker-ci/woodpecker#1393]
### Clear and concise description of the problem

As a colorblind user, it is difficult for me to see the status of steps in pipelines.

### Suggested solution

Change the colored dot in the web-ui over to an icon. We could possibly reuse the icons used to display the status in the workflow view.

The colored dot in question:
![image](https://user-images.githubusercontent.com/49525042/199749162-3f7d539b-400f-4ff4-af7f-d0f79887fa1e.png)

This is the icon I think we could use (of course "all of them" depending on status).
![image](https://user-images.githubusercontent.com/49525042/199748765-3f0702d6-ba2b-4eb3-a8cc-504c8fe93104.png)

### Alternative

Other icons or leave it be? It's not a huge inconvenience (though I'm not fully colorblind)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by gapodo** [comment]
also tagging #1314 as this would be a UI improvement / feedback

**Comment by altdsoy** [comment]
Couldn't agree more with a16y improvements!

**Comment by anbraten** [comment]
Thanks for this helpful feedback. I would really like to see it changed. 

Linking #959

**Comment by anbraten** [comment]
I guess best option longterm would be to have a check as part of the CI 🤩. Testing it manually requires some time and therefore would be to much to ask every UI developer to do. We could create a section in the docs in the development section noting some useful tools like the ones you suggested, so someone could check from time to time.
