### ISSUE TITLE
DRONE_BUILD_STATUS environment variable not set to CI_BUILD_STATUS (makes plugin drillster/drone-email fail)

### ISSUE THREAD

**Issue by smainz** [woodpecker-ci/woodpecker#1416]
### Component

server, agent

### Describe the bug

While trying to port some pipelines from drone to woodpecker-ci I found out, that the [drillster/drone-email](https://github.com/Drillster/drone-email)  plugin is not working with woodpecker-ci.

Even if the build is successful, the plugin will always send failure notifications. The reason is, that the plugin checks for `DRONE_BUILD_STATUS=='success'` (`DRONE_BUILD_STATUS` is put into the context of a template as `build.status`, the templates uses this to create the message / subject).

 The reason seems is that `DRONE_BUILD_STATUS` has the value `pending`. In the [docs](https://woodpecker-ci.org/docs/usage/environment) it says:

|   NAME  |    Description  |
|----|----|
| CI_BUILD_STATUS | build status (success, failure) |

`DRONE_*` environment variables are not mentioned.

A simple `env | sort` reveals:
```text
CI_BUILD_STATUS=success
CI_JOB_STATUS=success
CI_PIPELINE_STATUS=success
CI_STEP_STATUS=success
DRONE_BUILD_STATUS=pending
```

Is it intended behavior that `CI_BUILD_STATUS` differs from `DRONE_BUILD_STATUS` or a bug?

If the DRONE_* environment variables are just a deprecated legacy, i can offer to fork the plugin and use the correct environment variable. For this it would be helpful, if someone explained to me the difference between `BUILD_STATUS`, `JOB_STATUS`, `PIPELINE_STATUS` and `STEP_STATUS` and when they are set.

### System Info

```shell
I am using a simple docker-compose config with

-compose.yml
services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:next

...

  woodpecker-agent1:
    image: woodpeckerci/woodpecker-agent:next
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by smainz** [comment]
Any hint where to start to fix this? metadata.go copies the value, but maybe before the status is set to success / failure.

**Comment by 6543** [comment]
It's in the drone compatibilety file ...

**Comment by 6543** [comment]
I guess it's a regression of some refactor

-> https://github.com/woodpecker-ci/woodpecker/pull/1284 would likely fix it ... to, ...

**Comment by 6543** [comment]
uh now ... that one is set by the agent again 

agent/runner.go
293:		state.Pipeline.Step.Environment["CI_PIPELINE_STATUS"] = "success"
312:			state.Pipeline.Step.Environment["CI_PIPELINE_STATUS"] = "failure"

**Comment by smainz** [comment]
Do you want me to start fixing it?

**Comment by 6543** [comment]
sure if you d'like to, go on :)

**Comment by smainz** [comment]
Hope it is not beyond my current skill level, but shouldn't it be enough to **move** the call to the drone_compatibility before each call to Runner.run() where the step status is updated?
No need to have these env vars in the metadata (is it is only for compatibility with drone plugins).

https://github.com/woodpecker-ci/woodpecker/blob/master/agent/runner.go#L309-L319

just copy the env vars before the 

```
return nil
```
