### ISSUE TITLE
HTTP#500 with nested HTTP#422 when trying to activate a Github Repo in Woodpecker

### ISSUE THREAD

**Issue by florianrein** [woodpecker-ci/woodpecker#142]
Given I have a running Docker Compose - Setup on Mac localhost according to https://woodpecker.laszlo.cloud/server-setup/ with Github as the driver. My docker-compose.yml is located below. I have an oauth application configured in my Github account, I can login successfully to the woodpecker UI using it and I can see my repositories.

When I click on the switch to activate my appium-experiment - repository, then I get the following error messages.
This happens for a freshly created empty test repository, too.

**UI**
Failed to activate your repository.

**Dev Tools**
```
XHRPOSThttp://localhost/api/repos/florianrein/appium-experiment
[HTTP/1.1 500 Internal Server Error 422ms]

Object { status: 500, message: "POST https://api.github.com/repos/florianrein/appium-experiment/hooks: 422 Validation Failed [{Resource:Hook Field: Code:custom}]" }
```

**As promised, my docker-compose.yml (with credentials blackened)**

```
# docker-compose.yml

version: '3'

services:
  woodpecker-server:
    image: laszlocloud/woodpecker-server:v0.9.0
    ports:
      - 80:8000
      - 9000
    volumes:
      - woodpecker-server-data:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=http://localhost
      - DRONE_GITHUB=true
      - DRONE_GITHUB_CLIENT=valid_oauth_client_id
      - DRONE_GITHUB_SECRET=valid_oauth_secret
      - DRONE_SECRET=some_random_hex
  woodpecker-agent:
    image: laszlocloud/woodpecker-agent:v0.9.0
    command: agent
    restart: always
    depends_on:
      - woodpecker-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=woodpecker-server:9000
      - DRONE_SECRET=some_random_hex

volumes:
  woodpecker-server-data:
```

**Comment by rosscdhscimetic** [comment]
Hi there! unfortunately this still happens on woodpecker:latest 

```
docker inspect woodpeckerci/woodpecker-server:latest
[
    {
        "Id": "sha256:515f1c819d58385a1dfa75ba7f202bbb4b60e25eee2a9c98cdf7c8a22d6d9eb7",
        "RepoTags": [
            "woodpeckerci/woodpecker-server:latest"
        ],
        "RepoDigests": [
            "woodpeckerci/woodpecker-server@sha256:c37f23aa369b8282f1ab8ea8d2a8849fdc6ce30e5a0cbde25d145f43ab20d278"
        ],
```

**Comment by 6543** [comment]
@rosscdhscimetic latest is latest stable ... you might have a look at next -> https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use

**Comment by rosscdh** [comment]
Thanks for that info, only see next at https://hub.docker.com/r/woodpeckerci/woodpecker-server/tags?page=1

**Comment by rosscdh** [comment]
upgraded to next; but still get

```
POST https://gitlab.com/api/v4/projects/4.....935/hooks: 422 {error: Invalid url given}
```

when clicking on add repo

**Comment by rosscdh** [comment]
ah looks like its external dns issue ! thanks
