### ISSUE TITLE
HTTP#500 when trying to activate a Bitbucket Repo in Woodpecker

### ISSUE THREAD

**Issue by florianrein** [woodpecker-ci/woodpecker#143]
Given I have a running Docker Compose - Setup on Mac localhost according to https://woodpecker.laszlo.cloud/server-setup/ but with Bitbucket as the driver. My docker-compose.yml is located below. I have an oauth application configured in my Bitbucket account, I can login successfully to the woodpecker UI using it and I can see my repositories.

When I click on the switch to activate any repository, then I get the following error messages.

**UI**
Failed to activate your repository.

**Dev Tools**
```
XHRPOSThttp://localhost/api/repos/florianreinh/file_encryptgor
[HTTP/1.1 500 Internal Server Error 812ms]

Object { status: 500, message: "Bad request" }
```

**As promised, my docker-compose.yml (with credentials blackened)**
```
# docker-compose.yml
version: '3'

services:
  woodpecker-server:
    image: laszlocloud/woodpecker-server:v0.9.0
    ports:
      - 80:8000
      - 9000
    volumes:
      - woodpecker-server-data:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=http://localhost
      - DRONE_BITBUCKET=true
      - DRONE_BITBUCKET_CLIENT=valid_oauth_client_id
      - DRONE_BITBUCKET_SECRET=valid_oauth_secret
      - DRONE_SECRET=some_random_hex
  woodpecker-agent:
    image: laszlocloud/woodpecker-agent:v0.9.0
    command: agent
    restart: always
    depends_on:
      - woodpecker-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=woodpecker-server:9000
      - DRONE_SECRET=some_random_hex

volumes:
  woodpecker-server-data:


```

**Comment by anbraten** [comment]
@florianrein This normally is a result from BitBucket, Github, ... not allowing localhost domains to be used as webhooks. In the moment you try to activate a repo woodpecker tries to set the needed webhooks and seems to fail here in your case.
