### ISSUE TITLE
Allow to run CI pipelines locally on developer machines

### ISSUE THREAD

**Issue by alexruf** [woodpecker-ci/woodpecker#1444]
Woodpecker runs CI pipelines steps inside Docker containers. Wouldn't it be possible to allow developers to also run a Woodpecker CI locally on their machines using the local Docker runtime (simillar to what [Dagger](https://dagger.io/) does. In theory I could install Woodpecker server and agent locally, but I would be much more convenient to have something like a Woodpecker CLI which basically does the same as the agent.
This could be very helpfull for developers to debug their CI pipelines locally instead of having to push changes first into the Git repository.

**Comment by gapodo** [comment]
This is already possible using the woodpecker-cli with the `exec` command, the documentation on this is "a bit" thin" though, so you may need to go through some trial and error with it.

I am currently using the `woodpecker-cli exec` to test the helm chart build of woodpecker (the projects helm charts) using the following `woodpecker-cli exec . --debug --local` which is run in the repos root directory and mounts the local repo into the container (including unstaged changes).

**Comment by alexruf** [comment]
@gapodo Thanks for pointing you this already exists! Exactly what I was looking for.

**Comment by TechnologyClassroom** [comment]
@jaqua Make a new issue for that question.

**Comment by 6543** [comment]
> @gapodo How do I install `woodpecker-cli`on macOS? For drone I could use `brew install drone-cli`.

install via brew is a new issue :)
