### ISSUE TITLE
Error when adding organization wide secret

### ISSUE THREAD

**Issue by pat-s** [woodpecker-ci/woodpecker#1446]
### Component

cli

### Describe the bug

I am getting the following error:

```sh
woodpecker-cli secret add  --organization <org> <secret> <secret value>
10:11PM FTL error running cli error="invalid character '<' looking for beginning of value"
```

NB: I am running `woodpecker-cli` dev version on a WP 0.15.5 server install. Are they maybe incompatible?

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"0.15.5"}

woodpecker-cli version next-b6399c0a (built from source for macOS arm64)
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by gapodo** [comment]
While I have not tried to use org level secrets, the error in your CLI is fairly simple.

`woodpecker-cli secret add  --organization <org> <secret> <secret value>`
Is an example command, using the commonly used markers for required arguments `<the argument>`, when using the command you must replace `<the argument>` '(including the `<>`) with your value (and potentially quote the value if it contains spaces or other special characters).

As a side note / addon, `[]` usually (there are rare cases where people abuse it to show arrays) marks optional arguments (they may be fully omitted). This syntax is used by Linux, BSD, Unix as well as the PowerShell on Windows (not remembering if Windows cmd.exe uses the same demonstration syntax).

**Comment by pat-s** [comment]
@gapodo Thanks, I am aware what placeholders are and used them for the example on purpose.

@qwerty287 Thanks, makes sense! As there is not always a direct relation between CLI and server functionality, I was not sure whether this is a potential issue :)
