### ISSUE TITLE
Allow adding private registries on the organization level

### ISSUE THREAD

**Issue by pat-s** [woodpecker-ci/woodpecker#1448]
### Clear and concise description of the problem

Currently private registries can only be added on a repository level via `woodpecker-cli registry add`.

### Suggested solution

Add a `--organization` flag, similar as in `woodpecker-cli secret add --organization`.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by ChriFo** [comment]
What options do I have to get around the lack of this feature?

**Comment by anbraten** [comment]
For now you have to add the registry credentials in each repository you use in woodpecker. There is #1672 to add org level registries
