### ISSUE TITLE
Sort repos by owner and name (UI)

### ISSUE THREAD

**Issue by smainz** [woodpecker-ci/woodpecker#1466]
### Clear and concise description of the problem

As a user having permissions on a lot of repos in different organisations, I would like to have the option to sort the list of repos by organisation and repo

### Suggested solution

The easiest option would be to add a sort function and always sort by owner / repo. Another option would be to add a drop down with different sort methods:
- Sort by Owner / Repo name
- Sort by Repo name only
- Sort by last build time
- ...

### Alternative

none

### Additional context

Looking for input on what would be the best sort option(s) and if a single sort is enough.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by smainz** [comment]
Any preferences? I have a local versiun whch just sorts by owner / repo-name and I am happy with it.

**Comment by 6543** [comment]
sort or filter? -> #1229

**Comment by smainz** [comment]
> sort or filter? -> #1229

My main point is, that after filtering the list of repost the order is random instead of sorted. I will just file a PR to sort the search result alphabetically.

**Comment by anbraten** [comment]
resolved by #1548
