### ISSUE TITLE
Allow to skip SSL verification when cloning repos with self-signed SSL certificates

### ISSUE THREAD

**Issue by alexruf** [woodpecker-ci/woodpecker#1472]
### Clear and concise description of the problem

When the Woodpecker agent tries to clone a repository via HTTPS which is using self-signed SSL certificates, it will throw an error.
On self-hosted Git instances, self-signed SSL certificates are something Woodpecker should be able to deal with.

### Suggested solution

Add a new configuration option to allow skipping SSL certificate validation when cloning a repository.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by 6543** [comment]
you should be able to do so:
- https://woodpecker-ci.org/docs/next/usage/pipeline-syntax#clone
- https://woodpecker-ci.org/plugins/Git%20Plugin

setting `skip_verify: true`

**Comment by alexruf** [comment]
> you should be able to do so:
> 
>     * https://woodpecker-ci.org/docs/next/usage/pipeline-syntax#clone
> 
>     * https://woodpecker-ci.org/plugins/Git%20Plugin
> 
> 
> setting `skip_verify: true`

Thanks for pointing that out!

**Comment by UTF-8x** [comment]
Sorry for reviving such an old issue, but is it possible to enable this globally? It's quite inconvenient to have to do this repeatedly for every single pipeline

**Comment by 6543** [comment]
no ...
... but you can use a config extension to chage all configs on the fly or have a global one...
