### ISSUE TITLE
WOODPECKER_HOST is not properly configured

### ISSUE THREAD

**Issue by geekette86** [woodpecker-ci/woodpecker#1474]
### Component

server, agent

### Describe the bug

Hey!
I run the woodpecker version 0.15.4(agent and server)
But i got this error when i try to run a simple pipeline 
`fatal: unable to access ' ': Could not resolve host: github.com`
and in the server container i have this
`WOODPECKER_HOST is not properly configured`
even the host is set ( ngrok URL) since i run it on my localhost so i can add the Authorization callback URL on my github profile
and in the agent container 
`cannot find backend engine 'auto-detect'`
Any idea ?
Tahnk you

### System Info

```shell
woodpecker version 0.15.4(agent and server)
Ubuntu 20
Docker compose 1.29.2
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by 6543** [comment]
https://woodpecker-ci.org/docs/next/migrations#100

@geekette86 please use correct config vars for the version you use
