### ISSUE TITLE
Add a cancel button to the secrets administration

### ISSUE THREAD

**Issue by gapodo** [woodpecker-ci/woodpecker#1476]
### Clear and concise description of the problem

From a UX perspective, it is awkward not to have a `cancel` button when editing/adding secrets. I pretty much always search for it before realizing it's not there... and using either the `secrets` link in the ribbon or the `show secrets` in the top right.

### Suggested solution

Add a cancel button (next to the `add secret` and `save secret` button) to the secret creation / editing dialog, taking the user back to the secrets overview (same as `show secrets` up top), and potentially also ask the user to confirm (but `show secrets` doesn't do that right now).

The cancel button should probably be to the left of the `save secret`/`add secret` (to keep with typical UIs).

![image](https://user-images.githubusercontent.com/49525042/206901097-49a99eec-fb40-4b31-97d5-14d0c116755c.png)

### Additional context

While this is not majorly important, it's just something I stumble over regularly.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by 6543** [comment]
nice!
