### ISSUE TITLE
Add option to query prometheus endpoint without token (true/false or sourse-net based filter?)

### ISSUE THREAD

**Issue by gapodo** [woodpecker-ci/woodpecker#1477]
### Component

server

### Describe the bug

With #1469 and #1470 the use of metrics without a token was inhibited, causing my scraping setup to **break**.

There are use-cases, where using metrics without a token makes sense
* Automated metrics scraping in Kubernetes (access restricted by ingress)
* having the reverse-proxy limit access
* and other use-cases (most likely when filtering before requests reach woodpecker)

In some use-cases, requiring a token gets messy configuration wise (hard to implement in e.g. Kubernetes centralized Prometheus scraping stack, as the standard scraping definition doesn't implement sending tokens).

### System Info

```shell
Anything after #1469 / #1470 was merged and released.
```

### Additional context

Potential solutions would be:
* add a new config flag allowing scraping without a token (basically "I know what I'm doing, please let me do it")
* Allow defining an alternate / additional port for metrics to be exposed (potentially also lifting the token requirement if not served from the main port)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by gapodo** [comment]
> If limiting is done on reverse proxy, it should be possible also to add authorization header in proxy configuration. It is intential to disable this without authorization for security reasons

Adding headers is not always that easy (once again, Kubernetes is one of the worst culprits in this regard, since monitoring doesn't take the route via ingress (the reverse proxy), but accesses the containers port directly).

I understand the security concerns (and turning it off by default is IMHO the correct way), but this is breaking (so should be communicated, esp. with the backport), and has no way to override (maybe the flag would be a feasible idea, defaulting to false would not be a problem if it's known that this flag would be needed).

**Comment by lafriks** [comment]
Would probably ok to add some allowlist of IP/netmasks that can access it without token as an option

**Comment by gapodo** [comment]
Allowlist could work, but once again will get tricky in Kubernetes as IP assignments are done dynamically (and internal firewall rules updated accordingly).

**Comment by lafriks** [comment]
yes but netmask is know for internal network in k8s or you can even set netmask `0.0.0.0/0` if that's ok with you to allow all IP addresses

**Comment by gapodo** [comment]
If the allow list allows **CIDR** notation and not just single IPs, I'm fine with it (one could really just go with `0.0.0.0/0` when firewalled/filtered outside).

**Comment by alexmt** [comment]
Another option is to expose the metrics endpoint on a different port that is not exposed to the outside world. Since the port is internal, there is no need to require a token, and it still would be accessible to Prometheus ( because Prometheus is an inside the cluster). 

Let me know what you think please, happy to send a PR

**Comment by anbraten** [comment]
@alexmt A second port is what most other systems are doing as well, right? Would probably be the easiest and cleanest option.

**Comment by alexmt** [comment]
@anbraten , correct. Pretty much all systems I've worked with ([argo-cd](https://github.com/argoproj/argo-cd), [tekton](https://github.com/tektoncd) ) in the Kubernetes ecosystem use this approach. 

Created PR that exposes the endpoint on `:9001`: https://github.com/woodpecker-ci/woodpecker/pull/1614
