### ISSUE TITLE
the `*_FILE` values are not sanitized/cleaned sending control characters to upstream oAuth servers

### ISSUE THREAD

**Issue by gapodo** [woodpecker-ci/woodpecker#1479]
### Component

server, web-ui

### Describe the bug

When providing the forge client and secret via file (likely also other values, but I've stumbled across these) control characters are not stripped, this causes oAuth to fail as there is as %0A in the id / secret passed to the upstream oAuth server.

I've hit this problem while using `WOODPECKER_GITEA_CLIENT_FILE` and `WOODPECKER_GITEA_SECRET_FILE`, while one can work around this by doing an `echo -n "value" > file`, when adding manually, many secrets providers and tools always have at least the %0A (\0) at the end of string (even when it's just a single line/string), also good luck when preparing these files from a non *nix os.

### System Info

```shell
next-a3f4f305 on Linux
```

### Additional context

When using editors / tools providing the file:

File:
```text
<client-id stripped>

```

Results in
`https://codeberg.org/login/oauth/authorize?client_id=<client-id stripped>%0A%0A&redirect_uri=...`

File:
```text
<client-id stripped>
```
Results in
`https://codeberg.org/login/oauth/authorize?client_id=<client-id stripped>%0A&redirect_uri=...`

---
When doing the `echo -n "" >file` or `cat createdWithEditorOrTool | awk '{printf $1}' > file` trick, there is no control character at the end, and it works as intended.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by 6543** [comment]
https://github.com/woodpecker-ci/woodpecker/blob/b1d697b52a49666cb6b8cccda04f3518db9e9a0d/cmd/server/flags.go#L333

look's like an upstream issue within github.com/urfave/cli/v2

**Comment by 6543** [comment]
todo: check if it got fixed upstream already (v2.20.2 => v2.23.7) else submit an issue

**Comment by gapodo** [comment]
> look's like an upstream issue within github.com/urfave/cli/v2

This may well be intended behavior, as the same process can be used to load multi-line values... but the way woodpecker uses values read via this "generic" process, requires them to be "cleaned" / sanitized before sending them out to the authentication server

**Comment by danial23** [comment]
This bug is still present as of 2.4.1, preventing integration with Forgejo v7

**Comment by danial23** [comment]
I did some testing, and found that this feature (using *_FILE for oauth client-id and secret) doesn't work at all on the main branch. #1417 seems to be the source of the regression.
