### ISSUE TITLE
Failed register at Weblate (no email comes)

### ISSUE THREAD

**Issue by lcomrade** [woodpecker-ci/woodpecker#1486]
I want to translate the Woodpecker CI interface into Russian, but I can't register at https://translate.woodpecker-ci.org. I tried to report the problem with the https://translate.woodpecker-ci.org/contact/ form, but got no response. That's why I'm asking here.

I do the following:
1. Click to register.
2. Enter my email - root@lcomrade.su.
3. Fill other data and click continue.

The problem is that I never got a letter to my email (root@lcomrade.su).

PS: I already checked the my email server logs and anti-spam status. I am sure that I didn't get any mail.

**Comment by anbraten** [comment]
I will have a look.

**Comment by 6543** [comment]
did it worked?

**Comment by lcomrade** [comment]
Thank you all. It all works now. I got the email and successfully created an account: https://translate.woodpecker-ci.org/user/lcomrade/
