### ISSUE TITLE
Provide drone-kaniko Docker image

### ISSUE THREAD

**Issue by laurivosandi** [woodpecker-ci/woodpecker#1491]
### Clear and concise description of the problem

The `drone-kaniko` source repo seems to have been forked but no image is built. The upstream image is 3 years old and does not work anymore https://hub.docker.com/r/banzaicloud/drone-kaniko

### Suggested solution

Please add pipeline to build `drone-kaniko` image and update the Kaniko pipeline examples

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by 6543** [comment]
well we use https://woodpecker-ci.org/plugins/Docker%20Buildx mainly so kaniko got a bit of low prio ...

however pulls to https://github.com/woodpecker-ci/plugin-kaniko are always welcome :heart:
