### ISSUE TITLE
server segfaults during login: [signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7f7fa4589298

### ISSUE THREAD

**Issue by Kunsi** [woodpecker-ci/woodpecker#1497]
### Component

server

### Describe the bug

I just installed woodpecker-server onto my machine and tried to login. I authorized woodpecker on my gitea instance, it redirected me to woodpecker, which then crashed with a segfault. I do not see any configuration errors on my side which would cause such a behaviour.

### System Info

```shell
0.15.5 running on debian bullseye. Configs are attached
```

### Additional context

- [woodpecker-server.service.txt](https://github.com/woodpecker-ci/woodpecker/files/10289308/woodpecker-server.service.txt)
- [woodpecker.log](https://github.com/woodpecker-ci/woodpecker/files/10289303/woodpecker.log)
- [woodpecker-nginx.conf](https://github.com/woodpecker-ci/woodpecker/files/10289304/woodpecker-nginx.txt)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by 6543** [comment]
@Kunsi 

can you `export GODEBUG=netdns=go` before starting the server and see if it fix it?

**Comment by 6543** [comment]
( -> https://github.com/woodpecker-ci/woodpecker/issues/748#issuecomment-1034983733 )

**Comment by Kunsi** [comment]
hi @6543, that did fix the issue. However, contrary to the linked issue, i installed the official debian package from https://github.com/woodpecker-ci/woodpecker/releases/tag/v0.15.5

**Comment by 6543** [comment]
https://github.com/golang/go/blob/38cfb3be9d486833456276777155980d1ec0823e/src/net/net.go#L96

**Comment by 6543** [comment]
@Kunsi could you verify if  #1502 fix it?
would you need a deb to be provided for this test?

**Comment by 6543** [comment]
->  #1505

**Comment by neel** [comment]
Looks like #1576 but I use system dns only.
