### ISSUE TITLE
SSH runner crashes on start up

### ISSUE THREAD

**Issue by thedjnK** [woodpecker-ci/woodpecker#1523]
### Component

agent

### Describe the bug

It seems that there is an issue with the ssh runner backend, it crashes upon starting with the following log:
```
 woodpecker-agent[212270]: {"level":"info","time":"2023-01-03T21:56:07Z","message":"Starting Woodpecker agent with version 'dev' and backend 'ssh' running up to 1 pipelines in parallel"}
 woodpecker-agent[212270]: panic: runtime error: invalid memory address or nil pointer dereference
 woodpecker-agent[212270]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5649917a0c44]
 woodpecker-agent[212270]: goroutine 36 [running]:
 woodpecker-agent[212270]: github.com/woodpecker-ci/woodpecker/pipeline/backend/ssh.(*ssh).Load(0xc0003d4390)
 woodpecker-agent[212270]:         github.com/woodpecker-ci/woodpecker/pipeline/backend/ssh/ssh.go:49 +0xa4
 woodpecker-agent[212270]: main.loop.func3()
 woodpecker-agent[212270]:         github.com/woodpecker-ci/woodpecker/cmd/agent/agent.go:156 +0xd1
 woodpecker-agent[212270]: created by main.loop
 woodpecker-agent[212270]:         github.com/woodpecker-ci/woodpecker/cmd/agent/agent.go:152 +0x10e9
 systemd[1]: woodpecker-agent.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

Where line 49 is (and showing some later code in this function):
```
func (e *ssh) Load() error {
	cmd, err := e.client.Command("/bin/env", "mktemp", "-d", "-p", "/tmp", "woodpecker-ssh-XXXXXXXXXX")
	if err != nil {
		return err
...
client, err := goph.New(user, address, auth)
	if err != nil {
		return err
	}
	e.client = client
	return nil
}
```
It looks like e.client is being used before it is set, which happens later on in the code. Moving the top part of the function to the bottom prevents the crash, although ssh does still not work (will raise another bug for that)

### System Info

```shell
source	"https://github.com/woodpecker-ci/woodpecker"
version	"dev"

(git commit ID for build is the latest, f1e9c8416dafb6c236694765d9f7dde9620592da, built on arch linux by using the woodpecker-agent-git aur package)
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by anbraten** [comment]
The ssh runner will be removed by the next release

**Comment by thedjnK** [comment]
> The ssh runner will be removed by the next release

Any reason why? It's a useful runner
