### ISSUE TITLE
default privileged plugins also are privileged when used as normal images

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#1525]
e.g.
https://github.com/woodpecker-ci/woodpecker/blob/f1e9c8416dafb6c236694765d9f7dde9620592da/shared/constant/constant.go#L17-L23

should only have privileged permissions in plugin usage ...

else you could use custom commands to escape jail

---

bounty 50$

**Comment by 6543** [comment]
well if we can backport it we should determine on the implementation .. but it would be nice if it's able to

**Comment by 6543** [comment]
well there is still a repo config that will allow to set that privileges so your usecase will work

**Comment by gapodo** [comment]
> well there is still a repo config that will allow to set that privileges so your usecase will work
> 
> but for the default config Im better save than sory

Absolutely, 100%, the question on my part was (I may have been a bit confusing in that reply), if there could / should be 2 settings on the repo 1 for privileged plugins and another one for "always" privileged (there may be enough trust to allow additional plugins, but not "always" privileged setups)
