### ISSUE TITLE
[Docs] Mention that agents dont delete images and an demo howto add clean task

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#1532]
agents dont clean pulled images, so sysadmin has to deal with it.

we should mention that and add a hint how to do so for docker:
```
sudo crontab -e

> @daily               docker system prune --all -f --volumes
```

**Comment by c00kie123** [comment]
Hey, I can try working on this! Can you give more info ?

**Comment by 6543** [comment]
docs are in https://github.com/woodpecker-ci/woodpecker/tree/master/docs

and are markdown files

just add at the "admin" section that https://woodpecker-ci.org/docs/next/administration/agent-config ?

In the end you just have to mention it ... more info of course is better

**Comment by 6543** [comment]
PS: feel free to ask :)

**Comment by smainz** [comment]
> agents dont clean pulled images, so sysadmin has to deal with it.
> 
> we should mention that and add a hint how to do so for docker:
> 
> ```
> sudo crontab -e
> 
> > @daily               docker system prune --all -f --volumes
> ```

This remove all unused containers, networks, images (both dangling and unreferenced) and all volumes. Unused means, no running container is using it.

But this assumes, there are **no images no volumes one wants to keep** on the system. Which may or may not be the case.
Maybe it would be a good idea to add lables to volumes and only remove the ones with this label.

Images will most likely be available one some registry

**Comment by 6543** [comment]
well that's for each sysadmin to decide ... and one reason why the agent does not handle it :)

**Comment by smainz** [comment]
Here is my approach:

Remove all dangling images (those without a tag):
```
 docker image rm $(docker images --filter "dangling=true" -q --no-trunc)
```
and remove all unused volumes starting with `wp_` which seems to be the naming convention for volumes used by woodpecker:
```
docker volume rm $(docker volume ls --filter name=^wp_* --filter dangling=true  -q)   
```

The thing to add is: ignore the error message, if no dangling image / volume is found.

Maybe @c00kie123 can make something out of this discussion.

**Comment by c00kie123** [comment]
I will take a look at it.
