### ISSUE TITLE
Output line number anchors

### ISSUE THREAD

**Issue by azmeuk** [woodpecker-ci/woodpecker#1555]
### Clear and concise description of the problem

At the moment there is no way to share a part of a CI output with collaborators

### Suggested solution

In the fashion of the github code view, this would be nice to set anchors to line numbers in the CI output, so users can share the link with collaborators.

Ideally the selected line should be highlighted, and like in the github code view, several lines could be shared at once.

### Additional context

![Capture d’écran du 2023-01-19 16-34-58](https://user-images.githubusercontent.com/60163/213485041-b9ff4994-3714-4f86-9477-b58e8416d4e8.png)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by anbraten** [comment]
added by #1852 and #1922
