### ISSUE TITLE
New jobs are pending forever

### ISSUE THREAD

**Issue by lumpi101** [woodpecker-ci/woodpecker#1557]
### Component

server

### Describe the bug

New jobs are pending forever (with the hourglass symbol).

From Docker's point of view, both the server and agent are up and healthy. I haven't seen any errors in the logs which seem related to this issue.
But probably important: the last executed job is technically not finished. The time is still counting up for the last stage. But it does not seem to occupy any agent. Restarting the containers, Docker or the whole raspberry pi or updating the woodpecker versions does not change anything to it.

I also looked into the sqlite-db. The `agents` table is empty (is that a problem?)!
The pending job is listed in the `builds` table as `pending` and also in the `procs` table with 3 entries as `pending`.
The "unfinished" job is listed in the `builds` table as `killed` and otherwise unsuspicious (all time columns are filled with non-zero values). In the `procs` table, 2 of 3 entries for this job are marked as `running` with `proc_stopped` entry being `0` (that's why the still-up-counting, I'd assume). There are also other jobs which are "unfinished" in such a way further in the past which never seemed to be a problem.

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-e0a497a4"}
```

### Additional context

![image](https://user-images.githubusercontent.com/43500561/213582438-189075b3-542e-429e-a330-45848d27294b.png)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by anbraten** [comment]
raspberry is a good keyword here. I guess your woodpecker server is looking for some amd64 agent, but instead only has an arm agent. I think we already fixed that in latest next. Could you try out the latest next images for server & agent.

**Comment by lumpi101** [comment]
That indeed solved the problem (there are other issues now but I still have to investigate and if so open another Issue...).
It also makes sense because before I already had the `next` tag and because of several version updates in the past thougt that the newest 0.15.x version would work (seems I misunderstood the meaning of the tags).
Can you say when I can switch to "normal" version numbers with the raspberry pi?
