### ISSUE TITLE
Debian containers behave different from what they should.

### ISSUE THREAD

**Issue by cap-jmk** [woodpecker-ci/woodpecker#1566]
### Component

agent

### Describe the bug

Running pytest in various Debian containers yields problems in the agent. The typing throws errors where it should not. I am not sure but I had the feeling (I am sorry if it is not more) that sometimes these containers are cached or messed-up. 

The problem with typing is not appearing locally however!

I tested Ubuntu 22.04 with python3.10 locally. The respective Debian containers on Woodpecker seem to fail. 

Please compare the run: 
 https://ci.codeberg.org/cap_jmk/amarium/pipeline/76/6

Not sure if you can do anything about it. Just wanted to let you know.

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-8f687cc7"}
```

### Additional context

No additional context.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by 6543** [comment]
with `docker run --rm -it -v $(pwd):/work --workdir /work --entrypoint /bin/sh python:3.9-buster` in your repo,

and run the commands inside ... it also fails

so it's a problem of the used container image ...

**Comment by 6543** [comment]
`lia heal src` also fails on my pc ... so it's more an your side :/ ...

if you need help, the best way might be the matrix chat rooms ;)
