### ISSUE TITLE
Github check pending when part of pipeline is cancelled via branches: [ master ]

### ISSUE THREAD

**Issue by kyngs** [woodpecker-ci/woodpecker#1580]
### Component

server

### Describe the bug

When using `branches` in a pipeline and then pushing to a branch that is ignored (for example, branch dev when `branches` is `[master]`) the GitHub check on the commit never completes and still shows pending:
![image](https://user-images.githubusercontent.com/38181667/216813878-dd95defa-cbf1-4018-97ea-b44974b85a63.png)

Web UI shows that the part was canceled:
![image](https://user-images.githubusercontent.com/38181667/216813911-30486491-3c7e-41cf-bcdd-8dfabe4eac9d.png)

See checks on commit: https://github.com/kyngs/LibrePremium/commit/b3991ff803c005be8a576aefca465b5472404111

### System Info

```shell
{
  "source": "https://github.com/woodpecker-ci/woodpecker",
  "version": "0.15.6"
}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by 6543** [comment]
@kyngs does this still happen with `next` ?

**Comment by kyngs** [comment]
> @kyngs does this still happen with `next`-version ?

I can confirm it happens on the "next" version. See: https://ci.kyngs.xyz/kyngs/LibrePremium/pipeline/35

by the way, may I ask how old is "latest" compared to "next"? I see some fantastic progress and features on "next".

**Comment by anbraten** [comment]
`latest` is pretty old compared to `next` 😅 We are basically holding `next` back for such a while as our intention was to bundle breaking changes in one release.

**Comment by kyngs** [comment]
Yeah, that makes sense. Thanks for the explanation.
