### ISSUE TITLE
Webinterface does not show error when "branch does not match restrictions defined in yaml"

### ISSUE THREAD

**Issue by Nold360** [woodpecker-ci/woodpecker#1605]
### Component

web-ui

### Describe the bug

When executing a pipeline, that "does not match restrictions defined in yaml", the Webinterface will only show "An unknown error occurred".

In the logs there is a better message: `Error #01: ignoring hook: branch does not match restrictions defined in yaml\n`

### System Info

```shell
next-0bcbcb35
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by lafriks** [comment]
I don't know if this is same or different bug but when restrictions does not match (also for changed files `when path`) than webhook will also receive error 500 in response

**Comment by zc-devs** [comment]
Reproduces on `next-556607b525`.
![Screenshot 2023-06-15 174032](https://github.com/woodpecker-ci/woodpecker/assets/127358482/abea3337-be47-446e-9e5d-f82c47ca7cdb)
```
{"level":"error","error":"Error #01: ignoring hook: branch does not match restrictions defined in yaml\n",
"ip":"10.10.10.10","latency":524.149729,"method":"POST","path":"/api/repos/user/repo/pipelines",
"status":500,"time":"2023-06-15T14:40:10Z","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) 
Gecko/20100101 Firefox/114.0","time":"2023-06-15T14:40:10Z"}
```
And after that I cannot run pipeline manually without refreshing page, because `Trigger a manual pipeline run` window doesn't appear, only background shadow.

**Comment by 6543** [comment]
we should now have better error handling :)
