### ISSUE TITLE
`depends_on` ignored if server is restarted

### ISSUE THREAD

**Issue by alexef** [woodpecker-ci/woodpecker#1606]
### Component

server

### Describe the bug

assume a multi pipeline set up, with:
- pipeline a
- pipeline b, depends_on: [pipeline a]

while a is running and b is pending, restart the drone server

what is expected: b stays in pending until a completes
what happens: b immediately starts running, ignoring a which is also still running

### System Info

```shell
{
  "source": "https://github.com/woodpecker-ci/woodpecker",
  "version": "v0.14.2"
}

I know this is an older version, I will now try to reproduce the issue on the latest release.
```

### Additional context

maybe related to: https://github.com/woodpecker-ci/woodpecker/issues/200

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by alexef** [comment]
Update: we (cc: @lukaszgyg) were able to reproduce the issue (same steps) also on latest stable: 
```
{
  "source": "https://github.com/woodpecker-ci/woodpecker",
  "version": "0.15.6"
}```

**Comment by alexef** [comment]
By checking the code (it's been a while since I touched it), it seems like we have two representation of a Task, with a slight difference:
- queue.Task (in memory, has Dependencies and DepStatus)
- model.Task (in datastore, has only Dependencies)

the [task.ShouldRun](https://github.com/woodpecker-ci/woodpecker/blob/e79ad0082687ea9aa1ecc7847f69e2c851752dc4/server/queue/queue.go#L42) method will check DepStatus. However, when we load tasks in memory (at start up) we [don't fill the DepStatus property](https://github.com/woodpecker-ci/woodpecker/blob/e79ad0082687ea9aa1ecc7847f69e2c851752dc4/server/queue/persistent.go#L39). When this is empty, then ShouldRun returns true.

@anbraten does this make sense?

**Comment by 6543** [comment]
I'm not happy how queue is implemented atm at all ...: #1518 , ...

I think that could be done in one catch :)

**Comment by alexef** [comment]
Agree a rewrite is granted, but I would like to see this bug fixed (as it negatively impacts our organisation). Will prepare a pr :)

**Comment by alexef** [comment]
changes are in master.

now trying to also backport to v0.15 https://github.com/woodpecker-ci/woodpecker/pull/1625
