### ISSUE TITLE
PR pipelines are visible in the branches tab

### ISSUE THREAD

**Issue by kyngs** [woodpecker-ci/woodpecker#1619]
### Clear and concise description of the problem

If someone opens a PR to a branch (for example master), you can find the relevant pipeline under the target branch's section. For example:
![image](https://user-images.githubusercontent.com/38181667/224828869-4246c018-3973-4065-b537-7ea99ffc09f2.png)

This could cause some great confusion on which pipelines are run from commits verified by trusted people (people with push rights to the repo), and which are not. (I realize there's the PR icon on the pipeline, but most people won't notice it/won't know what it means.)

If something like #1577 merged, this could even lead to dangerous code being distributed to the target users. 
Example of abuse:
Users are instructed to download the artifact from the latest pipeline on branch `master`. 
A malicious person opens a PR to `master` containing malicious code.
Now users download the malicious binary when downloading the last artifact on branch `master`.

### Suggested solution

Somehow separate PRs (not sure how exactly ATM).

### Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by lafriks** [comment]
Probably would be good create separate PRs tab where to show list of all PR and be able to list specific PR builds

**Comment by anbraten** [comment]
That was also my idea some time ago. To add an additional tab `Pull Requests` as well

**Comment by kyngs** [comment]
I can confirm that this works correctly.
Thanks for the quick implementation!
