### ISSUE TITLE
Woodpecker Agent is being shown as `starting` in a container.

### ISSUE THREAD

**Issue by GamePlayer-8** [woodpecker-ci/woodpecker#1624]
### Component

agent

### Describe the bug

Woodpecker Agent is being shown as `starting` when executing `docker ps -a` / `podman ps -a`.

### System Info

`Artix Linux Rolling - OpenRC`
```
version	"0.15.6"
```

On podman / `podman.sock`.

Runner:
```
#!/usr/bin/openrc-run

supervisor=supervise-daemon

depend() {
	need localmount net pihole postgresql woodpecker-server pipeline
}

start() {
	echo -n "Starting:"
	if [ "$(podman ps -aq -f name='cwoodpecker')" ]; then
		podman stop cwoodpecker > /dev/null
	fi

	if [ "$(podman ps -aq -f name='cwoodpecker')" ]; then
		podman start cwoodpecker
	else
		podman run \
			-d --restart=unless-stopped \
			--stop-signal SIGKILL \
			--name cwoodpecker \
			--ip 192.168.2.13 \
			--privileged \
			-v /server/pipeline:/listen \
			-e WOODPECKER_LOG_LEVEL=warn \
			-e WOODPECKER_HOSTNAME=woodpeckeragent \
			-e WOODPECKER_AGENT_SECRET="secret" \
			-e WOODPECKER_HEALTHCHECK=false \
			-e WOODPECKER_MAX_PROCS=2 \
			-e WOODPECKER_SERVER=192.168.2.14:9000 \
			-e WOODPECKER_BACKEND=docker \
			-e DOCKER_HOST="unix:///listen/podman.sock" \
			woodpeckerci/woodpecker-agent
	fi
}

stop() {
	if [ "$(podman ps -aq -f name='cwoodpecker')" ]; then
		podman stop cwoodpecker > /dev/null
	fi
}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by 6543** [comment]
where did you get that open-rc script from?

**Comment by GamePlayer-8** [comment]
I wrote it.
