### ISSUE TITLE
[Docs] Motivation and goals

### ISSUE THREAD

**Issue by 3nprob** [woodpecker-ci/woodpecker#165]
Thank you so much for this project!

The project description says Woodpecker is "a highly opinionated fork" of Drone CI, but neither docs nor the repos mention what those opinions are, what the difference to Drone is and why one would choose one over the other.

The original motivation is laid out in now archived https://github.com/laszlocph/drone-oss, but I think it could be very helpful for those new to either with a brief FAQ in the readme and/or docs

**Comment by laszlocph** [comment]
I updated the Readme and project description by removing the opinionated part.

My ambitions are certainly faded over time, and the project right now is just going with the flow. We will find focus if something surfaces.

I also see that there is higher activity recently, with contributions etc. which I'm super happy about and happy to support. But I don't have clear goals at the moment, besides making it work for people who want to use it. Including me.
