### ISSUE TITLE
Build manifest testing

### ISSUE THREAD

**Issue by vanceism7** [woodpecker-ci/woodpecker#1665]
### Clear and concise description of the problem

Writing build manifests, especially when getting started, can sometimes be difficult to get right. Often times what happens is you end up making a bunch of commits in your repo with small tweaks to the build config until things finally start working. It would be nice to be able to test build manifests _before_ committing them to your repo. 

### Suggested solution

Sourcehut is a git server similar to gitlab, with its own built in CI/CD pipeline processor. Their solution to the problem was to create a web submission form, where you can paste code for a build manifest, and run a one off job right then and there to test if the build script functions as intended. Once you get all the kinks worked out, then you can commit the build manifest to your repo. You can read about it here
https://man.sr.ht/tutorials/getting-started-with-builds.md#submitting-jobs-on-the-web

### Alternative

Perhaps some sort of CLI utility that took the build manifest as an input and simulated the pipeline locally

### Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by 6543** [comment]
@vanceism7 it's already covered by https://woodpecker-ci.org/docs/next/cli#lint

and it can also test the exec locally https://woodpecker-ci.org/docs/next/cli#exec

**Comment by vanceism7** [comment]
Ah my bad! I looked around the docs but didn't find anything. That's great, thanks for the response!

**Comment by 6543** [comment]
made it easier to find for others in the issue tracker ;)
