### ISSUE TITLE
Add Manual workflow Trigger

### ISSUE THREAD

**Issue by tiny6996** [woodpecker-ci/woodpecker#1668]
### Clear and concise description of the problem

I would like to be a able to run only certian workflows in a deployment without updating code in a repository.

### Suggested solution

Add a an option in the yaml file or a UI option that requires each workflow be triggered manually.

### Alternative

* skip workflows as described in #1354
* skip 

### Additional context

I would like to see manual workflow steps added so I can have a 1 work flow per ansible role I would like to deploy. Then start a build manually to deploy that role whenever without updating git. This would function to manual steps in bitbucket pipelines https://bitbucket.org/blog/pipelines-manual-steps-confidence-deployment-pipeline

### Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by 6543** [comment]
hmm you can already skip by filter out event "manual" for all workflows not intended to run

I don't think we should make a selector for workflows ... if at all, an option to specify the config path (witch would result in same functionality)

**Comment by 6543** [comment]
-> #1722

**Comment by anbraten** [comment]
You can pass variables already using the manual workflow. Such a variable could be the ansible role / filter. Or you could pre-define all ansible tasks you want to execute and add when filters like:

```yml
when:
  - evaluate: 'MY_ROLE == "openssh"'
```

**Comment by tiny6996** [comment]
How would I define `MY_ROLE` I updated one of my files in the .woodpecker folder and I am getting an error saying 

```
Execution error
unknown name ROLES (1:1) | ROLES contains "kics" | ^
```

when roles defined as a secret and and as a variable when I run the pipeline manually? I am guess [this](https://woodpecker-ci.org/docs/next/usage/pipeline-syntax#evaluate) section of the docs is the right place to look

```
clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      skip_verify: true
pipeline:
  KICS Scan:
    image: checkmarx/kics:latest
    commands:
      - kics scan --no-progress -p . --disable-secrets --report-formats json --output-name kics-results
    when:
      - evaluate: 'ROLES contains "kics"'
  Ansible Lint:
    image: docker.io/pipelinecomponents/ansible-lint
    commands:
      - ansible-lint --show-relpath .
    when:
      - evaluate: 'ROLES contains "lint"'
```

**Comment by zc-devs** [comment]
> You can pass variables already using the manual workflow. Such a variable could be the ansible role / filter. Or you could pre-define all ansible tasks you want to execute and add when filters like:
> 
> ```yaml
> when:
>   - evaluate: 'MY_ROLE == "openssh"'
> ```

That doesn't work :(

```
when:
  event: manual
  evaluate: 'TESTVAR == "testval"'
skip_clone: true
steps:
...
```

![Screenshot 2023-06-10 171903](https://github.com/woodpecker-ci/woodpecker/assets/127358482/903ee7ae-cc58-4a52-af3d-821bab6664cd)
![Screenshot 2023-06-10 171942](https://github.com/woodpecker-ci/woodpecker/assets/127358482/b8c8e24d-913b-4d8f-8081-238a9526bbe8)

Only built-in environment variables work now.

**Comment by tiny6996** [comment]
After updating the container this worked thanks for all the hard work :)

**Comment by anbraten** [comment]
seems to be resolved
