### ISSUE TITLE
Can you provide a code review feature based on ChatGPT?

### ISSUE THREAD

**Issue by vicnoah** [woodpecker-ci/woodpecker#1673]
### Clear and concise description of the problem

The Curve storage team is experimenting with this feature recently, and I think it could be very useful.
![f8ca23f764c730ca](https://user-images.githubusercontent.com/20820831/227072194-26346750-c2c0-4268-9fb6-3f55eb8b013d.jpg)

### Suggested solution

There are already related implementations on GitHub.
[ChatGPT-CodeReview](https://github.com/anc95/ChatGPT-CodeReview)

### Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by 6543** [comment]
well the simple answer is yes: just build your plugin in any language you want

the long: that's not in scope of the woodpecker **core** project so **we** wont do that at all.
So I'll close this issue here but if you have a existing plugin, we are happy to add it to our plugin index :)
