### ISSUE TITLE
Make code consistent when deleting to return 404 status if not found

### ISSUE THREAD

**Issue by lafriks** [woodpecker-ci/woodpecker#1675]
### Component

server

### Describe the bug

Currently in some places this would be checked but in other places not. We should make it consistent.

https://github.com/woodpecker-ci/woodpecker/pull/1672/commits/c99d72bb0cef79f412538c1b96efbb9cf7545073

### System Info

```shell
latest
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by anbraten** [comment]
@Rogue-striker sure.

**Comment by 6543** [comment]
@Rogue-striker got already implemented in #1703 now .. so you can look at this pull if you wana educate yourself at least ;)
