### ISSUE TITLE
Agent doesn't run platform conditionals correctly set for it

### ISSUE THREAD

**Issue by dessalines** [woodpecker-ci/woodpecker#1677]
### Component

agent

### Describe the bug

When I add this to either a build step, or the entire pipeline, it won't run / is skipped on my agent.

```
  when:
    platform: linux/amd64
```

Agent:
```
Kernel: Linux 5.15.0-60-generic
Architecture: x86-64
```

I've also tried changing it to `linux/*`, with no luck.

My agent also explicitly says its using this in its logs:

`{"level":"info","time":"2023-03-23T17:54:01Z","message":"Starting Woodpecker agent with version 'next-3a475ce2' and backend 'docker' using platform 'linux/amd64' running up to 1 pipelines in parallel"}`

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-3a475ce2"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by dessalines** [comment]
cc @anbraten @6543

**Comment by 6543** [comment]
issue: https://github.com/woodpecker-ci/woodpecker/blob/master/server/pipeline/filter.go

return: `ignoring hook: branch does not match restrictions defined in yaml` but there is none :/

**Comment by 6543** [comment]
@dessalines sorry for the long round-trip-time ;)

https://woodpecker-ci.org/docs/next/usage/pipeline-syntax#labels is what you want I would say ...

I'll test it and improve the documentation to add a hint to the platform filter

**Comment by 6543** [comment]
@dessalines ok the labels should be the way to go ... but `plaftorm` label do not worked in my test ... so I need to investigate into that

in any case you can use the *old* https://woodpecker-ci.org/docs/next/usage/pipeline-syntax#platform-1 option

**Comment by 6543** [comment]
related to #1870

**Comment by pat-s** [comment]
The platform handling got updated lately in `next` and now uses `labels:`. Is this still an issue? @dessalines 
If so, which backend?

https://woodpecker-ci.org/docs/next/usage/workflow-syntax#filter-by-platform

**Comment by dessalines** [comment]
Its pry good now, thx!
