### ISSUE TITLE
env for pipeline name

### ISSUE THREAD

**Issue by wenerme** [woodpecker-ci/woodpecker#1681]
### Clear and concise description of the problem

When I send notify, I want to include the pipeline name, e.g. the miniapp & app-server for below build

<img width="648" alt="image" src="https://user-images.githubusercontent.com/1777211/227702720-f1eac3e2-e404-4895-bff7-0d59d0308308.png">

### Suggested solution

how about `CI_PIPELINE_NAME`

### Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by anbraten** [comment]
Nice idea. Would name it `CI_WORKFLOW_NAME` and also add `CI_STEP_NAME` for the step name.
