### ISSUE TITLE
Woopecker prometheus metrics not getting exposed

### ISSUE THREAD

**Issue by kartik-sareen** [woodpecker-ci/woodpecker#1683]
### Component

server

### Describe the bug

Hi team
I have deployed Woodpecker next version in kubernetes but metrics are not getting exposed as it is returning 404
Do we need to provide any extra flag/env variable Can someone pls help me in exposing woodpecker prometheus metrics ?

### System Info

```shell
Version info {"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-f6811a20"}

Curl output
curl -i --location --request GET 'https://woodpecker.<domain>.com/metrics' \
--header 'Authorization: Bearer <Token>'
HTTP/1.1 404 Not Found

Prometheus scrape config
- job_name: "woodpecker"
  bearer_token: <token>
  static_configs:
  - targets: ["woodpecker.<domain>.com"]

Prometheus response 404; expecting 200; response body: ""
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by pat-s** [comment]
You need to set `WOODPECKER_METRICS_SERVER_ADDR`, or configure authenticated access for https. See https://woodpecker-ci.org/docs/next/administration/prometheus#metric-reference.
