### ISSUE TITLE
Bitbucket Server / Data Center: List branches endpoint 404

### ISSUE THREAD

**Issue by majodev** [woodpecker-ci/woodpecker#1695]
### Component

server

### Describe the bug

Hi,

I'm currently in the process of migrating a fairly old Bitbucket Server 7.x (non-cloud) instance to Bitbucket Data Center 8.8. As part of this, I'm also investigating migration of a super old woodpecker instance (`v0.8.105`) to `v0.15.7` and now to `next`.

Apart from the typical to be expected DB migrations and breaking `ENV` configuration changes, the branch list integration introduced with #907  (more exactly the `<base>/2.0/repositories/<owner>/<name>/refs/branches` template string [here](https://github.com/woodpecker-ci/woodpecker/pull/907/files#diff-ecc104bf0e9c2d9167c43bce82421e93507f8a8660f061ac2171d298dfe214ea)) is actually something still blocking us currently. It `404`s on Bitbucket Server / Data Center and consequently `500` within Woodpecker.

AFAIK for both Bitbucket Server / Data Center 7.x and 8.x (non-cloud) the proper integration endpoint should be `GET <base>/rest/api/latest/projects/<owner>/repos/<name>/branches`. Sample Bitbucket Response of this endpoint is:

```json
{
    "size": 4,
    "limit": 25,
    "isLastPage": true,
    "values": [
        {
            "id": "refs/heads/dev",
            "displayId": "dev",
            "type": "BRANCH",
            "latestCommit": "<SHA>",
            "latestChangeset": "<SHA>",
            "isDefault": false
        },
        {
            "id": "refs/heads/main",
            "displayId": "main",
            "type": "BRANCH",
            "latestCommit": "<SHA>",
            "latestChangeset": "<SHA>",
            "isDefault": true
        }
    ],
    "start": 0
}
```

Sources:
* https://developer.atlassian.com/server/bitbucket/rest/v808/api-group-repository/#api-api-latest-projects-projectkey-repos-repositoryslug-branches-get

### System Info

```shell
woodpeckerci/woodpecker-server:next-e408c1ba27-alpine
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-e408c1ba"}
```

### Additional context

Woodpecker Server Log:
```json
{
    "level": "error",
    "error": "Error #01: invalid character '<' looking for beginning of value\n",
    "ip": "xxx.xxx.xxx.xxx",
    "latency": 54.356947,
    "method": "GET",
    "path": "/api/repos/PROJECT/REPO/branches",
    "status": 500,
    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36",
    "time": "2023-04-03T15:57:01Z",
    "caller": "/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/logger.go:43"
}
```

Browser Console / UI:
<img width="997" alt="Bildschirm­foto 2023-04-03 um 17 57 28" src="https://user-images.githubusercontent.com/2149883/229565185-5c2b1a17-735d-43c7-ab2f-31214801da71.png">
<img width="120" alt="Bildschirm­foto 2023-04-03 um 18 00 10" src="https://user-images.githubusercontent.com/2149883/229565201-340e64e4-85fb-45be-80a3-af8072dc243e.png">

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by majodev** [comment]
> Do you only refer to hosted BitBucket 

AFAIK the "cloud" variant of Bitbucket has this branches API endpoint which [you currently use](https://github.com/woodpecker-ci/woodpecker/blob/3372d1a87c5b2f7b3376c0594e5e42681bc6b07f/server/forge/bitbucket/internal/client.go#L47) (I've not tested those).

> or also to the self-hosted BitBucket Server (Stash)?

yes, my issue **only** refers to **self-hosted** Bitbucket (formerly Stash, available as `Server` or `Data Center` license) and the branches endpoint [here](https://github.com/woodpecker-ci/woodpecker/blob/3372d1a87c5b2f7b3376c0594e5e42681bc6b07f/server/forge/bitbucketserver/internal/client.go#L46).

**Comment by 6543** [comment]
@majodev https://github.com/woodpecker-ci/woodpecker/pull/1698#issuecomment-1500319408
