### ISSUE TITLE
Clone step is skipped for cron job

### ISSUE THREAD

**Issue by dessalines** [woodpecker-ci/woodpecker#1716]
### Component

agent

### Describe the bug

When running a `when: cron` job, the woodpecker clone plugin step is skipped:

woodpecker.yml:

```
clone: 
  git: 
  ...
```

Working clone / git step:

- https://woodpecker.join-lemmy.org/LemmyNet/lemmy/pipeline/205

Examples of broken for cron jobs:

- https://woodpecker.join-lemmy.org/LemmyNet/joinlemmy-site/pipeline/72/2
- https://woodpecker.join-lemmy.org/LemmyNet/lemmy/pipeline/197

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-3a475ce2"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by 6543** [comment]
my asumption:
 as by default the clone step gets added if not exist when all `when` filters are falidated it still gets added for cron

but asap you have a custom clone step you get the default cron filter too and so it's filtered out

so we either have to add a specific case that take this into account or do drop default filter and let cron jobs run wild by default :sweat: ...

**Comment by 6543** [comment]
@dessalines for you the workaround would be to add a when filter to the clone step and add events: cron, pull, push,tag ...

**Comment by 6543** [comment]
-> #1451

**Comment by dessalines** [comment]
Thanks... should I close this in favor of the other issue?

**Comment by 6543** [comment]
no let it open its still an issue
