### ISSUE TITLE
Kubernetes: agents are not removed/replaced when pods change

### ISSUE THREAD

**Issue by pat-s** [woodpecker-ci/woodpecker#1740]
### Component

agent

### Describe the bug

When an agent pod changes, the agents listed in the Server overview are not updated or replaced. New pods are just appended and the old ones still exist without any new contact.

This leads to a very long list of outdated/stale agents referenced in the server.

![image](https://user-images.githubusercontent.com/8430564/236622162-47d2754a-d06d-4d67-a7ce-c3e2eb539f29.png)

### System Info

```shell
`next-049c2622`
```

### Additional context

![image](https://user-images.githubusercontent.com/8430564/236622184-57ee7e9d-4f73-43cd-814d-cc13964245ca.png)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by anbraten** [comment]
There are two kind of agent tokens. One is using the "system token" which adds a new agent each time the agent restarts. And the newer agent specific token. This token is explicitly bound to an agent. To get one of the newer tokens you can add an agent via the UI and use that token for your kubernetes deployment.

**Comment by anbraten** [comment]
> Is there a way to prevent the "system-token" agents to prevent spawning new agents each time the agent pods are recreated?

We would need to identify those "system-token" agents somehow and delete them after they disconnect. In general we do need to thing how we can deprecate "system-token" agents in general.
