### ISSUE TITLE
Access orgs by id

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#1743]
Similar to #1295 it would be great to access orgs by their id. This would solve renaming issues

**Comment by anbraten** [comment]
I started the change, but ran into an issue:

We do not store org data in the database and therefore do not have a unique id. We could use the remote forge id (if one exists), but that would not help with #138. Any suggestions?

**Comment by pat-s** [comment]
Should we move this to 1.1? Given the issues encountered and discussion I don't think this will be merged in the nearby future?

**Comment by anbraten** [comment]
As it will be breaking I would like to include it.

**Comment by pat-s** [comment]
Alright, then this tag change might help to better reflect this issue :)

**Comment by mvdkleijn** [comment]
Just a random comment after stumbling over this issue... if you don't want to store the ID in the DB... why not do something fediverse style?

org@forge1.net
org@forge2.net

or a variation thereof
