### ISSUE TITLE
use  'WOODPECKER_ROOT_URL'   can't  login 

### ISSUE THREAD

**Issue by wenchao5211** [woodpecker-ci/woodpecker#1773]
### Component

server

### Describe the bug

when i use `WOODPECKER_ROOT_URL`,  woodpecker  can't  login 

```
 apply style from 'http://xxx/ci/assets/index-6d181f24.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
ci:1  Refused to execute script from 'http://xxx/ci/web-config.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
index-b6d7ab2a.js:1  Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
ci:1  Refused to apply style from 'http://xxx/ci/assets/index-6d181f24.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

### System Info

```shell
kubernets 1.25

woodpecker v0.15.9 
woodpecker image tag：next
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by wenchao5211** [comment]
@spantaleev  
I see https://github.com/devture/com.devture.ansible.role.woodpecker_ci_server/pull/2#issuecomment-1530932964
Also, I found some static file access issues on the front end, and I would like to know if there is a specific completion schedule for this feature ?  I haven't seen any pr for that yet.

**Comment by absolutejam** [comment]
Just to check, should Docker image `docker.io/woodpeckerci/woodpecker-server:pull_1783` have these changes?

As I'm still getting a missing favicon & icon, and the `Login` button sends me to `/login` instead of respecting the `WOODPECKER_ROOT_URL`

**Comment by wenchao5211** [comment]
> Just to check, should Docker image `docker.io/woodpeckerci/woodpecker-server:pull_1783` have these changes?
> 
> As I'm still getting a missing favicon & icon, and the `Login` button sends me to `/login` instead of respecting the `WOODPECKER_ROOT_URL`

me too

**Comment by mkibp** [comment]
Here's a fun-fact now. You not only need to use your external path like `/woodpecker`, but you also gotta redirect it into `127.0.0.1:8000/woodpecker` instead of the root of `127.0.0.1:8000`. This is a bit different from what other projects usually do, but it works after changing it like that. Leaving that here in case someone runs into that issue again otherwise.
