### ISSUE TITLE
Test agent running pipelines while server is offline

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#1776]
What happens if the server goes offline, but the agent is still running pipelines. Will the agent buffer logs and status changes and send them again, after the server comes back online?

This should be tested and if necessary a roadmap with improvements should be created.

**Comment by zc-devs** [comment]
I've tested it on `next-556607b525` and Kubernetes backend. Step before connection lost is finished and pipeline is paused until server is up. Then pipeline continues and successfully finishes.

[woodpecker-agent.log](https://github.com/woodpecker-ci/woodpecker/files/11676013/woodpecker-agent.log)
[woodpecker-server-1.log](https://github.com/woodpecker-ci/woodpecker/files/11676016/woodpecker-server-1.log)
[woodpecker-server-2.log](https://github.com/woodpecker-ci/woodpecker/files/11676017/woodpecker-server-2.log)

![Screenshot 2023-06-07 130231](https://github.com/woodpecker-ci/woodpecker/assets/127358482/74898874-cdaf-4ee2-a8c6-75e4a1c9732a)
![Screenshot 2023-06-07 130244](https://github.com/woodpecker-ci/woodpecker/assets/127358482/f1ee9af3-e349-4ae1-8a2c-0d1171e6f4b8)
![Screenshot 2023-06-07 130334](https://github.com/woodpecker-ci/woodpecker/assets/127358482/a5b82f62-e478-4755-913e-dc3f08e5b934)
![Screenshot 2023-06-07 130526](https://github.com/woodpecker-ci/woodpecker/assets/127358482/6566ea55-7ef8-4235-b15e-4c90b7a77fe7)
![Screenshot 2023-06-07 130713](https://github.com/woodpecker-ci/woodpecker/assets/127358482/638690fb-1759-469a-b49b-d7b670ee04fe)
![Screenshot 2023-06-07 130753](https://github.com/woodpecker-ci/woodpecker/assets/127358482/a6d73a56-f399-49a7-9250-405a432b7f4a)

**Comment by anbraten** [comment]
thanks for testing
