### ISSUE TITLE
Provide images the two latest alpine releases

### ISSUE THREAD

**Issue by pat-s** [woodpecker-ci/woodpecker#1778]
### Clear and concise description of the problem

~~The bump to alpine 3.18 in #1765 caused the side-effect of WP requiring the docker version on the host to be 23.x as otherwise an incompatibility with Docker API 1.42 is thrown.~~

~~Many package managers don't provide docker 23.x yet which makes staying on WP next impossible atm.~~

Provide images for the last two alpine versions - in case something is up with latest.

### Suggested solution

~~It would be great if alpine 3.17 could be added to the distribution matrix for better distro support until all those package managers have catched up with the docker daemon versions.~~

### Alternative

~~Downgrade to alpine 3.17 until the situation has improved.~~

### Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by danog** [comment]
+1, would really need this, wanted to add a new worker on a riscv machine running debian and couldn't do that because it only has docker 20.10 (and I would really like to avoid the hassle of recompiling docker, too, since it's the only thing I didn't have to recompile to use that board :P)

**Comment by pat-s** [comment]
You can use an image of next before the bump to 3.18 was done as a workaround for now. The non-alpine variants might work as well.

**Comment by pat-s** [comment]
You can use an image of next before the bump to 3.18 was done as a workaround for now. The non-alpine variants might work as well.

**Comment by pat-s** [comment]
I was wrong. #1765 is not responsible for this error. Instead it was introduced by #1744. So using images with the tag `:next-21a2fcbc38` will work. All afterwards won't.

**Comment by anbraten** [comment]
As I wrote in https://github.com/woodpecker-ci/woodpecker/pull/1779#issuecomment-1568259913 the maintance overhead of two alpine version wouldn't bring a benefit atm. We should however in general definitely make sure the select alpine version works with Woodpecker (currently there is no problem with the selected alpine version afaict).
