### ISSUE TITLE
Incompability with docker 20.10 and it's API 1.41

### ISSUE THREAD

**Issue by pat-s** [woodpecker-ci/woodpecker#1786]
### Component

agent

### Describe the bug

After #1744 WP requires docker 23.0. Many distros don't provide that yet and hence can't use `next` later than `next-21a2fcbc38`. 

Many distros will be slow on catching up and will take months/years until docker 23.0 is supported.
I suggest to revert this dependency bump for compatibility.

### System Info

```shell
-
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by anbraten** [comment]
Afaik the bump was related to a CVE report. Is there a patch version for the previous version?

**Comment by 6543** [comment]
well the next version is going to target latest taged dependencys ... and so require an uptodate docker deamon ...

the v0.15.0 did got a patch that is non breaking ... through I understand you want to have the features of next.

I want to tag the 1.0 release soon but .. well it's done when it's done (https://github.com/woodpecker-ci/woodpecker/milestone/4)

**Comment by pat-s** [comment]
> well the next version is going to target latest taged dependencys ... and so require an uptodate docker deamon ...

I can't follow the reasoning here. Just because it's next I don't see why it *must* depend on docker 23.x?

It's not even about the features of next per so, I think the latest release (even if released or not) should be compatible with the majority of the linux lifecycle and not introduce a dependency which has not yet arrived in the package managers of most distros out there.

> Afaik the bump was related to a CVE report. Is there a patch version for the previous version?

#1744 doesn't list any CVE so I can just guess. AFAICS Docker 20.x also get's CVE patches so I'd assume the referenced one was also included as I don't see a reason for docker not to patch the 20.x series for CVEs (https://docs.docker.com/engine/release-notes/20.10/).

**Comment by lafriks** [comment]
I don't see the reason why not to use docker-ce instead that's more up to date version.

**Comment by pat-s** [comment]
As not everyone can control the used repos themselves. In many environments only the managed/built-in repo are allowed by security and no "most recent" ones can installed.

One particular example (out of more) is Suse Enterprise 15.4 which only provides `docker` and not `docker-ce` and the former only in version 20.x. 

I don't understand the motivation against staying compatible for a project aiming towards serving all users/platforms.

**Comment by lafriks** [comment]
wasn't there also compatibility issues with alpine 3.18 anyway on 20.10?
