### ISSUE TITLE
Add forge build in env vars

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#1787]
```
CI_FORGE_TYPE = (gitea,github,...)
CI_FORGE_URL = github.com # gitea.com, codeberg.org, gitea.company.xyz ...
[CI_FORGE_API] = should we craft that too, or leave it to plugins?
```

did I missed something else that is usefull

might be usefull for plugins to address #1376

**Comment by anbraten** [comment]
Nice idea. Even without #1376 it is interesting for plugins to for example load the correct forge library: https://github.com/woodpecker-ci/plugin-surge-preview/blob/main/main.go#L54

**Comment by anbraten** [comment]
linking #621
