### ISSUE TITLE
use 'WOODPECKER_ROOT_URL' not operating properly

### ISSUE THREAD

**Issue by wenchao5211** [woodpecker-ci/woodpecker#1798]
### Component

server

### Describe the bug

i see https://github.com/woodpecker-ci/woodpecker/pull/1783  pr。
When I used the tag of [next-f91ee5d23a](https://hub.docker.com/layers/woodpeckerci/woodpecker-agent/next-f91ee5d23a/images/sha256-bf85a8ad052d42364d96214e8cbf45fe789ba185600d9018124c2ac3c818e268?context=explore)   to verify, I found that the function of `WOODPECKER_ROOT_URL` had not been developed. I used woodpecker + gitea and only corrected the access path of the front-end static file display at present. The other URIs are not deeply modified, https://github.com/devture/com.devture.ansible.role.woodpecker_ci_server/pull/2#issuecomment-1530932964 will this issue on the agenda

### System Info

```shell
kubernets 1.25

woodpecker next-f91ee5d23a 

gitea: latest
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by wenchao5211** [comment]
What I mean is that this function seems to have not been completely completed, currently only static file access is normal, and other access is problematic. when I click woodpecker login, the url I access is' https://xxx/login '. Actually it should be https://xxx/ci/login.Of course, this is just one example, other similar problems can not be listed

**Comment by absolutejam** [comment]
https://github.com/woodpecker-ci/woodpecker/issues/1773#issuecomment-1571623072

I'm experiencing the same thing. I'll see if I can fix the issues I'm having locally and push to a branch.

**Comment by Seryta** [comment]
> Can you give the exact issues? Were are links that do not work for you?

In my environment, the root url of woodpecker is /ci. When I visit example.com/ci, the href in the response html does add /ci, but other js is referenced in it, as shown below:

![image](https://github.com/woodpecker-ci/woodpecker/assets/31036794/02f47671-ca57-4efd-a68f-353bde3d6b44)

And in this js file, the file link it refers to is still without root url:

![image](https://github.com/woodpecker-ci/woodpecker/assets/31036794/d13e3247-967c-45cd-b1ea-e4b821f781a0)

It went to request the file, and 404:

![image](https://github.com/woodpecker-ci/woodpecker/assets/31036794/f45bf183-0947-4cb3-b6f4-c3e6fc800fc8)

**Comment by Seryta** [comment]
After using the latest fix-root code, the previous problem is solved, all the links are 200, but after visiting `example.com/ci`, it is a white screen, nothing is displayed

``` html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="alternate icon" type="image/png" href="/ci/favicons/favicon-light-default.png" id="favicon-png" />
    <link rel="icon" type="image/svg+xml" href="/ci/favicons/favicon-light-default.svg" id="favicon-svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="theme-color" content="#65a30d" />
    <title>Woodpecker</title>
    <script type="" src="/ci/web-config.js"></script>
    <script type="module" crossorigin src="/ci/assets/index-fe797969.js"></script>
    <link rel="stylesheet" href="/ci/assets/index-6d181f24.css">
  </head>
  <body>
    <div id="app"></div>
    
  </body>
</html>

```
![image](https://github.com/woodpecker-ci/woodpecker/assets/31036794/f9badb98-5281-44b2-9a6f-43c4c2a1c0e4)
