### ISSUE TITLE
Release agent for darwin / macos 

### ISSUE THREAD

**Issue by kvaster** [woodpecker-ci/woodpecker#181]
Currently we're investigating CI/CD system for us and it is not clear if it's possible to build iOS applications with woodpecker.

**Comment by laszlocph** [comment]
The Woodpecker frontend communicates with the backend through an API, so a mobile client can be made to use the exact same one.

Here is the go client so you get the impression: https://github.com/laszlocph/woodpecker/blob/master/drone-go/drone/interface.go

**Comment by anbraten** [comment]
@kvaster You probably need to build that app on a macos device / vm? You therefore would need to run at least the Woodpecker agent on macOS which is currently not supported as far as I know.

**Comment by 6543** [comment]
agent does not need cgo so we could cross-compile ...
