### ISSUE TITLE
Issue migrating datastore with `79c8da2`

### ISSUE THREAD

**Issue by pat-s** [woodpecker-ci/woodpecker#1821]
### Component

server

### Describe the bug

Most likely caused by #1817 or #1806?

```
{"time":"2023-06-04T08:53:12Z","message":"LogLevel = info"}
{"level":"error","error":"drop table `steps` columns [step_machine]: pq: column \"step_machine\" of relation \"steps\" does not exist","time":"2023-06-04T08:53:12Z","message":"migration task 'remove-machine-col' failed but is not required"}
{"level":"fatal","error":"pq: Could not complete operation in a failed transaction","time":"2023-06-04T08:53:12Z","message":"could not migrate datastore"}
Stream closed EOF for woodpecker/woodpecker-server-0 (server)
```

I also get the issue with `next-317bd24abb` (which is the commit just before #1817).

With `next-f683c62748` all is good (commit before #1806)

FYI @qwerty287 

### System Info

```shell
-
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by 6543** [comment]
@pat-s please test :) PS: keep in mind our latest main version does have the log bug -> #1802

**Comment by zc-devs** [comment]
`next-556607b5` works for me: there is no the migration issue and logs streaming works too.

**Comment by pat-s** [comment]
Yup works again!
