### ISSUE TITLE
GRPC version mismatch

### ISSUE THREAD

**Issue by Sebclem** [woodpecker-ci/woodpecker#1831]
### Component

server, agent

### Describe the bug

Since this morning, after upgrading to next-556607b5 my agent can't connect to my woopecker-server: 
```json
{"level":"error","error":"GRPC version mismatch","time":"2023-06-06T09:25:04Z","message":"Server version next-556607b5 does report grpc version 3 but we only understand 2"}
```

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-556607b5"}
```

### Additional context

Server env:
```yaml
WOODPECKER_OPEN: "true"
WOODPECKER_HOST: "xxxxxxxx"
WOODPECKER_GITEA: "true"
WOODPECKER_GITEA_URL: xxxxxxxxx
WOODPECKER_GITEA_CLIENT: "{{ woodpecker_gitea_clien_id }}"
WOODPECKER_GITEA_SECRET: "{{ woodpecker_gitea_clien_secret }}"
WOODPECKER_ADMIN: xxxxxxxxx
WOODPECKER_DATABASE_DRIVER: postgres
WOODPECKER_DATABASE_DATASOURCE: "{{ woodpecker_database_datasource }}"
TZ: Europe/Paris
```
Agent env: 
```yaml
TZ: Europe/Paris
WOODPECKER_AGENT_SECRET: "{{ woodpecker_agent_secret }}"
WOODPECKER_SERVER: woodpecker.cloud.home:9000
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by Sebclem** [comment]
Forget about this, by the time I write this issue, this as been fixed by a new agent image version

**Comment by zc-devs** [comment]
> server version 3.0.0-rc1 does report grpc version 11 but we only understand 10
> woodpecker-*:latest

@ki9us, #4597 is for you.
