### ISSUE TITLE
Builds fail with execution error "context deadline exceeded"

### ISSUE THREAD

**Issue by Nutomic** [woodpecker-ci/woodpecker#1836]
### Component

agent

### Describe the bug

Recently a lot of builds are failing with this error message:`Execution error Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.42/containers/wp_01h297rn608hcqja117arzyqmm_0_step_6/json": context deadline exceeded`

Some examples:
- https://woodpecker.join-lemmy.org/LemmyNet/lemmy/pipeline/13/10
- https://woodpecker.join-lemmy.org/LemmyNet/lemmy/pipeline/19/8
- https://woodpecker.join-lemmy.org/LemmyNet/lemmy/pipeline/18/8

As far as I can see it only affects this one repo, others are working fine. Maybe there is a problem with the `.woodpecker.yml` or with a specific docker image used. It seems that the problem started happening after we upgraded to `woodpecker:next-540ad108`.

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-540ad108"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by 6543** [comment]
@Nutomic could you check if next-556607b5 fix it?

I think it could be #1786

**Comment by Nutomic** [comment]
That image doesnt exist, I guess you mean `next-556607b525`? And do we only need to upgrade the builders or also the server?

**Comment by Nutomic** [comment]
Looks like this was fixed, thanks!
