### ISSUE TITLE
Changed files counter shows 0 if opening pipeline directly

### ISSUE THREAD

**Issue by qwerty287** [woodpecker-ci/woodpecker#1843]
### Component

web-ui

### Describe the bug

just saw this... Open for example https://ci.woodpecker-ci.org/woodpecker-ci/woodpecker/pipeline/6081 and look at the changed files counter

### System Info

```shell
our ci
```

![image](https://github.com/woodpecker-ci/woodpecker/assets/24977596/7ed7376f-6643-4748-a65b-f8525f7473cb)

**Comment by anbraten** [comment]
seems to work for me atm
