### ISSUE TITLE
WOODPECKER_HOST is not properly configured

### ISSUE THREAD

**Issue by BegleitPanzer** [woodpecker-ci/woodpecker#1861]
### Component

server

### Describe the bug

Every time I run woodpecker-server I get:
```
{"time":"2023-06-13T10:58:57-04:00","message":"LogLevel = warn"}
{"level":"fatal","time":"2023-06-13T10:58:57-04:00","message":"WOODPECKER_HOST is not properly configured"}
```
This is odd though, because in my server.env file WOODPECKER_HOST was set to `ci.mydomain.com`

### System Info

```
Woodpecker Server: 0.15.9-1 (Installed from the AUR)
```
I really don't know what is supposed to be here because the thing won't even run.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by anbraten** [comment]
Please have a look at the [next](https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use) version of woodpecker or wait for the [1.0.0 release](https://github.com/woodpecker-ci/woodpecker/milestone/4)
