### ISSUE TITLE
migrate-logs-to-log_entries err

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#1865]
server/store/datastore/migration/migration.go:171","message":"migration task 'migrate-logs-to-log_entries' failed but is not required"}
[xorm] [warn]  2023/06/14 02:58:23.234055 Table pipelines column pipeline_error db type is TEXT, struct type is VARCHAR(255)
[xorm] [warn]  2023/06/14 02:58:23.234088 Table pipelines column changed_files db type is TEXT, struct type is JSON
[xorm] [warn]  2023/06/14 02:58:23.265721 Table steps column step_error db type is TEXT, struct type is VARCHAR(500)
{"level":"fatal","error":"Sync error '*model.Step': pq: could not create unique index \"UQE_steps_step_uuid\"","time":"2023-06-14T02:58:23Z","caller":"/woodpecker/src/github.com/woodpecker-ci/woodpecker/cmd/server/setup.go:90","message":"could not migrate datastore"}

**Comment by pat-s** [comment]
Is this happening when going from 0.15 to next?

**Comment by 6543** [comment]
Yes

**Comment by 6543** [comment]
(Postgresql)

**Comment by 6543** [comment]
#1949
