### ISSUE TITLE
Release arm version

### ISSUE THREAD

**Issue by dkaparis** [woodpecker-ci/woodpecker#187]
Using configuration based on the sample docker-compose.yml given in documentation, I get repeated error messages:

`woodpecker-server_1  | standard_init_linux.go:219: exec user process caused: exec format error`
`woodpecker-agent_1   | standard_init_linux.go:219: exec user process caused: exec format error`

Same error occurs both with images v0.9.0 as in the sample, and latest.

System is Armbian (Debian 10-based), linux 4.4.213-rockchip64 aarch64

Docker version 20.10.5, build 55c4c88; docker-compose version 1.21.0

**Comment by laszlocph** [comment]
ARM would need images built for it.
I dropped those Dockerfiles some time ago to increase focus. It could be restored however, if somebody wants to dig it up and test them.

**Comment by dkaparis** [comment]
I'd give it a try, if someone can point me to build instructions.

**Comment by laszlocph** [comment]
This is where I dropped it: https://github.com/laszlocph/woodpecker/commit/8bb5c50eb65785460b45828c90997de209b82223

**Comment by fpiesche** [comment]
Since I'm running a Raspberry Pi k8s cluster at home here and would like to shift away from Drone, I've created [a repo](https://github.com/fpiesche/woodpecker-multiplat) with some Actions that will build multi-platform Docker images for the Woodpecker server and agents.

The images are available from Docker Hub as `florianpiesche/woodpecker-server` and `florianpiesche/woodpecker-agent` respectively and are built as multi-platform manifests for armv6, armv7, arm64 and amd64 via `docker buildx` - but do note they are as yet untested outside of the unit tests.

I've got a little more work to do on that repository as well; specifically I'm planning to have a `development` tag that's kept up to date with the latest commits daily, as well as stable tags for each tagged release here. Currently there's only a `0.13` tag which is the latest tagged release.

**Comment by reivilibre** [comment]
It might be interesting to look at the https://docs.docker.com/buildx/working-with-buildx/ `docker buildx` tools, which can use QEMU to emulate e.g. `arm64` and build multi-arch images.
`.drone.sh` should perhaps not hardcode the `GOARCH`, but I have no experience with Go and couldn't say.

**Comment by 6543** [comment]
similar to #181 ...

**Comment by TheFrenchGhosty** [comment]
@laszlocph This is something we ( @iv-org ) would really like to have. We plan to move to a selfhosted CI, and we need to release an ARM docker image.

**Comment by c-4-m** [comment]
So what is the status of a woodpecker-SERVER docker image for ARM?

Since the solution by fpiesche
> Since I'm running a Raspberry Pi k8s cluster at home here and would like to shift away from Drone, I've created [a repo](https://github.com/fpiesche/woodpecker-multiplat) with some Actions that will build multi-platform Docker images for the Woodpecker server and agents.
> 
> The images are alpine-based and available from Docker Hub as [`florianpiesche/woodpecker-server`](https://hub.docker.com/r/florianpiesche/woodpecker-server) and [`florianpiesche/woodpecker-agent`](https://hub.docker.com/r/florianpiesche/woodpecker-agent) respectively and are built as multi-platform manifests for armv6, armv7, arm64 and amd64 via `docker buildx` - but do note they are as yet untested outside of Woodpecker's unit tests.

is currently outdated, I would like to know if there is an "official" solution on the horizon?

**Comment by fpiesche** [comment]
Sorry I've left my builds unfixed for a while; I've been extremely busy with work and life so haven't had much time to groom my custom Docker builds and mess with my cluster.

As far as I can tell, the reason my builds are broken is that one of Woodpecker's dependencies won't compile on 32-bit ARM - if I can get my kid to bed at a sensible time tonight I'll try and tidy up my repo to produce at least arm64 builds for the server...

**Comment by c-4-m** [comment]
> Sorry I've left my builds unfixed for a while; I've been extremely busy with work and life so haven't had much time to groom my custom Docker builds and mess with my cluster.
> 
> As far as I can tell, the reason my builds are broken is that one of Woodpecker's dependencies won't compile on 32-bit ARM - if I can get my kid to bed at a sensible time tonight I'll try and tidy up my repo to produce at least arm64 builds for the server...

No need to apologize for prioritizing work and life over servicing software for strangers for free :)
Thank you for your efforts!

**Comment by anbraten** [comment]
There will hopefully be an official arm version of the server soonishly. Have a look at #635

**Comment by 6543** [comment]
@anbraten short term we could rent an arm server for an agent to build arm images ...

**Comment by 6543** [comment]
-> #821
