### ISSUE TITLE
Overview of last run status in dashboard

### ISSUE THREAD

**Issue by pat-s** [woodpecker-ci/woodpecker#1872]
### Clear and concise description of the problem

When working with many repos, a global overview showing the status of the last run of each repository is very helpful. Drone is showing this nicely in the UI

![image](https://github.com/woodpecker-ci/woodpecker/assets/8430564/2134ddf0-9a07-4a02-ba67-4035cd5ec1f8)

Would be great to have something similar for WP :)

### Suggested solution

Implement a dynamic status indicator of the last run of a repo

### Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by 6543** [comment]
linking #345

**Comment by xoxys** [comment]
@6543 What was the reason to link it to the admin panel issue?

**Comment by anbraten** [comment]
It has nothing to do with the admin panel

**Comment by xoxys** [comment]
Removed from the liked issue

**Comment by pat-s** [comment]
Ah, great for catching this, forgot about it 😄️
