### ISSUE TITLE
Emoji in logs not parsed correctly

### ISSUE THREAD

**Issue by Sebclem** [woodpecker-ci/woodpecker#1879]
### Component

server, web-ui

### Describe the bug

Since the migration to the new login system, all emoji en logs are not parsed correctly :
![image](https://github.com/woodpecker-ci/woodpecker/assets/23737709/5cb4c0c0-e9bd-4121-8d5f-5c4ebcd9f875)
 Same issue with text generated by toilet: 
![image](https://github.com/woodpecker-ci/woodpecker/assets/23737709/43bbb02c-a8f8-4733-bb7d-1782faa909c1)

Here the entrypoint of my plugin if you need to check what it does : https://git.sebclem.fr/sebclem/woodpecker-ansible-runner/src/branch/master/entrypoint

### System Info

```shell
{
  "source": "https://github.com/woodpecker-ci/woodpecker",
  "version": "next-6ab9f802"
}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by lafriks** [comment]
was it working correctly before?

**Comment by Sebclem** [comment]
I don't have screenshots but yes was working before, i think it's related to https://github.com/woodpecker-ci/woodpecker/pull/1802 but i'm not sure

**Comment by anbraten** [comment]
Unicode chars are currently not working: #1874 fixes it

**Comment by Sebclem** [comment]
Sorry, didn't see this PR, I will close this issue when merged :+1:
