### ISSUE TITLE
BitBucket auth is not working

### ISSUE THREAD

**Issue by kotyara85** [woodpecker-ci/woodpecker#188]
Hey there, we're trying to downgrade from drone.io to woodpecker.
So far everything is up and running, but when I try to authorize vi bitbucket server I'd just show Access approved message and never redirects back to woodpecker.
It does work fine with drone though.
Thanks

**Comment by laszlocph** [comment]
Can you attach your env vars you use with bitbucket?

**Comment by kotyara85** [comment]
Here it's
```
            - name: DRONE_STASH_GIT_PASSWORD
              value: "password"
            - name: DRONE_STASH_GIT_USERNAME
              value: "user"
            - name: DRONE_HOST
              value: https://woodpecker.example.com
            - name: DRONE_STASH
              value: "true"
            - name: DRONE_STASH_CONSUMER_KEY
              value: "key"
            - name: DRONE_STASH_CONSUMER_RSA
              value: "/etc/bitbucket/key.pem"
            - name: DRONE_STASH_URL
              value: "https://bitbucket.example.com"

```

**Comment by kotyara85** [comment]
@laszlocph any suggestions?

**Comment by 6543** [comment]
@kotyara85 can you provide me with a docker-compose for bitbucket instance you run to test against?

**Comment by 6543** [comment]
NOTE: https://hub.docker.com/r/atlassian/bitbucket-server

**Comment by anbraten** [comment]
We dropped support for bitbucket stash with 1.0. Bitbucket cloud was tested by me recently and works fine.
