### ISSUE TITLE
allow deleting runs

### ISSUE THREAD

**Issue by KiaraGrouwstra** [woodpecker-ci/woodpecker#1883]
### Clear and concise description of the problem

sometimes one may want to debug pipelines, which may involve printing sensitive info.
now, one may fortunately set such a repo to private to protect such info, but ideally, one would be able to cleanse any such sensitive info such as to put such a repo public again.

### Suggested solution

allow deleting runs to cleanse sensitive info

### Alternative

keep repo private to protect sensitive info

### Additional context

version: next

### Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by anbraten** [comment]
Would be deleting logs be enough? Otherwise I would recommend to debug using the cli. Removing complete runs would allow to bypass the kind of auditlog it currently has which is often used for quality assurance and prevents for example unaware deployments, manipulated releases, ...

**Comment by KiaraGrouwstra** [comment]
fair, that should do!
