### ISSUE TITLE
SVG animations -> 100 cpu

### ISSUE THREAD

**Issue by JensMadsen** [woodpecker-ci/woodpecker#189]
When using the UI in Chrome on Ubuntu I get 100-200 cpu once the UI has animated SVG icons. I have tried to see if I can fix it m,myself but I cannot get the frontend up and running against our drone server. If I get some help to get it up and running I would like to see if I can fix the cpu issue and submit a PR.

**Comment by laszlocph** [comment]
Can you  try `yarn install` in web, then these?
https://github.com/laszlocph/woodpecker/blob/master/web/README.md#running

This will run a local UI against your actual server. Server that you specify in env vars

**Comment by JensMadsen** [comment]
Thats what I did but I cannot authenticate. I get a 401 and infinite redirect `http://localhost:9999/login?url=http://localhost:9999/login` `http://localhost:9999/login?url=http://localhost:9999/login?url=http://localhost:9999/ `. I get the bearer token for `DRONE_TOKEN` from our running drone server.

**Comment by JensMadsen** [comment]
.... upgraded from ubuntu 18.04 to 20.04 and to a newer laptop. solved the problem

**Comment by laszlocph** [comment]
👌
