### ISSUE TITLE
A failed step should change the top level status of a run

### ISSUE THREAD

**Issue by pat-s** [woodpecker-ci/woodpecker#1893]
### Component

web-ui

### Describe the bug

Currently when running (matrix) builds, when a step fails, the respective step is shown as "failed" but not the specific matrix pipeline.
I.e. in the following screenshot, "build images" is marked as "passed" while in fact it should be marked as "failed" if one step failed.

![image](https://github.com/woodpecker-ci/woodpecker/assets/8430564/17990807-ee12-4f7c-8355-b94bc388631a)

This is especially misleading when the run is collapsed, as it's indicates a successful run and the failure is only visible after expanding the run:

![image](https://github.com/woodpecker-ci/woodpecker/assets/8430564/13481b87-ebee-4540-bdaa-a2b14933a6a4)

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-3033abc3"}
```

### Additional context

related to #1871

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by 6543** [comment]
should be fixed now :)
