### ISSUE TITLE
Statuses are not correctly calculated/reported

### ISSUE THREAD

**Issue by qwerty287** [woodpecker-ci/woodpecker#1895]
### Component

server

### Describe the bug

1. https://ci.woodpecker-ci.org/repos/3780/pipeline/6235/31 fails, but the pipeline is marked as success.
2. ![](https://github.com/woodpecker-ci/woodpecker/assets/80460567/f64df20e-eb36-4f9f-9196-68336ce1b435)

### System Info

```shell
our ci
```

### Additional context

Could be related to https://github.com/woodpecker-ci/woodpecker/issues/1871 and https://github.com/woodpecker-ci/woodpecker/issues/1893

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by dessalines** [comment]
I'm also getting this: `{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-e1c31df6"}`
