### ISSUE TITLE
workflow config view not colapsable

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#1924]
e.g. https://ci.woodpecker-ci.org/repos/3780/pipeline/6355/config

version: `"next-2ba64dcb`

if you click on the header the view should be able to un-/colapse (hide it's content part)

**Comment by vinay-nb** [comment]
Hi Can I work on this?

**Comment by 6543** [comment]
Sure, just submit a pull :)

**Comment by xoxys** [comment]
Fixed by: https://github.com/woodpecker-ci/woodpecker/pull/2166
