### ISSUE TITLE
Allow/Block-Lists for repos & users

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#193]
We at codeberg looking at a CI that fits our needs.

A feature against abuse would be some whitelisting.

Ref: https://codeberg.org/Codeberg/Community/issues/428#issuecomment-195258

**Comment by 6543** [comment]
@laszlocph do there exist a chat for the woodpecker comunity? like a official matrix room or discord server etc ...

**Comment by laszlocph** [comment]
How about Discord? https://discord.gg/fcMQqSMXJy

There is basic build approval logic in the code now: if a repo is "Protected" then PRs not from the project org need to be approved manually
https://github.com/laszlocph/woodpecker/pull/51

![Screenshot from 2021-05-03 10-59-35](https://user-images.githubusercontent.com/4289031/116858463-b1534780-abfe-11eb-8fb6-8cda9ba45c1b.png)
![Screenshot from 2021-05-03 10-59-25](https://user-images.githubusercontent.com/4289031/116858464-b1ebde00-abfe-11eb-81a7-acc6701d6d11.png)

**Comment by 6543** [comment]
close since new issue with clear description was created -> #336
