### ISSUE TITLE
Add option, to log to file

### ISSUE THREAD

**Issue by lonix1** [woodpecker-ci/woodpecker#1933]
### Clear and concise description of the problem

# BACKGROUND
Woodpecker seems to log to `stdout` only, and thus to docker's built-in "json driver". The logs can be access like so:
- `$ docker logs -t $CONTAINER_NAME`
- `tail -f /var/lib/docker/containers/$CONTAINER_ID/$CONTAINER_ID-json.log`

# PROBLEM
When the container is recycled, the logs are lost. The workaround is to use another logging tool, but that is unnecessary complexity, especially for small deployments.

Also, in general, the logs are not in a friendly format - it's much simpler, especially in small deployments, to simply have the log in a file that can be easily manipulated. Not everyone uses large complex logging apps and servers, etc.

### Suggested solution

# SOLUTION
Many apps have an option to log to file as well. Gitea does that, for example.

It would be nice if the log could be sent to a file instead of (or in addition to) stdout. If enabled, it could be written to `/var/lib/woodpecker/app.log` by default.

Personally, I would mount it as `/var/log/woodpecker.log:/var/lib/woodpecker/app.log` so that I could have it on the host, and use logrotate on it.

### Alternative

An unnecessarily complicated environment that includes log aggregation and monitoring, and who knows what else. For small servers that is overkill and hard to manage.

### Additional context

Thank you for considering it!

### Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by anbraten** [comment]
I don't see the underlying issue.

Currently a no as of following reasons:
- you can already use bash pipes to write to a file and add mounts
- this seems to be a pretty special docker backend related use-case and would introduce other issues exp when using multiple agents etc

**Comment by 6543** [comment]
so if we would add some `WOODPECKER_LOG_FILE` witch is by default `` so it's stdout

and if set, instead of stdout it will print to mentioned destination?

**Comment by 6543** [comment]
->  #2115
