### ISSUE TITLE
Add an healthcheck to server container

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#1943]
like the agent:
https://github.com/woodpecker-ci/woodpecker/blob/205f8ecc1649ab48a9d5fb52b0ecd7b8c24abf4f/docker/Dockerfile.agent.multiarch#L21

ref https://docs.docker.com/engine/reference/builder/#healthcheck

TODO:
- [ ] add subcommand to server that can test against https://github.com/woodpecker-ci/woodpecker/blob/205f8ecc1649ab48a9d5fb52b0ecd7b8c24abf4f/server/router/router.go#L69
- [ ] use subcommand in container

**Comment by 6543** [comment]
Yes but we cant use wget and need a build in func for tje from-scratch container

**Comment by 6543** [comment]
but `next-45319b24cd` is not ... and so if we officially want to support it ... we have to do it that way

**Comment by lafriks** [comment]
The best option would be to add a command line option that would call the health check endpoint and return the exit code based on response

**Comment by 6543** [comment]
That's exactly whatvi try to write 😅
