### ISSUE TITLE
expose new build-in swagger api UI

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#1944]
e.g. https://ci.woodpecker-ci.org/swagger/index.html 

- [x] link from normal WebUI to it #1984 
- [ ] redirect `<rootURL>/swagger/*` to it
- [x] server flag to disable swaggerUI #2093

**Comment by 6543** [comment]
hide it would not make a difference as api is public documented anyway - we are a opensource project and follow good security practices :laughing: (not security by obscurity) ... anyway disable it is a valid suggestion

**Comment by anbraten** [comment]
added apart from the redirect (which seems to be not really necessary).
