### ISSUE TITLE
Show cancelled builds in another color than failed builds

### ISSUE THREAD

**Issue by dr460nf1r3** [woodpecker-ci/woodpecker#1946]
### Clear and concise description of the problem

Currently, when cancelling a build either manually or via the cancel running pipeline feature, they show up as failed as indicated by the red color. This alarms users about a failure and an eventually needed manual intervention.

### Suggested solution

Showing the cancelled builds in another color, eg. grey, would indicate this is actually the desired outcome of given configuration and would not alarm the user about eventually needed interventions.

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by 6543** [comment]
that's a known bug :/ ->  #833

**Comment by dr460nf1r3** [comment]
Oh, I must've missed this while searching for similar issues :/

Before I open another issue (already looked for similar ones), is there already one concerning no more log streams to the log view when a lot of output is getting generated? @6543
