### ISSUE TITLE
Logs missing and "unknown error" printed on exit code 2

### ISSUE THREAD

**Issue by strk** [woodpecker-ci/woodpecker#1951]
### Component

agent

### Describe the bug

We are getting `exit code 2` as the ONLY error message for a pipeline, with no other information, and replacing previously gathered logs about the job being executed.

I connected to the container running the step and did see it working fine and doing its things until my interactive shell section got killed by something (I guess by the agent) and its processes output logs, previously shown on the job page were replaced by this obscure `exit code 2`.

See https://trac.osgeo.org/postgis/ticket/5438 for details

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"0.15.5"}
```

### Additional context

![image](https://github.com/woodpecker-ci/woodpecker/assets/289678/76ab3379-f427-47b4-a22e-e752902619dc)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by strk** [comment]
Under which occurrences does the agent kill the containers running jobs ?

Could this be a case of no output coming out for too much time ?
If so I think the web UI should (1) not hide the logs gathered until that point (2) tell what the problem was, rather than "An unkonwn error occurred"

**Comment by strk** [comment]
We found out what the problem was by running the job manually in the container.
Doing so we were able to read the actual error message, which was printed to stderr, and the exit status (which was 2)

**Comment by 6543** [comment]
uh ... stderr should be logged too :eyes:

**Comment by strk** [comment]
The problem in this case is that EVERYTHING gets removed, even after being initially visible, that's the concerning part

**Comment by strk** [comment]
I just found out that the "unknown error" is also occurring on builds that are otherwise marked green !
See https://woodie.osgeo.org/postgis/postgis/build/593/10 and click on "build-pdf" under the "docs" section

**Comment by 6543** [comment]
that looks strange ... api just tell 404 without message

**Comment by 6543** [comment]
you are running on 0.15.5 ... you should consider to update to [0.15.9](https://github.com/woodpecker-ci/woodpecker/releases/tag/v0.15.9)

**Comment by 6543** [comment]
if it will fix the problem I dont know

**Comment by 6543** [comment]
first err could be  #1620

**Comment by 6543** [comment]
v1.0.0 is just tagged and it should be upgraded :)
