### ISSUE TITLE
Organizations tab for admins

### ISSUE THREAD

**Issue by lonix1** [woodpecker-ci/woodpecker#1968]
### Clear and concise description of the problem

The server config page shows tabs: "Secrets", "Users", "Agents" and "Queue".

There should be another tab, "Organizations".

There are various org-level settings, e.g. organization secrets (exposed by the API), but they aren't viewable in the UI. So they are effectively "hidden" and it's easy to forget about it.

### Suggested solution

A new tab named "Organizations".

Doesn't need to be complicated, or to allow interaction. Only to show the orgs, and secrets related to them. Readonly to keep it simple.

### Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by 6543** [comment]
well reread your isssue ... and yes your feature is already in the webUI ... nother the less we can use a org tab at the admin pannell from now on, as mentioned pull do store them
