### ISSUE TITLE
Do we need a syncing repos via API? [-> no]

### ISSUE THREAD

**Issue by pat-s** [woodpecker-ci/woodpecker#1973]
### Clear and concise description of the problem

It seems there's no API endpoint to sync repos? Would be great to have one. 

### Suggested solution

Add an API endpoint to sync new repos. 

### Additional context

I have some need for it within some automation which 

1. syncs new repos
2. enables repos
3. triggers a build by an automated commit

Apologies if I have overlooked the obvious - but I couldn't get it working even when invoking other endpoints (with the aim of triggering an implicit sync). 

### Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by 6543** [comment]
there is no need as they get queried on demand to be activated

you need:
1. get repos (optionallly filtered)
2. enable repos
3. ...

**Comment by 6543** [comment]
1. https://github.com/woodpecker-ci/woodpecker/blob/fe7eb64bf9fdeb3243dedaf53f35b32f19e59646/server/router/api.go#L34
  & query: all=true
2. https://github.com/woodpecker-ci/woodpecker/blob/fe7eb64bf9fdeb3243dedaf53f35b32f19e59646/server/router/api.go#L65

**Comment by 6543** [comment]
and if you already know the remote-repo-id you can just do step 2.

**Comment by 6543** [comment]
while I was looking at it, found:  #1974

**Comment by pat-s** [comment]
Thanks for the quick reply!

I tried your suggested workflow (also before opening this issue) but wasn't successful. I did

1. `user/repos` -> successful
2. `repos/lookup/<slug>` -> failure, even though the repo exists and the call looks good
3. `repos/<id>` -> to activate; Pending

For (2) I get the following return

```
Status code was 404 and not [200]: HTTP Error 404: Not Found
```

I can lookup other (old) repos just fine (proofing that I use the endpoint correctly) but recently created ones (without a manual sync in the UI) don't show up when using this API-only approach. 

Am I overlooking something?

**Comment by pat-s** [comment]
Hmm OK no, `user/repos` does not do an interactive sync. I can only see repos which are already activated. Confirmed with

```
curl -s -X GET https://$INSTANCE/api/user/repos -H "Authorization: Bearer $TOKEN" | jq '.[] | .full_name'
```

Gonna re-open this one as I think there's an issue.

> & query: all=true

Is this was I am missing? I can't see this documented anywhere 🤔

**Comment by pat-s** [comment]
Using `curl -s -X GET https://$INSTANCE/api/user/repos?all=true -H "Authorization: Bearer $TOKEN" | jq '.[] | .full_name'` gets me all repos but the unactivated ones don't have an ID field. Which is required to active the repo 🤔 

(BTW: the `all=true` query is not documented in the API docs)

**Comment by 6543** [comment]
Hmm we also have to add tge all query option to swagger docs

**Comment by 6543** [comment]
https://github.com/woodpecker-ci/woodpecker/pull/1974/commits/3874dded39c1bcdc1bdd7dfae6e7ba895023f754

**Comment by pat-s** [comment]
Also I noticed that the `repos/<id>` API endpoint always returns a 200 even if non-valid repo ID's are used.

**Comment by pat-s** [comment]
@anbraten @6543 Unless I am overlooking something badly, this could be a bug? I can reproduce it using the above `curl` commands. Happy to open a new issue but first wanted to double-check with you.

**Comment by anbraten** [comment]
To verify how it works you could have a look into the networks tab of your browser while activating a repo in the UI. For the 200 code that go also reported in #1947

**Comment by pat-s** [comment]
Good idea. AFAICS the call looks like `https://$INSTANCE/api/repos?forge_remote_id=$ID`. 

So `forge_remote_id` is handed over as a query rather and I tried to use it directly in the path like `api/repos/<forge_remote_id>`. 🤦 
I overlooked that it's a query instead of a path parameter - my bad! I think an example could have avoided that. Or testing interactively via the (newish) swagger UI. But anyhow, human error...

Thanks a ton!!
