### ISSUE TITLE
Avoid running the same workflows for push & PR events

### ISSUE THREAD

**Issue by pat-s** [woodpecker-ci/woodpecker#1980]
Currently many PRs run duplicated workflows, one for the PR and one for the push trigger.

To save resources this could be filtered to run the PR one's only? Push workflows are only needed on the default branch?

![image](https://github.com/woodpecker-ci/woodpecker/assets/8430564/32b75aff-080e-47fe-a38a-ae8208fd69d6)

**Comment by anbraten** [comment]
https://github.com/woodpecker-ci/woodpecker/pull/1130
