### ISSUE TITLE
agent option "stop agent from taking new tasks" not working

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#1990]
version: 8d625788461eacfbb3645a40c4ef099cb2737afb do not respect this option

**Comment by runephilosof-karnovgroup** [comment]
If https://ci.woodpecker-ci.org/repos/3780/pipeline/10780/9 is using the autoscaler then this issue might be causing the
```
Oh no, we got some errors!
Canceled
```
When an agent is shut down while processing a pipeline, this is sometimes the error message woodpecker shows.

**Comment by anbraten** [comment]
Good catch.

**Comment by anbraten** [comment]
I checked again and with my agent in the debugger it seems to work and stops in https://github.com/woodpecker-ci/woodpecker/blob/619858e0e96743dc72079b5f1989a2f415138119/server/grpc/rpc.go#L68

**Comment by zc-devs** [comment]
`2.1.1`, Kubernetes - doesn't work.

**Comment by anbraten** [comment]
The issue seems to be that the agent is long-polling and as soon as its inside of the [`queue.Poll()`](https://github.com/anbraten/woodpecker/blob/e573513b1d71e5779f8776a60b365669927e9bee/server/queue/fifo.go#L97)  loop it wont recognize updates to `NoSchedule`.
