### ISSUE TITLE
Org membership lookup failed for regular users

### ISSUE THREAD

**Issue by xoxys** [woodpecker-ci/woodpecker#1993]
### Component

server

### Describe the bug

Clicking on the username part of a repository results in an error message, while it works for organizations:

![image](https://github.com/woodpecker-ci/woodpecker/assets/3391958/15f46de0-8e14-45ef-8d34-a8a8ab1521b7)
![image](https://github.com/woodpecker-ci/woodpecker/assets/3391958/73b7daad-1bf4-4b20-8514-ab59613fb1da)

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-87cef417"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by xoxys** [comment]
As the issue is closed and the PR merged, shouldn't this work on `next` then?

**Comment by anbraten** [comment]
Sorry, linked the wrong PR. Should have been: #1873

**Comment by xoxys** [comment]
Ah, thanks :+1:
