### ISSUE TITLE
publish images to  quay.io too

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#1995]
next to docker.io push to  quay.io too

**Comment by anbraten** [comment]
I wouldn't add quay.io at the moment. Docker-hub is free for us again and currently works. With the recent things going on at RedHat I am not really sure if quay.io is a better place. Adding any additional registry would currently just be maintenance overhead and additional problems.

**Comment by xoxys** [comment]
What problems do you see that would be added? IMO, relying on the availability of a single public registry is a bad idea and has already caused trouble for many users in the past. Removing DockerHub in favor of Quay may be questionable, but I would like to see at least a second registry added as fallback. This could be Quay or GitHub Container registry. The maintenance overhead is also quite low to my experiences. I have set this up for a lot of repos and it "just works" reliable in the same way it works for the DockerHub upload process of your CI.

**Comment by anbraten** [comment]
As long as all works its most of the time fine, until sth does not work straightforward. All those tiny things are often adding maintenance overhead in the end. Things like uploading does not work (credentials are outdated, ...), we need to update all image strings at all places in code, docs etc, users could be confused which registry to choose, ...

**Comment by xoxys** [comment]
I see. In case Docker will decide tomorrow to kill all open source free projects (and we had nearly such situations already) things will become unusable immediatly.

**Comment by 6543** [comment]
I'll add and maintain that :)
