### ISSUE TITLE
ui: back arrow button of pipeline view does not lead to repo 

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#1998]
the back button return to the previous site/url and not to the repo the pipeline do run in

regression of #1691 

![image](https://github.com/woodpecker-ci/woodpecker/assets/24977596/b492d9ce-c452-4607-8b13-a63174af0210)

**Comment by pat-s** [comment]
I noticed this as well but was not motivated enough to report 😓 
There might be more "back button" issues - I often encounter situations where I would have expected something else to happen compared to what happened instead (sometimes followed by a red error message in the bottom right).

**Comment by 6543** [comment]
Well if you expect X and got Y ... it's bad UX design and should be fixed

**Comment by pat-s** [comment]
I second your observation: 

> the back button return to the previous site/url and not to the repo the pipeline do run in

I'll try to describe other "unnatural" behavior next time I encounter it
