### ISSUE TITLE
All tasks are missing / empty from woodpecker-server on `next-669abdf6`

### ISSUE THREAD

**Issue by dessalines** [woodpecker-ci/woodpecker#1999]
### Component

server

### Describe the bug

`{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-669abdf6"}`

![Screenshot_2023-07-14-17-13-33-207_mark via gp](https://github.com/woodpecker-ci/woodpecker/assets/930215/06f0e91a-1fbf-4208-9598-ad0d78c6d40a)

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-669abdf6"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by dessalines** [comment]
Nevermind, it appears to only affect builds done before the server upgrade. Apologies.

**Comment by 6543** [comment]
is migration not working ?!?
