### ISSUE TITLE
`depends_on` randomly ignored

### ISSUE THREAD

**Issue by alexef** [woodpecker-ci/woodpecker#200]
I have a repo with 3 pipelines:
```
- .drone/build.yml
- .drone/test.yml
- .drone/deploy.yml
```
the `deploy.yml` contains:
```
depends_on:
- build
- test
```

this works as expected most of the times, in the sense that:
- deploy waits for both `build` and `test` pipelines to finish successfully before starting

some times, randomly, when `build` fails in a stage in the middle, and `test` succeeds, `deploy` is **triggered** and executes. Why would that happen?

Attaching a couple of screenshots: 
<img width="336" alt="Screenshot 2021-05-20 at 17 11 48" src="https://user-images.githubusercontent.com/346576/119004033-7e46dd00-b98e-11eb-973b-83d00079c970.png">
<img width="343" alt="Screenshot 2021-05-20 at 17 11 40" src="https://user-images.githubusercontent.com/346576/119004040-8010a080-b98e-11eb-9dd5-f8ea61f7149f.png">

**Comment by laszlocph** [comment]
Made two tests: one trivial and one multithreaded for your case.
They both pass.

Can you verify if it matches your case: https://github.com/laszlocph/woodpecker/commit/3849d1e2b3623b31beb50f9d007e85cf8ba1ec02

I will try to come up with more extreme theories/testcases

**Comment by alexef** [comment]
Today we had another occurrence of this issue:
![Screenshot 2021-05-25 at 13 38 56](https://user-images.githubusercontent.com/346576/119491822-a94e7980-bd5e-11eb-8fad-eabc411fef6c.png)

If it helps, this time the failing step was part of a `group` that ran in parallel, this is why you seen green steps afterwards.

**Comment by laszlocph** [comment]
A potential fix was merged and released in https://github.com/laszlocph/woodpecker/releases/tag/v0.14.0-rc.1

Basically if a pipeline depended on more than one pipeline, only the first pipeline outcome was regarded. This could explain your case, but best would be if you come back with a some stats after using it for a week or two.

**Comment by alexef** [comment]
will deploy it now and report back

**Comment by alexef** [comment]
running 14.rc for 8 days now, we didn't see new occurrences, I believe we can close this

**Comment by laszlocph** [comment]
Thank god.
