### ISSUE TITLE
Agent config not created

### ISSUE THREAD

**Issue by lafriks** [woodpecker-ci/woodpecker#2010]
In latest version when adding new agent I don't see log record about agent being registered in logs and agent config file is not written. Could be related to #1971?

**Comment by lafriks** [comment]
In older agent I have only `agent-id.conf` that is how it was written previously

**Comment by 6543** [comment]
Fixed by c805c87e9035898e712c918cbbdda9c4394013e5

**Comment by lafriks** [comment]
oh, damn, I was too slow 😆  Thanks 🎉

**Comment by 6543** [comment]
To be specific, it got introduced while fightung the linter ...

**Comment by 6543** [comment]
Anyway we now have tests to check it also in place :)
