### ISSUE TITLE
ignoring hook: hook parsing resulted in empty build

### ISSUE THREAD

**Issue by JulienPalard** [woodpecker-ci/woodpecker#2015]
### Component

server

### Describe the bug

I'm getting `ignoring hook: hook parsing resulted in empty build` in the logs without explanation. I think something more could be logged here.

To get it I added a `.woodpecker.yml` file to a repo in a PR, seen it's ignored, tried to debug by reading the logs.

I'm probably just tired and I didn't took my coffee yet, and forgot something, I'm opening this issue only because I think the logs could be enhanced for this case.

I pushed the log level to `trace` and got:

```text
Jul 19 09:17:30 woodpecker1 woodpecker-server[618821]: {"level":"trace","time":"2023-07-19T09:17:30Z","caller":"/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/router.go:38","message":"[POST] /hook?access_token=[obviously-redacted]"}
Jul 19 09:17:30 woodpecker1 woodpecker-server[618821]: {"level":"debug","time":"2023-07-19T09:17:30Z","caller":"/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/hook.go:90","message":"ignoring hook: hook parsing resulted in empty build"}
Jul 19 09:17:30 woodpecker1 woodpecker-server[618821]: {"level":"info","ip":"2001:4b98:dc0:43:f816:3eff:fed8:3222","latency":0.53809,"method":"POST","path":"/hook","status":200,"time":"2023-07-19T09:17:30Z","user-agent":"Go-http-client/1.1","time":"2023-07-19T09:17:30Z","caller":"/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/logger.go:45"}
```

The PR triggering this is here: https://git.afpy.org/AFPy/pospell/pulls/9

The woodpecker is here: https://woodpecker.afpy.org/AFPy/pospell

I know this looks like a "please debug my setup" issue, but I'd prefer for woodpecker to log something a tad more verbose so next time someone falls in the same trap as me he'll be able to get out more easily.

I don't read `go`, so ... I'm probably not helpfull here: it looks like if there's an error it's bubbled up and logged by `hook.go`, so I expect `tmpBuild is nil and err is nil` out of `forge.Hook()`, the only path is from `return nil, nil, nil` near `// ignore hook`, so there's either no repo or no pipeline. I don't see how this can happen without logging.

But it looks like the error may be misleading: maybe the repo is nil, not the build, as it's behind:

```go
	if repo == nil || pipeline == nil {
		// ignore  hook
		return nil, nil, nil
	}
```

But this has been removed in https://github.com/woodpecker-ci/woodpecker/pull/1942 so maybe I'd get "failure to ascertain repo from hook" now?

### System Info

```shell
woodpecker 0.15.11 with gitea 1.20.0 both running on Debian bullseye.
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by 6543** [comment]
we are now at v2.1 ... and this should code part should be refactored a lot & fixed
