### ISSUE TITLE
JSON schema out of date

### ISSUE THREAD

**Issue by lonix1** [woodpecker-ci/woodpecker#2020]
### Component

other

### Describe the bug

Since https://github.com/woodpecker-ci/woodpecker/issues/1948 was fixed (yesterday), the json schema for `.woodpecker` is out of date, but that issue was locked so I can't comment  there.

This is possible so that the logs show "clone" (as it was before the fix) instead of "git":
```yml
clone:
  clone:           # can be any word: "clone", "git" or whatever
    image: woodpeckerci/plugin-git:2.0.3
steps:
  build:
    # ...
```
But the schema [only allows `"git"`](https://github.com/woodpecker-ci/woodpecker/blob/3a85559763a5a9df197ffc04a4c22294ccf5097b/pipeline/schema/schema.json#L45). If I use `"clone"` then I get an error in vscode: `Property clone is not allowed.`.

I couldn't submit a PR because I'm unsure how to fix it - I can't just change "git" to "clone" as both are valid, as well as any other word.

(I'm willing to try fixing it if someone has an idea how to specify "any word"?)

### System Info

```shell
version next
vscode
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by 6543** [comment]
#2063

**Comment by 6543** [comment]
Well I'm not aware of how we should version tje schemastore ... so it can only bee about making sure it's about latest stable ...
