### ISSUE TITLE
unknown name with evaluate condition

### ISSUE THREAD

**Issue by twatel** [woodpecker-ci/woodpecker#2026]
### Component

agent

### Describe the bug

Hi, i report you this issue because i got this error when i tried to apply some condition in my pipeline : 

![image](https://github.com/woodpecker-ci/woodpecker/assets/113833571/5cb3bfec-b00a-4064-b064-8524c6b9c79e)

Here is my pipeline code : 
![image](https://github.com/woodpecker-ci/woodpecker/assets/113833571/90f2f875-957a-46e6-a06e-b094a1b93121)

Is my code wrong or something ? 

### System Info

```shell
woodpecker-agent version next-1fa02127

![image](https://github.com/woodpecker-ci/woodpecker/assets/113833571/90f2f875-957a-46e6-a06e-b094a1b93121)
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by anbraten** [comment]
How did you solved it?

**Comment by twatel** [comment]
> How did you solved it?

Sorry i didn't solve it, but the issue already exist : https://github.com/woodpecker-ci/woodpecker/pull/1907

**Comment by 6543** [comment]
Hmm that's a pull not an issue ?

**Comment by twatel** [comment]
> Hmm that's a pull not an issue ?

Yes you're right

**Comment by twatel** [comment]
Hey, this error have been solve in the new release ! 
https://github.com/woodpecker-ci/woodpecker/releases/tag/v1.0.0-rc1

Enjoy
