### ISSUE TITLE
Kubernetes backend : too many agents registered

### ISSUE THREAD

**Issue by ymettier** [woodpecker-ci/woodpecker#2027]
### Component

server, agent

### Describe the bug

I noticed that I have a lot of agents declared in http://my-ci/admin/settings#agents.

After few tests, I noticed that every time I restart a pod with an agent, it registers itself, adding a new agent declared in http://my-ci/admin/settings#agents.

Note : in the Kubernetes world, pods can be deleted at any time, for load balancing, draining a node, upgrading, or any other good or bad reason. With the Helm chart provided at [woodpecker-ci/helm](https://github.com/woodpecker-ci/helm) the pods are under control of a Deployment, which means that they are stateless. Any new pod has no idea of the registration of the older one.

Bug : some cleanup should be done automatically when a pod is removed.

Suggestion : when an pod terminates, the agent should unregister before leaving.

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-2e851ba4"}

Backend: Kubernetes
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by ymettier** [comment]
Of course : a manual fix is to remove all the agents. Then restart the pods : they will registers automatically.

**Comment by zc-devs** [comment]
> some cleanup should be done automatically when a pod is removed.

+1. Or by scheduled task at least.

>  when an pod terminates, the agent should unregister before leaving.

+1.

Seems the same problem appears for autoscaler. And I wonder if it has been resolved somehow.

As a workaround we can:
1. Make it statefulset ([1](https://github.com/woodpecker-ci/woodpecker/pull/1888#issuecomment-1612720214), [2](https://github.com/woodpecker-ci/woodpecker/pull/1971))
2. Use [agent token](https://woodpecker-ci.org/docs/next/administration/agent-config#using-agent-token) if we have one agent, because configuring that way more agents is inconvenient.

**Comment by pat-s** [comment]
I second this behavior and have also asked/reported this somewhere some months ago but can't find it anymore.

> Suggestion : when an pod terminates, the agent should unregister before leaving.

I think this would be the best approach. I don't think that switching to a statefulset would make anything better.
