### ISSUE TITLE
Dark terminal "breaks" ANSI colors

### ISSUE THREAD

**Issue by feliperuiz** [woodpecker-ci/woodpecker#203]
`ansi-bright-white-fg` has a value of `#151515`, which is a rather black color. Ignoring the confusing aspect of bright-white being a rather dark black, after #196 got merged, anything using it is pretty much unreadable, as can be seen in the screenshot below:
<img width="731" alt="image" src="https://user-images.githubusercontent.com/3370823/119533745-77510d80-bd86-11eb-8f74-238a7f875964.png">

**Comment by laszlocph** [comment]
Oops. I guess the PR should have to adjusted that too. We will adjust it accordingly.

**Comment by sudip-moengage** [comment]
@laszlocph How to enable colored log lines? I am generating colored logs from my python script but all logs are still black. And how to enable dark mode?

**Comment by sudip-moengage** [comment]
Nevermind! This fixed my problem: https://github.com/pallets/click/issues/1090
