### ISSUE TITLE
Does not pull latest plugin image when using implicit 'latest'

### ISSUE THREAD

**Issue by lonix1** [woodpecker-ci/woodpecker#2060]
### Component

server

### Describe the bug

Suppose a plugin is referenced by implicit `:latest` rather than explicit `:0.1.2`:
```yml
variables:
  - &PLUGIN gitea.example.com/my-org/my-repo
```

Now suppose that plugin is updated to `0.1.3`. The next time this pipeline runs, I'd expect it to automatically pull the latest version, but it does not - it continues to use the old version.

To force it to pull and use the new version, I need to change from implicit `:latest` to explicit `:0.1.3`.

I'm not sure if that's intentional? But it's surprising, given docker always checks whether `latest` is really the latest, and pulls the real latest before running an image.

### System Info

```shell
1.0.0-rc1
docker
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by 6543** [comment]
that's nothing a plugin can do about, it's how the docker image release is configured

**Comment by 6543** [comment]
No woodpecker bever interfeared with how docker/podman/... pull images

**Comment by 6543** [comment]
You describe what you want and you will get it if it exists

**Comment by 6543** [comment]
I read your issue as, latest did had the RC and you expect th not contain rc's just latest stable ...?

**Comment by 6543** [comment]
Ah thats because by default woodpecker dont pull images if it finds an existing one

If you like to see it pulled you either can pull from time to time upfront on the agents or config it via pipeline config: https://woodpecker-ci.org/docs/usage/pipeline-syntax#image (pull: true)

**Comment by tyler71** [comment]
Ran into this issue. Provided link isn't correct anymore.
For reference, the documentation for this can be found here now:
https://woodpecker-ci.org/docs/next/usage/workflow-syntax#image

**Comment by truenicoco** [comment]
> Feedback: it's a pity one must specify `pull: true` on each step - it would be a nice top-level setting to have `pull: true` for all steps in the pipeline.

Is that true though? If you use sequential steps and pull on the first step, then you have the up-to-date image in all steps, don't you?
