### ISSUE TITLE
Using squash merge

### ISSUE THREAD

**Issue by inverse** [woodpecker-ci/woodpecker#207]
@laszlocph what do you think of changing the default merge strategy to squash to have cleaner git history when merging pull requests?  

While you can easily do this on the merge button arrow you can set this as the default by disallowing merge from the settings main page.

**Comment by laszlocph** [comment]
I can allow / disallow, but can't set a default. I'm not very good at this. What option do you prefer?

![image](https://user-images.githubusercontent.com/4289031/119941349-c7032500-bf90-11eb-8fa8-b7a1d704f514.png)

**Comment by jolheiser** [comment]
I recommend leaving the squash option enabled and disabling the other two. (or at least the top one)

**Comment by inverse** [comment]
I normally go with disabling the top one 👍🏼

**Comment by laszlocph** [comment]
Set
![image](https://user-images.githubusercontent.com/4289031/120185737-e315f900-c212-11eb-9d35-22229b68ecb7.png)
