### ISSUE TITLE
Phase out environment variables prefixed DRONE_, use WOODPECKER_

### ISSUE THREAD

**Issue by marians** [woodpecker-ci/woodpecker#209]
Currently (as of v0.13.0), every environment variable for configuring woodpecker seems to come in two flavours: One prefixed `DRONE_` and one prefixed `WOODPECKER_`.

The coexistence of these two versions of variables with identical meaning makes documentation, help text, and error messages hard to read (see my PR https://github.com/woodpecker-ci/woodpecker/pull/208 for an example).

To improve the user experience, I recommend to make a decision regarding when to drop the `DRONE_` spelling and communicate that decision clearly.

Since woodpecker is still in the v0.x.x major version realm, I would argue such a change could happen with any minor version bump.

**Comment by laszlocph** [comment]
Let's do it.

**Comment by marians** [comment]
How about using the occasion for these additional clean-ups?

- Remove `DATABASE_DRIVER` in favour of `WOODPECKER_DATABASE_DRIVER`
- Remove `DATABASE_CONFIG` in favour of `WOODPECKER_DATABASE_DATASOURCE`
- Remove `WOODPECKER_HOST`in favour of `WOODPECKER_SERVER_HOST`
- Remove `WOODPECKER_SECRET` in favour of `WOODPECKER_AGENT_SECRET`

IMO it would help to remove the guesswork and make the code more maintainable.

**Comment by marians** [comment]
... and rename `XDG_CACHE_HOME` to `WOODPECKER_LETS_ENCRYPT_PATH`

**Comment by tboerger** [comment]
It's best practice for many projects to prefix the env variables by the project name, so let's use WOODPECKER_.

The xdg env variable should keep the name as it is.

**Comment by tboerger** [comment]
XDG_CACHE_HOME is a standard env variable name from freedesktop and it's only the base path where the let's encrypt certificates are stored.
