### ISSUE TITLE
Introduce issue labels

### ISSUE THREAD

**Issue by marians** [woodpecker-ci/woodpecker#210]
I'm thinking some labels would make issues here more useful.

- easier to filter
- easier to understand context

Some labels I would add:

- Component based labels, e. g.
  - `server`
  - `agent`
  - `ui`
  - `plugin`
  - `documentation`
- Labels classifying an issue by type
  - `bug`
  - `improvement`
  - `question`
  - `discussion`
  - `epic`
- `governance` (for issues like this, topics like dev collaboration, reviews, licensing, ...)

**Comment by marians** [comment]
... and not to forget for the different RCS `github`, `gitlab`, `gitea` etc.

**Comment by laszlocph** [comment]
Sounds good to me. Added the proposed labels.
