### ISSUE TITLE
Cloning repo fails with "fatal: no path specified" / exit 128

### ISSUE THREAD

**Issue by dr460nf1r3** [woodpecker-ci/woodpecker#2111]
### Component

server, agent

### Describe the bug

Web UI logs:
~~~
+ git config --global http.sslVerify false
+ git init -b main
Initialized empty Git repository in /woodpecker/src/19[2](http://192.168.22.78:8000/repos/2/pipeline/472#L2).1[6](http://192.168.22.78:8000/repos/2/pipeline/472#L6)8.22.[7](http://192.168.22.78:8000/repos/2/pipeline/472#L7)8/org/repo/.git/
+ git remote add origin 
+ git fetch --no-tags --depth=1 --filter=tree:0 origin +refs/heads/main:
fatal: no path specified; see 'git help pull' for valid url syntax
exit status 128
~~~

Server logs:
~~~
{"level":"error","repo_id":"2","pipeline_id":"538","workflow_id":"2215","error":"stream: not found","time":"2023-08-04T07:10:32Z","message":"done: cannot close log stream for step 2693"}
~~~

Agent logs:
~~~
{"level":"warn","repo":"org/repo","pipeline":"472","id":"2215","error":"rpc error: code = Unknown desc = Step finished with exit code 128, ","time":"2023-08-04T07:10:32Z","message":"cancel signal received"}
~~~

First seen here: https://github.com/woodpecker-ci/woodpecker/issues/1169

It worked before updating to the latest next version yesterday. 
Reverting to the tag `next-0cf602a1f6-alpine` fixes the issue, so it must've been introduced in the latest commits.

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-fa747aa9"}
```

### Additional context

Using the official `next-alpine` Docker containers. 

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by danog** [comment]
+, same here

**Comment by SeriousBug** [comment]
The earliest tag I could find that works was `next-6d373daea0`, although I did skip over some tags so there could be an earlier point that is functional.

**Comment by pat-s** [comment]
Can you double check that you're using `plugin-git:2.1.0`? I got the same error when still using `2.0.3`.

https://github.com/woodpecker-ci/plugin-git/releases

**Comment by pat-s** [comment]
You don't even need the `clone:` part explicitly as this is inferred in the background automatically (just fyi in case this is not clear).

But other than that, it should use 2.1.0 automatically, yes. But it might be that you had fixed the image in your server config to some other version, that's why I asked.

I can't replicate the issue anymore with 2.1.0.

**Comment by SeriousBug** [comment]
I put in the `latest` tag and pulled, and it all seems to work fine now! Either it's fixed, or it was operator error to begin with 😅

**Comment by pat-s** [comment]
As everything is working with the latest release, let's close here 🙂

**Comment by patrickuhlmann** [comment]
I upgraded to docker v2.0.0 today and am encountering the same issue:

`clone:
  git:
    image: woodpeckerci/plugin-git
    environment:
      - PLUGIN_LFS=false
      - PLUGIN_CUSTOM_SSL_PATH=/LAN.crt
    volumes:
      - /volume1/LAN.crt:/opt/LAN.crt`

**Comment by patrickuhlmann** [comment]
Yes it was the same. But also with an outdated image.

**Comment by patrickuhlmann** [comment]
Yes
