### ISSUE TITLE
Docs mention `.woodpecker.yml`, but does it work?

### ISSUE THREAD

**Issue by marians** [woodpecker-ci/woodpecker#212]
The documentation front page mentions `.woodpecker.yml` as the YAML file name for configuring a pipeline.

(In other places in the docs, and in this repo's README, the file name `.drone.yml` is used. That's confusing.)

Assuming that `.woodpecker.yml` would be future proof, I renamed a file in one repository which was connected with a woodpecker server. But no builds were happening. Is that actually supposed to work?

In the source code I cannot find any occurrence of `.woodpecker.yml` except for `docs/docs/incex.md`.

**Comment by laszlocph** [comment]
I was clearly aspirational there. I mitigated it by updating the docs for now.

Handling in https://github.com/woodpecker-ci/woodpecker/issues/133
