### ISSUE TITLE
Save log file on USR1 signal

### ISSUE THREAD

**Issue by qwerty287** [woodpecker-ci/woodpecker#2136]
This is an exciting feature.

If you send a USR1 signal to woodpecker, will it "release" the file so the host can logrotate it?

_Originally posted by @lonix1 in https://github.com/woodpecker-ci/woodpecker/pull/2115#issuecomment-1666332445_

> If you send a USR1 signal to woodpecker, will it "release" the file so the host can logrotate it?

not jet that's a followup ... I need to write a wrapper for the os.FileOpen that can do so ... so that's a followup

_Originally posted by @6543 in https://github.com/woodpecker-ci/woodpecker/pull/2115#issuecomment-1666338517_

I just created this mentioned wrapper as lib here: https://github.com/6543/logfile-open ...
... so once merged I can create a followup, that can be tested seperate

_Originally posted by @6543 in https://github.com/woodpecker-ci/woodpecker/pull/2115#issuecomment-1666373271_

**Comment by 6543** [comment]
->  #2151
