### ISSUE TITLE
Explain registration feature in more detail (docs)

### ISSUE THREAD

**Issue by marians** [woodpecker-ci/woodpecker#216]
When reading docs I can't figure out what DRONE_OPEN/WOODPECKER_OPEN really do (if `true`, or prevent if `false`).

In the server's help text it says `enable open user registration`.

What if it's false, who can do what?

What if it's true, who can do what?

**Comment by laszlocph** [comment]
short answer:

DRONE_OPEN: people can register, you don't have to create them manually. With only this set, anyone with a Github/Gitlab.. etc account can register
DRONE_ORGS: further limits who can register. Only accounts from the listed orgs.

you most likely want DRONE_OPEN **and** DRONE_ORGS if you want to limit users to your company or open source project.

This part of the docs gets the closest to explain this, but I can see how it is not clear 
![image](https://user-images.githubusercontent.com/4289031/120189956-4191a600-c218-11eb-8396-243022abdc3f.png)

**Comment by marians** [comment]
So woth DRONE_OPEN=false, an admin can create users manually? Where is this done? And how does that work if gitlab, gitea or whatever is used as an auth backend?

**Comment by laszlocph** [comment]
With DRONE_OPEN=false, DRONE_ADMINS can use the platform, or you may add users with `woodpecker user *` CLI commands, although I never tried that.

The usernames are for authorization. Auth is done through the provider specific auth method, so your Github (OAuth) username is matched against the user name entry in Woodpecker.
