### ISSUE TITLE
Use organization woodpecker-ci on Dockerhub

### ISSUE THREAD

**Issue by marians** [woodpecker-ci/woodpecker#217]
Since the git repo has moved into a project organization, it would make sense to use a project specific namespace on dockerhub for the official images, too, right?

**Comment by laszlocph** [comment]
Yep, next release will come from there: https://github.com/woodpecker-ci/woodpecker/blob/master/.drone.yml#L79

With one caveat: Docker Hub doesn't support dashes in account names 🙃

**Comment by marians** [comment]
> With one caveat: Docker Hub doesn't support dashes in account names 🙃

Dang!

Let's better close the issue then, before people get used to another org name.

**Comment by tboerger** [comment]
Maybe rename the github org, better now than later? Than we can have the same org name for github and docker hub.

**Comment by laszlocph** [comment]
Right. It's just `woodpecker-ci` is already a mouthful / long to type. I would prefer having the dash in there just to help the eye.

And wait for Docker Hub to come to their senses and allow dashes some point in the future.

But I do see that it may lead to errors, but perhaps people copy paste stuff mostly and not try to type it :man_shrugging: I can be very wrong here.. just `woodpeckerci` looks bad :)

**Comment by tboerger** [comment]
I personally think woodpeckerci would also be fine, but if there is a decision to keep the dash I can also live with that :)
