### ISSUE TITLE
Missing steps from web UI

### ISSUE THREAD

**Issue by strk** [woodpecker-ci/woodpecker#2178]
### Component

web-ui

### Describe the bug

Only 13 steps are shown while the configuration contains 22 steps, see
https://woodie.osgeo.org/repos/30/pipeline/775

I'm pretty sure it was working before upgrade to 1.0.0 docker container

### System Info

```shell
Using docker.io/woodpeckerci/woodpecker-server:latest
sha256:bb57d0c1ffae2fde73d90538774f2707a345f9762452ebbcc029d62e50b835b6

{"source":"https://github.com/woodpecker-ci/woodpecker","version":"1.0.0"}
```

### Additional context

It may (or may not) be related to #1708

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by strk** [comment]
When will the fix be included an the "latest" docker image for woodpecker-server ? We're still missing steps as of  https://woodie.osgeo.org/repos/30 ( 1.0.1 )

**Comment by strk** [comment]
I believe we're running the woodpeckerci/woodpecker-server:latest docker image with id 3d72301f0d69

**Comment by 6543** [comment]
1.0 tag should have it now else it will be in 1.0.2
