### ISSUE TITLE
Migrate Let's Encrypt certs library to certmagic

### ISSUE THREAD

**Issue by marians** [woodpecker-ci/woodpecker#219]
I'd like to know if the way woodpecker creates certificates via Let's Encrypt is secure and can be considered production ready.

There is a post on Stackoverflow which caught my eye: https://stackoverflow.com/a/61223820/1228491

It states that the SNI challenge is considered insecure. Are we using that one?

> You also should NOT use the SNI challenge anymore as it is considered insecure. Instead use the ALPN challenge.

In a [blog post](https://marcofranssen.nl/use-the-acme-dns-challenge-to-get-a-tls-certificate/) the author describes how to use [lego](https://go-acme.github.io/lego/) as a replacement for acme/autocert which supports more challenges.

In terms of a design decision, if the implementation turns out not to be secure, it could also be an option to advise using the server behind a proxy which does TLS termination and handles certificates.

**Comment by techknowlogick** [comment]
rather than lego, I recommend [certmagic](https://github.com/caddyserver/certmagic) and have implemented it in Gitea with ease. It is the underlying ACME library for Caddy as well.
