### ISSUE TITLE
Wrong pipeline status

### ISSUE THREAD

**Issue by xoxys** [woodpecker-ci/woodpecker#2197]
### Component

server

### Describe the bug

Pipeline status for cancelled pipeline is wrong:

![image](https://github.com/woodpecker-ci/woodpecker/assets/3391958/0b861239-d99e-43be-9057-dee32a53bb4f)

![image](https://github.com/woodpecker-ci/woodpecker/assets/3391958/9c9d1306-3542-40bd-8648-a7c818b711f0)

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-63d5c40a"}
```
```


### Additional context

_No response_

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by pat-s** [comment]
related #1871 #1893

**Comment by anbraten** [comment]
Maybe related. Pipeline is already show as error, but is still running and no steps has an error 🤔 
https://ci.woodpecker-ci.org/repos/3780/pipeline/9551

**Comment by anbraten** [comment]
![image](https://github.com/woodpecker-ci/woodpecker/assets/6918444/0e5ebb37-93c7-40ca-9959-4fc89de6600d)

Step failed, but pipeline was marked as successful: https://ci.woodpecker-ci.org/repos/3780/pipeline/13542

**Comment by anbraten** [comment]
I think this line could be the issue: https://github.com/woodpecker-ci/woodpecker/blob/2bda19024ece0bf0deab5244fb8799f653d5adfc/agent/runner.go#L168

In case of a canceled workflow the error is set to `""` (no error). The configured exit code doesn't seem to be considered by any logic at all and is only used for logging: #3848
