### ISSUE TITLE
UI still showing "next" as version when using "v1.0" tag

### ISSUE THREAD

**Issue by philipkozeny** [woodpecker-ci/woodpecker#2225]
### Component

web-ui

### Describe the bug

Just a small UI issue, but running the `v1.0` tag instead of `latest`, `v1.0.2` is showing `next` as the version in the UI and via `/version`.

### System Info

```shell
v1.0: {"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-d9e06696"}
latest: {"source":"https://github.com/woodpecker-ci/woodpecker","version":"1.0.2"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by 6543** [comment]
I think this was already reported somewhere 👀

**Comment by 6543** [comment]
It's an issue with our build pipeline ...

**Comment by philipkozeny** [comment]
> ~I think this was already reported somewhere 👀~ cant find it

Yeah, I was the one who asked if I should open an issue on discord when testing that :)

**Comment by 6543** [comment]
->  #2227
