### ISSUE TITLE
Incorrect version of agent

### ISSUE THREAD

**Issue by zc-devs** [woodpecker-ci/woodpecker#2236]
### Component

agent

### Describe the bug

Agent image builds with `next-*` version instead of tag/release. Server version is OK.

### System Info

```shell
{"level":"info","time":"2023-08-17T11:47:41Z","message":"Starting Woodpecker server with version '1.0.2'"}
{"level":"info","time":"2023-08-17T12:01:26Z","message":"Starting Woodpecker agent with version 'next-d9e06696' and backend 'kubernetes' using platform 'linux/amd64' running up to 1 pipelines in parallel"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by 6543** [comment]
to check run: `docker run -it --rm woodpeckerci/woodpecker-agent:v1.0.2 --version` ... 😆

**Comment by 6543** [comment]
well of course ... should mention this was a note for others if they wana check too

**Comment by 6543** [comment]
cli image is also affected

**Comment by 6543** [comment]
for the server this works as we have a different build step in this case

**Comment by 6543** [comment]
-> https://github.com/woodpecker-ci/woodpecker/pull/2238
