### ISSUE TITLE
Organizations tab for admins

### ISSUE THREAD

**Issue by qwerty287** [woodpecker-ci/woodpecker#2307]
### Discussed in https://github.com/woodpecker-ci/woodpecker/discussions/2257

<div type='discussions-op-text'>

<sup>Originally posted by **lonix1** July 10, 2023</sup>
### Clear and concise description of the problem

The server config page shows tabs: "Secrets", "Users", "Agents" and "Queue".

There should be another tab, "Organizations".

There are various org-level settings, e.g. organization secrets (exposed by the API), but they aren't viewable in the UI. So they are effectively "hidden" and it's easy to forget about it.

### Suggested solution

A new tab named "Organizations".

Doesn't need to be complicated, or to allow interaction. Only to show the orgs, and secrets related to them. Readonly to keep it simple.

### Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.</div>

**Comment by anbraten** [comment]
There are some open questions to me. First of all what's the purpose of this list. Does it provide extra admin settings like the users list like restricting orgs or is it just another overview redirecting to the org settings or repo list page? One thing to always keep in mind is also that there are often two different hosting kinds:
- I am an admin of the instance and also the main user and therefore owner of almost all orgs and repos
- I am just the admin of a large instance used by many different independent users and orgs and I am mainly curious about a working instance and healthy community

Especially the second type would currently not really benefit from having a look at the secrets from others and the first user could easily open the orgs page to get to the secrets.

**Comment by anbraten** [comment]
Maybe a redesign of the home page (currently list of repos the user is a member if) which shows the own repos and also the own orgs would help.

**Comment by anbraten** [comment]
I am currently against adding it until the purpose is clearly defined. It's still not clear from the description and discussion how the user will interact with the list.

I can image it will look somehow like the users list:
![image](https://github.com/woodpecker-ci/woodpecker/assets/6918444/17008b66-bdf9-4373-b943-acc3599a9707)

- with the open-icon redirecting to sth like: https://ci.woodpecker-ci.org/orgs/2
- and the settings icon redirecting to: https://ci.woodpecker-ci.org/orgs/2/settings

But that's just an idea and might not solve the issue OP had.

**Comment by anbraten** [comment]
The users list has some action, delete, make an user an admin which can only be done by an admin. The orgs page wont offer such a feature and is only listing orgs and redirecting to existing pages. I think the issue of OP is to find his own orgs and their settings and not the orgs of everyone. In case of large instances (imagine codeberg) why would they want to access an org of someone and change someones secrets.
