### ISSUE TITLE
GitLab nested group - pipeline fails

### ISSUE THREAD

**Issue by gu1ll0me** [woodpecker-ci/woodpecker#2311]
### Component

server

### Describe the bug

Project in a nested group is detected and added successfully, but when triggered by the webhook (push event) the pipeline fails with the error below in the server logs (the PROJECT_NAME seems missing in the GET URL). However, everything is working fine when the pipeline is triggered manually with the "Run pipeline" button (no error in the server logs and the pipeline completes successfully).

```
{"level":"error","error":"GET https://SERVER/api/v4/projects/GROUP/SUBGROUP: 404 {message: 404 Project Not Found}","repo":"GROUP/SUBGROUP/PROJECT_NAME","user":"USER","time":"2023-08-21T12:03:16Z","message":"could not get folder from forge"}
```

And the UI shows :
```
Execution error
pipeline definition not found in GROUP/SUBGROUP/PROJECT_NAME
```

After that, the UI always shows `An unknown error occurred`. I have to use the "Repair repository" action to be able to work with the repository again.

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"1.0.2"}

GitLab 16.2.4
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by 6543** [comment]
->  #2981
