### ISSUE TITLE
Don't fail on missing CI config

### ISSUE THREAD

**Issue by xoxys** [woodpecker-ci/woodpecker#2312]
### Component

server

### Describe the bug

Not necessarily all branches of a repository are intended to have a CI config. But branches without a CI config will always create an error in the UI. 

![image](https://github.com/woodpecker-ci/woodpecker/assets/3391958/c33ec141-ecf7-40c3-9ec8-c67f847d3649)

In the past, I was able to work around this issue by adding `[skip ci]` to all commits to branches without a CI config. This is now also broken, see https://github.com/woodpecker-ci/woodpecker/pull/2216.

My suggestion would be to simply ignore missing CI configurations, or at least not create a failed pipeline in the UI. Alternatively, users should have the option to ignore branches. A common example would be `github-pages` branches, where only page artifacts are published and no CI configuration.

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-06d1f3c92e"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by 6543** [comment]
Hmm you could add a noop ignore all pipeline to those branches ...

**Comment by lafriks** [comment]
problem with this is that it can give correct hint when you have misnamed pipeline definition file or forgot to commit it. imho it would be better to have option to configure this. At least in gitea there is option in webhooks to configure to not send events on specific branches, looks like GH does not have it

**Comment by 6543** [comment]
and why we **me** and @anbraten don't use a lot of configs via the repo settings is, that the pipeline config should be a single source of truth and represent the state of the pipeline. if we move to much outside of that config it does not do this anymore ... and so it's not versioned/documented etc...  anymore

**Comment by xoxys** [comment]
I don't have strong feelings how to handle it, as mentioned in the initial post a config option would be fine (at least for me) as well. But to me https://github.com/woodpecker-ci/woodpecker/pull/2216 would be breaking change as it is changing the behavior and leads to a lot of errors in the UI as I have a `docs` branch which does not have a CI config in nearly all of my repos.

**Comment by 6543** [comment]
added the label `breaking` to it for now

**Comment by xoxys** [comment]
I would like to get this fixed. Do we need an option? Then I'll add it to the existing PR, otherwise can someone review?

**Comment by anbraten** [comment]
> problem with this is that it can give correct hint when you have misnamed pipeline definition file or forgot to commit it. 

So summarizing:
- it would be fine to simply ignore webhooks if no config is available
- we need a way to show at least repo admins in woodpecker that a webhook was somehow triggered but ignored (maybe by adding a log to the repo settings showing ignored webhooks, could be used for #1574 as well)
- we need to consider how this works in terms of special config files for #2254 (we could simply require the user to set the config file in that case)

**Comment by xoxys** [comment]
Is it required to do all at once? Or can we merge the ignore missing config pr and improve the rest in dedicated PRs?

**Comment by anbraten** [comment]
As all other CI systems are not listening if there is no config file, I guess its fine for woodpecker to do so for now as well, so from my side we could for now just ignore it and add the log-view / notification / ... later on

**Comment by xoxys** [comment]
Thanks. I would appreciate an Approval for the PR in this case.

**Comment by Andre601** [comment]
I believe the CI should not run anything if there is no file. Tho, maybe have an option to toggle this for those people who want this behaviour for some reason?

I for my part dislike this behaviour as it creates failed runs where there shouldn't be one to begin with. That combined with the CI now apparently ignoring `[SKIP CI]` in such cases is just frustrating to deal with since apparently the `when` option is ignored too (I've set a when to only trigger on master branch, yet it triggers on others too)?

**Comment by xoxys** [comment]
Configurations are read per branch. If your `pages` branch has no `.woodpecker` config a `when` filter from the main/default branch doesn't matter.

**Comment by anbraten** [comment]
Recently started using a pretty large project with Woodpecker and experiencing this again. I get errors for a lot of branches, PRs, ... all of them because there is no Woodpecker config. I guess skipping those pipeline as almost other CI systems do it would be the best here.

**Comment by 6543** [comment]
Ok so i would say: if the forge report no found we ignore, if its any other error we show error config fetch failed :)
