### ISSUE TITLE
Latest image doesn't run ?

### ISSUE THREAD

**Issue by ygbillet** [woodpecker-ci/woodpecker#232]
Hi,

I just updated my woodpecker docker image (docker pull). It doesn't run.
Last update was when OAuth was added (10 days ago).

```
time="2021-06-28T16:48:40Z" level=error msg="sql: unknown driver \"sqlite3\" (forgotten import?)"
time="2021-06-28T16:48:40Z" level=fatal msg="database connection failed"
```

**Comment by 6543** [comment]
Will infestigate, we might need to rethink the release pipeline

**Comment by ygbillet** [comment]
I recreate .drone.sh, build it, make docker image and it succesfuly run.
If i use Makefile it didn't work.

Do you have any insight ?

**Comment by ygbillet** [comment]
find it ! 

We need to use `CGO_ENABLED=1` in [Makefile:release-server](https://github.com/woodpecker-ci/woodpecker/blob/master/Makefile#L80)

**Comment by 6543** [comment]
@ygbillet wana send a pull ;)

**Comment by ygbillet** [comment]
> @ygbillet wana send a pull ;)

Done
