### ISSUE TITLE
move from meddler to xorm (switch orm)

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#234]
move from **https://github.com/russross/meddler** to **https://xorm.io/**

-> get rid of sql file generation
-> make code easyer
-> add support for more databases (i.e. mssql, oracle, ...)
-> easier migrations

**Comment by anbraten** [comment]
After working with the server code and the database now a bit I found quite some a lot of unused parts. Their are quite some columns not being used at all. Using a more advanced orm would probably help a lot with that problem.

**Comment by catdevnull** [comment]
Wouldn't it be better to identify the issues currently and try to fix them directly before switching tools?

**Comment by 6543** [comment]
well the issue is: db is done manually by writing sql for each db ...

**Comment by 6543** [comment]
side note: https://github.com/bradrydzewski/togo is unmaintained ...

**Comment by 6543** [comment]
TODO:
 * [ ] migrate db-migration-framework
 * [ ] unify store things
 * [ ] dedub code
