### ISSUE TITLE
Deleting user/org does not delete repos

### ISSUE THREAD

**Issue by qwerty287** [woodpecker-ci/woodpecker#2344]
### Component

server

### Describe the bug

when deleting a user or org the repos it owns are not deleted

### System Info

```shell
latest next
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by anbraten** [comment]
Deleting all repos of an org could also remove the org again.

**Comment by xoxys** [comment]
Same reason here, I guess this will delete all org secrets, which shouldn't happen automatically even if there are no more repos remaining in an org.
