### ISSUE TITLE
Provide separate `commit-title` and `commit-message` in pipeline metadata

### ISSUE THREAD

**Issue by xoxys** [woodpecker-ci/woodpecker#2359]
We should expose `commit-title` and `commit-message` as dedicated metadata on the server-side because sometimes the title is more useful/readable instead of the full message e.g. in notification plugins or web UI.

posted by @xoxys in https://github.com/woodpecker-ci/woodpecker/issues/2356#issuecomment-1699254538

**Comment by anbraten** [comment]
What if we just leave new lines in the commit messages. This way it would be quite easy for the different places to decide if they just want to show the first line or more.

**Comment by xoxys** [comment]
Sure, I thought it might be more handy for users this way, and it's done just once on the server-side.

**Comment by anbraten** [comment]
I think the issue is however that the commit message is a one-liner atm?

**Comment by anbraten** [comment]
In that case we could just show the first line normally and on hover the full message with new-lines
