### ISSUE TITLE
Create build from API?

### ISSUE THREAD

**Issue by ChanceNCounter** [woodpecker-ci/woodpecker#240]
It looks like the Drone API has an endpoint where you POST to `/repos/<>/<>/builds` and the thing does the whoozit.

This would be very helpful, but I'm guessing it was implemented sometime after the fork. If I'm right, rather than just overlooking something, it might be worth implementing at some other endpoint. Personally, I see where putting it at "POST to /builds" saved time and trouble, but I think it's a little counterintuitive 🤷‍♂️

**Comment by anbraten** [comment]
linking to #83
