### ISSUE TITLE
woodpecker cli to support enabling tag based builds

### ISSUE THREAD

**Issue by sudip-moengage** [woodpecker-ci/woodpecker#243]
When we enable a repo, deployment and push events gets automatically enabled. We have automation of onboarding new microservices, where a part includes creating repo and integrate woodpecker. We drone cli to enable repos at the same time we want to enable tag based events. Is there any other way I can do this, like an API call?

**Comment by anbraten** [comment]
I plan to update the way woodpecker restricts if a webhook call should be executed in #281. The current plan is to allow all webhooks / events by default and add an option to disable pull requests. I think this would solve your problem somehow. 

In addition to that there alreday is an api endpoint to change the settings of a project under POST: `/api/repos/" + owner + "/" + repo`. You should find the implementation of that endpoint [here](https://github.com/woodpecker-ci/woodpecker/blob/master/server/repo.go#L101). There also is a swagger documentation of woodpecker, but I don't know if it is up to date ATM.
