### ISSUE TITLE
add a shell to the docker images

### ISSUE THREAD

**Issue by ChanceNCounter** [woodpecker-ci/woodpecker#244]
I'm in DNS hell over here. My tools quit earlier today, something's clearly changed, I can't figure out what, and I would *really* like to connect to this container and ask it some questions.

At the moment, my instance is a very frustrating doorstop and I haven't accomplished anything useful today, because I've been fighting with tools.

**Comment by 6543** [comment]
Sounds bad, but you can do this already if you have questions we have a discord server :)

**Comment by 6543** [comment]
Tld: the node who do run workers show the running docker as usual and so you can exec things in them manualy as long as woodpecker do not kill them

**Comment by ChanceNCounter** [comment]
Indeed, but you can't get into the Woodpecker containers themselves, server or agent, and it's their situation I'm concerned about. I can see all the right DNS queries going all the right places, so I wanna see what's getting lost in translation, and where.

I should probably have titled the issue, "*expose* a shell in the docker images," because the fundamental problem seems to be with Woodpecker's PATH. You can't `docker exec`, well, anything as far as I can tell =P

**Comment by 6543** [comment]
it depends on your setup but woodpecker itselve is also just a container you could have a look into ... and if you start woodpecker in developmend mode it should be even more verbose `GIN_MODE=debug`
