### ISSUE TITLE
Broken link in docs to extra plugin list

### ISSUE THREAD

**Issue by sknebel** [woodpecker-ci/woodpecker#2493]
This link is broken
https://github.com/woodpecker-ci/woodpecker/blob/ecdc729cdca0728a95f64721db552afc42d2bff0/docs/docs/20-usage/51-plugins/10-plugins.md?plain=1#L43 

@xoxys is there a new location for that? (as far as I can tell it is/was hosted by you?)

**Comment by xoxys** [comment]
Thanks for pinging me 🙂 I wasnt aware that it is linked in the WP docs. 

Yes, I have migrated all plugins and the docs to https://woodpecker-plugins.geekdocs.de/

I can create a PR to fix the link later.
