### ISSUE TITLE
Document installing as Oauth app

### ISSUE THREAD

**Issue by runephilosof-karnovgroup** [woodpecker-ci/woodpecker#2498]
### Clear and concise description of the problem

https://github.com/woodpecker-ci/woodpecker/discussions/2482#discussioncomment-7099587

>> We use the GH app as described in the docs.

> The Woodpecker docs does not mention whether to create Woodpecker as a Github App or as an Oauth app.
It does not seem like tokens need to be refreshed, if installed as an Oauth app. The Github docs does not mention refreshing Oauth token https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authenticating-to-the-rest-api-with-an-oauth-app#implementing-persistent-authentication.

Update to that...
The `next` documentation tells admins to install as a Github App. I don't think Woodpecker is ready for that. It needs more token handling for that.

### Suggested solution

https://woodpecker-ci.org/docs/administration/forges/github#registration should tell admins to set it up as an Oauth App, not a Github App.
Also, update the screenshot.

### Additional context

The instructions to install as a Github App were merged here https://github.com/woodpecker-ci/woodpecker/pull/2472

### Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by pat-s** [comment]
Thanks, that is helpful! I've issued #2472 and will provide an update. Though the instructions before weren't specific on this either. 

But yes, this could be the reason for the issues reported in #2488.
