### ISSUE TITLE
Woodpecker agent logs wrong version on startup

### ISSUE THREAD

**Issue by Maddin-M** [woodpecker-ci/woodpecker#2529]
### Component

agent

### Describe the bug

When starting the agent (version v1.0.2) it logs the following:
`Starting Woodpecker agent with version 'next-d9e06696'`
While it is the correct commit hash that the version has been tagged with, the expected version would be `1.0.2`, like the woodpecker server correctly does.
Very minor, but worth mentioning :)

### System Info

```shell
version: 1.0.2
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by zc-devs** [comment]
Duplicate of #2236

**Comment by Maddin-M** [comment]
Oh, you're right
