### ISSUE TITLE
Documentation site out of date

### ISSUE THREAD

**Issue by inverse** [woodpecker-ci/woodpecker#254]
I noticed the documentation site is out of date. 

See: https://woodpecker.laszlo.cloud/server-setup/

Is there plans to update this on this domain or move it to GitHub pages?

**Comment by 6543** [comment]
I think we should update asap after final release

**Comment by anbraten** [comment]
Would be nice if we could use woodpecker-ci to release docs automatically. The current docs seem to be hosted on some "private" Netlify instance from laszlocph, correct? Sounds like a good idea to migrate them to github to have them closer to the woodpecker org.

**Comment by inverse** [comment]
Thanks all!

**Comment by inverse** [comment]
Where is the documentation hosted at? The URLs on the repo and readme are still the old ones.

**Comment by inverse** [comment]
Thank you - I see it now!
