### ISSUE TITLE
Missing v0.14.0-rc.2  on dockerhub

### ISSUE THREAD

**Issue by inverse** [woodpecker-ci/woodpecker#256]
Currently I can see that `laszlocloud/woodpecker-agent:v0.14.0-rc.1` however I am unable to find the `laszlocloud/woodpecker-agent:v0.14.0-rc.2` release.

I can see that there is a new repo `woodpeckerci/woodpecker-agent` however this only contains `latest`. Would it be possible to publish `v0.14.0-rc.2` as well?

**Comment by 6543** [comment]
tag webhook was not enabled on woodpecker ci will test with tagging v0.14.0 if it doesnt work I'll retage after #257 was merged else we will switch to goreleaser in next version

**Comment by 6543** [comment]
yes did worked :)
https://hub.docker.com/layers/woodpeckerci/woodpecker-server/v0.14.0/images/sha256-47b2669eeb3b6c39a475a08e7537d520da435398a8e12c1cfc71c38157041175?context=explore
