### ISSUE TITLE
Sidebar can't be closed with the counter button

### ISSUE THREAD

**Issue by qwerty287** [woodpecker-ci/woodpecker#2570]
### Component

web-ui

### Describe the bug

open the sidebar panel with the counter button (top right) -> try to close with the same button

### System Info

```shell
latest main and https://ci.woodpecker-ci.org
```

### Additional context

regression #2325  

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by pat-s** [comment]
@qwerty287 This is still in 2.0.0 - do you wanna still fix it, or should we move it out?
