### ISSUE TITLE
Locales

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#258]
use locales for strings so we can make it translatable
- [x] add locales framework (#912)
- [ ] user is able to select/set language
- [x] decide on translation platform
  - [ ] [Crowdin](https://crowdin.com/)
  - [x] [Weblate](https://weblate.org/en/)
  - [ ] [pontoon](https://pontoon.mozilla.org/)
- [x] add ci pipeline that upload & download from translation platform

**Comment by 6543** [comment]
@anbraten in look to the Vue rewrite - how much do you already had considered it?

**Comment by anbraten** [comment]
@6543 Haven't planned that for the initial rewrite, but I used `vue-i18n` before which is easy to add. 

Do you think translations are really necessary for this kind of software. I had the feeling that most devops are somehow used to English anyways.

**Comment by 6543** [comment]
For the initial rewrite it's not needed, but it wont hurt and help non native english speaker ...

**Comment by anbraten** [comment]
We know have our own weblate instance: <translate.woodpecker-ci.org>. Language selection will be handled by #1109
