### ISSUE TITLE
Unify build models

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#259]
Currently there are three different versions of a build-model being used: 
- "normal" build model
- build-feed (build model with repo-name, repo-owner and repo-fullname)
- build with procs and file-changes

Using the same data-model in three different versions brings some complexity with data-storing in the frontend as data has to be merged / stored twice.

A suggestion to fix this problem would be:
- create a new separate data-model called build-details
  - contains: build-id, procs and changed-files
  - could have its own endpoint similar to `/api/build`
- add repo-id / repo-owner and repo-name to every build, so the corresponding repo information can simply be gathered from the data-store or by requesting the repo-endpoint. This way build-feed model can be easily replaced by normal build-model

**Comment by 6543** [comment]
sounds resonable but we still have to consider if there was a reason to do so in the first place ... I prever to do it ligicaly right in backend view and make it then easy to work with for ui ontop ...

... so after the UI rewrite is done we can refactor bit more or do you need it for your ui pull now?!?

**Comment by anbraten** [comment]
> ... so after the UI rewrite is done we can refactor bit more or do you need it for your ui pull now?!?

Don't need it now. It is more or less a general design which could be discussed IMO. I just noticed it and wasn't lets say impressed by the way it is solved atm 😉

**Comment by anbraten** [comment]
Should be getting resolved by #994 and over time 😅
