### ISSUE TITLE
Feature to let agents require labels for pipelines

### ISSUE THREAD

**Issue by simcop2387** [woodpecker-ci/woodpecker#2634]
### Clear and concise description of the problem

Right now if you set `WOODPECKER_FILTER_LABELS=...` on an agent, if a pipeline doesn't set any labels (or only sets labels that matches that agent) then it will accept all pipelines, even if they don't have a label that you defined for them

### Suggested solution

I'm proposing a way to set on the agent side something like this:

```bash
# define the labels and their values for the agent
WOODPECKER_FILTER_LABELS=customlabel1=foobar,...
# define which labels *MUST* be set on a pipeline to be picked up and must match the value the agent has for them
WOODPECKER_REQUIRE_LABELS=customlabel1,...
```

The idea being here then that you could say require that the hostname label is set for a pipeline to run on a specific agent,
and that jobs that don't have a hostname set, are ineligible to run on that host.

### Additional context

The motivation here being that I've got multiple systems I want to run agents on with different resources (disk space, cpu, etc.)
which makes them unsuitable to use in the general case but there are some jobs I want to run there.

Some more specific examples below

    build_server - Major build/job server, has lots of ram and disk space available and isn't used interactively so it can just chug along
    ai_server - Another server that runs some AI jobs.  It has GPUs, CPUs, etc. but not much disk space since it accesses things over the network.  It's also not as power efficient so it's more expensive to run jobs here that aren't AI related.
    riscv_board - Small SBC that can run stuff, has 8gb of ram but only 8gb of local disk also.  Shouldn't run anything except stuff explicitly asking for RISC-V platform
    arm_board - Similar to the riscv board above

So for those systems I'd set build_server to be unrestricted, since it's purpose is to be the general job runner.
The AI server I'd allow jobs that need the gpus or other specific things there, and only those, so set `WOODPECKER_REQUIRE_LABELS=hostname`
And then the arm and riscv SBCs would get `WOODPECKER_REQUIRE_LABELS=platform` since a specific board isn't needed (I have several of each) but
because they're much smaller they shouldn't run anything that could be bigger or that doesn't specifically need them, my plan there is
to have them around for running integration tests on projects on other architectures.

### Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by xoxys** [comment]
Honestly, the default implementation of how `WOODPECKER_FILTER_LABELS` works doesn't make sense to me. Why would someone want to set labels on the agent if they are not enforced?

@woodpecker-ci/maintainers How do we want to handle it? Fix the behavior of `WOODPECKER_FILTER_LABELS` or a second config option as proposed?

**Comment by lafriks** [comment]
@simcop2387 can you check if #4326 fixes also your use case?

**Comment by xoxys** [comment]
@lafriks I have a dedicated runner on my own infrastructure. While 99% of my repos can run pipelines on any runner that is dynamically provisioned by the autoscaler, I have some repos where I want to force the pipelines to run only on my private infrastructure runner. Would this be possible with your approach?

**Comment by xoxys** [comment]
Looking at your implementation, I don't see how this would fix at least my use case but I might be wrong.

**Comment by lafriks** [comment]
@xoxys Actually I have very similar use case and why I created PR, I have docker runners and one macos local runner that needs to run only specific workflows.

Idea to solve this is that you add config for all your default runners (all but private) config ex `WOODPECKER_FILTER_LABELS: kind=default`
and than for server add new config `WOODPECKER_DEFAULT_WORKFLOW_LABELS: kind=default` - now all your workflows with no `labels` conditions specified will run only on runners that has this filter label set. Than for your private runner config you can add ex `WOODPECKER_FILTER_LABELS: kind=private` and in your pipeline you would use:

```yaml
labels:
  - kind=private
```

and it will be executed on your private infrastructure runner

**Comment by xoxys** [comment]
Thanks for the details! But shouldn't we not just fix the IMO broken and useless behavior of `WOODPECKER_FILTER_LABELS`? While your approach might work, it sounds a bit like a workaround, or am I missing something?

**Comment by lafriks** [comment]
For now I had no need to use label filters so I may be missing something but can you explain a bit more about broken/useless how?

**Comment by 6543** [comment]
#5633 got merged witch also could help u :)
