### ISSUE TITLE
Secret image filter with port invalid

### ISSUE THREAD

**Issue by HamburgerJungeJr** [woodpecker-ci/woodpecker#2641]
### Component

server, web-ui

### Describe the bug

I'm running a local registry on a custom port (:8443) . So when I'm using a local image in my pipelines I reference it by specifying the following image:
```
steps:
  image:
    image: myregistry.example.com:8443/myimage:mytag
```

Now I tried to add a global secret and restrict it to an image from my registry. So I entered the following image name in the webui: `myregistry.example.com:8443/myimage:mytag`

This results in the error message 
`Error updating global secret. Invalid Secret Image: image 'myregistry.example.com:8443/myimage:mytag' do not match regexp '^([\w\d\-_\.\/]*[\w\d\-_]+)+(:[\w\d\-_]+)?$'`

I searched the code and found the following RegEx
https://github.com/woodpecker-ci/woodpecker/blob/a1a35eb7be62309aad1c5ecf35746a9df636568f/server/model/secret.go#L117-L122
This RegEx does not allow the port in the url part.

A RegEx like this should fix the problem
```
var validDockerImageString = regexp.MustCompile(
	`^([\w\d\-_\.\/]*` + // optional url prefix
        `(:\d*/)?` + // optional port prefix
	`[\w\d\-_]+` + // image name
	`)+` +
	`(:[\w\d\-_]+)?$`, // optional image tag
)
```

### System Info

```shell
V1.0.2
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by anbraten** [comment]
Would you like to open a PR fixing it
