### ISSUE TITLE
Remove repository hooks option

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#265]
# Problem
Currently there is a setting per repo to listen only to specific webhooks:

![Screenshot from 2021-08-18 00-33-53](https://user-images.githubusercontent.com/6918444/129809423-9f1b1f1e-fa0f-43a6-9463-bdd334b24758.png)

I don't see a reason to have this setting. If I am not interested in webhooks like deployment then my workflow file simply does not have a deployment trigger.

Having this setting makes things just complicated and duplicates settings IMO.

# Suggestion
Remove that setting and always listen to all 4 events with the webhook.

**Comment by UnlimitedCookies** [comment]
Agreed. This confused me at first because I thought I was supposed to declare this in the yml file.
