### ISSUE TITLE
Allow users to register own agents

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#267]
It would be nice to add my own agent to some kinda public woodpecker instance. 
- There should be an option for the server to allow user-registered agents. 
- There should be to kinds of agents: shared agents (probably provided by the woodpecker admin), user-agents
- There has to be some way of regiserting new agents without the need to share a single secret (like currently implemented) with evil users
- User-agents should be assignable to own repos, but not to all repos (securtiy risk, if secrets / sensitive code gets loaded to some strangers agent)
- Agents should have a setting to disallow privilged / trusted builds
- There should be some way to invite agents to other repos (not directly owner of repo like a repo from some org) 

# TODO
- [ ] move label filtering to server to prevent agents from taking pipelines they should not get
- [ ]

**Comment by anbraten** [comment]
From: https://codeberg.org/Codeberg-CI/feedback/issues/94#issuecomment-690822

> I like that invitation idea. Using some kind of invitations and having a two way approval is important as the agent owner does not want some stranger to execute anything on his agent and on the other hand we need to protect orgs / other users from automatically scheduling pipelines on some strangers system potentionally doing harmful stuff with their secrets / code, etc.

**Comment by lafriks** [comment]
Maybe agent could authenticate with per-user secret that would be stored in user table. This way we could automatically detect that this agent is user owned

**Comment by anbraten** [comment]
That's already possible after #1189 gets merged. It allows to connect an agent with a previously created token and the token gets assigned to an user (for the beginning only admin users) which acts as an owner of that agent.

For sharing agents with others it would be somehow needed that the agents owner is able to send an invitation to another org / user, so they can accept it.
