### ISSUE TITLE
UI: separate services and build-jobs 

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#269]
It would be nice if a user could somehow notice that a build-job is of type service.

**Comment by 6543** [comment]
indicate it by different icons?

**Comment by 6543** [comment]
idea: instead of a dot -> add a gear (not spinning if cancled/pending/...  & spinning if state = running)

**Comment by dvjn** [comment]
Currently, I couldn't find a way to differentiate a proc between service and build-job in the front-end.
This will require changes in server api first.

**Comment by 6543** [comment]
good point!

**Comment by 6543** [comment]
there is now a `type` field in the step struct. so only the ui part is missing :)
