### ISSUE TITLE
Distributed Cache

### ISSUE THREAD

**Issue by esamson** [woodpecker-ci/woodpecker#2699]
### Clear and concise description of the problem

I saw a somewhat related concern discussed in #2155 but want to expand the capability a bit more.

The main idea is to cache some specified files or directories after a step completes. Then, any subsequent step (or that same step in a subsequent pipeline run) gets those files and directories loaded back from the cache before running that step.

We can kind of already do this as volumes, but that only works if the pipeline is pinned to a single machine.

We need a machine-independent way of specifying the cache contents and then use a centralized cache shared between runners.

### Suggested solution

One approach might be to steal the feature from GitLab.

* https://docs.gitlab.com/runner/configuration/speed_up_job_execution.html#use-a-distributed-cache
* https://docs.gitlab.com/ee/ci/yaml/#cache

### Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by anbraten** [comment]
Sound similar to those suggestions:
- https://github.com/woodpecker-ci/woodpecker/discussions/2295#discussioncomment-6895751
- https://github.com/woodpecker-ci/woodpecker/discussions/2272
- https://github.com/woodpecker-ci/woodpecker/discussions/2296

**Comment by anbraten** [comment]
> We can kind of already do this as volumes, but that only works if the pipeline is pinned to a single machine.

Could you add that requirement to the discussion

**Comment by esamson** [comment]
Thanks for pointing me to the discussions. It seems that the point about volumes and their availability for other agents has already been covered so I have nothing more to add there.
