### ISSUE TITLE
User don't have permission for own Org

### ISSUE THREAD

**Issue by JakobDev** [woodpecker-ci/woodpecker#2714]
### Component

other

### Describe the bug

Please take a look at this [issue on Codeberg](https://codeberg.org/Codeberg-CI/feedback/issues/136). I found out what causes this problem. See [this comment](https://codeberg.org/Codeberg-CI/feedback/issues/136#issuecomment-1318012) for details. #2126 added a Org for each user. But it looks like there was a mistake in the Migration, so the Users don't have access to their Org. `https://ci.codeberg.org/api/user `say my Org ID is 592, but `https://ci.codeberg.org/api/orgs/592 `gives me a 403.

### System Info

```shell
{
    "source":"https://github.com/woodpecker-ci/woodpecker",
    "version":"next-62e1081b24"
}
```

### Additional context

I'm just a User and not the Admin of this instance, so I can't give you detailed technical information, but I want to share my findings.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by pat-s** [comment]
Moving this out of 2.0.0 until we really know the issue. Can also just go into a follow-up release then.

**Comment by JakobDev** [comment]
> Looking at the code, I don't see how this could fail

Maybe the user gets added to the Org, but there's a problem in the Permission Check.

@qwerty287 If you have access to the database and want to investigate, my User ID is 240.

**Comment by JakobDev** [comment]
I get now a 404 instead of a 403 for some reason

**Comment by 6543** [comment]
https://github.com/woodpecker-ci/woodpecker/pull/2967
