### ISSUE TITLE
Add json-schema for ci files

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#275]
It would be nice to add a json-schema for yml files to [schemastore.org](https://github.com/SchemaStore/schemastore). This would probably help many users with typos and autocompleting configs.

Before a schema can be added some kind of default path should be discussed see #133.

Maybe the following catalog entry would fit:
```json
{
      "name": "Woodpecker pipeline config",
      "description": "YAML schema for Woodpecker pipeline",
      "fileMatch": [
        ".woodpecker/**.yml",
        ".woodpecker.yml"
      ],
      "url": "https://json.schemastore.org/woodpecker.json"
    }
```

**Comment by 6543** [comment]
#133 got resolved

**Comment by 6543** [comment]
how is this pipeline&feature related, I think this is documentation?

**Comment by anbraten** [comment]
> how is this pipeline&feature related, I think this is documentation?

You are right. #276 will be the part that checks the pipeline-config with the json-schema.
