### ISSUE TITLE
Linter: show warning if a secret is not populated to the current build due to filtering

### ISSUE THREAD

**Issue by pat-s** [woodpecker-ci/woodpecker#2800]
### Clear and concise description of the problem

Upstream issue: https://codeberg.org/Codeberg-CI/feedback/issues/40

### Suggested solution

Now that the UI linter is parsing the config, it could also check for secrets which are not inserted into the build because

- they are limited to certain images (still would actually create a permanent note then, not sure...)
- they are limited to certain event triggers which are not matched for the respective build

### Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by anbraten** [comment]
Would be pretty hard to code I think as they are normally not even loaded from database if they are not relevant, but interesting idea

**Comment by pat-s** [comment]
Ah ok. Should we close here then if it's close to impossible? At least we talked about it 😄

**Comment by pat-s** [comment]
@anbraten 

The following has been suggested by @6543 

> so what about this proposal: print into log before exec a warning about secrets getting scipted because of filter XY ?

Is this feasible? If not, we can close here and I can close the related CB issues as "wontfix".

**Comment by anbraten** [comment]
> so what about this proposal: print into log before exec a warning about secrets getting scipted because of filter XY ?

Don't get that one?

**Comment by pat-s** [comment]
I understand it as: Print a log message into the build output (maybe also now the new "warnings" output, but that might be a bit disturbing) before the execution of any command if a secret is getting skipped/omitted because it's filtered for certain images (e.g. plugins).
