### ISSUE TITLE
bump `axios`

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#2814]
ref https://github.com/woodpecker-ci/woodpecker/pull/2799#issuecomment-1806913435

blocked by https://github.com/jeffbski/wait-on/issues/143 (https://github.com/jeffbski/wait-on/pull/147)

**Comment by xoxys** [comment]
Use overrides in the meantime? https://github.com/woodpecker-ci/woodpecker/blob/main/web/package.json#L72-L74

**Comment by xoxys** [comment]
No overrides are working for peer/transitive dependencies.

**Comment by xoxys** [comment]
Ah ok missed that -.-
