### ISSUE TITLE
2.0.0: moving webhook endpoint behind `/api` prefix should probably be considered a breaking change

### ISSUE THREAD

**Issue by otaconix** [woodpecker-ci/woodpecker#2824]
### Component

server

### Describe the bug

Hi, apologies if this has already been reported (I searched but couldn't find any issues), but I've recently updated my installation to 2.0.0-rc.0, and I was confused as to why webhooks didn't seem to work anymore. 

I went over the changelog for the RC, and found a reference to https://github.com/woodpecker-ci/woodpecker/pull/2212

This change breaks all webhooks created prior to the upgrade to 2.0.0-rc.0, as those still point at `${HOST}/hook`. And by leaving no route behind for the old hooks endpoint, it appears as though incoming the hook succeeds, as Woodpecker responds with a statuscode `200` (the body being the landing page).

It would've been helpful if:

1. The change had been marked as a breaking change
2. There had been some route left behind that responds with some kind of error statuscode (perhaps `410 Gone`?) so some kind of alerting would go off in whatever called the hook. Bonus points if this logs some warning in the woodpecker server logs!

I did eventually find https://github.com/woodpecker-ci/woodpecker/blob/main/docs/docs/91-migrations.md, which does describe what could be done. Still, it would have helped me personally if the changelog would have mentioned this more prominently.

### System Info

```shell
{
    "source": "https://github.com/woodpecker-ci/woodpecker",
    "version": "2.0.0-rc.0"
}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by 6543** [comment]
marked as breaking

**Comment by 6543** [comment]
> There had been some route left behind that responds with some kind of error statuscode (perhaps 410 Gone?) so some kind of alerting would go off in whatever called the hook. Bonus points if this logs some warning in the woodpecker server logs!

nice idea!

**Comment by 6543** [comment]
no breaking was done at #2639
