### ISSUE TITLE
Server crashes and after a restart SQL lite db is locked

### ISSUE THREAD

**Issue by aozomaro** [woodpecker-ci/woodpecker#2827]
### Component

server

### Describe the bug

During the execution of a pipeline, often times the server crashes. After crash, when the server is restarted the server is in a very slow state, often times reporting that "db is locked"

When the server crashes the following info is outputted to the logs:

goroutine 33930 [running]:
net/http.(http2responseWriter).write(0xc0017c6780?, 0xc00111fea8?, {0x0?, 0x12634a0?, 0x1362a80?}, {0x141f1bf?, 0xc000074d00?})
    /usr/local/go/src/net/http/h2_bundle.go:6797 +0x13f
net/http.(http2responseWriter).WriteString(0xc00111fee0?, {0x141f1bf?, 0xc000074d00?})
    /usr/local/go/src/net/http/h2_bundle.go:6790 +0x28
io.WriteString({0x7f428c48e2b8, 0xc000074d00}, {0x141f1bf, 0x18})
    /usr/local/go/src/io/io.go:316 +0x58
github.com/gin-gonic/gin.(*responseWriter).WriteString(0xc00154a000, {0x141f1bf, 0x18})
    /woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/response_writer.go:90 +0x73
io.WriteString({0x7f428c48e278, 0xc00154a000}, {0x141f1bf, 0x18})
    /usr/local/go/src/io/io.go:316 +0x58
go.woodpecker-ci.org/woodpecker/server/api.LogStreamSSE.func2()
    /woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/stream.go:224 +0x134
created by go.woodpecker-ci.org/woodpecker/server/api.LogStreamSSE in goroutine 33971
    /woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/stream.go:208 +0x7a5

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"2.0.0-rc.0"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by 6543** [comment]
> During the execution of a pipeline, often times the server crashes. 

the server should not crash at all, could you give us the log before it crashes (with trace as loglevel would be best).
if the db itselve is locked you likely can repair it by manually open it once with the sqlite3 cli tool ... or delete a lockfile

**Comment by aozomaro** [comment]
Sorry I was mistaken, the server doesn’t crash. However multiple workflows start getting hung. The problem seems to be worse when I start multiple woodpecker agents on the same machine .. would you be able to prevent the error from occurring?

**Comment by 6543** [comment]
well that indicates we open session and then open a new session witch do wait for the previous one -> a deadlock

**Comment by aozomaro** [comment]
Ahh, what’s the best way to prevent the deadlock? I seem to hit it easily and consistently LOL. Or if you have any recommendations on how I can debug I would love to help resolve this!

**Comment by 6543** [comment]
hmm the easyest way would be to use a framework like https://codeberg.org/6543/xorm_context but mentioned framework needs bit of testing ...

**Comment by aozomaro** [comment]
Just another update, I captured the logs when db locking presents itself. You can see that the db seems infinetly locked and so everything stops working

![image](https://github.com/woodpecker-ci/woodpecker/assets/1720196/cf3dae62-4b6e-4fc5-b375-f0640ab4a570)

**Comment by 6543** [comment]
looks like an issue in cron handler

I'll create a pull that add the option to disables cron, if it go away we know it's this code part and can fix it

**Comment by aozomaro** [comment]
btw, thank you for being so responsive, this is unheard of! 

I finally got the log up to the point of the write failure:


1:03AM TRC ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/router.go:43 > [GET] /api/stream/events
1:03AM DBG ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/stream.go:63 > user feed: connection opened
1:03AM TRC ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/cron/cron.go:48 > Cron: fetch next crons
1:03AM DBG ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/stream.go:205 > log stream: connection closed
1:03AM DBG ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/logger.go:59 > ip=98.255.236.224 latency=120000.597605 method=GET path=/api/stream/logs/1/13/605 status=200 user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
1:03AM TRC ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/router.go:43 > [GET] /api/stream/logs/1/13/605
1:03AM DBG ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/session/repo.go:150 > aozomaro granted &{UserID:1 RepoID:1 Repo:<nil> Pull:true Push:true Admin:true Synced:1700090349 Created:1700077655 Updated:1700090349} permission to provusinc/quoting
1:03AM DBG ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/stream.go:200 > log stream: connection opened
1:03AM DBG ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/stream.go:234 > log stream: reconnect: last-event-id: 18
1:03AM TRC ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/cron/cron.go:48 > Cron: fetch next crons
1:03AM DBG ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/stream.go:82 > user feed: connection closed
1:03AM DBG ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/logger.go:59 > ip=98.255.236.224 latency=120000.656015 method=GET path=/api/stream/events status=200 user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
1:03AM TRC ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/router.go:43 > [GET] /api/stream/events
1:03AM DBG ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/stream.go:63 > user feed: connection opened
1:03AM TRC ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/cron/cron.go:48 > Cron: fetch next crons
1:03AM TRC ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/router.go:43 > [GET] /api/queue/info
1:03AM DBG ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/logger.go:59 > ip=98.255.236.224 latency=0.200651 method=GET path=/api/queue/info status=200 user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
1:03AM TRC ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/cron/cron.go:48 > Cron: fetch next crons
1:04AM TRC ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/cron/cron.go:48 > Cron: fetch next crons
1:04AM TRC ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/cron/cron.go:48 > Cron: fetch next crons
1:04AM DBG ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/stream.go:82 > user feed: connection closed
1:04AM DBG ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/logger.go:59 > ip=98.255.236.224 latency=120000.464587 method=GET path=/api/stream/events status=200 user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
1:04AM TRC ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/cron/cron.go:48 > Cron: fetch next crons
1:04AM TRC ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/router.go:43 > [GET] /api/stream/events
1:04AM DBG ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/stream.go:63 > user feed: connection opened
1:04AM DBG ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/stream.go:82 > user feed: connection closed
1:04AM DBG ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/logger.go:59 > ip=98.41.152.206 latency=120000.165897 method=GET path=/api/stream/events status=200 user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/119.0"
1:04AM TRC ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/cron/cron.go:48 > Cron: fetch next crons
1:04AM TRC ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/router.go:43 > [GET] /api/stream/events
1:04AM DBG ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/stream.go:63 > user feed: connection opened
1:04AM DBG ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/stream.go:82 > user feed: connection closed
1:04AM DBG ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/logger.go:59 > ip=172.56.169.144 latency=120000.208164 method=GET path=/api/stream/events status=200 user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
1:04AM TRC ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/router.go:43 > [GET] /api/stream/events
1:04AM DBG ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/stream.go:63 > user feed: connection opened
1:04AM TRC ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/cron/cron.go:48 > Cron: fetch next crons
1:04AM TRC ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/router.go:43 > [GET] /api/queue/info
1:04AM DBG ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/logger.go:59 > ip=98.255.236.224 latency=0.271021 method=GET path=/api/queue/info status=200 user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
1:04AM DBG ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/stream.go:82 > user feed: connection closed
1:04AM DBG ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/logger.go:59 > ip=98.255.236.224 latency=120000.200485 method=GET path=/api/stream/events status=200 user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
1:04AM DBG ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/stream.go:82 > user feed: connection closed
1:04AM DBG ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/logger.go:59 > ip=24.205.169.244 latency=120001.019399 method=GET path=/api/stream/events status=200 user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
1:04AM TRC ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/cron/cron.go:48 > Cron: fetch next crons
1:04AM TRC ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/router.go:43 > [GET] /api/stream/events
1:04AM DBG ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/stream.go:63 > user feed: connection opened
1:04AM TRC ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/router.go:43 > [GET] /api/stream/events
1:04AM DBG ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/stream.go:63 > user feed: connection opened
1:05AM TRC ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/cron/cron.go:48 > Cron: fetch next crons
1:05AM TRC ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/cron/cron.go:48 > Cron: fetch next crons
1:05AM TRC ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/router.go:43 > [GET] /api/repos/1/branches?page=1
1:05AM DBG ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/session/repo.go:150 > bradbooth2723 granted &{UserID:4 RepoID:1 Repo:<nil> Pull:true Push:true Admin:false Synced:1700092728 Created:1700081184 Updated:1700092728} permission to provusinc/quoting
1:05AM DBG ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/logger.go:59 > ip=98.41.152.206 latency=575.944923 method=GET path=/api/repos/1/branches status=200 user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/119.0"
1:05AM DBG ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/stream.go:82 > user feed: connection closed
1:05AM DBG ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/logger.go:59 > ip=98.41.152.206 latency=120000.169876 method=GET path=/api/stream/events status=200 user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/119.0"
1:05AM TRC ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/cron/cron.go:48 > Cron: fetch next crons
1:05AM TRC ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/router.go:43 > [GET] /api/stream/events
1:05AM DBG ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/stream.go:63 > user feed: connection opened
1:05AM DBG ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/stream.go:205 > log stream: connection closed
1:05AM DBG ../../woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/logger.go:59 > ip=98.255.236.224 latency=120000.738471 method=GET path=/api/stream/logs/1/13/605 status=200 user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
panic: Write called after Handler finished

goroutine 130571 [running]:
net/http.(*http2responseWriter).write(0xc001dfc9c0?, 0xc001a18ea8?, {0x0?, 0x12634a0?, 0x1362a80?}, {0x141f1bf?, 0xc001c8e0f0?})
	/usr/local/go/src/net/http/h2_bundle.go:6797 +0x13f
net/http.(*http2responseWriter).WriteString(0xc001a18ee0?, {0x141f1bf?, 0xc001c8e0f0?})
	/usr/local/go/src/net/http/h2_bundle.go:6790 +0x28
io.WriteString({0x7f1c8472cbf8, 0xc001c8e0f0}, {0x141f1bf, 0x18})
	/usr/local/go/src/io/io.go:316 +0x58
github.com/gin-gonic/gin.(*responseWriter).WriteString(0xc0019a6e00, {0x141f1bf, 0x18})
	/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/response_writer.go:90 +0x73
io.WriteString({0x7f1c8472cbb8, 0xc0019a6e00}, {0x141f1bf, 0x18})
	/usr/local/go/src/io/io.go:316 +0x58
go.woodpecker-ci.org/woodpecker/server/api.LogStreamSSE.func2()
	/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/stream.go:224 +0x134
created by go.woodpecker-ci.org/woodpecker/server/api.LogStreamSSE in goroutine 130567
	/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/stream.go:208 +0x7a5

**Comment by 6543** [comment]
ok #2830 is ready and a test image is currently build

**Comment by 6543** [comment]
@aozomaro ok there is now a `pull_2830` tag for server and agent images (build ontop of `next`) witch you could test out.

if you set env var `WOODPECKER_CRON_ENABLE=false` there should be no cron - if the db-deadlocks disapear we have a better clue

**Comment by aozomaro** [comment]
So i've been testing out this image and i'm happy to say that I have not seen any db locking issues, however this issue appeared much faster:

{"level":"trace","time":"2023-11-16T01:58:10Z","caller":"/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/router.go:43","message":"[GET] /api/stream/events"}
{"level":"debug","time":"2023-11-16T01:58:10Z","caller":"/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/stream.go:63","message":"user feed: connection opened"}
{"level":"trace","time":"2023-11-16T01:58:26Z","caller":"/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/router.go:43","message":"[GET] /api/stream/logs/1/1/3"}
{"level":"debug","time":"2023-11-16T01:58:26Z","caller":"/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/session/repo.go:150","message":"psvillanueva granted &{UserID:4 RepoID:1 Repo:<nil> Pull:true Push:true Admin:true Synced:1700099557 Created:1700099557 Updated:1700099557} permission to provusinc/quoting"}
{"level":"debug","time":"2023-11-16T01:58:26Z","caller":"/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/stream.go:200","message":"log stream: connection opened"}
{"level":"trace","time":"2023-11-16T01:58:31Z","caller":"/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/router.go:43","message":"[GET] /api/repos/1/logs/1/8"}
{"level":"debug","time":"2023-11-16T01:58:31Z","caller":"/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/session/repo.go:150","message":"psvillanueva granted &{UserID:4 RepoID:1 Repo:<nil> Pull:true Push:true Admin:true Synced:1700099557 Created:1700099557 Updated:1700099557} permission to provusinc/quoting"}
{"level":"debug","time":"2023-11-16T01:58:31Z","caller":"/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/stream.go:205","message":"log stream: connection closed"}
{"level":"debug","ip":"133.32.217.3","latency":5345.951858,"method":"GET","path":"/api/stream/logs/1/1/3","status":200,"time":"2023-11-16T01:58:31Z","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36","time":"2023-11-16T01:58:31Z","caller":"/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/logger.go:59"}
panic: Write called after Handler finished

goroutine 9426 [running]:
net/http.(*http2responseWriter).write(0xc00189cea0?, 0xc001d75ea8?, {0x0?, 0x1262b80?, 0x135f460?}, {0x141bc62?, 0xc00061e908?})
	/usr/local/go/src/net/http/h2_bundle.go:6797 +0x13f
net/http.(*http2responseWriter).WriteString(0xc001d75ee0?, {0x141bc62?, 0xc00061e908?})
	/usr/local/go/src/net/http/h2_bundle.go:6790 +0x28
io.WriteString({0x7fb938728c98, 0xc00061e908}, {0x141bc62, 0x18})
	/usr/local/go/src/io/io.go:316 +0x58
github.com/gin-gonic/gin.(*responseWriter).WriteString(0xc001673200, {0x141bc62, 0x18})
	/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/response_writer.go:90 +0x73
io.WriteString({0x7fb938728c58, 0xc001673200}, {0x141bc62, 0x18})
	/usr/local/go/src/io/io.go:316 +0x58
go.woodpecker-ci.org/woodpecker/server/api.LogStreamSSE.func2()
	/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/stream.go:224 +0x134
created by go.woodpecker-ci.org/woodpecker/server/api.LogStreamSSE in goroutine 9410
	/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/stream.go:208 +0x7a5

**Comment by aozomaro** [comment]
If i'm not mistaken I think this is saying the stream is closed while we're still writting?

**Comment by 6543** [comment]
Ah that indicates that you just have bad I/O on the storage you save sqlite ... not ideal

**Comment by aozomaro** [comment]
Hey there, so I ended up switching to postgres, which got rid of the db locking issue. Now i'm facing this issue consistently.

<img width="913" alt="image" src="https://github.com/woodpecker-ci/woodpecker/assets/1720196/d11388f4-e20b-4233-b0eb-64c4e41149a9">


When this issue arrises, the serve stops, docker container restarts. However, some of the dependent steps start executing as a result of the restart. Is there a way to fix the panic?

**Comment by aozomaro** [comment]
Alrighty, I believe my problems are solved. _I did a number of things:_
1. Replace default sqlite w/ a Postgres db. Running Postgres reduced db lock errors and running the db in a separate process/container got rid of the db lock errors completely.
2. reduced the logging level of the agents down to `info` (agents borking is why the server was writing to a stream that had been closed)
3. Add a reverse proxy in front of woodpecker-server (this made the UI experience snappy under heavy job load (30+ simultaneously running workflows)

Thus i'll close this w/ a couple thoughts.
* Perhaps sqlite should be recommend only for testing
* Perhaps include a docker-compose example which includes the proxy (today all this info is on the website, but spread out amongst multiple sections)
