### ISSUE TITLE
Use `when` keyword for pipeline conditions

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#283]
Currently there is a single condition for whole pipeline files named `branches`. As woodpecker will probably support more conditions in the future like #86 and to match the way conditions for pipeline-steps are working it would be nice to move the branch condition below the `when` keyword.

```diff
pipeline:
  build:
    image: golang
    commands:
      - go build
      - go test
   when:
     branch: [master, develop]

-branches: [ master, develop ]
+when:
+  branch: [master, develop]
```

**Comment by 6543** [comment]
yes we should unify the when filter for pipeline ans steps ...
