### ISSUE TITLE
Secrets don't work

### ISSUE THREAD

**Issue by zc-devs** [woodpecker-ci/woodpecker#2832]
### Component

server

### Describe the bug

Pipeline doesn't start with error `secret "secret_name" not found or not allowed to be used`.

1. Create pipeline:
```yaml
steps:
  test:
    image: alpine
    commands:
      - printenv
    secrets:
      - test_secret
```
2. Create secret:
```sql
woodpecker=# select * from secrets;
 secret_id | secret_org_id | secret_repo_id | secret_name |      secret_value       | secret_images |   secret_events
-----------+---------------+----------------+-------------+-------------------------+---------------+-------------------
         5 |             0 |              1 | test_secret | value_test_secret_value | ["alpine"]    | ["manual","push"]
(1 row)
```
3. Run pipeline manually.
4. Get error:
![Screenshot 2023-11-16 180643](https://github.com/woodpecker-ci/woodpecker/assets/127358482/ad297cca-4d37-4cc9-bbcb-4f2accb06789)

### System Info

```shell
2.0.0-rc.0, next-342b25826c, Kubernetes
```

### Additional context

[woodpecker-server-rc.log](https://github.com/woodpecker-ci/woodpecker/files/13379201/woodpecker-server-rc.log)
[woodpecker-server-342b25826c.log](https://github.com/woodpecker-ci/woodpecker/files/13379202/woodpecker-server-342b25826c.log)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by anbraten** [comment]
If you set an image the secret is only available to plugins, so not for this one as you set commands
