### ISSUE TITLE
Add repository page is empty

### ISSUE THREAD

**Issue by crapStone** [woodpecker-ci/woodpecker#2854]
### Component

web-ui

### Describe the bug

When trying to add a repository the "Add repository" page is empty

### System Info

```shell
Woodpecker CI @ Codeberg
we are using next
```

### Additional context

![image](https://github.com/woodpecker-ci/woodpecker/assets/23100555/a0171d12-1194-4fe0-927f-335e1d4cb326)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by pat-s** [comment]
Can confirm the issue.

**Comment by crapStone** [comment]
Thanks for fixing this so quickly :)
