### ISSUE TITLE
Tidy up Dockerfiles and remove dependency on drone/ca-certs

### ISSUE THREAD

**Issue by UnlimitedCookies** [woodpecker-ci/woodpecker#288]
I would love to test out the UI rewrite, but I am confused by the seemingly duplicate Dockerfiles. 

E. g. `Dockerfile.agent{.alpine}`  seem quite similar.

The `Dockerfile.agent` apparently still depends on `drone/ca-certs`, which I think should be dropped.

**Comment by anbraten** [comment]
I already started on doing that in #257 

To test the UI rewrite ATM the easiest way is currently to checkout that branch and run woodpecker via the debug with vs-code.

**Comment by UnlimitedCookies** [comment]
Awesome, that PR already looks promising.

I am still wondering though why there are still two very similar docker images (one ending with .alpine).

**Comment by anbraten** [comment]
Without alpine is the scratch image with just the binaries in it and with .alpine is an image based on alpine so you are able to use a command line. I prefer the scratch images, but some others like to have a command line next to woodpecker so we have both.

**Comment by UnlimitedCookies** [comment]
I understand, thanks for the explanation!

Even better would it be to just let docker handle the building with a `docker-compose.yml`. Is that currently possible?
