### ISSUE TITLE
step logs stuck in `loading`, trying to stream logs for a finished step

### ISSUE THREAD

**Issue by runephilosof-karnovgroup** [woodpecker-ci/woodpecker#2942]
### Component

web-ui

### Describe the bug

Often selecting a step before it has started will result in getting stuck with a `loading` screen for the logs.
The exit code of the step will update to `Exit code 1`, but the logs will keep showing `loading`.
Reloading the page works (most of the time, I have seen examples where I had to reload more than once).

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"2.0.0"}
```

### Additional context

The UI keeps retrieving the stream/logs endpoint, even though that endpoint returns `error	step not running (anymore)`.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by anbraten** [comment]
Logging was improved in #3722 and probably fixed this issue as well. Please re-open if not
