### ISSUE TITLE
An unknown error occurred on repository setting page (access to global secrets)

### ISSUE THREAD

**Issue by zc-devs** [woodpecker-ci/woodpecker#3013]
### Component

server, web-ui

### Describe the bug

1. Optional: Activate a repo in Woodpecker
2. Open repository without secrets
3. Go to settings page, General tab
4. Get error

```
An unknown error occurred
index-yc-Su7Fu.js:25 
GET https://woodpecker.test.smthd.com/api/secrets?page=1 403 (Forbidden)
```

There are two requests to the `secrets?page=1`: one with HTTP 200, another HTTP 403.

---

If there is at least one secret, then there is no error and only one request to the `secrets?page=1` with HTTP 200.

### System Info

```shell
next-acec955943
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by zc-devs** [comment]
Yes, just general user.

**Comment by zc-devs** [comment]
On `2.1.1` if there is no one secret, then all is the same as on `2.0`.

But now, even if there is one secret, error appears when page is scrolled down to the bottom:
![Screenshot 2023-12-28 191754](https://github.com/woodpecker-ci/woodpecker/assets/127358482/46954230-e46b-45e8-899b-23804cd392ed)
![Screenshot 2023-12-28 191818](https://github.com/woodpecker-ci/woodpecker/assets/127358482/89a06fda-ea24-40ea-96f1-ffed717e7075)

**Comment by zc-devs** [comment]
> There are two requests to the secrets?page=1: one with HTTP 200, another HTTP 403.

Corrections:

1. 200 is to `/api/orgs/3/secrets?page=1`
2. 403 is to `/api/secrets?page=1`, global secrets
3. The same on Repository's Secrets page

**Comment by anbraten** [comment]
Ahh, the issue is we query instance secrets to show if the user overrides them, but unfortunately we don't allow normal users to access that endpoint. Not sure why the org endpoint is failing your case. 🤔 Are you not an admin of your org?

**Comment by zc-devs** [comment]
> Not sure why the org endpoint is failing your case

It was OK 200, I think. I just didn't look carefully inside, my bad.
![Screenshot 2024-02-05 1](https://github.com/woodpecker-ci/woodpecker/assets/127358482/417da115-a48f-4af9-96f7-0c65dc35a7c9)

^ there are
200 to `api/repos/22/secrets?page=2`
200 to `api/orgs/3/secrets?page=1`
403 to `api/secrets?page=1`

> Are you not an admin of your org?

Don't know, if I wasn't, but now [I am](https://github.com/woodpecker-ci/woodpecker/issues/3328#issuecomment-1927525420) :)

> we don't allow normal users to access that endpoint

Yeah. Seems, that's the cause.

**Comment by anbraten** [comment]
I am currently checking how to fix this one. We can either skip the api request in case the user is not an admin or we allow every user to get (read-only) the global secrets as they don't include the actual value and will be available in the pipeline anyway.
