### ISSUE TITLE
Update notice showing for v2.1.0 while already on v2.1.0

### ISSUE THREAD

**Issue by kemitix** [woodpecker-ci/woodpecker#3034]
After switching to the v2.1.0 docker image for woodpecker, the admin interface says to update to the current version.

![image](https://github.com/woodpecker-ci/woodpecker/assets/1147749/e976a089-ac98-48b7-89f3-6d21f88967ce)

This is from the docker image: `woodpeckerci/woodpecker-server:v2.1.0`

**Comment by anbraten** [comment]
https://woodpecker-ci.org/version.json is having the v-prefix. So we either need to strip it when updating in ci or use string-replace in UI.

**Comment by awnion** [comment]
Similar in case of the `woodpeckerci/woodpecker-server:next` container:
<img width="517" alt="Screenshot 2023-12-27 at 11 18 28" src="https://github.com/woodpecker-ci/woodpecker/assets/1329201/5f2a3de5-660e-496c-ab91-8cc97d75c714">

But the "recommended" version doesn't exist!
<img width="844" alt="Screenshot 2023-12-27 at 11 21 28" src="https://github.com/woodpecker-ci/woodpecker/assets/1329201/ce83958c-33bd-4f8a-b88e-2d5fe42a47e5">

**Comment by 6543** [comment]
I'll create a hotfix, and we should do semversion parsing wo compares versions

**Comment by kemitix** [comment]
Thanks. Everything looks great now.
