### ISSUE TITLE
depends_on: [] doesn't enable DAG mode

### ISSUE THREAD

**Issue by xfix** [woodpecker-ci/woodpecker#3055]
### Component

server

### Describe the bug

`depends_on: []` like specified in https://github.com/woodpecker-ci/woodpecker/blob/c1a1f7c10b3c0840bad9c0b25fcd7f5ff8b0173b/.woodpecker/securityscan.yml is useless, and doesn't enable DAG mode as documented on https://woodpecker-ci.org/docs/usage/workflow-syntax#depends_on.

This is because DAG is only enabled for non-empty lists: https://github.com/woodpecker-ci/woodpecker/blob/c1a1f7c10b3c0840bad9c0b25fcd7f5ff8b0173b/pipeline/frontend/yaml/compiler/dag.go#L44-L51

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"2.1.1"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by anbraten** [comment]
Should check for `nil`, but afaik we will run into `depends_on: []` being `nil` as well when parsed by the yaml parser: https://github.com/go-yaml/yaml/issues/42

**Comment by 6543** [comment]
@anbraten we chould allow `depends_on: [""]` ...

as this would also address https://github.com/woodpecker-ci/woodpecker/discussions/3047

**Comment by 6543** [comment]
if we merge  #3008 that should be addressed

**Comment by xfix** [comment]
I don't think #3008 is really a solution. `depends_on: []` still won't work, and `depends_on: [""]` looks like some kind of workaround that shouldn't be necessary.

**Comment by xfix** [comment]
As for yaml/yaml#42, as far as I can tell, parsing empty arrays works as expected, the following Go program:

```go
package main

import (
	"fmt"

	"gopkg.in/yaml.v3"
)

type Item struct {
	DependsOn []string `yaml:"depends_on"`
}

func main() {
	var a Item
	yaml.Unmarshal([]byte("{}"), &a)
	fmt.Println(a.DependsOn == nil)
	out, err := yaml.Marshal(a)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(out))

	var b Item
	yaml.Unmarshal([]byte("depends_on: []"), &b)
	fmt.Println(b.DependsOn == nil)
	out, err = yaml.Marshal(b)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(out))
}
```

Outputs this:

```
true
depends_on: []

false
depends_on: []
```

An empty array is not null, unlike an unprovided array. However, it's worth noting that that when marshaled with YAML, `nil` array ends up being `[]`.

However, there is a workaround to make YAML marshaling work as well of providing the type as `*[]string`. Then, both marshaling and unmarshaling will work fine.

```go
package main

import (
	"fmt"

	"gopkg.in/yaml.v3"
)

type Item struct {
	DependsOn *[]string `yaml:"depends_on,omitempty"`
}

func main() {
	var a Item
	yaml.Unmarshal([]byte("{}"), &a)
	fmt.Println(a.DependsOn == nil)
	out, err := yaml.Marshal(a)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(out))

	var b Item
	yaml.Unmarshal([]byte("depends_on: []"), &b)
	fmt.Println(b.DependsOn == nil)
	out, err = yaml.Marshal(b)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(out))
}
```

This will output:

```
true
{}

false
depends_on: []
```

This works fine with `*StringOrSlice` type as well.

**Comment by 6543** [comment]
could you create a pull :)
