### ISSUE TITLE
Release binary from server and agent

### ISSUE THREAD

**Issue by genofire** [woodpecker-ci/woodpecker#309]
### Clear and concise description of the problem

after a release server and agent have to build on there own (if no docker is used)

### Suggested solution

create an `.woodpecker` publish binary release for server and agent to github (like cli)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.github.io/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by UnlimitedCookies** [comment]
This is already planned with #257 
Though, I am unsure how to get CI working without having a working docker daemon (or podman) running.

**Comment by genofire** [comment]
This is great. Thanks for the feedback

**Comment by anbraten** [comment]
> This is already planned with #257 
> Though, I am unsure how to get CI working without having a working docker daemon (or podman) running. 

I used Kaniko in #257 for building docker images which already works quite well 😉
