### ISSUE TITLE
Kubernetes `backend_options`: use snake_case

### ISSUE THREAD

**Issue by qwerty287** [woodpecker-ci/woodpecker#3091]
Backend options for kubernetes currently use camelCase while everything else uses snake_case (e.g. https://woodpecker-ci.org/docs/next/administration/backends/kubernetes#nodeselector).

For consistency, all should be snake_case.

**Comment by pat-s** [comment]
CamelCase is the primary notation in kubernetes. If this changed, one cannot c/p valid k8s code anymore. 

I would vote for keeping it as is.
