### ISSUE TITLE
Can not restart failed pipelines

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#3107]
if the pipeline fails because of an external issue like:

https://ci.woodpecker-ci.org/repos/3780/pipeline/11472

the restarted pipeline do not find the pipeline config:

https://ci.woodpecker-ci.org/repos/3780/pipeline/11475/errors

I would expect that the pipeline restart with the old config and try to fetch external things like e.g. secrets again

**Comment by anbraten** [comment]
duplicate #2982
