### ISSUE TITLE
`when` evaluation string filter

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#312]
### Clear and concise description of the problem

Currently Woodpecker already has quite some options for `when` to filter steps, but there are already some more requested adding all kind of exceptions would require quite some maintenance in the future.

### Suggested solution

Woodpecker could introduce artithmetic/string expressions to evaluate if a step should be executed replacing the current yml options. This could be done by some library like [govaluate](https://github.com/Knetic/govaluate). By adding all kind of meta-data available for a step as variables and adding a few special functions a user could simply write own expressions like this example:

```bash
woodpecker.event == "tag" && contains(toLowerCase(woodpecker.commit.message), "[skip ci"])
```

A similar feature is available for [Github Actions](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions)

**Comment by 6543** [comment]
drone did something similar with its new pipeline config format: 
https://github.com/go-gitea/gitea/blob/7815f244d6254f85fca439b0bbfaf63c0e263ea4/.drone.yml#L5-L13

for expressions I would say we should not do that, instead add support for **Starlark** as it's already in used:
 * https://docs.drone.digitalstacks.net/l/en/scripting/starlark
 * https://cirrus-ci.org/guide/programming-tasks/

that way we have two options: a nice readable simple strait forward condig - or a powerful scripting lang to generate config dynamicaly

**Comment by 6543** [comment]
it the starlark part in drone is apache2 ... we might just can copy it?

**Comment by anbraten** [comment]
> ~it the starlark part in drone is apache2 ... we might just can copy it?~ no: https://github.com/drone/drone-convert-starlark/blob/master/LICENSE.md

Damn.

---

I like the starlark approach, but on the other hand we wont drop the yml support and IMO there are already quite some special when options like `when.path.ignore_message` ([docs](https://woodpecker-ci.github.io/docs/usage/pipeline-syntax#path)) and some similar possibilities have already been asked for: #125, #224, #304

My suggestion for the long term would be:
- add some new field to when called something like: `if` or `condition` which can take an expression as string
- add some variables like commit title, commit sha, commit author, tag, ref, step-id, ... to the context variables
- change when to accept an array to be able to define multiple when conditions as some kind of OR (the conditions inside a current when are evaluated as AND)
- deprecate some very special options like: `when.path.ignore_message`
- add step when conditions to pipeline as well (context of variables could be different as some values of a step could not be available and some additional values could be added) 

Maybe may example (`contains(toLowerCase(woodpecker.commit.message)`) was a bit drastic with adding something like this `contains` function 😉 . I would only start with standard expressions like `==` .
This would in addition match how Github, Gitlab, ... have it so migration would maybe be simpler for new users.

**Comment by 6543** [comment]
the easiest way to add or: `A | B => !(!A & !B)` if we make branch= or ref= to condition matching -> where `branch: !ignore|!release/**` would work

**Comment by x80486** [comment]
While my intent on linking all these is not to make `Woodpecker CI` the same as the others, I think the `GitLab CI` [solution](https://docs.gitlab.com/ee/ci/yaml/#rules) around `rules` is pretty powerful and flexible.
