### ISSUE TITLE
Docker Tag vX.X not working

### ISSUE THREAD

**Issue by dR3b** [woodpecker-ci/woodpecker#3131]
### Component

other

### Describe the bug

The docker tag `vX.X` (v2.1) (details: https://woodpecker-ci.org/docs/administration/deployment/docker-compose#docker-images) does not work.

### Additional context
```
docker pull woodpeckerci/woodpecker-server:v2.1-alpne
Error response from daemon: manifest for woodpeckerci/woodpecker-server:v2.1-alpne not found: manifest unknown: manifest unknown
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by dR3b** [comment]
I don't think that's a good idea. If there is a release 3.0 later, I'll get this version straight away without a warning!

**Comment by pat-s** [comment]
@qwerty287 Using `auto_tag` of the buildx plugin should take care of this automatically - or a slight modification of the manifest template. It doesn't cost anything and the usefulness by @dR3b is well described.

**Comment by dR3b** [comment]
Is there any status update?

**Comment by pat-s** [comment]
Not yet, somebody would need to add the `auto_tag` to all docker release builds. PR welcome :)
