### ISSUE TITLE
Add Documentation how to develop woodpecker

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#314]
* [ ] how can you create database migration
* [ ] where you find what (packages, ...)
* [ ] Rquirements (go >= 1.16, make, nodejs)
* [ ] ...

diagrams https://whimsical.com/woodpecker-ci-92tFmAMd5KuEFdcrJsuWMs

**Comment by 6543** [comment]
cc @cognifloyd after restructure ... your svg/png would be a nice thing :)

**Comment by cognifloyd** [comment]
I'll update the diagram as we merge changes.

**Comment by cognifloyd** [comment]
Here's the diagram assuming that #347 gets merged
![Woodpecker Architecture](https://user-images.githubusercontent.com/1558590/134590004-ad8a8c79-508f-4bc1-8ec1-2053b19421bc.png)
I can also export an svg, or we can embed it directly in docs:
```
<iframe style="border:none" width="800" height="450" src="https://whimsical.com/embed/V3iRFaQUWKm1dYXgd5KHAz"></iframe>
```
Here's a direct link to the sources: https://whimsical.com/woodpecker-architecture-V3iRFaQUWKm1dYXgd5KHAz

**Comment by cognifloyd** [comment]
This is a very detailed diagram where I traced how data flows from SCM through build completion
It does not include all API endpoints. It just focuses on the ones involved in the build itself and the interactions between the server, the agent, the server's services, and external services.

**Comment by 6543** [comment]
Add desc how to builld and start for local tests:

" ...I'm completely new to the woodpecker community and want to contribute ... but don't know how to run the server on my computer can you both tell me the steps? thanks ..."
-> make it easy for new devs to do stuff!
