### ISSUE TITLE
Remove all references to drone

### ISSUE THREAD

**Issue by davidak** [woodpecker-ci/woodpecker#319]
There are still a lot of places where "drone" is mentioned.

Is there a place where the transition is coordinated? If not, this issue can be used.

Examples:

https://github.com/woodpecker-ci/woodpecker/search?q=drone&type=code
https://github.com/woodpecker-ci/woodpecker/tree/master/cli

**Comment by 6543** [comment]
most references are gone - it there are some the will be changed while refactoring / extending that pice of code ...

and I would not completely remove all references since our code roots still back to drone and as long as we do not rewrite it all it will continue ;)
