### ISSUE TITLE
Promote topic

### ISSUE THREAD

**Issue by davidak** [woodpecker-ci/woodpecker#320]
You ask in the readme:

>Who uses Woodpecker?

A topic (repository tag) can help answer the question.

A good example is: https://github.com/topics/github-actions

So, please decide on a tag that should be used and promote it in the readme.

[woodpecker](https://github.com/topics/woodpecker) is already used for unrelated purposes, so [woodpecker-ci](https://github.com/topics/woodpecker-ci) seem to be the best choice.

I have used it here: https://codeberg.org/explore/repos?q=woodpecker-ci&topic=1

**Comment by anbraten** [comment]
We can create a PR at https://github.com/github/explore/tree/main/topics to improve the topic page.

**Comment by davidak** [comment]
can you state the decision for the tag? then i can promote it in the codeberg community

**Comment by anbraten** [comment]
I think you could use `woodpecker-ci`

**Comment by davidak** [comment]
then this is now the official tag. thanks

**Comment by davidak** [comment]
It was noticed that `#woodpecker-ci` does not work as tag on Mastodon and Twitter. So we have to use a different one that works everywhere.

https://mastodon.technology/@WoodpeckerCI/107009639135334609
![Screenshot from 2021-10-10 06-24-00](https://user-images.githubusercontent.com/91113/136682008-b68d3635-03be-460b-b0c7-ffdbdf3aadda.png)
(Twitter)

`#WoodpeckerCI` seem to be the next best choice that is already used. Any remarks?

https://mastodon.technology/tags/WoodpeckerCI (only related posts)

People already use `#Woodpecker` which is a terrible mess: https://mastodon.online/tags/Woodpecker

**Comment by davidak** [comment]
Can we have a decision (again)?

**Comment by 6543** [comment]
Whats up?

**Comment by davidak** [comment]
We have to decide on a new tag to use, since `#woodpecker-ci` does not work as tag on Mastodon and Twitter. See comment above!

**Comment by anbraten** [comment]
`#WoodpeckerCI` should be closest to the previous selected one.

**Comment by aschrijver** [comment]
Yes, used that myself too on the Fediverse until now. Would like to add that case-sensitivity as suggested by @anbraten is important, accessibility-wise for those who are vision-impaired and using screenreaders.

**Comment by davidak** [comment]
I added the topic and tag to the README and also created a topic on GitHub. They did not complain that there is actually just one repo that uses the tag legitimally and that is the project itself. (I added the topic to a test repo that actually not uses Woodpecker CI, so the tag page does not look too empty)

https://github.com/topics/woodpeckerci

Can you post a note on social media (Fediverse, Twitter) with the official account that users should use the new tag, so other users can get inspired and learn?
