### ISSUE TITLE
Can't authenticate to Forgejo (Gitea) - ERR cannot authenticate user. unknown version: b5757a6

### ISSUE THREAD

**Issue by voltagex** [woodpecker-ci/woodpecker#3240]
### Component

server

### Describe the bug

I have Forgejo  up and running with an OAuth application for Woodpecker defined.

![image](https://github.com/woodpecker-ci/woodpecker/assets/83080728/7ce65d90-38e0-4f45-a0a7-b6963cc53d7e)

Logs say: `ERR cannot authenticate user. unknown version: b5757a6`

This is coming back from the _Gitea SDK_: https://gitea.com/gitea/go-sdk/src/branch/main/gitea/version.go#L81

I think Forgejo will need to be able to report back a different version number to what is expected, or you (the Woodpecker project) need to modify the Gitea SDK to be a bit more flexible

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"2.1.1"}

./forgejo/gitea -v
Forgejo version b5757a6 built with GNU Make 4.4.1, go1.21.6 : bindata, sqlite, sqlite_unlock_notify
```

### Additional context

Forgejo config is correct as far as I can tell.

The error messages on both sides of this need to be improved.

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by voltagex** [comment]
https://github.com/woodpecker-ci/woodpecker/blob/072fa29f4a40239a85b0d3cfe5ffe7eb0680445e/server/api/login.go#L53 is part of that error, but where's the "unknown version" coming from?

**Comment by voltagex** [comment]
Dropped back to the release version, with settings 

```
[service]
REGISTER_EMAIL_CONFIRM = false
ENABLE_NOTIFY_MAIL = false
DISABLE_REGISTRATION = false
ALLOW_ONLY_EXTERNAL_REGISTRATION = false
```

And now the SDK error is `ERR cannot register voltagex. registration closed`

It shouldn't need to register me, I already exist! Would you like me to open another issue for this?

**Comment by lafriks** [comment]
I think this is a problem with fogejo, gitea sdk need to be able to detect version number to know the supported API endpoints and features

**Comment by voltagex** [comment]
Yes that's what I suspected and worked out reading the SDK code.

Really, it'd be better to do feature detection or have a concept of "feature version"

At any rate, the error message needs to be better on the Woodpecker side.

**Comment by 6543** [comment]
we already have an code that should have handled it in place:

**Comment by 6543** [comment]
we already have an code that should have handled it in place:

https://github.com/woodpecker-ci/woodpecker/blob/646f2c5c7a1da4ef58059b7db0409c01ddeac976/server/forge/gitea/gitea.go#L589-L593

but we do check for an string ... I should upstream an error type we can check agains with `errors.Is()`

**Comment by 6543** [comment]
-> #3243
