### ISSUE TITLE
remove of agent does not reset task in queue

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#3248]
![image](https://github.com/woodpecker-ci/woodpecker/assets/24977596/41253e88-e967-41a1-9e56-79ad89f7ed83)
![image](https://github.com/woodpecker-ci/woodpecker/assets/24977596/8d949332-09b1-49cd-ae34-2fe5e894018a)

woodpecker version: v2.2.2

if the autoscaler just cancled an agent who just managed to mark an task as started ... we will wait without any chance of success.

so i propose on agent removal, (and if agent heartbet do timeout) to "reset" all running tasks in queue, so healthy agents can pick them up again

**Comment by 6543** [comment]
I still think it should land in server itselve

**Comment by anbraten** [comment]
fixed by https://github.com/woodpecker-ci/woodpecker/pull/3377
