### ISSUE TITLE
Link to github release broken

### ISSUE THREAD

**Issue by whysthatso** [woodpecker-ci/woodpecker#3253]
### Component

web-ui

### Describe the bug

Please update your Woodpecker instance to [2.2.2](https://github.com/woodpecker-ci/woodpecker/releases/tag/2.2.2)

is missing the v before the version number.

This is the notification in the web ui

### System Info

```shell
Woodpecker 2.2.1
```

### Additional context

this is probably related to this change: https://github.com/woodpecker-ci/woodpecker/pull/2722

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by anbraten** [comment]
Sorry for the inconvenience our pipeline had an issue pushing somehow: https://ci.woodpecker-ci.org/repos/8958/pipeline/628

**Comment by whysthatso** [comment]
> @whysthatso Did you get this bug with 2.1.1? Because it's fixed in 2.2.0+ #3042

ah yes i see. brainfart, i thought i was on 2.2.0 when i read the changelog :(
