### ISSUE TITLE
kubernetes backend - step name with spaces causes label error

### ISSUE THREAD

**Issue by metawave** [woodpecker-ci/woodpecker#3272]
### Component

agent

### Describe the bug

Having a pipline like:
```
steps:
  - name: build image
    image: plugins/docker
```

on a woodpecker 2.2.2 server with kubernetes backend I get the following error:
```
Pod "wp-01hmywxc67eps76kjkryer0rc6" is invalid: metadata.labels: Invalid value: "build image": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```

This has worked before on the 2.1.x version

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"2.2.2"}
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by zc-devs** [comment]
What is expected behavior, apart from `This has worked before`? What label should be in your opinion?

**Comment by metawave** [comment]
@zc-devs Currently, all pipelines with steps, which contain a space in the name don't work at all. I don't expect a certain label on pods (for steps). Only when all steps don't have spaces it works. I'm currently blocked on all pipelines which have spaces in the step name.

**Comment by metawave** [comment]
Yes I think that was the behaviour before. The problem has been introduced by #3204 I think, where the step name is now used to label the pod. That wasn't the case before. Now when a step name doesn't correspond to valid k8s-label regex (([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?'), it will fail. A translation of non-valid characters (according to label spec) to hyphens would be the best solution for now IMO. It might be worth adding a test in pod_test.go, where a step has a non basic naming, like "build & deploy".
