### ISSUE TITLE
An unknown error occurred on User Secrets page (migration v1 -> v2)

### ISSUE THREAD

**Issue by zc-devs** [woodpecker-ci/woodpecker#3328]
### Component

server

### Describe the bug

Some users face `An unknown error occurred` popup when follow to their profile Secrets page.

---

On that old instance (the first deployed version was 1.0, as I remember) we have:
```
woodpecker=# select user_id, user_login, user_org_id from users order by user_id;
 user_id |  user_login   | user_org_id
---------+---------------+-------------
       1 | admin         |           3
       2 | maria         |           3
       3 | kevin         |           3
       4 | piter         |           3
       5 | john          |           5
(5 rows)

woodpecker=# select * from orgs;
 id |     name      | is_user | private
----+---------------+---------+---------
  1 | maria         | t       | f
  2 | piter         | t       | f
  3 | kevin         | t       | f
  4 | admin         | t       | f
  5 | john          | t       | f
(5 rows)
```

As we can see, majority of users are members of an organization `3, kevin`. `john` is a pretty new user.
When `piter` goes to `https://woodpecker.example.com/user#secrets`, he sees error in browser console
```
GET
https://https://woodpecker.example.com/api/orgs/3/secrets?page=1
[HTTP/2 403  138ms]
```

On test instance (the first deployment was around version 2, as I remember) we have:
```
woodpecker_test=# select user_id, user_login, user_org_id from users;
 user_id | user_login | user_org_id
---------+------------+-------------
       3 | usr2       |           3
       2 | usr        |           2
       1 | admin      |           1
(3 rows)

woodpecker_test=# select * from orgs;
 id | name  | is_user | private
----+-------+---------+---------
  1 | admin | t       | f
  2 | usr   | t       | f
  3 | usr2  | t       | f
(3 rows)
```

All users have their own orgs. So there are no errors.

### System Info

```shell
Woodpecker 2.3.0, Gitea 1.21.5, PostgreSQL 16
```

### Additional context

https://github.com/woodpecker-ci/woodpecker/pull/3319

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by zc-devs** [comment]
`1.0.5`

```
woodpecker_test=# select user_id, user_login, user_org_id from users order by user_id;
ERROR:  column "user_org_id" does not exist
LINE 1: select user_id, user_login, user_org_id from users

woodpecker_test=# select user_id, user_login from users order by user_id;
 user_id | user_login
---------+------------
       1 | adm
       2 | usr
       3 | usr2
       4 | kcu
       5 | usr3
(5 rows)

woodpecker_test=# select * from orgs;
 id | name | is_user | private
----+------+---------+---------
(0 rows)
```

Right after upgrade to `2.0.0`

[woodpecker-server-2.0.0.log](https://github.com/woodpecker-ci/woodpecker/files/14190174/woodpecker-server-2.0.0.log)

```
woodpecker_test=# select user_id, user_login, user_org_id from users order by user_id;
 user_id | user_login | user_org_id
---------+------------+-------------
       1 | adm        |           5
       2 | usr        |           5
       3 | usr2       |           5
       4 | kcu        |           5
       5 | usr3       |           5
(5 rows)

woodpecker_test=# select * from orgs;
 id | name | is_user | private
----+------+---------+---------
  1 | adm  | t       | f
  2 | usr  | t       | f
  3 | kcu  | t       | f
  4 | usr2 | t       | f
  5 | usr3 | t       | f
(5 rows)
```

**Comment by pat-s** [comment]
Thanks for the insights! I think this strengthens my gut feeling that #3319 might be needed. 
Help is needed to finish/test this one.

**Comment by zc-devs** [comment]
#3347

**Comment by pat-s** [comment]
I think #3013, #3347, https://codeberg.org/Codeberg-CI/feedback/issues/149, https://codeberg.org/Codeberg-CI/feedback/issues/136, #2714 do all originate from the same underlying problem(s). We should consolidate all issues and only keep one in which a focused discussion can happen.

**Comment by OCram85** [comment]
Do you have a preferred approach for this? - Which data should be evaluated in which way to further investigate this problem?

Maybe it's also worth to find a manual workaround for a small database. A quick way to restore an falsyl marked account as user again as a org identity?

**Comment by pat-s** [comment]
TBH, I don't know. I haven't interacted with the DB code in WP so far. I only found out that false mapping when doing a deep dive into the Codeberg DB which resulted in #3319. 

An official migration might be needed, maybe even multiple ones. 

For your own installation: You can surely make some changes within your own DB tables, at your own risk though. But I can't tell you what to do exactly so that everything works again afterward, as the issue is not yet fully understood (i.e. yes there is the wrong non-unique mapping of user orgs but this does not seem to resolve access issue for the own org, see the feedback form the Codeberg link above).

**Comment by OCram85** [comment]
Can we somehow estimate how many instances ( or percentage of users ) might be affected by this problem?

**Comment by zc-devs** [comment]
>how many instances

I guess, all who run Postgres and have upgraded from v1.

**Comment by MrMeeb** [comment]
I feel I'm seeing something similar, although I'm not using Postgres and haven't upgraded from v1. It's a new install using sqlite with Gitea as the forge. 

When accessing the user page I see the same error, and when trying to create a secret I get the same 403 error when accessing `https://ci.domain.com/api/orgs/1/secrets`. It sounds similar?

**Comment by zc-devs** [comment]
> It sounds similar?

Let's see: run this
```
select user_id, user_login, user_org_id from users order by user_id;
select * from orgs;
```
`users.user_org_id` should be equal to `orgs.id` for your user.

**Comment by MrMeeb** [comment]
Hmm, I guess it's something else. They're both `1`

```
sqlite> select user_id, user_login, user_org_id from users order by user_id;
user_id  user_login  user_org_id
-------  ----------  -----------
1        MrMeeb      1
sqlite> select * from orgs;
id  name    is_user  private
--  ------  -------  -------
1   mrmeeb  1        0
```

**Comment by zc-devs** [comment]
What do we have now?
1. Issue is about `1.0`->`2.0` migration
2. The both versions are [not supported](https://woodpecker-ci.org/versions#past-versions-not-maintained-anymore) long time ago
3. Nobody wants to fix migration (see 2)
4. This issue moves from one milestone to another (see 3)
5. Who was affected, has fixed it by now manually, I suppose

Therefore I'm closing it for now. Reopen if disagree.
