### ISSUE TITLE
add link checker to ci

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#3332]
add a link checker for the docs into our pipelines.

https://lychee.cli.rs/ should be a good way to go.

this should run as a docs linter ... only for files changed **and** block
and weekly check the whole docs ... but do **not** block

**Comment by 6543** [comment]
quick run:
![image](https://github.com/woodpecker-ci/woodpecker/assets/24977596/16a51f33-e826-47b5-adc0-05c5bbef9576)

so yes we need it!

**Comment by pat-s** [comment]
`lychee` is great. Using it in some projects, fast and reliable.

**Comment by anbraten** [comment]
https://career.axelspringer.com/de/job/office-365-consultant-2

**Comment by anbraten** [comment]
https://docusaurus.io/docs/api/docusaurus-config#onBrokenLinks
