### ISSUE TITLE
Organizations not accessible after upgrading to woodpecker 2++

### ISSUE THREAD

**Issue by OCram85** [woodpecker-ci/woodpecker#3347]
### Component

server

### Describe the bug

After upgrading Woodpecker server and agent from v1 to 2++ version al the organizations and their settings page are not accessible:
- Missing the pre existing orgs also in the `admin#orgs` view. All repos and org secrets are still consumable but not editable.
- Can't can't navigate to a org settings page or browse directly via `/orgs/<orgid>/settings`. 
- The org definition still seems to be present in the db but marked as user (`is_user=true`):

![image](https://github.com/woodpecker-ci/woodpecker/assets/13993700/e8d86438-a00d-480e-a3fc-a02eed9d1c9e)

### System Info

```shell
{
  "source": "https://github.com/woodpecker-ci/woodpecker",
  "version": "2.3.0"
}
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by OCram85** [comment]
Is there anything I can do to help debugging / fixing this? - If I got this right the same issue appears on instances running with PostgreSQL after migrating from v1 to v2.

Maybe there is also a save way to restore the organization and also keeping its secrets? - But I'm not familiar enough with the db schema to manually mess around with it.

**Comment by pat-s** [comment]
There's no official doc on what to do, as we don't know if all instances are affected in the same way.
You can check what I did in https://codeberg.org/Codeberg-CI/feedback/issues/149 and try to replicate the steps in your instance.

**Comment by lafriks** [comment]
I can also confirm that we are also affected by this, we do manually fix records in db when we find them...

**Comment by OCram85** [comment]
@lafriks: Did you just update the user record in the orgs table from `is_user: true` to `false`  to fix this? -Or did you also have to change records in the `users` and `permission` table?

**Comment by OCram85** [comment]
Just tried to fix my issues by:
- Updating affected orgs with setting `is_user: false`.
- fixing the `users.user_org_id` which points to the wrong and not existing orgs.

But unfortunately this ended up causing permission issues for user repos and org settings. So I did a restore and started investigating.

----

I came up with these simple SQL joins to be able visualizing obvious db record issues:

1. Show user and their orgs:

```sql
SELECT
  user_id,
  orgs.name "RESOLVED ORG",
  user_login, user_email
FROM users
INNER JOIN orgs
  ON users.user_org_id = orgs.id
ORDER BY user_id;
```

2. Show orgs and search for records with wrong `is_user`  markings

```sql
SELECT id, name, is_user
FROM orgs
ORDER BY id;
```

3. Show repos with their resolved orgs and uers

```sql
SELECT 
  repo_id,
  repo_user_id,
  users.user_login "RESOLVED USER",
  repo_org_id,
  orgs.name "RESOLVED ORG",
  repo_full_name
FROM repos
INNER JOIN orgs
  ON repos.repo_org_id = orgs.id
INNER JOIN users
  ON repos.repo_user_id = users.user_id
ORDER BY repo_id;
``` 

4. Show permission table with resolved repo, user and org name:

```sql
SELECT 
  repos.repo_full_name "RESOLVED REPO",
  perm_user_id,
  users.user_login "RESOLVED USER",
  perm_repo_id,
  repos.repo_org_id,
  orgs.name "RESOLVED ORG NAME",
  perm_admin
FROM perms
INNER JOIN users
  ON perms.perm_user_id = users.user_id
INNER JOIN repos
  ON perms.perm_repo_id = repos.repo_id
INNER JOIN orgs
  ON repos.repo_org_id = orgs.id
ORDER BY repos.repo_full_name, perm_user_id;
```

**Comment by OCram85** [comment]
Just updated to woodpecker `2.4.0` and fixed the `user -> org` mapping like described above. Also checked for _Capitalization problems_.

Now users can access their own org again and add + edit user wide secrets.

But on every repository settings page ( like https://mywoodpecker.org/repos/4/settings) they now get this error when manually scrolling to the bottom of the page on the current settings tab:

![image](https://github.com/woodpecker-ci/woodpecker/assets/13993700/e08e30a4-bbda-432b-ab62-2ce665cb4dad)

> [!IMPORTANT]
> - If you switch to the secrets tab **before** getting the error you only get displayed the repository secrets.
> - **After** the error occurred you can switch to the secrets page and the org/user secrets will also be displayed.

Any ideas what could cause this problem?

**Comment by OCram85** [comment]
> Yes, that's a known issue and not related to this one, see https://github.com/woodpecker-ci/woodpecker/issues/3013

Got it, should we close this issue?
