### ISSUE TITLE
Linter should not report warning for missing when in steps if global when is set

### ISSUE THREAD

**Issue by lafriks** [woodpecker-ci/woodpecker#3401]
### Component

server

### Describe the bug

Currently even if global when is set warning for each step is still shown
```
[bad_habit] Please set an event filter on all when branches
```

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-65d88be523"}
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by lafriks** [comment]
yes, sorry, works correctly, had typo

**Comment by dessalines** [comment]
I'm getting this now on `2.4.1`, even when every one of my when branches has an event filter.

**Comment by dessalines** [comment]
https://github.com/LemmyNet/lemmy/blob/c719ffce404b2a42fdeacb4e17d53c953cb46a4c/.woodpecker.yml

I'd tried adding `event: pull_request` to every when filter, but it still gave me the same error.

**Comment by dessalines** [comment]
Ah gotcha, didn't know that's required now.

**Comment by dessalines** [comment]
There has to be something broken here, what am I missing?

![Screenshot_20240326_171231_Kiwi Browser_1](https://github.com/woodpecker-ci/woodpecker/assets/930215/e76b09e6-c3cc-427e-93d5-c9b39663a1fe)

![Screenshot_20240326_171320_Kiwi Browser](https://github.com/woodpecker-ci/woodpecker/assets/930215/a509cc65-1be0-4136-8eb2-7d05b0b8c8da)

**Comment by dessalines** [comment]
Ahhh okay my bad, I see that event needs to be first, and no indent. That wasn't super clear in the docs, the difference between AND and OR.

**Comment by Tchoupinax** [comment]
Sorry to comment on this closed issue, but it's not clear for me.
I have an event filter set _globally_, shared by all step. It works fine however I meet these warnings. You said that *every* step should have a path filter. Must I really copy/paste the even filter for every step while it works well globally?

e.g.
```
steps:
[...]
when:
 - branch: '*'
 - path:
    include:
      - ".woodpecker/spa-build-image.yaml"
      - "spa/**"
    ignore_message: "[REFRESH]"
```

**Comment by Tchoupinax** [comment]
Yeah, thank you it works!
I badly understood, I thought `-branch: '*'` was the event and I did think about the event property.
Thank you a lot!
