### ISSUE TITLE
Add custom timeout and retrys to gitea/forgejo client

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#3403]
the only error i see in the woodpecker server logs is this (for one or another of the yaml pipeline definitions) but i also sometimes see this on successful runs so i expect it's unrelated
```
{"level":"error","error":"multi-pipeline cannot get .woodpecker/.woodpecker-ci.yml: Get \"https://codeberg.org/api/v1/repos/nyaa/koobernoots/raw/.woodpecker/.woodpecker-ci.yml?ref=dd9857cc7b8c94e1142ec02c7236fadb67d24aaa\": context deadline exceeded","repo":"nyaa/koobernoots","user":"nyaa","time":"2024-02-16T23:00:33Z","message":"could not get folder from forge"}
```

...

The forge api runs into timeouts!
I just need to add a setting to increase it and meby also retrys

**Comment by 6543** [comment]
I guess I forgot that we do it not in the forge driver but a level higher up already ...

**Comment by dunn** [comment]
still seeing errors even after bumping to 10s; i guess in my case it's an issue with codeberg

**Comment by stevapple** [comment]
Retries are still important since we cannot assume the availability of Git Forges...
