### ISSUE TITLE
Volume Mount error: name is not a valid kubernetes dns name

### ISSUE THREAD

**Issue by iFrozenPhoenix** [woodpecker-ci/woodpecker#3417]
### Component

server

### Describe the bug

```yaml
volumes:
  - /var/containerd/containerd.sock:/var/containerd/containerd.sock
```

results in an error: "name is not a valid kubernetes DNS name"

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"2.3.0"}
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by ssube** [comment]
I encountered this error as well, after following https://woodpecker-ci.org/docs/usage/volumes while trying to port a container build from gitlab to woodpecker. The error makes sense if the kubernetes backend is trying to create a PVC for each volume, but then how would you go about mounting existing sockets, devices, etc for building containers or using GPUs?

**Comment by iFrozenPhoenix** [comment]
Found the solution, it is described in the k8s specifics.
You have to create a persistent volume and use this name as the volume name in woodpecker.
