### ISSUE TITLE
Ability to delete step's logs manually

### ISSUE THREAD

**Issue by zc-devs** [woodpecker-ci/woodpecker#3444]
### Clear and concise description of the problem

I've had an "incident" recently. I ran pipeline with command below:
```
skopeo copy --dest-authfile=.cicd/ecr-creds "docker://$SRC_IMAGE" "docker://$DST_IMAGE"
```
I had AWS ECR credentials in that file: `AWS:AKIAIOSFODNN7EXAMPLE` instead of JSON. Therefore `skopeo` wasn't happy and printed content to the log.
I had to remove step's logs from the database.

### Suggested solution

It would be great if an admin could remove _step_ logs via UI. For example, button can be placed in positions 1 or 2:

![wp-remove-logs](https://github.com/woodpecker-ci/woodpecker/assets/127358482/c0515ac0-3315-4bf5-981d-5af807cb819e)

### Alternative 1

Delete from database.

1. Note pipeline ID in UI (for example 11).
2. Find step (for example 33):
```sql
select * from steps where step_pipeline_id=11;
```
3. Delete logs:
```sql
delete from log_entries where step_id=33;
```

### Alternative 2

Delete _all_ pipeline logs using [API](https://woodpecker-ci.org/api#tag/Pipeline-logs/paths/~1repos~1%7Brepo_id%7D~1logs~1%7Bnumber%7D/delete). Requires admin token.

### Additional context

#1883 suggested to delete whole pipeline. Answering the [question](https://github.com/woodpecker-ci/woodpecker/issues/1883#issuecomment-1606280240): yes, that is what the feature request about.
Seems, https://github.com/woodpecker-ci/woodpecker/issues/1068#issuecomment-1427621985 talks about the same, but in a little bit different FR.

### Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by anbraten** [comment]
There is at least an api endpoint already, maybe even a cli command.

**Comment by zc-devs** [comment]
> api endpoint

Thanks, added as **Alternative 2** in FR.
Unfortunately, it deletes logs from _all_ steps. I would like to delete logs of one step.
Seems, `DELETE /repos/{repo_id}/logs/{number}/{stepID}` endpoint have to be implemented like [GET /repos/{repo_id}/logs/{number}/{stepID}](https://woodpecker-ci.org/api#tag/Pipeline-logs/paths/~1repos~1%7Brepo_id%7D~1logs~1%7Bnumber%7D~1%7BstepID%7D/get).

> cli command

I didn't find... Only [show](https://woodpecker-ci.org/docs/cli#logs)
