### ISSUE TITLE
Show CLI commands arguments in documentation

### ISSUE THREAD

**Issue by zc-devs** [woodpecker-ci/woodpecker#3456]
### Clear and concise description of the problem

For now documentation looks like:
```
purge

purge a log

--log-file="": where logs are written to. 'stdout' and 'stderr' can be used as special keywords (default: stderr)

--log-level="": set logging level (default: info)

--nocolor: disable colored debug output, only has effect if pretty output is set too

--pretty: enable pretty-printed debug output

--server, -s="": server address

--token, -t="": server auth token
```

Seems, those flags are global ones, there are no arguments/flags specific to particular command.

### Suggested solution

Show arguments and its description in documentation:
```go
var logPurgeCmd = &cli.Command{
	Name:      "purge",
	Usage:     "purge a log",
	ArgsUsage: "<repo-id|repo-full-name> <pipeline>",
	Action:    logPurge,
}
```

### Additional context

^ `2.3.0`

On `next` it looks like:
```
log
manage logs

purge
purge a log
```

### Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by anbraten** [comment]
Seems like they created a separate tool to create docs for v3 now allowing to specify what should be printed using a go template: https://github.com/urfave/cli-docs

**Comment by anbraten** [comment]
sorry, linked the wrong issue
