### ISSUE TITLE
Approving pipeline lists workflows twice

### ISSUE THREAD

**Issue by qwerty287** [woodpecker-ci/woodpecker#3472]
### Component

web-ui

### Describe the bug

Approving a pipeline lists its workflows twice. Duplicates are removed as soon as the pipeline starts.

probably a regression of #2757 

### System Info

```shell
ci.woodpecker-ci.org
```

### Additional context

![grafik](https://github.com/woodpecker-ci/woodpecker/assets/80460567/aa25f200-f1ff-406c-bed1-a050c84b43e7)

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by 6543** [comment]
the database has correct records and after an reload it is fixed ... so that's most likely an WebUI bug, witch dont know what to do with getting the new created workflows pushed via eventstream (pubsub) again ...
