### ISSUE TITLE
Duplicate step/service names results in conflicting container names

### ISSUE THREAD

**Issue by xoxys** [woodpecker-ci/woodpecker#3494]
### Component

server

### Describe the bug

If a workflow contains multiple steps or services with the same name (one service and one step with the same name is affected as well) it will result in a race condition during the container creation.

![image](https://github.com/woodpecker-ci/woodpecker/assets/3391958/82cb05e8-9993-4d3d-ac95-ef6da3acd228)

![image](https://github.com/woodpecker-ci/woodpecker/assets/3391958/09586881-66b5-4b9c-a578-3a1e7cdacd9f)
![image](https://github.com/woodpecker-ci/woodpecker/assets/3391958/f1d2edc2-20c1-4df2-a136-452ee3b772f7)
 

### System Info

```shell
next-5d98a717ac
```

### Additional context

caused by https://github.com/woodpecker-ci/woodpecker/pull/2757/files#diff-6f809c0a6ea3b1924d8664a9f0dba9e308c15a5915d6444a18f0cb913809e26aR90

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by xoxys** [comment]
Wondering a bit how this can happen with ULID + StepID in https://github.com/woodpecker-ci/woodpecker/blob/main/server/pipeline/stepbuilder/stepBuilder.go#L288

**Comment by xoxys** [comment]
What's also strange is that it's called `StepID` https://github.com/woodpecker-ci/woodpecker/blob/main/server/pipeline/stepbuilder/stepBuilder.go#L289 while the `WorkflowID` is passed to the method https://github.com/woodpecker-ci/woodpecker/blob/main/server/pipeline/stepbuilder/stepBuilder.go#L166

**Comment by xoxys** [comment]
I'm a bit confused. While the description of `compiler.WithPrefix` is `WithPrefix configures the compiler with the prefix. The prefix is used to prefix container, volume and network names to avoid collision at runtime.` it looks like the container name is __not__ using this prefix. Instead, `"wp_" + step.ID` is used :thinking:

**Comment by xoxys** [comment]
@anbraten you were looking in the right direction already, this is caused by https://github.com/woodpecker-ci/woodpecker/pull/2757/files#diff-6f809c0a6ea3b1924d8664a9f0dba9e308c15a5915d6444a18f0cb913809e26aR90

**Comment by anbraten** [comment]
@xoxys Makes total sense now. Thanks for investigating it.

> What's also strange is that it's called StepID https://github.com/woodpecker-ci/woodpecker/blob/main/server/pipeline/stepbuilder/stepBuilder.go#L289 while the WorkflowID is passed to the method https://github.com/woodpecker-ci/woodpecker/blob/main/server/pipeline/stepbuilder/stepBuilder.go#L166

It should probably be called `workflowId` instead of `stepId` in the function as well.

**Comment by xoxys** [comment]
I still don't have an idea how to solve it. We should probably finally investigate *why* we need to reparse the entire pipeline on approvals and how to get rid of it.

**Comment by xoxys** [comment]
Nah, no worries. Very naive question by why can we not just parse everything on pipeline create and just update the status to pending on approvals? What is missing during create that the real parsing has to be done on approval?

**Comment by xoxys** [comment]
Oh, I see... Thank.

**Comment by xoxys** [comment]
I agree, storing `backendTypes.Step` as JSON in DB looks like a simple way. But it should only be stored for blocked pipeline steps, and we should remove it from the DB on approvals/declines to not blow up the DB. What do you think?

**Comment by anbraten** [comment]
> I agree, storing backendTypes.Step as JSON in DB looks like a simple way. 

Sounds kinda cheesy to me TBH.

Why did we need to update the UUIDs again?

**Comment by xoxys** [comment]
During the pipeline creation, the Pipeline is stored in the DB. All steps of this pipeline are created and stored with a unique ID in the DB as well. As we don't store any step information that is required to execute them, the pipeline config needs to be parsed again on approval.

At this point, we have a list of `backendTypes.Step` with a new UUID and a list of `model.Step` in the DB with the original UUID's, but there is no way to map them except step names (as done right now) but is causing this bug.

I also don't really like the approach, but it should be simple to implement and I have no better idea.

**Comment by 6543** [comment]
we had that fixed in the past!

**Comment by xoxys** [comment]
How does that help? It was reintroduced by an accident and because the current reparsing approach is broken by design... This issue has collected all information why this happended already.

**Comment by xoxys** [comment]
Right now, a consent **how** to fix it properly has not been found. @qwerty287 had made a suggestion already, and I agreed to this suggestion. If you have an idea for a better way to handle it, please add it to the discussion.

**Comment by 6543** [comment]
uh now I'm up-to-date with the issue ... let me thing I'll try to come up with a nice solution ... and also explain how/why things are done etc ...

**Comment by 6543** [comment]
why we have two different step model structs:
-> because the pipeline engine itself should be self-contained (independent e.g. run without the server)
-> because the server needs to store the state before/after the engine (statefull) while the engine is stateless

we should not store the backend steps because:
- they contain secrets
- might not be portable between agents

why we use UUIDs:
- because the engine do create steps initially and we need a way to make them unique to address
- so the question is, why we did not store the UUIDs initially for blocked pipelines and use that as identifier instead

**Comment by eliasscosta** [comment]
Could It be a rename of the container?

In the https://github.com/woodpecker-ci/woodpecker/blob/main/pipeline/backend/docker/convert.go#L69 
The container gets a prefix plus the step name when it is a service. 

I don't test it if works or not. 

```go
func toContainerName(step *types.Step) string {
	if step.Type == types.StepTypeService {
		return "wp_svc_" + step.UUID + "_" + step.Name
	}

	return "wp_" + step.UUID
}

```
