### ISSUE TITLE
Unable to deploy PRs

### ISSUE THREAD

**Issue by praveen-livspace** [woodpecker-ci/woodpecker#3559]
### Component

server, web-ui

### Describe the bug

I noticed that PRs can no longer be deployed using the web UI due to this change #3522 
However this has broken our UX where our team deploys the PRs in dev/alpha environments to carry out testing before the PR is merged. Please suggest.

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-326069c983"}
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by anbraten** [comment]
Deploy uses secrets with enabled for the deploy event. Clicking the deloy button can be done by every repo member (not by externals), right?

**Comment by anbraten** [comment]
> So you can access any secret if you have push perms

I might be wrong, but aren't just secrets with the deploy filter exposed?

**Comment by anbraten** [comment]
> Click the "deploy" button

As clicking the deploy button can only be done by a repo member.

Isn't it the same risk as this:
- A member pushes to a branch
- Wait until the pipeline finished
- Click the "deploy" button
- ...

**Comment by praveen-livspace** [comment]
IMO, we should have a config to enable or disable deployment on PRs. We can keep it disabled by default.  However, for private environments the risk is minimal.
