### ISSUE TITLE
Pipeline status is error, but last job is OK

### ISSUE THREAD

**Issue by petersone-netic** [woodpecker-ci/woodpecker#3561]
### Component

web-ui

### Describe the bug

The pipeline status image (on Woodpecker - returned by API: /api/badges/25/status.svg ) shows ERROR, even that last build is OK:
![Screenshot 2024-03-27 at 12 16 11](https://github.com/woodpecker-ci/woodpecker/assets/78849156/568c8c39-402b-4ea5-855d-70dc600152b5)

### System Info

```shell
version 2.4.1 running on Docker
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by anbraten** [comment]
Could you check if the green pipeline actually has same failed steps. In that case it could be related to #2197

**Comment by petersone-netic** [comment]
All steps green:
![image](https://github.com/woodpecker-ci/woodpecker/assets/78849156/9f0d98b6-7cbb-431f-9968-984b3daaf3af)

**Comment by petersone-netic** [comment]
Yes - GoogleChatNotify only executes on failure.
Without it, pipeline still shows status error:
![image](https://github.com/woodpecker-ci/woodpecker/assets/78849156/a5945bfa-45e7-4f7f-9e17-d5cb60f0d4e8)

![image](https://github.com/woodpecker-ci/woodpecker/assets/78849156/98ada8ab-03c1-4baf-ac9e-0ce199f8e029)

**Comment by petersone-netic** [comment]
Invalid status is shown in 2 of 21 (~identical) repos. Nothing to see in web output.

Requests to /api/badges/25/status.svg log:
{"level":"debug","ip":"xxx","latency":1.382428,"method":"GET","path":"/api/badges/25/status.svg","status":200,"time":"2024-04-09T10:37:33Z","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36","time":"2024-04-09T10:37:33Z","caller":"/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/logger.go:59"}

Repo just builded OK and log shows:
{"level":"debug","repo":"DBRDEV/monitoring","pipeline":"41","id":"514","error":"","exit_code":0,"canceled":false,"time":"2024-04-09T13:33:20Z","caller":"/src/agent/runner.go:181","message":"pipeline complete"}
{"level":"debug","repo":"DBRDEV/monitoring","pipeline":"41","id":"514","error":"","exit_code":0,"time":"2024-04-09T13:33:20Z","caller":"/src/agent/runner.go:190","message":"updating pipeline status"}
{"level":"error","repo_id":"25","pipeline_id":"578","workflow_id":"514","error":"stream: not found","time":"2024-04-09T13:33:21Z","caller":"/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/grpc/rpc.go:302","message":"done: cannot close log stream for step 2125"}

**Comment by petersone-netic** [comment]
Just for "fun", I tried clicking on the action "Repair repository" - and it worked 👍👍
