### ISSUE TITLE
Limit concurrent builds per repo and user

### ISSUE THREAD

**Issue by pinpox** [woodpecker-ci/woodpecker#3579]
### Clear and concise description of the problem

It would be very helpful to limit the concurrent builds on per-repository and per-user basis. This would prevent a single repository or user from blocking the whole CI for everyone.

E.g. when pushing a lot of commits at once to a repository, woodpecker will build all of them with as many workers as are available, effectively blocking other users completely.

If there already is such a feature, let me know. I haven't been able to find a workaround for that problem.

### Suggested solution

Add an option for administrators to limit the parallel jobs for each individual user.
Add an option for users in the repository settings to set the maximum number of concurrent builds of that repository

### Alternative

Add a fixed per-user limit of concurrent jobs as environment variable. 

### Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by LcLz0** [comment]
Looks like a duplicate issue of #1461

**Comment by pinpox** [comment]
> Looks like a duplicate issue of #1461

In part, yes. I would also like to configure the concurency per user.

**Comment by pinpox** [comment]
Fair enough, I think those two cover it!
I'll see if I can help out on those issues. 
Closing as duplicate.
