### ISSUE TITLE
Confusing [bad_habit] Please set an event filter on all when branches message

### ISSUE THREAD

**Issue by oliverpool** [woodpecker-ci/woodpecker#3607]
### Component

web-ui

### Describe the bug

Initially reported on https://codeberg.org/Codeberg-CI/feedback/issues/170

When a `when` block has no `event` field, a `[bad_habit] Please set an event filter on all when branches message` warning is shown, introduced by #3222.

![image](https://github.com/woodpecker-ci/woodpecker/assets/3864879/a4d94a63-7caf-4c51-b8cb-ad8fbbabc5ab)

This is not really actionable for the user:
- no idea which part of the pipeline is faulty
- no much idea how to solve it.

### System Info

```shell
source	"https://github.com/woodpecker-ci/woodpecker"
version	"2.4.1"
```

### Additional context

Having the step involved would be nice (it is recorded, but not displayed).

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by zc-devs** [comment]
> warning is shown

even though [there is no "when" directive at all](https://github.com/woodpecker-ci/woodpecker/pull/3269#issuecomment-2016852418).

**Comment by anbraten** [comment]
If I am correct the idea was basically to encourage the user to add at least some kind of when filters as otherwise in the case we add more functionality like additional events the existing pipelines would also be triggered by those new events when updating.

I guess we can simply improve the message a bit and additionally show the workflow file it was detected in.
