### ISSUE TITLE
Global Environment Variable UI editor

### ISSUE THREAD

**Issue by hairlesshobo** [woodpecker-ci/woodpecker#362]
### Clear and concise description of the problem

At the moment, the only way to set a global environment variable is to change the configuration of the service itself and restart the Woodpecker application. [See here](https://woodpecker-ci.github.io/docs/usage/environment#global-environment-variables)

An example of where I would find this incredibly useful is for image names. Let say that I use one specific docker image throughout a number of projects and I know ahead of time that, periodically, I may need to change that image name. It would be great to easily do so without having to restart the entire Woodpecker platform.

### Suggested solution

I propose, in the spirit of #7 and #345 that there be Global and/or Project level environment variables and the corresponding UI editor. These environment variables could be stored in the database and would then be easily made available to all projects.

### Alternative

 At the moment, the closest solution to this would be to create a secret per-project and then map that to the environment variable, but this comes with limitations. With the fact that secrets are, by design, secret.. there would be no way to easily see what the current value of that secret is. For anything that isn't actually a secret, this would be counter-productive. 

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.github.io/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by anbraten** [comment]
We added global secrets with #1027. By doing #1007 this should be solved as well.

**Comment by 6543** [comment]
as per comment, it should be 'addrest', the rest is polishing
