### ISSUE TITLE
Cannot login on Woodpecker paired with gitea

### ISSUE THREAD

**Issue by masfaraud** [woodpecker-ci/woodpecker#3626]
### Component

server

### Describe the bug

Hello,
I have a functionnal instance of woodpecker CI working with a gitea instance. About one time per day I get stuck on the login page, clicking on connect redirects to the same page.
 
![image](https://github.com/woodpecker-ci/woodpecker/assets/14061753/12b4821c-d782-4732-bf9a-5c867c7e85af)

I find this log on the server container:
```
{"level":"error","repo_id":"1","pipeline_id":"49","workflow_id":"49","error":"stream: not found","time":"2024-04-18T08:18:24Z","message":"done: cannot close log stream for step 441"
```
I have tried to disconnect from gitea to force relogin and flush site data in browser from both gitea and woodpecker but without success.
The strange thing is that on the same browser if I switch to private mode or I change the browser I can login by beeing redirected to gitea.

What do you guys think?

### System Info

```shell
woodpecker CI version 2.4.1
gitea version 1.21.10
firefox 124.0.2
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by anbraten** [comment]
The mentioned error is related to log / event streaming and shouldn't be relevant. 

Woodpecker syncs all your projects from gitea on login. There might be a problem with it in your case.

**Comment by masfaraud** [comment]
Never encountered the problem since a while. I made a gitea from 1.21.10 to 1.21.11, maybe the problem was there.
