### ISSUE TITLE
Tag ref contains prefix on forgejo v7

### ISSUE THREAD

**Issue by xoxys** [woodpecker-ci/woodpecker#3665]
### Component

server

### Describe the bug

> I have some weird mixed results with woodpecker and releases on forgejo v7.
On the UI does it display the tag itself (i.e. v1.0.0) but the ${CI_COMMIT_TAG} is now returning refs/tags/v1.0.0
>
> I assume this to more be an issue with forgejo, but I still wanted to report it here in case someone knows a possible workaround for now.

Originally reported by @Andre601 via chat

### System Info

```shell
next-00ccec078c
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by oliverpool** [comment]
Note that a fix from Forgejo side is also underway: https://codeberg.org/forgejo/forgejo/issues/3558

(Woodpecker was faster in fixing this :)

**Comment by xoxys** [comment]
Great :) However, I think it doesn't harm to sanitize it in any case.
