### ISSUE TITLE
Linter: cSpell add golang dic

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#3705]
we should use `go` and `node` dics

https://cspell.org/docs/dictionaries

to be able to ignore less paths

for that we have to find a way to easy install mentioned dictionaries for ci as via make

**Comment by 6543** [comment]
https://github.com/woodpecker-ci/woodpecker/blob/42f2734308f2cb3810edfd4d3048ce0beb50eed1/.cspell.json#L178

Now is only missing

**Comment by anbraten** [comment]
and `docs/` and `_test.go`

**Comment by 6543** [comment]
Do test files need to be checked for misspells?!?

**Comment by anbraten** [comment]
I would say so. They are not generated and include text that could have mistakes.
