### ISSUE TITLE
Woodpecker UI output not updating/out of sync

### ISSUE THREAD

**Issue by davidhazell-tst** [woodpecker-ci/woodpecker#3716]
### Component

web-ui

### Describe the bug

I am attempting to use Woodpecker to build an image using the [Cypress Factory](https://hub.docker.com/r/cypress/factory/) docker image that can be used with docker args to generate a container with specific package versions. I am using the woodpecker docker buildx plugin to build the image.

When I run my build job and view the progress in the UI it appears the job is stuck installing GPG keys. However, when I look at the log output on the agent I can see that the GPG key installations are successful and the rest of the job steps are executed and the final image is published.

Additionally, the UI never marks the job as completed and the kubernetes builds pods stayed in a 'Completed' state until the job times out or is manually cancelled. When this happens the agents no longer pull new work from the server.

### Steps to reproduce

1. Create a Dockerfile using the Cypress factory image
```
ARG NODE_VERSION='18.16.0'
ARG YARN_VERSION='1.22.19'
ARG CYPRESS_VERSION='13.7.1'
ARG CHROME_VERSION='120.0.6099.71-1'
ARG EDGE_VERSION='120.0.2210.61-1'
ARG FIREFOX_VERSION='120.0.1'

FROM cypress/factory
```
2. Create a woodpecker job to build the image
```
steps:
  - name: docker-cypress
    image: woodpeckerci/plugin-docker-buildx
    secrets: [docker_username, docker_password]
    settings:
      platforms: linux/amd64
      registry: <my_docker_registry>
      repo: <my_docker_repo>
      dockerfile: Dockerfile.cypress.test
      tags: buildx.test-build
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args_from_env:
        - CI_REPO
        - CI_COMMIT_BRANCH
        - CI_COMMIT_SHA
        - CI_PIPELINE_NUMBER
      debug: true
```
3. Run the job

### Expected behavior

* The job should successfully build the container and be marked Successful
* The UI log output should stay in sync with the worker agent log output
* The UI should not hang indefinitely during the build

### System Info

```shell
{
"source": "https://github.com/woodpecker-ci/woodpecker",
"version": "2.4.1"
}
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by anbraten** [comment]
Sounds to be related to #3468, #2072 & #2253
