### ISSUE TITLE
Per-agent environment variables option

### ISSUE THREAD

**Issue by silverwind** [woodpecker-ci/woodpecker#3762]
### Clear and concise description of the problem

A way to load common environment variables that can differ per agent is needed. Especially for things like `https_proxy` which can differ based on physical location of the agent. For example proxy1 in dc1 and proxy2 in dc2 can not realistically be configured from the workflow file because it does not know the location of the agent and shouldn't have to know either.

### Suggested solution

Support a option `WOODPECKER_AGENT_ENV_FILE` that works like [DRONE_RUNNER_ENV_FILE](https://docs.drone.io/runner/docker/configuration/reference/drone-runner-env-file/) which can be mounted into the agent which would make the variables available to all pipelines.

### Alternative

Maybe it could also be a per-agent config option in the UI.

### Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by zc-devs** [comment]
https://github.com/woodpecker-ci/woodpecker/issues/3311

**Comment by silverwind** [comment]
Right, it's a duplicate, added my notes there.
