### ISSUE TITLE
Make repo URLs include repo names

### ISSUE THREAD

**Issue by terminalnode** [woodpecker-ci/woodpecker#3865]
### Clear and concise description of the problem

Repos have URLs such as `/repos/1` which doesn't really say anything about which repo it is. So when I type our woodpecker URL into the address bar I'm forced to go to the root and click myself to the right repo.

### Suggested solution

If the URL was instead `/repos/1-myrepositoryname` (and possibly the non-URLified name was part of the title, e.g. `WoodPecker: MyRepositoryName`), I could just type `pecker MyRepositoryName` into the URL bar and it would pop up as a suggestion.

### Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by anbraten** [comment]
This was changed on purpose in #1691 to support features like gitlabs nested plugins and as you could have multiple repos with the same name when using multiple forges #138
