### ISSUE TITLE
Restructure cli commands

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#3866]
To easily find the correct cli command, it would be quite helpful if they were structured in "groups" / sub-commands similarly to the UI:

- setup
- help
- info
- exec
- update
- lint
- repo (to manage repos)
- repo (not sure if those commands might be better at the top-level)
  - pipeline
    - ls
    - approve
    - info
    - ...
    - log
  - secrets
  - registries
  - cron
  - deploy
- org
  - secrets
  - registries 
- admin
  - user
  - secrets (global secrets)
  - registries (global registries)
  - log-level

**Comment by lafriks** [comment]
I agree that this structure looks much better

**Comment by zc-devs** [comment]
I would put `log` in `pipeline`:
```
repo:
  pipeline:
    log
```
