### ISSUE TITLE
Migration fails in latest version.

### ISSUE THREAD

**Issue by rubenelshof** [woodpecker-ci/woodpecker#3870]
### Component

server

### Describe the bug

A migration fails in the latest version of Woodpecker.

The server wouldn't startup and crashes while attempting to finish the migration.

Last working version is `next-2fa9432ef8`

### Steps to reproduce

1. Set up Woodpecker server with MariaDB server as database.
2. Run docker compose and see logs.

### System Info

```shell
Woodpecker version: next-e118f8d980
MariaDB 10.11.6
```

### Additional context

```
{"level":"info","time":"2024-07-03T21:30:09Z","message":"log level: info"}
{"level":"fatal","error":"can't setup store: could not migrate datastore: migration alter-table-registries-fix-required-fields failed: Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'COLUMN `repo_id` SET NOT NULL' at line 1","time":"2024-07-03T21:30:09Z","message":"error running server"}
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by lafriks** [comment]
I think problem is in invalid mysql query in common migration helper: https://github.com/woodpecker-ci/woodpecker/blob/b23fdaa6dc30fcfa862e5d855404fe0bb8108dea/server/store/datastore/migration/common.go#L207
