### ISSUE TITLE
variable CI_PIPELINE_DEPLOY_TASK is empty in woodpecker

### ISSUE THREAD

**Issue by lara-clink** [woodpecker-ci/woodpecker#3872]
### Component

other

### Describe the bug

I am testing version 2.6 in my development environment, so I updated an application code to use 
```- evaluate: CI_PIPELINE_DEPLOY_TASK == "sre-dummy-rest-app"```
instead of the 'task:' filter.
In my github hooks payload I get: 
![Captura de Tela 2024-07-04 às 14 21 31](https://github.com/woodpecker-ci/woodpecker/assets/59903882/bf2d5cad-235b-4930-9d65-268b857744be)
But the CI_PIPELINE_DEPLOY_TASK is empty and woodpecker is not running the steps that it should run.

### Steps to reproduce

Using :
```    
when:
      - evaluate: CI_PIPELINE_DEPLOY_TASK == "value" 
```

Instead of:
`task: "value"`

### Expected behavior

Run with the variable as it should run with the filter in previous versions.

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"2.6.0"}
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by zc-devs** [comment]
> it should run with the filter in previous versions

[Has it ever been](https://github.com/woodpecker-ci/woodpecker/pull/3512)?

[Constraints](https://github.com/woodpecker-ci/woodpecker/blob/987c201c0db1114215d982f7da8da5d7a2139067/pipeline/frontend/yaml/constraint/constraint.go#L39-L54) doesn't contain `task` filter and seems has never been.
