### ISSUE TITLE
Git clone step fails with "Could not resolve host" error when running fetch

### ISSUE THREAD

**Issue by voidcontext** [woodpecker-ci/woodpecker#3892]
### Component

agent

### Describe the bug

On an arm64 agent (Raspberry Pi 4b+), the clone step fails when the container is running in podman:

```
+ git init -b main
Initialized empty Git repository in /woodpecker/src/git.vdx.hu/voidcontext/nix-config/.git/
+ git config --global --replace-all safe.directory /woodpecker/src/git.vdx.hu/voidcontext/nix-config
+ git remote add origin https://git.vdx.hu/voidcontext/nix-config.git
+ git fetch --no-tags --depth=1 --filter=tree:0 origin +a4b83a869d6366bf24921b8f4f3f5836f806f57e:fatal: unable to access 'https://git.vdx.hu/voidcontext/nix-config.git/': Could not resolve host: git.vdx.hu
exit status 128
```

The server is on a different server (on amd64).

Example: https://woodpecker.ci.vdx.hu/repos/109/pipeline/119/5

The same pipeline is successful on an amd64 agent (Kubernetes on a 3rd machine).

The issue seems to be similar to https://github.com/woodpecker-ci/woodpecker/issues/1407 which has been closed bacause of inactivity.

### Steps to reproduce

1) install server on amd64 machine (A)
2) install agent on arm64 machine (B) using Docker backend that points to a docker compatible podman socket.
3) Run pipeline

### Expected behavior

Git is able to resolve the host as it has a public DNS record.

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"2.6.0"}
```
```


### Additional context

Unfortunately I wasn't able to test this on `next`.

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by 6543** [comment]
to debug it @voidcontext I would suggest to create an debug workflow witch:
1. has the `skip_clone` option enabled
2. has a single step where you try to manually clone the repo with verbose option and or also use the `dig` tool to see what dns resolution path would look like :)

**Comment by pat-s** [comment]
I see this every once in a while but could never reproduce it. Restarting the build always worked.

Are you sure this is a reproducible issue that is related to arm64 + podman? (btw, I think there is still no official podman support yet)

**Comment by voidcontext** [comment]
Ok, so it turned out this one was definitely a user error. The dnsmasq instnance on the server was listening on a specific address so it wouldn't accept queries from the podman* interfaces. After adding "podman[1-5]" everything seems to be working fine.
