### ISSUE TITLE
Helm Chart archive unavailable after 2.6.0 release 

### ISSUE THREAD

**Issue by VerosK** [woodpecker-ci/woodpecker#3937]
### Component

other

### Describe the bug

After 2.6.0 release helm chart archive 1.5.0 got missing.

### Steps to reproduce

Get latest helm chart

    helm fetch --repo https://woodpecker-ci.org/ woodpecker

Got result:

    Error: failed to fetch https://github.com/woodpecker-ci/woodpeckerci.github.io/releases/download/helm-woodpecker-1.5.0/woodpecker-1.5.0.tgz : 404 Not Found

### Expected behavior

Helm chart should be downloaded. 

I've checked docs on https://github.com/woodpecker-ci/helm/blob/main/charts/woodpecker/README.md to make sure I'm using correct helm repository.

### System Info

```shell
probably not important.

Helm version: is 3.11.1, running on Fedora Linux on x86

version.BuildInfo{Version:"v3.11.1", GitCommit:"293b50c65d4d56187cd4e2f390f0ada46b4c4737", GitTreeState:"clean", GoVersion:"go1.18.10
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by 6543** [comment]
Should be fixed
