### ISSUE TITLE
woodpecker-cli: 2.7.0 version complains like if it's 2.6.0 and wants to be updated

### ISSUE THREAD

**Issue by awnion** [woodpecker-ci/woodpecker#3941]
### Component

cli

### Describe the bug

2.7.0 version complains like if it's 2.6.0 and wants to be updated
see screenshot

<img width="1014" alt="Screenshot 2024-07-19 at 22 27 41" src="https://github.com/user-attachments/assets/2e51c78c-9cae-450e-b7a5-4fdcc00707d5">

### Steps to reproduce

In empty dir just do this:

```bash
cd $(mktemp -d)
cat <<EOF >test.yaml
when:
  - event: push
    branch: test

steps:
  deploy:
    image: bash
    commands:
      - test
EOF
woodpecker-cli lint test.yaml
```

### System Info

```shell
it's not a server issue
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by 6543** [comment]
Should be fixed
