### ISSUE TITLE
Redirection after oauth2 login should point to page which initiated the login

### ISSUE THREAD

**Issue by pat-s** [woodpecker-ci/woodpecker#3987]
### Component

server

### Describe the bug

As title

### Steps to reproduce

1. View a build without being logged in
2. Click on "Login"
3. Login

### Expected behavior

The redirect after successful is pointing to the root of the WP instance instead of redirecting to the page from which the initial login was initiated. I'd expect to not be redirected to the WP root but to the build page from which I initiated the login

### System Info

```shell
WP 2.7.0
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by zc-devs** [comment]
Works for me on `next-2d039f85cb`. There is no [error on login](https://github.com/woodpecker-ci/woodpecker/discussions/2162#discussioncomment-10102150) page and then it redirects to the page from which I started logging in.

**Comment by pat-s** [comment]
Link the commit and close?

**Comment by zc-devs** [comment]
I think it was #3962.

**Comment by pat-s** [comment]
Thanks 👍
