### ISSUE TITLE
FTL error running cli error="json: cannot unmarshal array into Go value of type woodpecker.Secret"

### ISSUE THREAD

**Issue by yonas** [woodpecker-ci/woodpecker#4004]
### Component

cli

### Describe the bug

```sh
$ woodpecker-cli secret info --org yonas
5:19AM FTL error running cli error="json: cannot unmarshal array into Go value of type woodpecker.Secret"
```

### Steps to reproduce

Run `woodpecker-cli secret info --org <your username>`

### Expected behavior

I should get info about the secrets I've created.

### System Info

```shell
FreeBSD 14
Commit: 54b91db
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by yonas** [comment]
FYI The one secret I have installed has a whitespace in it's name.

**Comment by zc-devs** [comment]
> I should get info about the secrets I've created

[info display secret info](https://woodpecker-ci.org/docs/cli#info-7)
[ls list secrets](https://woodpecker-ci.org/docs/cli#ls-6)

**Comment by yonas** [comment]
Ok, `--name` was missing. Needs to be patched to let the user known more explicitly.
