### ISSUE TITLE
Build ref link should point to commit not compare if only on commit has changed

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#401]
example:
get: `https://codeberg.org/6543/woodpecker/compare/97554816f4b927328ed523a6506aa38a1b99f039...d086e8268fa7713d72c6f1d03bab52f762c99325`
want: `https://codeberg.org/6543/woodpecker/commit/d086e8268fa7713d72c6f1d03bab52f762c99325`

**Comment by vanous** [comment]
plus, right now it can also be wrong:

https://codeberg.org/Freeyourgadget/Gadgetbridge/compare/0000000000000000000000000000000000000000...943f33e0cec05324c3495dec1e9cbbcbd1aaa6d6
this is from https://ci.codeberg.org/Freeyourgadget/Gadgetbridge/build/139
