### ISSUE TITLE
ISA: aarch64 vs arm64

### ISSUE THREAD

**Issue by Release-Candidate** [woodpecker-ci/woodpecker#4051]
### Component

agent

### Describe the bug

The Woodpecker agent registers itself as running on `linux/aarch64`

```json
{
"message":"starting Woodpecker agent with version 'next-0b34578923' and backend 'docker' using platform 'linux/aarch64' running up to 1 pipelines in parallel"
}
```

and does not work when using the platform `linux/arm64` in workflows.

### Steps to reproduce

1. Compile Woodpecker agent from the current main branch on AARCH64
2. Install and configure the agent
3. Setup a workflow which uses `linux/arm64` as `platform`.
4. Observe, that `linux/aarch64` is not regarded the same as `linux/arm64` by Woodpecker.

### Expected behavior

Woodpecker recognizes `arm64` and `aarch64` as synonyms for the same CPU ISA or uses one of these consistently - the agent sets `linux/arm64` on AARCH64.

### System Info

```shell
Linux debian 6.1.0-23-arm64 #1 SMP Debian 6.1.99-1 (2024-07-15) aarch64 GNU/Linux
```

```json
{
  "source": "https://github.com/woodpecker-ci/woodpecker",
  "version": "next-0b34578923"
}
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by zc-devs** [comment]
Seems, the same as https://github.com/woodpecker-ci/woodpecker/discussions/2861
https://ci.daniil.it/repos/65/pipeline/1469/config
