### ISSUE TITLE
Stuck on Login (Github)

### ISSUE THREAD

**Issue by s00500** [woodpecker-ci/woodpecker#4086]
### Component

server

### Describe the bug

I cant login, getting a "internal error" on the login screen and this message in the logs

`{"level":"error","error":"sql: no rows in result set","time":"2024-09-05T10:36:31Z","message":"cannot get org s00500"}`

### Steps to reproduce

Running in Kubernetes, using github

### Expected behavior

Be able to log in

### System Info

```shell
2.7.0 release
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by s00500** [comment]
Really weird stuff... seems like my organisation was deleted from the db, I have now readded it... that seemed to fix it, also had to delete my user to have it get recreated...

**Comment by s00500** [comment]
I guess so... still weird, will keep an eye on it...

**Comment by 6543** [comment]
Well a lot of noice to the database has ben fixed by https://github.com/woodpecker-ci/woodpecker/pull/4100 (not released jet)

That there was a data lose should have never happen, i also would rely like to know why so if it's an issue on our side that we can fix it ...

Anyway sorry for your this

**Comment by s00500** [comment]
I experienced lockups on the login often but also logs not easily loading and finally every once in a while a pipeline did not fire on the first try (second usually worked then)

Will keep you posted, but stuff has been fine since switching to postgres (was yesterday, so we will see 😅)
