### ISSUE TITLE
Missing path condition docs

### ISSUE THREAD

**Issue by alexef** [woodpecker-ci/woodpecker#409]
### Component

documentation

### Describe the bug

When browsing the docs at: https://woodpecker.laszlo.cloud/multi-pipeline/ I cannot find the docs about using `when.path` (from here: https://github.com/woodpecker-ci/woodpecker/pull/174)

I believe they were accidentally removed.

### System Info

```shell
{
  "source": "https://github.com/woodpecker-ci/woodpecker",
  "version": "v0.14.0"
}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.github.io/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy).

**Comment by anbraten** [comment]
>  Read the [docs](https://woodpecker-ci.github.io/docs/intro). 

Have a look on whats behind that link you checked. 😉 Seems like you are looking at the old docs on woodpecker.laszlo.cloud.

This [page](https://woodpecker-ci.github.io/docs/usage/pipeline-syntax#path) should help you.

**Comment by alexef** [comment]
Niice, I didn't see them!
