### ISSUE TITLE
After update to version 2.7.1 buildx plugin stopped working

### ISSUE THREAD

**Issue by steinhobelgruen** [woodpecker-ci/woodpecker#4096]
### Component

agent

### Describe the bug

After updating both the server and the agent to version 2.7.1 all steps using the woodpeckerci/plugin-docker-buildx stopped working. The docker build would not start:

```
+ coredns -conf /etc/coredns/Corefile
+ /usr/local/bin/dockerd --data-root /var/lib/docker --host=unix:///var/run/docker.sock --dns 172.17.0.2
Detected registry credentials
+ /usr/local/bin/docker version
Client:
 Version:           27.1.2
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
 API version:       1.46
 Go version:        go1.21.13
 Git commit:        d01f264
 Built:             Mon Aug 12 11:49:34 2024
 OS/Arch:           linux/amd64
 Context:           default
time="2024-09-07T16:16:31Z" level=error msg="execution failed: exit status 1"
```

Switching back to 2.7.0 fixed the problem.

### Steps to reproduce

* Update to 2.7.1.
* Run any pipeline with image: woodpeckerci/plugin-docker-buildx

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"2.7.1"}

(running on ubuntu 22.04LTS with docker 24.0.7)
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by 6543** [comment]
well by default it should be allowed:

https://github.com/woodpecker-ci/woodpecker/blob/324ab4ac89758f994b32923b072d02e6c8dfb797/shared/constant/constant.go#L23

**Comment by 6543** [comment]
If you have changed the default privileged plugins and added a tag, now the tag is respected so it must match to be privileged:

https://github.com/woodpecker-ci/woodpecker/pull/4076

**Comment by steinhobelgruen** [comment]
Since it happens with all pipelines I can just copy a very short one completely:

```
steps:
  docker-build:
    secrets: [docker_username, docker_password]
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: dentaku/postfix
      tags:
        - latest
        - v0.1
      auto-tag: true
      platforms: [linux/amd64, linux/arm64]
```

With 2.7.0 I get no warnings on this pipeline at all, 2.7.1 on the other hand complains:

[linter] docker: steps.docker-build Should not configure both secrets and settings
[linter] docker: steps Must validate one and only one schema (oneOf)
[linter] docker: steps.docker-build Must validate one and only one schema (oneOf)
[linter] docker: steps.docker-build Additional property secrets is not allowed
[bad_habit] docker: steps.docker-build Please set an event filter for all steps or the whole workflow on all items of the when block

So I probably *should* change something about the secrets handling now, but that doesn't explain why even `docker version` fails, and it also doesn't explain why it fails with a timeout.

(I have no idea what WOODPECKER_ESCALATE is)

**Comment by steinhobelgruen** [comment]
Ah, I found WOODPECKER_ESCALATE in the documentation. I haven't set that to anything, so it should be on default.

**Comment by steinhobelgruen** [comment]
Thanks, that works, I'll close the issue.

But:

> While it was possible to use it before, it never was documented that this is possible.

Yes, it is documented *exactly* like that here:
https://woodpecker-ci.org/docs/usage/secrets#use-secrets-in-commands

**Comment by 6543** [comment]
@steinhobelgruen yes for commands

You use a plugin witch has no commands ;)

**Comment by 6543** [comment]
But i agree the docs should be improved ...

**Comment by 6543** [comment]
@steinhobelgruen would https://github.com/woodpecker-ci/woodpecker/pull/4099 have clarifyed it for you?

**Comment by steinhobelgruen** [comment]
> @steinhobelgruen would #4099 have clarifyed it for you?

A lot. :-)
