### ISSUE TITLE
WebUI: agent edit/detail view: change the **HELP** url based on the backend

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#4137]
![image](https://github.com/user-attachments/assets/e8733c55-1acc-4406-a0b7-b226386e9d85)

the default url is `https://woodpecker-ci.org/docs/next/administration/backends/docker` and that should remain.

but if it is `local` or `kubernetes` it would be nice to show different urls towards `https://woodpecker-ci.org/docs/next/administration/backends/local` and `https://woodpecker-ci.org/docs/next/administration/backends/kubernetes`.

**Comment by tori-27** [comment]
I can try to do this

**Comment by 6543** [comment]
@tori-27 feel free to ask for help here or at matrix :)

**Comment by tori-27** [comment]
Hi, I've done this. Here is a video with result

https://github.com/user-attachments/assets/c012026b-cf4f-4ca6-9fde-b34973f327a5
