### ISSUE TITLE
GitLab: push hook event reponses are not sent

### ISSUE THREAD

**Issue by pat-s** [woodpecker-ci/woodpecker#4264]
### Component

server

### Describe the bug

Push event hooks don't get replied to properly. Builds still start as they are parsed internally and started but there's an issue with the response to the incoming hook.

This leads to GL deactivating the hook after a few hook iterations that didn't get a response.

<img width="582" alt="image" src="https://github.com/user-attachments/assets/a80e0e6e-14b5-4ce2-97d4-7e3069c15f4d">

### Steps to reproduce

- trigger a push event hook

### Expected behavior

next (9a7623359ecbfb65e9f9e4ad9bbb0aa169e03531) (Oct 27th)

### System Info

```shell
.
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by pat-s** [comment]
They are sent, but take longer than 10s and exceed GL timeout limit.

**Comment by pat-s** [comment]
Problematic timings in detail (workflow is a matrix workflow with 3 entries):

- Hook is parsed at `:35`

```
{"level":"trace","time":"2024-10-28T21:51:35Z","caller":"/source/server/router/router.go:43","message":"[POST] /api/hook"} 
```

- Fetching `.woodpecker` from forge takes 3s

```
{"level":"trace","time":"2024-10-28T21:51:35Z","caller":"/source/server/services/config/forge.go:146","message":"fetching .woodpecker/ from forge"}                                                      │
│ {"level":"trace","time":"2024-10-28T21:51:38Z","caller":"/source/server/services/config/forge.go:158","message":"configFetcher[devxy/ansible/data_science_core]: found 2 files in '.woodpecker/'"} 
{"level":"trace","time":"2024-10-28T21:51:38Z","caller":"/source/server/services/config/forge.go:99","message":"configFetcher[owner/group/repo]: user did not define own config, followin │
│ g default procedure"}
```

- Fetching again at `:38` (?) -> 2 secs

```
{"level":"trace","time":"2024-10-28T21:51:38Z","caller":"/source/server/services/config/forge.go:146","message":"fetching .woodpecker/ from forge"}                                                      │
│ {"level":"trace","time":"2024-10-28T21:51:40Z","caller":"/source/server/services/config/forge.go:158","message":"configFetcher[owner/group/repo]: found 2 files in '.woodpecker/'"} 
```

- fetching again at `:40` (?) -> 2 secs

```
{"level":"trace","time":"2024-10-28T21:51:40Z","caller":"/source/server/services/config/forge.go:146","message":"fetching .woodpecker/ from forge"}  
{"level":"trace","time":"2024-10-28T21:51:42Z","caller":"/source/server/services/config/forge.go:158","message":"configFetcher[owner/group/repo]: found 2 files in '.woodpecker/'"}  
```

- stepbuilder (4s):

```
 {"level":"debug","pipeline":"lint","time":"2024-10-28T21:51:42Z","caller":"/source/server/pipeline/stepbuilder/stepBuilder.go:158","message":"marked as skipped, does not match metadata"}  
```

- final hook response
```
{"level":"debug","ip":"10.42.97.0","latency":10782.947155,"method":"POST","path":"/api/hook","status":200,"time":"2024-10-28T21:51:46Z","user-agent":"GitLab/17.6.0-pre","time":"2024-10-28T21:51:46Z"," │
│ caller":"/source/server/router/middleware/logger.go:59"} 
```

**Comment by zc-devs** [comment]
#4052
