### ISSUE TITLE
Unable to connect to MariaDb

### ISSUE THREAD

**Issue by Flying--Dutchman** [woodpecker-ci/woodpecker#428]
### Component

server

### Describe the bug

Using the configuration from the [docs](https://woodpecker-ci.github.io/docs/administration/database#configure-mysql), I'm unable to start woodpecker, using MariaDB. 

Other containers on the same network can reach the database container without problems.

### System Info

```shell
devops_woodpecker_ci:
    image: woodpeckerci/woodpecker-server:${WOODPECKER_TAG}
    restart: unless-stopped
    ports:
      - ${WOODPECKER_PORT}:8000
      - 9000
    networks:
      - devops_network
    environment:
      - WOODPECKER_DATABASE_DRIVER=mysql
      - WOODPECKER_DATABASE_DATASOURCE=DBUSER:DBPASSWORD@tcp(DBHOST:3306)/DATABASE?parseTime=true
      - WOODPECKER_OPEN=true
      - WOODPECKER_HOST=${WOODPECKER_URL}
      - WOODPECKER_GITEA=true
      - WOODPECKER_GITEA_URL=${GITEA_URL}
      - WOODPECKER_SECRET=${WOODPECKER_SECRET}
    depends_on:
      - devops_woodpecker_db
```

### Additional context

```shell
Logs:
time="2021-10-10T10:59:20Z" level=error msg="unable to open database file: no such file or directory",
time="2021-10-10T10:59:57Z" level=fatal msg="database ping attempts failed"
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.github.io/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy).

**Comment by 6543** [comment]
@Flying--Dutchman what `WOODPECKER_TAG` did you use?!!
