### ISSUE TITLE
Woodpecker 2.7.1 can't find files in the form of .woodpecker/*.yaml on Codeberg

### ISSUE THREAD

**Issue by Sebbito** [woodpecker-ci/woodpecker#4295]
### Component

server

### Describe the bug

After pushing an update to my Codeberg repository, woodpecker errors with the message:

```
[generic] pipeline definition not found
```

[Link to CI](https://ci.codeberg.org/repos/13743)

The pipeline definition was in a file `.woodpecker/run-tests.yaml` and the woodpecker settings for the pipeline path were left on default.

After renaming the file to `.yml` instead of `.yaml`, woodpecker found the file and the pipeline ran just fine.

### Steps to reproduce

1. Make sure that the codeberg repo has woodpecker set up
2. Make changes and submit them to repo
3. Watch pipeline fail

### Expected behavior

Woodpecker should find the pipeline without a problem.

### System Info

```shell
Current Codeberg config.
I'm sorry, I'm not familiar with how they set it up.
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by pat-s** [comment]
This has nothing to do with the file renaming, there is no issue with `.yaml` file detection. The issue has been reported in multiple places over the last weeks and is not new. It appears when the server|agent|database is restarted and the config is unknown after restart. The reason for this behavior is unknown but related to to (unstable) WP service on CB.

https://codeberg.org/Codeberg-CI/feedback/issues/201

**Comment by zc-devs** [comment]
https://codeberg.org/Codeberg-CI/feedback/issues/201#issuecomment-2393873 looks like #4244

> The issue has been reported in multiple places over the last weeks and is not new

So, could you link here the issues from Woodpecker's repo?

**Comment by pat-s** [comment]
CB matrix channels and issue trackers.
