### ISSUE TITLE
Can not fetch config from gitea repo: error "context deadline exceeded"

### ISSUE THREAD

**Issue by MVD-H** [woodpecker-ci/woodpecker#430]
### Component

server

### Describe the bug

I created a pull request, which adds a `.woodpecker.yml` file to the repo.
Using the `latest` tag for both, server and agent, I'm getting following error in my server log:

`time="2021-10-11T23:24:00Z" level=error msg="Error #01: config '.woodpecker.yml' not found: Get \"https://DOMAIN/api/v1/version\": context deadline exceeded\n" fields.time="2021-10-11T23:24:00Z" ip=10.0.2.2 latency=57.967868ms method=POST path=/hook status=404 user-agent=Go-http-client/1.1`

My .woodpecker.yml file:
```
pipeline:
  build:
    image: tafilz/xamarin-android:29
    when:
      branch: master
    commands:
      - msbuild Project1
```

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-9c85c8fd"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.github.io/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy).

**Comment by 6543** [comment]
closed by  #458
