### ISSUE TITLE
woodpecker server docker image will not start after pulling latest

### ISSUE THREAD

**Issue by pixielark** [woodpecker-ci/woodpecker#4333]
### Component

server

### Describe the bug

woodpecker server docker image will not start after pulling latest
showing erro
```
2024-11-06T18:53:01Z INF log level: info 

2024-11-06T18:53:01Z ERR migration step 'create-table-users' missing, please upgrade to last stable v0.14.x version first 

2024-11-06T18:53:01Z ERR error running server | error=can't setup store: could not migrate datastore: migration xorm failed: legacy migration step missing
```

### Steps to reproduce

update woodpecker server docker from previou 2.7.2 release

### Expected behavior

server should start

### System Info

```shell
v2.7.3
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by zc-devs** [comment]
If you tried to downgrade from next #4323, then it won't work. Recover database from backup (`2.7`) or live with `next` version (with `3.0` eventually).

**Comment by pixielark** [comment]
I see, thanks for the explaination
I will for now stick with `next`, was forced to update agent to `next` due to the grpc mismatch issue but wasn't aware that agent modified DB
