### ISSUE TITLE
Cancelled pipelines marked as failed

### ISSUE THREAD

**Issue by xoxys** [woodpecker-ci/woodpecker#4349]
### Component

server

### Describe the bug

Sometimes pipeline cancellations still result in errors that will flag the pipeline as failed instead of cancelled:

![image](https://github.com/user-attachments/assets/ef6f79d3-e18d-4e06-bc0e-a26ef1f8164c)

### Steps to reproduce

Have not found a reliable way to reproduce this specific case.

### Expected behavior

Pipeline should be marked as cancelled instead of failed.

### System Info

```shell
next-bf5405b6cc
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by zc-devs** [comment]
#833
