### ISSUE TITLE
Triger Manuall Pipeline errors out

### ISSUE THREAD

**Issue by Michael-Purtill** [woodpecker-ci/woodpecker#4405]
### Component

server, agent, web-ui

### Describe the bug

I'm using docker swarm with the `latest` tag for the woodpecker-server image, and the `latest-alpine` tag for the woodpecker-agent image. using a .woodpecker file does seem to allow woodpecker to notice it as a workflow. The exact stack file I'm using worked roughly 2.5 weeks ago. Upon running the pipeline, nothing happens, and checking the dev console gives the message `Missing required param "pipelineId" ` The containers for both the server and agent print no logs when this happens.

### Steps to reproduce

1. Create a Docker Swarm stack using the provided stack file.
2. Set it up to access a bitbucket workspace
3. add a .woodpecker folder with some manual workflows to a repo
4. run a pipeline on that repo on whichever branch you added the .woodpecker folder
5. check the dev console for `Missing required param "pipelineId" ` error

### Expected behavior

Successfully find workflows and execute them

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"2.7.3"}

Here's the stack file:

services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:latest
    ports:
      - 8001:8000
    volumes:
      - woodpecker-server-data:/var/lib/woodpecker/
    env_file: woodpecker.env
    networks:
      - wpkr
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:latest-alpine
    command: agent
    depends_on:
      - woodpecker-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - woodpecker-agent-config:/etc/woodpecker
    env_file: woodpecker.env
    networks:
      - wpkr
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: any
volumes:
  woodpecker-server-data:
    driver: "local"
  woodpecker-agent-config:
    driver: "local"
networks:
  wpkr:
    external: true
    attachable: true
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by Michael-Purtill** [comment]
> Looks like a UI issue. With "dev console", you mean the browser console? Can you get a more detailed error?

Yes, browser console. Unfortunately the entire content of the error is 'Error: Missing required param "pipelineId"'. It's coming from minified Javascript. It appears to be because the call to `api/repos/<pipelinid>/pipelines` is returning no data.

**Comment by Michael-Purtill** [comment]
Sure.

upon clicking 'Run Pipeline' and selecting my branch, then clicking 'run pipeline' in the modal, a `POST` request is made to:

`http://<my-ip>:8001/api/repos/1/pipelines` 

with the payload `{"branch":"master","variables":{}}`

The response data is a completely empty body. Firefox displays it as `No response data for this request`

**Comment by 6543** [comment]
why cant bitbucket just have stable apis :/

**Comment by Michael-Purtill** [comment]
Thanks for the attention to this issue. I tried it again using a docker-compose file and hosting the server and agent locally on my machine, but still have the same problem. There's a chance I'm doing something wrong, but the containers are giving me no logs whatsoever when this happens.

**Comment by 6543** [comment]
uh well https://ci.woodpecker-ci.org/repos/3780/pipeline/22958 it works if you specify variables ...

@Michael-Purtill could you just out an random variable into it and retry?
e.g. `SOME` = `VALUE` or so ...

**Comment by 6543** [comment]
still it should work without variables!

**Comment by 6543** [comment]
if you use an external database ... you have to kill (delete that database) that one, else it's only an sqlite file that should be saved in an volume, witch you should be able to delete

**Comment by Michael-Purtill** [comment]
yeah, I'm just using the default compose file listed on the woodpecker website. the volumes only have an sqlite file inside of them. I've deleted the volumes for both server and agent several times but still observe this strange behaviour.

**Comment by Michael-Purtill** [comment]
Just wanted to note that my situation appears to mirror this issue from April:

https://github.com/woodpecker-ci/woodpecker/issues/3600

**Comment by Michael-Purtill** [comment]
Any updates on this? This is currently holding me back.

**Comment by Michael-Purtill** [comment]
nevermind... 

This turned out to be a configuration issue on my end. I had all my pipelines listening for the wrong branch. However, more logging would have been useful for fixing this.

**Comment by 6543** [comment]
@Michael-Purtill what exactly should be logged where? :eyes:

**Comment by Michael-Purtill** [comment]
@6543 changing the javascript log to something like 'No workflows found for branch xyz' would be helpful. Also, from a UI standpoint, nothing happens at all when this occurs, and the user has to open their browser consol to see that something has gone wrong.
