### ISSUE TITLE
Can not create secret

### ISSUE THREAD

**Issue by Reparierer** [woodpecker-ci/woodpecker#4545]
### Component

web-ui

### Describe the bug

Creating a new secret using the web-ui results in the following error: `: user not authorized`

Can anyone confirm this?

### Steps to reproduce

1. Log in the web-ui
2. Go to `settings` -> `secrets` -> `add secret`
3. add a secret, e.g. name `mail` and some random value like `abc`
4. click `add secret`
5. see error message `: user not authorized`. Also, the secret is not added.

### Expected behavior

no error message, adding a secret works

### System Info

```shell
`{"source":"https://github.com/woodpecker-ci/woodpecker","version":"2.8.0"}`
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by zc-devs** [comment]
> Can anyone confirm this?

I can't on `next-21755bef4e`

![Screenshot 2024-12-10 1](https://github.com/user-attachments/assets/85871745-8126-47d6-a30b-e83a741483c9)
![Screenshot 2024-12-10 2](https://github.com/user-attachments/assets/9d6509fa-7d5c-4729-b0fb-c8bf93c7a910)

**Comment by Reparierer** [comment]
After trying a few times on different days, it is like the behavior @zc-devs mentioned. Works sometimes, sometimes not.

**Comment by Reparierer** [comment]
Closing, as i have no access to server logs
