### ISSUE TITLE
Woodpecker 3.0.0-rc.1 Can't POST webhook deliveries: failure to parse token from hook

### ISSUE THREAD

**Issue by dessalines** [woodpecker-ci/woodpecker#4571]
### Component

server

### Describe the bug

All my webhook deliveries to my server are failing with the following message.

```
{"level":"error","error":"token is unverifiable: error while executing keyfunc: strconv.ParseInt: parsing \"\": invalid syntax","time":"2024-12-15T13:20:03Z","message":"failure to parse token from hook"}
```

I've also removed the internal letsencrypt in favor of an nginx-based one, so I'm not sure if that has anything to do with it.

### Steps to reproduce

1. Upgrade to woodpecker v3.0.0.-rc.1
2. All webhook deliveries fail

### Expected behavior

They should succeed, and not get the ParseInt failure above.

### System Info

```shell
"source":"https://github.com/woodpecker-ci/woodpecker","version":"3.0.0-rc1"}
```

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by anbraten** [comment]
The token schema of webhooks changed. Therefore you need to repair all repos. There is a button in the Armin settings. Probably sth that needs to be highlighted in the mivration notes again.

**Comment by dessalines** [comment]
That fixed it! Unfortunately I might have to manually re-trigger the PRs since the upgrade, but its nbd.

**Comment by walkero-gr** [comment]
Hello guys. I had the same issue even on a brand-new installation of 3.1.0 using docker. Below is the information as seen in GitHub. Using repair for the repository seems that solved that issue, but for a new installation, this should not be the case.

![Image](https://github.com/user-attachments/assets/149126f0-971a-4d12-b162-1d41d82a1172)
