### ISSUE TITLE
Only set Commit status "error" on pipeline error

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#459]
example https://ci.codeberg.org/crapsilon/JAMMM/1

do NOT set an ci status for related commit

**Comment by anbraten** [comment]
@6543 Do you want woodpecker to NOT report a status at all if the pipeline was not running at all caused by an error in the config etc? Or should it be pending?

**Comment by 6543** [comment]
if pipeline is skiped none
if error occur -> error

**Comment by anbraten** [comment]
🤔 I don't know if this would be ideal. A user wont get any feedback that way. For example in a PR he wont see that something was failing as the UI would not show a CI status at all (if status check is not required by repo settings). Second problem is the fact that a PR could be merged as the CI is not blocking if not required.

**Comment by 6543** [comment]
well we could add success with context "skiped" or so?

**Comment by 6543** [comment]
well skiped pipeline should not block things
 -> on main branch they are normaly intendent to save ci time
 -> on pull it should not create a status as otherwhies branch protection could be missed

**Comment by 6543** [comment]
> .. the fact that a PR could be merged as the CI is not blocking if not required.

this is a missconfigured branch protection!  
reporting back a pending on skiped is just wrong
