### ISSUE TITLE
Inline styles

### ISSUE THREAD

**Issue by zc-devs** [woodpecker-ci/woodpecker#4616]
### Component

web-ui

### Describe the bug

The code contains the inline styles.
Inline style, seems, was only in `web/src/components/admin/settings/queue/AdminQueueStats.vue:25` before.

### Expected behavior

Should not be inline styles.

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/style
https://stackoverflow.com/questions/2612483/whats-so-bad-about-in-line-css
https://content-security-policy.com/unsafe-inline/

### System Info

`next`

### Additional context

I accidentally saw #4609 and wanted to comment there, but I'm not allowed to comment on `pat-s` issues and PRs.

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by xoxys** [comment]
> I accidentally saw https://github.com/woodpecker-ci/woodpecker/pull/4609 and wanted to comment there, but I'm not allowed to comment on pat-s issues and PRs.

Can you please stop with such stuff? Most of the time your input is helpful and is taken into account, but some comments seem as if they are only intended to disturb development without making any constructive contribution. Thus, they might get ignored. If you have constructive feedback to add, pretty sure nobody told you to stop on PRs of a particular author.

**Comment by zc-devs** [comment]
> Can you please stop with such stuff?

Sorry, I do not understand, what are you asking to stop? But, sure, it won't be a problem from my side. Are you asking to stop filing the issues?

> I accidentally saw https://github.com/woodpecker-ci/woodpecker/pull/4609 and wanted to comment there, but I'm not allowed to comment on pat-s issues and PRs.

I just explained, why this issue appears. The same as with #4619.

> they are only intended to disturb development

OMG!

> without making any constructive contribution
> If you have constructive feedback to add

Testing and filing a bugs are not contribution, aren't? Or they are, but are not constructive? The are not constructive in general? Only my? Or only this one? How can I improve this one?

> they might get ignored

No problem. Feel free to close, if you find it non-constructive, disturbing or whatever.

I just wanted to say, that inline styles (and scripts) is a bad practice. And there was one place with that thing, but now it is two and could spread across the codebase.

**Comment by xoxys** [comment]
You missed the point. I fully agree with the technical details of this issue. Perfectly valid. I marked a single line and kindly ask you to avoid such provocative statements.
