### ISSUE TITLE
Feedback to new two-row pipeline layout

### ISSUE THREAD

**Issue by pat-s** [woodpecker-ci/woodpecker#4648]
### Component

web-ui

### Describe the bug

@qwerty287 

<img width="377" alt="image" src="https://github.com/user-attachments/assets/4ee0a301-9676-4620-9627-5e4712d5f295" />

- Min-width of commit hash field should be larger
- Sometimes the committer icon is missing (maybe use an anchored relative position for the start of the timing buttons so it doesn't matter if the icon is missing?)
- Maybe the committer icon could also be moved as the first entry of the second line? This would avoid the layout shift in case it is missing (although it should always exist actually, not sure why it is missing in some runs in the new view)

**Comment by pat-s** [comment]
Additional issues:

- The status indicator was changed from `w-3` to `w-2` and now looks way to thin. Was this in purpose, @qwerty287?
- Icons are not aligned with the text anymore

<img width="90" alt="image" src="https://github.com/user-attachments/assets/004f9827-7449-4030-84a1-00ad1b82bed9" />

@qwerty287 Should we maybe revert and have a new clean PR?

**Comment by pat-s** [comment]
All good, I also didn't test it in detail and I am partly guilty for merging :)

Let's revert and test it in more detail with PR images? Do you wanna revert or should I?

**Comment by xoxys** [comment]
> Maybe the committer icon could also be moved as the first entry of the second line? This would avoid the layout shift in case it is missing (although it should always exist actually, not sure why it is missing in some runs in the new view)

Its also possible to just reserve the required space (which is a good practice for images anyway)

**Comment by pat-s** [comment]
reverted via #4649, new discussions should happen in a new PR then.
