### ISSUE TITLE
Event for cancle job not send

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#469]
### Component

server, web-ui

### Describe the bug

If I click cancle in the UI for a job, there is no event send to the web-clients, so I have to manually reload the page to see the new state of the canceled job

### System Info

```shell
dev
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy).

**Comment by 6543** [comment]
@anbraten event is now triggered with the new ui ... can we close this issue?

**Comment by anbraten** [comment]
I will close it for now and re-open if needed.
