### ISSUE TITLE
Gitea git fetch always fatal

### ISSUE THREAD

**Issue by cubesky** [woodpecker-ci/woodpecker#473]
### Component

server, agent, other

### Describe the bug

Git fetch always fatal using Gitea OAuth. 

This happens on DroneCI too, but add `DRONE_GIT_ALWAYS_AUTH=true` can solve this problem. It there any similar solution for woodpecker? `WOODPECKER_GIT_ALWAYS_AUTH` doesn't work.

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-7725058f"}
```

### Additional context

```shell
+ git init
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /drone/src/git.example.com/foobar/test-repo/.git/
+ git remote add origin https://example.com/cubesky/test-repo.git
+ git fetch --no-tags origin +refs/heads/master:
fatal: could not read Username for 'https://git.example.com': No such device or address
exit status 128
```

> Gitea URL and username is replaced with example.com and foobar

Woodpecker and Gitea is on the same host with docker.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy).

**Comment by LamaAni** [comment]
https://github.com/woodpecker-ci/woodpecker/pull/760
