### ISSUE TITLE
Restart a single job [and it's dependencies]

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#500]
Add a function to restart and optional it's related job that would come next.

Problem:  The workspace is dropped after pipeline exec/fail. Let's say you had a "install build tools" step before build, it wont have access to those tools ...

**Comment by anbraten** [comment]
Would be quite hard / not possible as the mentioned workspace will be deleted. Instead we could allow to restart a complete workflow as suggested in #1886
