### ISSUE TITLE
RepoSync disable enabled repos

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#511]
#510 did fix a bug but create a new one ...

now let's do it properly!!!

**Comment by 6543** [comment]
cc @plafue, @eleith

**Comment by plafue** [comment]
Thanks for the quick bugfix! Now the `next` images work without problems :tada: .

**Comment by 6543** [comment]
Thanks for being on next and do quick bug reports :)

It has huge value for us!
