### ISSUE TITLE
CLI: try to delete non existing registry entry just returns not readable error

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#524]
```sh
[user@PC woodpecker]$ ./dist/cli/linux_amd64/woodpecker-cli registry rm --hostname docker.io test/testCI
[user@PC woodpecker]$ ./dist/cli/linux_amd64/woodpecker-cli registry rm --hostname docker.io test/testCI
 FTL error running cli error="client error 500: Error deleting registry \"a\". sql: no rows in result set"
```
woodpecker version: d02dfe993f4cc94bd8e87f454e17bbea8eea592d

**Comment by avinilcode** [comment]
is it just to catch the error and return the error, while deleting using CLI? If so,  I can return just return "hostname and repo does not exist", if not then can you explain bit more. I would want to contribute

**Comment by avinilcode** [comment]
I have raised pull request for this issue, can you please review it.
