### ISSUE TITLE
Allow the pipeline config to be generated dynamically

### ISSUE THREAD

**Issue by kevinsimper** [woodpecker-ci/woodpecker#53]
It would be really cool if the drone.yml could be generated dynamically.

It could be a step that executes a docker image and then drone uses that output to run the pipeline.

This would allow users and companies to easier share templates. Like automatically setting up reviewapps without having to have a long yaml file.

This is not like jsonette as that is not dynamic either.

**Comment by laszlocph** [comment]
Feels like the Drone configuration plugin idea is a variation of your proposal. What do you think? https://github.com/drone/drone/issues/1021#issuecomment-417819643

**Comment by kevinsimper** [comment]
No not exactly, that is globally on the drone installation.

I want the drone file to be allowed to be fetched with curl from a remote place, or generate with a docker container, or generated with bash.

Imagine being able to add another deploy target to all drone files when you are doing a Kubernetes deployment?

Or having a script that generate steps for reviewapps:

```yaml
# .drone.yaml
generate: docker run generate-woodpecker-file --features reviewapps,lint,nodejs,ruby,deploy
```

That file is then shown in the UI so you know where the steps where coming from.

**Comment by 6543** [comment]
will be covered by #1400
