### ISSUE TITLE
Add validation to UI forms

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#533]
We can add something like [vuelidate](https://vuelidate-next.netlify.app/). To catch errors in the frontend.

(error cases should in any way also be handled at backend, this is only to improve UX)

_Originally posted by @anbraten in https://github.com/woodpecker-ci/woodpecker/pull/532#discussion_r755610392_

**Comment by anbraten** [comment]
There seems to be no need for this atm. We can use `form` with `required` attributes in most cases.
