### ISSUE TITLE
prevent service name to be equal to step name

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#557]
![Unbenannt](https://user-images.githubusercontent.com/6918444/144145897-c17d0299-aad0-4594-8ee2-f19b825c8a21.PNG)

postgres and mysql jobs are skipped somehow

**Comment by anbraten** [comment]
Issue detected: Service name is not allowed to be equal to one step name.
TODO: add config check to prevent that.

**Comment by 6543** [comment]
instead of preventing it we should fix the underling bug

**Comment by anbraten** [comment]
```diff
// add services steps
if len(conf.Services.Containers) != 0 {
	stage := new(backend.Stage)
	stage.Name = fmt.Sprintf("%s_services", c.prefix)
	stage.Alias = "services"

	for i, container := range conf.Services.Containers {
		if !container.Constraints.Match(c.metadata) {
			continue
		}

+		name := fmt.Sprintf("%s_services_%d", c.prefix, i)
		step := c.createProcess(name, container, "services")
		stage.Steps = append(stage.Steps, step)
	}
	config.Stages = append(config.Stages, stage)
}
```

Hmm, the compiler should not be the problem.

**Comment by 6543** [comment]
without looking at the coude, i guess it's an issue with the gRPC api

**Comment by 6543** [comment]
https://github.com/woodpecker-ci/woodpecker/blob/master/pipeline/rpc/proto/woodpecker.proto#L92-L95

look's like the name is actually used as ID for gRPC - we just have to change that

**Comment by anbraten** [comment]
linking #983

**Comment by 6543** [comment]
-> #1802
