### ISSUE TITLE
ci.woodpecker-ci.org is not reporting status back

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#558]
The status checks are not resolved / updated atm.
Check if this is just a problem with `ci.woodpecker-ci.org` or a general issue.

**Comment by 6543** [comment]
fixed by `update repos set repo_user_id=2 where repo_id=3780;`  
user_id 1 -> laszlocph  
user_id 2 -> 6543

so we should add an repo-admin-option to set the user a context is reported back ...
