### ISSUE TITLE
Support `local` as backend

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#559]
run an agent that runs commands on the host machine

**Comment by 6543** [comment]
## workaround:
trigger ssh commands in a container that connect to the host machine

**Comment by anbraten** [comment]
Would be easy to implement and could be funny to play with 🙈

**Comment by Ta180m** [comment]
> Would be easy to implement and could be funny to play with see_no_evil

How easy is it to implement this? I'd love to be able to use it on my self-hosted server, and might try implementing it myself.

**Comment by anbraten** [comment]
@Ta180m You "simply" have to implement a new backend with the interface of `pipeline/backend/types/engine.go`.  

To add the new backend add it at https://github.com/woodpecker-ci/woodpecker/blob/master/pipeline/backend/backend.go#L17

You can select a backend by https://woodpecker-ci.org/docs/administration/agent-config#woodpecker_backend.

**Comment by ambroisie** [comment]
> You can select a backend by [woodpecker-ci.org/docs/administration/agent-config#woodpecker_backend](https://woodpecker-ci.org/docs/administration/agent-config#woodpecker_backend).

I would really like to be able to select which backend is used on a pipeline basis instead, like one can on Drone.
