### ISSUE TITLE
Tail of logs failed - logs only appear after the step

### ISSUE THREAD

**Issue by atilleh** [woodpecker-ci/woodpecker#580]
### Component

web-ui

### Describe the bug

Hello everyone !

First of all, thank you for the great work you do here!

We have a problem on our Woodpecker test instance; when running steps, the logs only appear after the step is completed. During execution, the log window remains black, which can be a problem when some tasks are very long.

As a quick diagnostic:
* https://host/stream/logs/org/repo/34/6 returns event=error, data=eof during the step execution

```
: ping

event: error
data: eof
```

The woodpecker server logs:
```
{"level":"error","error":"stream: not found","time":"2021-12-08T14:45:36Z","message":"tail of logs failed"}
```

it is always the case. As soon as the step is finished (failed or successful), the logs are displayed as if by magic.
Any idea ?

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-03a43567"}
```

### Additional context

```shell
The woodpecker-server is on the same machine as the woodpecker-agent, both running with docker-compose.

A Caddy reverse-proxy is setup in front of the woodpecker-server (reverse of localhost:8000) and the WOODPECKER_HOST variable is setup.

The build works fine, just the logs don't appear.
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy).

**Comment by argrento** [comment]
Seems that I have the same. During execution of step, no logs are presented. In Firefox development console only "eof" in the response presents.
![image](https://github.com/woodpecker-ci/woodpecker/assets/4477094/780d8234-9121-4bdd-baba-268eb19df657)
![image](https://github.com/woodpecker-ci/woodpecker/assets/4477094/567a3e8f-db37-4ac3-a574-890ef5a02f5c)
Config: https://codeberg.org/argrento/termux-packages/src/branch/master/.woodpecker.yml
docker-compose:
```
# docker-compose.yml:
version: '3'

services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:next
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8000:8000
      - 9000:9000
    volumes:
      - woodpecker-server-data:/var/lib/woodpecker/
    environment:
      - WOODPECKER_OPEN=false
      - WOODPECKER_HOST={hidden}
      - WOODPECKER_LETS_ENCRYPT=true
      - WOODPECKER_LOG_LEVEL=error
      - WOODPECKER_ADMIN=argrento
      - WOODPECKER_DEFAULT_PIPELINE_TIMEOUT=120
      - WOODPECKER_MAX_PIPELINE_TIMEOUT=1440
      - WOODPECKER_GITEA=true
      - WOODPECKER_GITEA_URL=https://codeberg.org
      - WOODPECKER_GITEA_CLIENT={hidden}
      - WOODPECKER_GITEA_SECRET={hidden}
      - WOODPECKER_AGENT_SECRET={hidden}

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:next
    command: agent
    restart: always
    depends_on:
      - woodpecker-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/data:/mnt/data
    environment:
      - WOODPECKER_SERVER=woodpecker-server:9000
      - WOODPECKER_AGENT_SECRET={hidden}

volumes:
  woodpecker-server-data:
```
