### ISSUE TITLE
Delete Repository should clean all evidence from DB

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#590]
![del](https://user-images.githubusercontent.com/24977596/145648066-049fcc48-0f89-4d93-84ea-94169b45607a.png)

current behaviour: dectivate webhooks at Forge
expect:
 - deactivatewebhook at Forge
 - delete all logs, task, job ... and repo istselv from db

**Comment by anbraten** [comment]
this function is already available api wise, but i decided to use the deactive for now. should I change it?

**Comment by 6543** [comment]
yes

**Comment by 6543** [comment]
@anbraten can you add a pop up "are you sure y/N" dialog to avoid acidents?

**Comment by anbraten** [comment]
We already have a dialog so I will just change it to remove.

**Comment by 6543** [comment]
wow you are fast ;)

**Comment by susnux** [comment]
Nice! Thats something I stumbled over when get in touch with woodpecker and something I would, form an user pov, expect to behave different.
Maybe add a third button (besides delete and repair) to deactivate only?
