### ISSUE TITLE
migration for `fix-pr-secret-event-name` causes fatal error

### ISSUE THREAD

**Issue by eleith** [woodpecker-ci/woodpecker#596]
### Component

server

### Describe the bug

migration triggers fatal error and server will not start. running with log level at trace shows the following messages

```
woodpecker-server_1  | {"level":"trace","time":"2021-12-12T05:03:30Z","caller":"/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/store/datastore/migration/migration.go:109","message":"migration task 'xorm' already applied"}
woodpecker-server_1  | {"level":"trace","time":"2021-12-12T05:03:30Z","caller":"/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/store/datastore/migration/migration.go:109","message":"migration task 'alter-table-drop-repo-fallback' already applied"}
woodpecker-server_1  | {"level":"trace","time":"2021-12-12T05:03:30Z","caller":"/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/store/datastore/migration/migration.go:109","message":"migration task 'drop-allow-push-tags-deploys-columns' already applied"}
woodpecker-server_1  | {"level":"trace","time":"2021-12-12T05:03:30Z","caller":"/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/store/datastore/migration/migration.go:113","message":"start migration task 'fix-pr-secret-event-name'"}
woodpecker-server_1  | {"level":"fatal","error":"pq: operator does not exist: json ~~ unknown","time":"2021-12-12T05:03:30Z","caller":"/woodpecker/src/github.com/woodpecker-ci/woodpecker/cmd/server/setup.go:84","message":"could not migrate datastore"}
```

### System Info

```shell
running `next` as of today
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy).

**Comment by 6543** [comment]
@eleith workaround: exec `INSERT INTO migrations VALUES('fix-pr-secret-event-name');`
this migration is not mandatory to let wodpecker run

**Comment by 6543** [comment]
@eleith can you send me the dump of your database **secrets replaced with random garbage** and only the secrets table is needed

-> you can send me a direct link via PM - just to limit things (db dumps are kinda **sensitive data**)

**Comment by eleith** [comment]
i'll have to dig into my backups as i've had many changes. however, i believe i only had three secrets (all the same, just different repos) and they were only assigned to `push` and `deploy`, so i was surprised it was triggering a failure as i wasn't even using the `pull-request` type.

**Comment by 6543** [comment]
@eleith I tested it with postgres (PostgreSQL) 13.4 and had no issue at al.

what version do you use?

**Comment by eleith** [comment]
postgres 13.1 alpine

**Comment by 6543** [comment]
@eleith it would help a lot if i can get the content from the secret_events column

**Comment by eleith** [comment]
```
 secret_events 
---------------
 ["push"]
 ["push"]
(2 rows)
```

but i think actually, one of them used to also have `deploy` and i toggled later after skipping the failed migration

**Comment by 6543** [comment]
ah `deploy` is no json object - I think I can harden the migration to accept that

**Comment by 6543** [comment]
@eleith since I could not reproduce this & handle the special case mentioned, would make migration very slow and add new code that can fail ... I instead propose  #729 - so an instance admin can manually exec some sql to fix it if it would really hit :)
