### ISSUE TITLE
Implement e2e test for WebUI

### ISSUE THREAD

**Issue by laszlocph** [woodpecker-ci/woodpecker#6]
I find myself testing the following way before merging any PR:
- start up a server and and agent
- find a former build and I restart it
- wait til it's green

A smoke test could be implemented:
- running a master and and an agent in a Docker dind setup
- having a fixture sqlite database that has a previously running build in it
  doing like this there is no need for valid Github tokens
- restart the build with API, token is known from the fixture
- poll the API until the build is done

Another smoketest:
- check if UI loads, search for a DOM element

What's the value? 
For example I had a case where one of the dependencies were updated and pulling of images was not working.

But to be frank, the value may not be that much.

**Comment by 6543** [comment]
issue is now tracked at  #2694
