### ISSUE TITLE
Repo Settings: Secrets: add field for image list

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#607]
# Currently
backend does support binding secrets to specific steps (this is set by the secret option of [a step](https://woodpecker-ci.org/docs/usage/secrets)):

https://github.com/woodpecker-ci/woodpecker/blob/442561fea21d01912843c1dd254bb9119d779814/pipeline/frontend/yaml/compiler/convert.go#L116-L121

match is derived from images at:
https://github.com/woodpecker-ci/woodpecker/blob/442561fea21d01912843c1dd254bb9119d779814/server/shared/procBuilder.go#L197-L207

# Expected

Add an option to the Vue UI to the secrets edit form to specify a list of images the secrets is allowed to be passed to.
In the backend it should filter the secrets list based on the allowed images of the secrets. If the images list of a secret is empty, it will can passed to all images.

To store the image in datastore add following property to the secret:
https://github.com/woodpecker-ci/woodpecker/blob/442561fea21d01912843c1dd254bb9119d779814/server/model/secret.go#L55

**Comment by ktprograms** [comment]
So if I understand the docs correctly, this is already doable using the CLI, right? (using the `-image <image>` option)

**Comment by 6543** [comment]
yes the server (backend) already support it and CLI too - just web ui dont

**Comment by ktprograms** [comment]
@6543 Ok, thanks. One other thing: I'm a bit unfamiliar with Go, so I'm not sure how exactly this: https://github.com/woodpecker-ci/woodpecker/blob/442561fea21d01912843c1dd254bb9119d779814/server/model/secret.go#L55 works. (What is the string in backticks after the type declaration)?

**Comment by 6543** [comment]
@ktprograms that are 'tags' -> https://www.digitalocean.com/community/tutorials/how-to-use-struct-tags-in-go

you wont touch go code if you try solve this issue

**Comment by ktprograms** [comment]
@6543 Thanks for the reference. I'll give it a try, but no need to assign me to the issue yet (I'm not sure if I can do it).

**Comment by ktprograms** [comment]
@6543 What's the best way to develop changes to the web UI? When I was just doing the simple change for the Safari Tab Bar it was ok to just use `yarn build && yarn serve`, but for something like this I think I need to have it interface with the actual server, which is running in a Docker container for me.

**Comment by 6543** [comment]
@ktprograms please do not use the issue tracker as chat ... we have matrix and discord to do so :)
PS: for developer docu look at https://github.com/woodpecker-ci/woodpecker/pull/610 and #314
