### ISSUE TITLE
Possibility to use Github Actions workflows

### ISSUE THREAD

**Issue by laszlocph** [woodpecker-ci/woodpecker#61]
This issue investigates the possibility to run Github Actions workflows on Woodpecker.

https://github.com/actions/workflow-parser
https://github.com/nektos/act

**Comment by 6543** [comment]
I think that should be done as plugin ... - since act do use a docker image to exec gh actions, we should be able to do that :)

**Comment by anbraten** [comment]
Not sure how it works, but maybe sth like this could be interesting as well: https://github.com/drone-plugins/github-actions

**Comment by anbraten** [comment]
As far as I understand the plugin runs github actions from drone with [act](https://github.com/nektos/act) using the underlying docker socket, so you could at least execute your github actions from within Woodpecker. Reporting will probably be quite bad (just a single step status & log), but it could work.

**Comment by 6543** [comment]
well I guess we can close this as it is either already covered or already tracked in other mentioned issues ...
