### ISSUE TITLE
Include forge type in repo model

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#621]
It could be helpful to include the SCMs type and maybe url / instance name in the repo model. This could be used to determine the type of SCM and improve parsing of for example ref in the UI. (Gitlab ref of MR is: `refs/merge-requests/2/head`, Githubs is: `refs/pull/620/merge`)

I would add this on a per repo basis as it could be a preparation for #138 and could be used if a user ever switches SCMs with their database.

**Comment by 6543** [comment]
i would recommend to add a new table and only link repos by foreginID to it

**Comment by anbraten** [comment]
yep see #1417
