### ISSUE TITLE
Unknown error and invalid state when pipeline contains invalid matrix tags

### ISSUE THREAD

**Issue by susnux** [woodpecker-ci/woodpecker#637]
### Component

server, agent

### Describe the bug

After renaming on matrix variable and forgetting to change on the `image` property,
I noticed that woodpecker will fail (of cause), but with no meaningful error and without showing the error.

The webui only shows "Unknown error" and show `exit code 0` within that step (also the step is marked as "succeeded").

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-c2b0c1d7"}
```

### Additional context
Log from server:
```shell
{"level":"warn","error":"sql: no rows in result set","time":"2021-12-14T14:34:17Z"}
{"level":"warn","error":"sql: no rows in result set","time":"2021-12-14T14:46:27Z"}
{"level":"error","time":"2021-12-14T14:47:52Z","message":"failure to parse yaml from hook for Flaschengeist/flaschengeist-frontend. yaml: line 5: found character that cannot start any token"}
{"level":"error","error":"Error #01: yaml: line 5: found character that cannot start any token\n","ip":"172.22.0.1","latency":554.057332,"method":"POST","path":"/hook","status":200,"time":"2021-12-14T14:47:52Z","user-agent":"Go-http-client/1.1","time":"2021-12-14T14:47:52Z"}
{"level":"warn","error":"sql: no rows in result set","time":"2021-12-14T14:57:07Z"}
```
Log from agent: [error.log](https://github.com/woodpecker-ci/woodpecker/files/7758788/error.log)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy).

**Comment by pat-s** [comment]
Closing since > 2 years old, please re-open with fresh logs if this is still an issue.
