### ISSUE TITLE
Use the agent hostname as pipeline constraint

### ISSUE THREAD

**Issue by nupplaphil** [woodpecker-ci/woodpecker#643]
### Clear and concise description of the problem

As a user of Woodpecker I want to use the agent hostname as a pipeline constraint so that I can force specific agents for a deployment pipeline.

**Real Life Example**
- 1 server
- 2 local agents (same docker-compose file)
- 2 support agents far far away :-)

One of the pipeline is a continuous deployment process which creates, signs and uploads artifacts. But the access to the corresponding fileserver is restricted to the local agents only.

### Suggested solution

We already use the `WOODPECKER_HOSTNAME` environment variable to force agents hostname. Maybe we can match it again an additional `when` property.

### Alternative

We can introduce a `node` constraint property in the pipeline syntax similar to Drone :-)

Uggly alternative I'm using here https://github.com/friendica/friendica/pull/11112 :
- Set `WOODPECKER_PLATFORM` to a fictive value (like `releaser/release`)
- add a `platform: releaser/release` constraint
- örks ... :D

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by anbraten** [comment]
Should be doable by one of the following options:
- https://woodpecker-ci.org/docs/usage/pipeline-syntax#instance
- https://woodpecker-ci.org/docs/usage/pipeline-syntax#labels

**Comment by helmut72** [comment]
> * https://woodpecker-ci.org/docs/usage/pipeline-syntax#labels

Where can I find the doc about labels? Thank you.
