### ISSUE TITLE
Corrupted proc structure

### ISSUE THREAD

**Issue by ChewingBever** [woodpecker-ci/woodpecker#645]
### Component

server

### Describe the bug

After running a few builds, I get the issue where the UI just shows the error "An unknown error occured" without loading the UI. Each time this page is accessed, the error message is accompagnied by a log message saying something about a "corrupt proc structure" (see Additional Context section). You find an example of such a bugged out page [here](https://ci.rustybever.be/rusty-bever/blog/build/2). I'll keep it up for a bit as I don't need really need it atm, maybe it can help you guys figure out the problem. The "repair repository" button doesn't help.

For reference, I use [this stack file](https://gitlab.com/rusty-bever/deployment/-/blob/master/stacks/woodpecker.yml) for deploying Woodpecker inside my Docker swarm.

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-b4094b9d"}
```

### Additional context

```shell
{"time":"2021-12-30T14:29:58Z","message":"LogLevel = warn"}
{"level":"warn","error":"sql: no rows in result set","time":"2021-12-30T14:30:30Z"}
{"level":"error","error":"Error #01: Corrupt proc structure\n","ip":"10.0.1.3","latency":7.694769,"method":"GET","path":"/api/repos/rusty-bever/blog/builds/2","status":500,"time":"2021-12-30T14:30:31Z","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0","time":"2021-12-30T14:30:31Z"}
{"level":"error","error":"Error #01: Corrupt proc structure\n","ip":"10.0.1.3","latency":8.75056,"method":"GET","path":"/api/repos/rusty-bever/blog/builds/2","status":500,"time":"2021-12-30T14:33:00Z","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0","time":"2021-12-30T14:33:00Z"}
{"level":"error","error":"Error #01: Corrupt proc structure\n","ip":"10.0.1.3","latency":5.638969,"method":"GET","path":"/api/repos/rusty-bever/blog/builds/2","status":500,"time":"2021-12-30T14:33:19Z","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0","time":"2021-12-30T14:33:19Z"}
{"level":"error","error":"Error #01: Corrupt proc structure\n","ip":"10.0.1.3","latency":5.858869,"method":"GET","path":"/api/repos/rusty-bever/blog/builds/2","status":500,"time":"2021-12-30T14:33:37Z","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0","time":"2021-12-30T14:33:37Z"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy).

**Comment by 6543** [comment]
@ChewingBever can test it via `woodpeckerci/woodpecker-server:test-647` image if this fix your issue?

**Comment by ChewingBever** [comment]
I tested it both with my own built image & @6543's, & the bug does indeed seem to be fixed!
