### ISSUE TITLE
support nested repositories (GitLab)

### ISSUE THREAD

**Issue by jdoubleu** [woodpecker-ci/woodpecker#648]
**Component:** server

### Describe the bug

It looks like Woodpecker does not properly handle nested repositories from GitLab. Nested repositories or [subgroups](https://docs.gitlab.com/ee/user/group/subgroups/) are a GitLab feature where a repository might exist inside a 2 level or greater hierarchy (e.g. `my-org-group/team-group/category-group/actual-repository.git`), as opposed to the 2 level hierarchy that is well established by SCMs (e.g. `vendor/project.git`).

When I try to sync my repositories in the Woodpecker UI, nothing happens. Looking that the `debug` error logs I get the following message:
```
{"level":"debug","time":"2021-12-31T17:45:34+01:00","message":"sync error: my-user: could not fetch permission of repo 'rootgroup/subgroup/my-repository': GET https://gitlab-instance.com/api/v4/projects/rootgroup/subgroup: 404 {message: 404 Project Not Found}"}
```

As you can see, Woodpecker is querying the wrong API endpoint:
```diff
- https://gitlab-instance.com/api/v4/projects/rootgroup/subgroup
+ https://gitlab-instance.com/api/v4/projects/rootgroup/subgroup/my-repository
```

I think there are two issues here, which can be resolved independently:
1. [ ] The complete repository sync fails/stops when only one repository fails to sync. I think Woodpecker should continue syncing the repositories and just skip the failed ones. It would be useful to display an error message to the user in that case.
2. [ ] Properly handle nested repositories. This might be harder to accomplish because they might need to be mapped to the tradition 2 level hierarchy as that's used internally?

## References
@6543 pointed out, they had replaced the GitLab API client with [github.com/xanzy/go-gitlab](github.com/xanzy/go-gitlab) in recent `master`.
- https://github.com/woodpecker-ci/woodpecker/blob/master/server/remote/gitlab/gitlab.go#L199-L207

### System Info

```shell
next-d11b2bb8
built from master@d11b2bb8e5bea6f29f82a20815ef7bf3fa96a0a2
```

**Comment by bck01215** [comment]
Still experiencing errors with nested repositories on [latest](https://hub.docker.com/layers/woodpeckerci/woodpecker-server/latest/images/sha256-413329ec87c33e89cd99b0cc025059ad5fee7497fb8bdc52d2758e694e617bd6?context=explore) docker build

**Comment by anbraten** [comment]
@bck01215 Cloud you give `next` a try. Latest is our latest stable release which does not include those unreleased changes from master.

**Comment by bck01215** [comment]
I'm still getting the following debug message in the next repo
> Skipping nested repository nested-repo for user username, because they are not supported, yet (see #648)."}

**Comment by anbraten** [comment]
I guess we have to introduce #1295 somehow to solve it.
