### ISSUE TITLE
Issues from rc1 run

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#684]
- [x] Changed file filter shuld be ignored on tag event
       see: https://ci.woodpecker-ci.org/woodpecker-ci/woodpecker/build/1707/7
       => #698
- [x] Gitea with multible commits have dublicated changed files
- [x] building binaries is missing / broken after #622 , #635 & #634 
- [ ] ~~link docker images to release~~ -> manual / maintainer docu / template ...
- [x] pipeline for latest release branch

**Comment by 6543** [comment]
release helm do not work: https://ci.woodpecker-ci.org/woodpecker-ci/woodpecker/build/1772/10

**Comment by 6543** [comment]
@anbraten can you describe `link docker images to release` ?

**Comment by anbraten** [comment]
![Screenshot from 2022-01-29 06-43-47](https://user-images.githubusercontent.com/6918444/151649151-7bdfb19e-0a4f-4333-ac01-7fa30738954c.png)

I had something like this text in mind, so a user directly nows the name of the new image.

**Comment by 6543** [comment]
ah ... that's more a manual thing for now - we could create some sort of template for maintainers ...
