### ISSUE TITLE
Global secrets

### ISSUE THREAD

**Issue by laszlocph** [woodpecker-ci/woodpecker#7]
At one of my clients we have 50 repos in Drone and have tooling to enable repos. This tooling injects the common secrets to each repository, so users don't have to insert Docker registry credentials, bucket credentials, etc.

The task is to:
- provide a way to add shared secrets
- the end users should be able to see what shared secrets are available

 One possible solution is to bootstrap secrets from a secrets file as a configuration parameter of the master. The UI should list these secrets as well as read only secrets on the secrets UI. But other ideas are very much welcome!

**Comment by laszlocph** [comment]
https://github.com/laszlocph/woodpecker/pull/118 provides global env vars. Which solves most of this usecase too.

**Comment by laszlocph** [comment]
https://woodpecker.laszlo.cloud/environment-variables/#global-environment-variables

**Comment by catdevnull** [comment]
https://github.com/woodpecker-ci/woodpecker/pull/148 would close this.

**Comment by anbraten** [comment]
solved by #1027
