### ISSUE TITLE
Matrix builds reports overwrite each other

### ISSUE THREAD

**Issue by ChewingBever** [woodpecker-ci/woodpecker#713]
### Component

other

### Describe the bug

I've noticed that when I run a matrix build, it gets reported in Gitea's UI as being successful, even though one or more of the builds are still running. It's seems that it reports being successful after the first build succeeds.

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-b15879d4"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy).

**Comment by fcool** [comment]
I just tried to create a solution here. I guess, the problem originates from `server/remote/gitea/gitea.go:324` (Status), where the Status of the current `proc` is read. And probably this have to take other procs into account. But as I am neither familiar with go nor with the data structures of woodpecker, I did not find out, where to find the related procs. (Are those children?)

Maybe I could try to help with the solution, if someone pushes me in the right direction ;)

**Comment by 6543** [comment]
https://codeberg.org/6543/vallumd-ci-test/commit/4a68ae80e53c6a518a8244be8c39fb44bef09ba1

-> it shows "success" but it's not ... (https://ci.codeberg.org/6543/vallumd-ci-test/build/2/8)

**Comment by 6543** [comment]
there is not jet a dessicion made what we do report back:
A. just collect and if non fails its successfull
B. append a suffix to the report id string
C. do both ... (let them report independent and have a "meta" pipeline report back)


this does highli affect how branch-prediction can be set in forges
so it will be a breaking change in one or another constelation

**Comment by wiktor-k** [comment]
I've also encountered this issue.

One way to workaround the problem would be to treat each matrix pipeline instance as a separate thing. I've seen this on GitHub where it happens that a matrix pipeline is expanded into 33 jobs or so. Example: https://github.com/rustyhorde/sss/pull/6/checks

It would be also good to be able to customize the status name in woodpecker yml, similarly to what GitHub actions allow: https://github.com/sfackler/rust-openssl/blob/master/.github/workflows/ci.yml#L222 (one could use matrix properties to customize this name).

Phew, I hope you don't mind me. Thanks for the excellent piece of software! 👋

**Comment by 6543** [comment]
Note to me: create empty "base workflow" that summarizes (success if all success) and try to add support for "tags" into status report to forges?
