### ISSUE TITLE
The spaces in task output should be kept.

### ISSUE THREAD

**Issue by wxiaoguang** [woodpecker-ci/woodpecker#718]
### Component

web-ui

### Describe the bug

The spaces in task output should be kept.

![image](https://user-images.githubusercontent.com/2114189/150945394-eef6b838-292a-4779-b50a-bdb160182d2f.png)

### System Info

```shell
"source": "https://github.com/woodpecker-ci/woodpecker",
"version": "next-9feb6be9"
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy).

**Comment by anbraten** [comment]
Context: https://github.com/rburns/ansi-to-html/issues/51

**Comment by wxiaoguang** [comment]
It's soooo old 😭

**Comment by anbraten** [comment]
Yeah, they have 3 open PRs all fixing some spaces / styling related code. Main problem is that our alternatives are pretty rare or do you know some cool / maintained library to convert ansi to html code?

**Comment by wxiaoguang** [comment]
How about replay the output to xterm.js (or some alternative web terminal) ?
