### ISSUE TITLE
What is the Drone Runner Volume Equivalent?

### ISSUE THREAD

**Issue by blaster128823782372** [woodpecker-ci/woodpecker#719]
### Clear and concise description of the problem

How can i mount certain files to each pipeline in the agent?

This is usefull for stuff like self signed cert in pipeline.

Thank you.

https://docs.drone.io/runner/nomad/configuration/reference/drone-runner-volumes/

### Suggested solution

New variable?

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by inflatador** [comment]
This has been closed as completed. Can someone point to the pull request or documentation? I still don't know what the replacement is. My best guess is [ WOODPECKER_BACKEND_DOCKER_VOLUMES
](https://woodpecker-ci.org/docs/next/administration/backends/docker#woodpecker_backend_docker_volumes) , but that isn't working for me.

**Comment by anbraten** [comment]
That should be it. Please open a new issue for further questions / issues.
