### ISSUE TITLE
Document about `WOODPECKER_DOCKER_CONFIG`

### ISSUE THREAD

**Issue by wxiaoguang** [woodpecker-ci/woodpecker#720]
As discussed in discord:

The document https://woodpecker-ci.org/docs/administration/server-config says: `If you want to make available a specific private registry to all pipelines, use the WOODPECKER_DOCKER_CONFIG server configuration. Point it to your server's docker config. Example: WOODPECKER_DOCKER_CONFIG=/home/user/.docker/config.json`

It's not easy to understand how WOODPECKER_DOCKER_CONFIG works and what affect it would bring, the path is unclear about where the config file should be put (on the host or in the docker). It's better to use a real example to demo the real usage.

Further more, if users want to setup a docker-in-docker (dind) system (which is more secure, isolate the host's docker), the problem becomes more complex: woodpecker agent container need to access the dind daemon to start pipeline containers, and the pipeline containers also need to access the dind daemon to do `docker build/push`, they all need correct `DOCKER_HOST` and `DOCKER_CONFIG` settings.

**Comment by 6543** [comment]
context: it's about the config file (created by https://docs.docker.com/engine/reference/commandline/login/) that can be read, if passed into the server.

It just obtain registry auth configs and everything else gets ignored ...

**Comment by wxiaoguang** [comment]
How it works:

1. server parses the `WOODPECKER_DOCKER_CONFIG` file, it must be readable inside the server container.
2. server passes the parsed `login`s to agents for pipeline pulling.
3. it's TOTALLY different from DOCKER_CONFIG, which is the DIRECTORY of config.json.

**Comment by BNC-Daniel** [comment]
do you have plan to support `docker-credential-ecr-login`?

**Comment by 6543** [comment]
@BNC-Daniel #1075

**Comment by 6543** [comment]
https://github.com/woodpecker-ci/woodpecker/pull/1075 got merged
