### ISSUE TITLE
Fix binaries pipeline

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#735]
I think we have to unify the `when.path`s options as we need all systems (server, agent, cli) to build to release them even if only the server for example changed. https://ci.woodpecker-ci.org/woodpecker-ci/woodpecker/build/1909

**Comment by 6543** [comment]
@anbraten did add it to the changelog pull as it's only adding two lines, rest is format ...  #736

**Comment by 6543** [comment]
->  #737
