### ISSUE TITLE
Pin a pipeline to an specific agent

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#740]
workaround could be done with set a "custom" platform, but since  #690 it's autodetected ...

the idea is to use the "agent labels" as filter but they do not work?

https://github.com/woodpecker-ci/woodpecker/blob/2f91bdd4a0f5167ef304c220865141c15f2dd563/cmd/agent/agent.go#L39-L44 ...

**Comment by anbraten** [comment]
#304

**Comment by 6543** [comment]
hmm could be a dublicate ... depending on if they can be used for this kind of feature ... - I need to test them and they need a good documentation!

**Comment by anbraten** [comment]
We probably need to refactor them a bit. I would like to have something like a tag property for whole pipelines & pipeline steps and something similar for agents. So it should be possible to
- add one / multiple tags to a pipeline to pin it to an agent having the same tags
- pin an agent based on its hostname (maybe not even needed as it could be solved by tags)
- pin an agent based on its backend #708 (maybe we could add automatic tags like `backend:docker` to solve this)
