### ISSUE TITLE
Make the Markdown badge template a link

### ISSUE THREAD

**Issue by 9p4** [woodpecker-ci/woodpecker#752]
### Clear and concise description of the problem

When clicking on a badge in Markdown, it should redirect to the CI status page for that repo. It is trivial to do by hand, but the template should be updated to reflect that.

### Suggested solution

https://github.com/woodpecker-ci/woodpecker/blob/58838f225c8425436b83b4aff98a33ad41218e61/web/src/components/repo/settings/BadgeTab.vue#L23

Update this to be a link in Markdown: `<pre class="box">[![status-badge]({{ baseUrl }}{{ badgeUrl }})]({{ baseUrl }}{{ repoUrl }})</pre>`

And add a function that generates the repo URL:

```
const repoRul = computed(() => {
      if (!repo) {
        throw new Error('Unexpected: "repo" should be provided at this place');
      }
      return `/${repo.value.owner}/${repo.value.name}`;
    });
```

And update the return to signify it: `return { baseUrl, badgeUrl, repoUrl };`

I can create the PR if you like, but I wanted to gauge whether this is something that would be merged first.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by 6543** [comment]
> I can create the PR if you like, but I wanted to gauge whether this is something that would be merged first.

sure go on, this is total valid :)
