### ISSUE TITLE
Ability to set custom path to Docker socket

### ISSUE THREAD

**Issue by 9p4** [woodpecker-ci/woodpecker#757]
### Clear and concise description of the problem

Set an environment variable to have the Docker client connect to a specific socket. This would enable people to use Podman as their runner (using the Docker compatibility socket). Currently, I have `/var/run/docker.socket` symlinked to the user's Podman socket `/run/user/1000/podman.sock`, but this is an inelegant solution at best.

### Suggested solution

Add an environment variable (maybe `WOODPECKER_DOCKER_SOCKET`) that, if set, can set the `addr` value in the Docker client (https://github.com/moby/moby/blob/88bd93fa603870897400b7d1f0c836d554caf85e/client/client.go#L73)

### Alternative

A dedicated Podman runner, but that would be much more difficult to use than using the Podman compatibility layer.

### Additional context

https://github.com/woodpecker-ci/woodpecker/issues/85

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by mscherer** [comment]
From a quick look at the code, you can set DOCKER_HOST and the underlying client library will do the right thing. 

The only issue is that https://github.com/woodpecker-ci/woodpecker/blob/master/pipeline/backend/docker/docker.go#L39 hardcode the path.

**Comment by wxiaoguang** [comment]
I bypass this problem by setting:

```
    environment:
      - DOCKER_HOST=unix:///data-dind/dockerd/docker.sock
      - WOODPECKER_BACKEND=docker
```
