### ISSUE TITLE
Non-existing pipeline image causes unclear UI

### ISSUE THREAD

**Issue by wxiaoguang** [woodpecker-ci/woodpecker#762]
### Component

web-ui

### Describe the bug

If there is a non-existing image in pipeline, the agent fails.

But the UI show that the step with a green icon (misleading), empty logs (helpless users)

![image](https://user-images.githubusercontent.com/2114189/152954875-2c30982d-2f72-4262-8bb7-90e9abebbb9a.png)

### System Info

```shell
All latest next.

server: "version": "next-8ce41788"
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy).

**Comment by UnlimitedCookies** [comment]
I noticed the same issue today, I tried to use `image: scratch` :D Shouldn't theoretically this be a valid image?

**Comment by UnlimitedCookies** [comment]
The server emits 
```
{"level":"error","error":"Error #01: sql: no rows in result set\n","ip":"77.3.75.228","latency":2.673312,"method":"GET","path":"/api/repos/<repo-owner>/CI-Test/logs/52/3","status":404,"time":"2022-03-05T22:50:14Z","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0","time":"2022-03-05T23:50:14+01:00"}
```

**Comment by anbraten** [comment]
linking to #817

Its pretty weird. WP sets the error, but on the level of the parent process (name of the config file -> woodpecker in this case) and does not set it to the step itself.

**Comment by anbraten** [comment]
#817 got merged and this should be solved by it
