### ISSUE TITLE
Browser tab crashes when long output printed and we attempt to monitor it in real time

### ISSUE THREAD

**Issue by ivictbor** [woodpecker-ci/woodpecker#768]
### Component

web-ui

### Describe the bug

On output with 5500 lines, clicking pipeline which is producing these lines in realtime browser gets frozen with message "Woodpecker is not reposinding [WAIT]". After build is done and we reopen woodpecker in different tab we able to see an output.

### System Info

```shell
0.15.32
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy).

**Comment by fifteenhex** [comment]
Same issue here: Really long logs from a Linux kernel build cause tabs in chrome to lock up. They sometimes eventually come back to life.
