### ISSUE TITLE
Auto Decline if newer build exists

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#773]
If for example you push 4 times a commit to a pull request, 4 builds get triggered. If not gated the first one should run, the following 2 will get declined as they where still pending and the last one will be executed too. If gated only the last one will stay to be accepted/declined

**Comment by anbraten** [comment]
seems to be a duplicate of #11

**Comment by 6543** [comment]
I should have a look at the old issues, to remember what do already exist :/
