### ISSUE TITLE
cut / tail very long logs

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#776]
We currently send all log data at once to the client. In the case a job generated a lot of logs we should for example think about just sending the last 500 lines of logs otherwise the browser tab will OOM when dealing with that much data. Chunking will probably not help in this case as well as the browser would have to load that data in memory. Maybe we can set a limit by default for the api endpoint and allow to download / receive the whole data (#566) when a parameter is applied.

**Comment by xuecanlong** [comment]
can we save log into s3 when job be done? then server can just access s3 log file?
