### ISSUE TITLE
Publish arm64 woodpecker-server

### ISSUE THREAD

**Issue by relnod** [woodpecker-ci/woodpecker#782]
### Clear and concise description of the problem

I want to run the woodpecker-server docker image on an arm64 computer. On https://hub.docker.com/r/woodpeckerci/woodpecker-server/tags I can only find `linux/amd64` builds.

### Suggested solution

Adding `platforms` setting to the docker ci might be enough.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by anbraten** [comment]
in progress see #635
