### ISSUE TITLE
Remove go vendor folder

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#786]
- [ ] remove the go vendor folder from source
- [ ] add step that vendor go **and** npm dependency's
- [ ] add step that package tarball with vendor-ed files

**Comment by 6543** [comment]
I'm not against this, since it did the purpose it was added for: make sure old v0.14.* to not break because of the just too outdated dependencys.

We just need: a source bundle with vendor folder & go cache for our agent would be nice
