### ISSUE TITLE
Cron triggers

### ISSUE THREAD

**Issue by laszlocph** [woodpecker-ci/woodpecker#8]
Implement cron like triggers to enable nightly builds.

**Comment by 6543** [comment]
drone example:
![Bildschirmfoto zu 2021-06-23 16-13-54](https://user-images.githubusercontent.com/24977596/123112553-14fb3380-d43e-11eb-9d70-a3965b06caec.png)

I also would add a manual "play-button" to trigger it manually next to delete icon

**Comment by 6543** [comment]
https://pkg.go.dev/github.com/robfig/cron?utm_source=godoc#hdr-Usage

**Comment by svdHero** [comment]
This feature is crucial for us, since we also want to execute long running nightly system tests with Woodpecker.

**Comment by ivictbor** [comment]
+1

**Comment by 6543** [comment]
https://github.com/woodpecker-ci/woodpecker/pull/934 is ready enouth ... only docu is missing

example:
 - https://ci.codeberg.org/6543/ci-cron-example/build/2/3
 - https://codeberg.org/6543/ci-cron-example/src/branch/main/.woodpecker.yml

![image](https://user-images.githubusercontent.com/24977596/187051996-0816ff06-864a-4928-bd6c-5b6c86f8fea4.png)
