### ISSUE TITLE
live log view: let "auto follow" enable / disable

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#810]
at the moment it's always enabled

**Comment by ADawesomeguy** [comment]
I think this could be implemented with a check box coupled with an empty element at the bottom of the build log that uses [this](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) function and updates either every interval or every time a new line is added.

**Comment by ADawesomeguy** [comment]
Maybe it could be added to the lowest line here? https://github.com/woodpecker-ci/woodpecker/blob/6ae7e2cc4f65edaa6382d4df9cc8f6c968e3d39e/web/src/components/repo/build/BuildLog.vue#L90-L92

**Comment by 6543** [comment]
I think on each time a new line is added with a delay to load segments if it goes fast?

**Comment by 6543** [comment]
cc @lafriks ?

**Comment by lafriks** [comment]
It could be easily added but any ideas where to place it?

**Comment by anbraten** [comment]
I would suggest to use a button similar at the same position as the download button as you will have enable auto follow for running jobs and download for finished jobs. It could just show an image like https://icones.js.org/collection/ic?s=baseline-file-download and the crossed if disabled.

**Comment by lafriks** [comment]
Yes but button should have different icon, this will be too confusing with donwload

**Comment by lafriks** [comment]
@anbraten could not find any better icon so just changed download icon
