### ISSUE TITLE
Add option for pipeline to use custom network

### ISSUE THREAD

**Issue by gbrlsnchs** [woodpecker-ci/woodpecker#813]
### Clear and concise description of the problem

Currently, I'm trying to make Woodpecker work with Gitea, both locally, using Docker Compose.

I've set both server and agent, along with Gitea, to use a custom Docker network under the 10.0.0.0/8 subnet.

The issue lies when running a pipeline: containers from pipelines can't reach that custom network, so they fail when trying to clone the repository from Gitea.

### Suggested solution

In Drone CI, it is possible to set `DRONE_RUNNER_NETWORKS`, so pipelines are able to use custom networks. Woodpecker CI could add an environment variable for that as well.

### Alternative

N/A

### Additional context

Docs for `DRONE_RUNNER_NETWORKS`: https://docs.drone.io/runner/docker/configuration/reference/drone-runner-networks/
The `docker-compose.yml` file for running Gitea and Woodpecker locally: https://codeberg.org/gbrlsnchs/void-pkgs/src/branch/trunk/docker-compose.yml

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by xseman** [comment]
I struggle with the same problem, my motivation to combine these services into one `docker-compose` is to simplify local testing.
As @gbrlsnchs mentioned, the `DRONE_RUNNER_NETWORKS` would be very helpful.

**Comment by anbraten** [comment]
For developing I currently solve this by adding this line to `Exec` in `pipeline/backend/docker/docker.go`:

```go
e.client.NetworkConnect(ctx, "my_custom_network", proc.Name, &network.EndpointSettings{})
```

We could add it as you two wrote by some env variable like: ``WOODPECKER_DOCKER_NETWORKS` to the agent.

**Comment by xseman** [comment]
> For developing I currently solve this by adding this line to `Exec` in `pipeline/backend/docker/docker.go`:
> 
> ```go
> e.client.NetworkConnect(ctx, "my_custom_network", proc.Name, &network.EndpointSettings{})
> ```

Would that inject the network name to runners as well? Thanks!
