### ISSUE TITLE
Change protected repo option to selection

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#819]
It could be quite helpful to change the protected option to be a selection with three options:
- **not protected**: run pipelines directly (same as currently disabled protection)
- **protect against forks**: if a pipeline from a PR of a fork is started wait for approval
- **completely protected**: always ask for approval

Maybe we should also think about renaming the option to something like: trust level, ...

**Comment by gapodo** [comment]
Found this when checking before opening a FR, another nice option would be to be able to allow based on event. In combination with the above would be huge, but event allowing to set protected while still auto running tags (as their protection can come from the forge) would be nice.

* *based on event* allow `<selection of events>` but protect the rest
