### ISSUE TITLE
Add support to trigger pipelines manually

### ISSUE THREAD

**Issue by laszlocph** [woodpecker-ci/woodpecker#83]
# Todo
- add api endpoint
- add button to ui
- add cli command

**Comment by anbraten** [comment]
@amtrack Pinning you at this issue for the manual pipeline execution.

**Comment by amtrack** [comment]
@anbraten I'm confused. Were you possibly trying to mention someone else?

**Comment by anbraten** [comment]
@amtrack Sorry, seem like I mixed sth up when selecting from GIthub suggestion list 🤦🏾

**Comment by anbraten** [comment]
@mrcates Pinning you at this issue for the manual pipeline execution.
