### ISSUE TITLE
Ignore failure in certain steps

### ISSUE THREAD

**Issue by johanvdw** [woodpecker-ci/woodpecker#834]
### Clear and concise description of the problem

For specific steps in our pipeline, we want to allow failure, eg overambitious linting or spellchecks, and still make the whole pipeline successful.
Alternatively we could probably isolate this check in a separate pipeline and have that fail. But for both cases I could not find a solution.

a similar feature in github actions:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error

Looks like it is already supported to run a specific step on failure (or on failure and success), but I'd like my whole pipeline to show up as succesful if this particular step fails
https://github.com/woodpecker-ci/woodpecker/blob/master/pipeline/samples/sample_4/pipeline.yml#L20-L21

### Suggested solution

allow skipping the exitcode of a specific pipeline step:

add an option on-error/on-failure

```
 check precommit:
   image: xxx/venv-3.9
   on-error: ignore
   commands:
     - tox -e pre-commit
```
 looks like drone also has a failure:ignore option

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by anbraten** [comment]
This is the existing feature for single steps: https://woodpecker-ci.org/docs/usage/conditional-execution#status
