### ISSUE TITLE
Agent unable to connect to host - Network issues

### ISSUE THREAD

**Issue by Flying--Dutchman** [woodpecker-ci/woodpecker#841]
### Component

server, agent

### Describe the bug

I'm currently facing an issue which completely blocks my network, as soon as a pipeline runs.
While the pipeline runs, I get ~a lot~ some connection errors to the Woodpecker server container (see log). Also, every other container on my system, and everything running barebone, has network problems while the pipeline runs.

Afterwards calling the build page comes with an error "An unknown error occurred" and an empty build log.

### System Info

```shell
Woodpecker version: 
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-5f2733f4"}
```

### Additional context

```shell
Agent log with connection errors:
{"level":"error","error":"rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp: lookup devops_prod_woodpecker_ci on 127.0.0.11:53: no such host\"","time":"2022-03-17T20:44:27Z","message":"grpc error: done(): code: Unavailable: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp: lookup devops_prod_woodpecker_ci on 127.0.0.11:53: no such host\""}


Further errors in Agent log:
{"level":"error","error":"io: read/write on closed pipe","time":"2022-03-17T20:48:29Z","message":"copy limited logStream part"},
{"level":"error","error":"Error response from daemon: Cannot kill container: 0_1399005776731211175_clone: Container 0e455f7d13d1170c7437cdb82f96e1cf736cc72eff7cd2685f8529e6145781d1 is not running","time":"2022-03-17T20:48:29Z","message":"could not kill container '0_1399005776731211175_clone'"},
{"level":"error","error":"io: read/write on closed pipe","time":"2022-03-17T20:48:44Z","message":"copy limited logStream part"},
{"level":"error","error":"io: read/write on closed pipe","time":"2022-03-17T20:59:20Z","message":"copy limited logStream part"},
{"level":"error","error":"rpc error: code = Unknown desc = Error 1406: Data too long for column 'log_data' at row 1","time":"2022-03-17T20:59:20Z","message":"grpc error: upload(): code: Unknown: rpc error: code = Unknown desc = Error 1406: Data too long for column 'log_data' at row 1"},
{"level":"error","repo":"ORG/REPO","build":"2","id":"3","image":"docker.io/tafilz/xamarin-android:29","stage":"build","error":"rpc error: code = Unknown desc = Error 1406: Data too long for column 'log_data' at row 1","time":"2022-03-17T20:59:20Z","message":"log stream upload error"}


Server log:
{"level":"error","error":"signature is invalid","time":"2022-03-17T20:48:30Z","message":"failure to parse token from hook for ORG/REPO"},
{"level":"warn","error":"sql: no rows in result set","time":"2022-03-17T20:49:05Z"},
{"level":"error","error":"Error #01: sql: no rows in result set\n","ip":"2001:16b8:d28f:ca00:a44:88c6:f3ff:7e61","latency":9.607305,"method":"GET","path":"/api/repos/ORG/REPO/logs/2/3","status":404,"time":"2022-03-17T20:59:23Z","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0","time":"2022-03-17T20:59:23Z"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy).

**Comment by lafleurdeboum** [comment]
Could you mention wether you run woodpecker from a docker compose setup or not ? Anyway, according to your logs, it seems your agent tries to resolve woodpecker server's address : 

    lookup devops_prod_woodpecker_ci on 127.0.0.11:53: no such host

You might need to unset `WOODPECKER_SERVER` in woodpecker-agent conf, to let it fallback to the default (`localhost:9000`).

If you're settting up woodpecker agent on a different machine than the woodpecker server, it's a different story, and you should mention it here.

**Comment by Flying--Dutchman** [comment]
Woodpecker runs, together with gitea, with a compose setup on the same host with a custom docker network, which restarts daily. As it seems the last connection error was on the 25 of May.
The other error messages still appear, an my network is also still slow when running the pipeline.

**Comment by 6543** [comment]
the first issue has a simple answer: the log is to long :X  

since the log is completely stored in DB at the moment, we are bound to the limits of the DBMS or what constrains are set to the content column

**Comment by lafleurdeboum** [comment]
I just noticed I only get the SQL error if I try to jump to a pending job using the right panel in the web interface. Otherwise both the server and agent are silent, and the job stays stuck in queue.

**Comment by Flying--Dutchman** [comment]
> the first issue has a simple answer: the log is to long :X
> 
> since the log is completely stored in DB at the moment, we are bound to the limits of the DBMS or what constrains are set to the content column

Ah, that makes sense. So each log is stored in a single row? Currently not familiar with woodpeckers database scheme, but would it be possible to split the content on multiple rows, if needed? If something like that sounds ok, I would check if I could create a PR somewhere in april.

> Rolling back to [v0.15.0-rc1](https://github.com/woodpecker-ci/woodpecker/releases/tag/v0.15.0-rc1) (version next-150c5e1c) does workaround the issue.
Thank you for the tip. Will try to revert to rc1.

**Comment by Flying--Dutchman** [comment]
Probably an issue with Docker and Plesk. After the latest updates everything works as it should be.
Next server will definitively not have Plesk installed...

**Comment by lafleurdeboum** [comment]
I could not find what you refer to as "latest updates". Could you point to the commits involved ? We're talking about the `master` branch right ?

**Comment by Flying--Dutchman** [comment]
Ah, my bad. I meant updates provided by Plesk for my system.

**Comment by 6543** [comment]
good to hear :heart:
