### ISSUE TITLE
IPv6 connectivity inside docker pipeline containers

### ISSUE THREAD

**Issue by fblaese** [woodpecker-ci/woodpecker#845]
### Clear and concise description of the problem

Currently it seems impossible to get IPv6 connectivity inside containers spawned by woodpecker, as it creates docker networks without IPv6 capability. Even if IPv6 support is configured for docker itself (see https://docs.docker.com/config/daemon/ipv6/), no IPv6 connectivity is available inside containers, because the mentioned settings only affect the dockers default network.

The container-specific network is created here and neither sets `EnableIPv6` to `true`, nor does it specify any IPv6 subnets to configure:
https://github.com/woodpecker-ci/woodpecker/blob/905350fa1573b39a41ba289b4d4e76b7f652df3b/pipeline/frontend/yaml/compiler/compiler.go#L91-L102

There seems to be an undocumented `network_mode` option, which should allows new networks to use the "host"-mode, but this option is understandably only available to trusted repositories (admin users). Also, I have not been able to make this option work; the default network is still created using the bridge driver (see above, probably related to the recent introduction of multiple backends).

### Suggested solution

As docker - for good or for worse - does not support IPv6 NAT (and IPv6 therefore cannot be configured in a similar way to IPv4), I can think of multiple solutions to this problem:
- Add the ability to use already existing docker networks for new containers (via server/agent configuration)
- Add the ability to configure the use of the docker "host" network driver
- Add the ability to configure a pool of IPv6 subnets for the newly spawned docker networks

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by anbraten** [comment]
> Add the ability to use already existing docker networks for new containers (via server/agent configuration)

Would it work for your use case if we could add a second already existing network per agent config?

**Comment by fblaese** [comment]
I am not very familiar with docker, but that might indeed work for my use case. Because only a single IPv6 default route (from the second network) is installed in this case, outbound IPv6 connections should be possible. So as a workaround, this might be feasible.

But going forward, proper IPv6 support will see higher and higher demand, so a solution which is able to provide IPv6 connectivity by default should be preferred in the long term. Sadly, IPv6 connectivity in the context of containerization still is a mess, so engineering this long term solution might not be straightforward.

**Comment by anbraten** [comment]
Problem is I just tried to set `EnableIPv6: true,` on the network the agent is creating per pipeline, but on a standard installation it only shows and users would have to manually set ipv6 prefix even if they currently would only use ipv4:

```
{"level":"error","error":"rpc error: code = Unknown desc = Proc finished with exitcode 1, Error response from daemon: could not find an available, non-overlapping IPv6 address pool among the defaults to assign to the network","time":"2022-03-20T20:13:22+01:00","message":"grpc error: wait(): code: Unknown: rpc error: code = Unknown desc = Proc finished with exitcode 1, Error response from daemon: could not find an available, non-overlapping IPv6 address pool among the defaults to assign to the network"}
```

We could also think about adding a agent env config like `WOODPECKER_DOCKER_ENABLE_IPV6=true`, but this should only be considered if there really is no better way to do things automatically as the plan for Woodpecker is to work out of the box in 99% of the use-cases. 🤔 It somehow is really frustrating how docker is doing iptables and networking like ipv6 in some cases.

**Comment by fblaese** [comment]
Yep, the state of IPv6 support in docker is quite frustrating. Docker does not come with any address pools by default, since it does not implement NAT, NDP Proxy or any kind of Prefix Delegation mechanism for IPv6, but requires subnets to be properly routed. The `default-address-pools` have to be configured with a routeable (or manually NATed) IPv6 prefix.

I have taken a quick look at the Docker Client library, but haven't spotted any way to check if IPv6 subnets are available from any pool. The error returned by the NetworkCreate call also does not allow a sane distinction of this specific error (so woodpecker could retry with `EnableIPv6: false`).

I would also prefer a solution which works out-of-the-box, but it does not look like that is curently a viable option.
