### ISSUE TITLE
Support "Exec runner"

### ISSUE THREAD

**Issue by davidak** [woodpecker-ci/woodpecker#847]
### Clear and concise description of the problem

People miss this feature Drone CI has: https://docs.drone.io/runner/exec/overview/

It allows you to execute a build on a systems default shell, without isolation.

### Suggested solution

A user should be able to add and choose agents for a repo.

### Alternative

People keep using Drone CI.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by anbraten** [comment]
See #709 and #559
We should add some docs explaining the different available backends. I created an issue for that => #849
