### ISSUE TITLE
Add SSH backend

### ISSUE THREAD

**Issue by davidak** [woodpecker-ci/woodpecker#848]
### Clear and concise description of the problem

People miss this feature Drone CI has: https://docs.drone.io/runner/ssh/overview/

It allows you to connect to a system by ssh and execute a build on the default shell, without isolation.

### Suggested solution

A user should be able to add and choose agents for a repo.

### Alternative

People keep using Drone CI.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by anbraten** [comment]
It can probably be implemented quite similar to the existing local backend.
