### ISSUE TITLE
Add changed files env var

### ISSUE THREAD

**Issue by qwerty287** [woodpecker-ci/woodpecker#853]
### Clear and concise description of the problem

There isn't a way to get the changed files of a commit/PR, which would be useful for static code checks so that they don't have to run on all files, only changed ones.

### Suggested solution

Add an environment variable that contains changed files, i.e. the list under the `Changed files` tab. To make it machine-readable, a json-style string could used. For example, [this build](https://ci.woodpecker-ci.org/woodpecker-ci/woodpecker/build/2300) would be:
```json
[".woodpecker/docs.yml"]
```

And an example with more files from a PR, https://ci.woodpecker-ci.org/woodpecker-ci/woodpecker/build/2303:

```json
["web/src/components/repo/build/BuildLog.vue","web/package.json","web/yarn.lock","web/src/components/repo/build/BuildProcList.vue","web/src/compositions/useBuildProc.ts","web/src/views/repo/build/Build.vue","web/src/views/repo/build/BuildWrapper.vue"]
```

### Alternative

I don't know if that's possible, but you could extract the build URL and then request the files from the api (if there's one).

### Additional context

I'm working on a plugin which checks files and I don't want this plugin to check all files of a repo, only changed ones.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by wxiaoguang** [comment]
Maybe another alternative: let `plugin-git` output the changed files into a file in workspace. It could avoid large memory usage if there are a lot of changed files in a big repo.

**Comment by luwol03** [comment]
Why integrating all that into woodpecker? What about a 3rd party plugin like it can be archived with github actions?

**Comment by qwerty287** [comment]
If you refer to [this action](https://github.com/marketplace/actions/get-changed-files), this is what @wxiaoguang is suggesting (`plugin-git` isn't part of woodpecker itself).
For me this option is fine, but it would be probably good to
* not save the file into the repository folder, but another one
* make this have a fixed location in docker containers or just add something like an env var with the file location

**Comment by qwerty287** [comment]
In general, I'd say the plugin approach requires a way to store data outside of the repo itself and then always add this as an extra volume to the  docker containers, and maybe provide an env var likeg `CI_EXTERNAL` that allows to find the directory easily that is used to store data  outside of the repo.
