### ISSUE TITLE
Context of commit statuses is not really "nice"

### ISSUE THREAD

**Issue by qwerty287** [woodpecker-ci/woodpecker#855]
### Clear and concise description of the problem

That's not a big problem, but currently the context is reported as `ci/woodpecker/<event>/<pipeline>`. This doesn't look really nice in UIs.

### Suggested solution

1. just use `Woodpecker CI` as context and put more information into the description
2. Only report the pipeline name and event as context (this is similar to GitHub Actions) and add more information in the description

### Additional context

GitHub Actions example:
![Screenshot_20220328-193038](https://user-images.githubusercontent.com/80460567/160454474-ce133516-94d2-4bb1-bb34-2f4d9fcb8066.png)
Woodpecker example:
![Screenshot_20220328-193115](https://user-images.githubusercontent.com/80460567/160454513-60524a03-55ef-4438-a811-4da3139081a1.png)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by 6543** [comment]
we  can experiment around a bit - but you have to take in mid, that branch protection roules depend on context be be different
so we realy have to look into each forge if there is a potion to split UI view and actual context

**Comment by 6543** [comment]
if we have to change the context - it will be breaking - just to mention
