### ISSUE TITLE
all jobs stall as "pending" in queue since v0.15.0_RC2

### ISSUE THREAD

**Issue by lafleurdeboum** [woodpecker-ci/woodpecker#860]
### Component

server

### Describe the bug

I'm having job running issues with woodpecker v0.15.0. Builds stay stuck into queue ; they display as "not yet started" in the web interface. According to logs, the server is up and the agent seems able to connect to it. The only log I was able to get is when I try and jump to a pending job in the right panel in the web interface. Then the server complains : 
``` json
{"level":"error","error":"Error #01: sql: no rows in result set\n","ip":"192.168.1.1","latency":15.180251,"method":"GET","path":"/api/repos/lafleur/wanderings/logs/19/1","status":404,"time":"2022-04-01T13:34:57Z","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0","time":"2022-04-01T13:34:57Z"}
{"level":"error","error":"Error #01: sql: no rows in result set\n","ip":"::1","latency":14.972052,"method":"GET","path":"/api/repos/lafleur/wanderings/logs/19/1","status":404,"time":"2022-04-01T13:34:57Z","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0","time":"2022-04-01T13:34:57Z"}
```

I'm running on a barebone ARMv7 Arch system, installing through its [PKGBUILD](https://aur.archlinux.org/packages/woodpecker).

I tried rolling back to v0.15.0-rc2. The result is the same, although this time the agent seems unable to connect to the server. Logs from the agent :
``` json
{"level":"error","error":"rpc error: code = Unavailable desc = closing transport due to: connection error: desc = \"error reading from server: EOF\", received prior goaway: code: ENHANCE_YOUR_CALM, debug data: \"too_many_pings\"","time":"2022-04-01T13:47:45Z","message":"grpc error: done(): code: Unavailable: rpc error: code = Unavailable desc = closing transport due to: connection error: desc = \"error reading from server: EOF\", received prior goaway: code: ENHANCE_YOUR_CALM, debug data: \"too_many_pings\""}
```
My RC2 version is `next-c79aa2b1`.

Rolling back to [v0.15.0-rc1](https://github.com/woodpecker-ci/woodpecker/releases/tag/v0.15.0-rc1) (version `next-150c5e1c`) does workaround the issue.

I compared my issue with #841 , and the logs do not match, hence this new issue.

Any clue appreciated !

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-28b15120"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy).

**Comment by anbraten** [comment]
The error you get in the logs is saying: "No logs for this jobs found" which makes sense as it hasn't finished and is also not running.
It could be a problem with executing a step. We have an open PR #817 to improve the error logging of such things, but it hasn't been merged yet

**Comment by lafleurdeboum** [comment]
I see. I tried and turn logging to the trace level to see if I could discover a runtime error. Nothing special there, the agent saying
``` json
{"level":"debug","time":"2022-04-01T21:24:33Z","message":"loaded docker backend engine"}
{"level":"debug","time":"2022-04-01T21:24:33Z","message":"request next execution"}
```
and the server answering
``` json
{"level":"debug","time":"2022-04-01T21:24:33Z","caller":"github.com/woodpecker-ci/woodpecker/server/grpc/rpc.go:63","message":"agent connected: noe.presentmatter.one: polling"}
{"level":"debug","time":"2022-04-01T21:24:33Z","caller":"github.com/woodpecker-ci/woodpecker/server/queue/fifo.go:321","message":"queue: pending right now: 526"}
{"level":"debug","time":"2022-04-01T21:24:33Z","caller":"github.com/woodpecker-ci/woodpecker/server/queue/fifo.go:293","message":"queue: trying to assign task: 526 with deps []"}
```
then, later, agent :
``` json
{"level":"trace","error":"rpc error: code = Unavailable desc = closing transport due to: connection error: desc = \"error reading from server: EOF\", received prior goaway: code: ENHANCE_YOUR_CALM, debug data: \"too_many_pings\"","time":"2022-04-01T21:25:13Z","message":"grpc: to many keepalive pings without sending data"}
```
and then server : 
``` json
{"level":"debug","time":"2022-04-01T21:25:14Z","caller":"github.com/woodpecker-ci/woodpecker/server/grpc/rpc.go:63","message":"agent connected: noe.presentmatter.one: polling"}
{"level":"debug","time":"2022-04-01T21:25:14Z","caller":"github.com/woodpecker-ci/woodpecker/server/queue/fifo.go:321","message":"queue: pending right now: 526"}
{"level":"debug","time":"2022-04-01T21:25:14Z","caller":"github.com/woodpecker-ci/woodpecker/server/queue/fifo.go:293","message":"queue: trying to assign task: 526 with deps []"}
```

So the server goes as far as _intending_ to assign the task, supposedly to the agent, but the agent never reacts.

**Comment by lafleurdeboum** [comment]
@anbraten I tried with a dead-simple CI def in an empty project, to see if it was getting stuck as well : 
``` yaml
pipeline:
  build:
    image: alpine
    commands:
      - pwd
      - ls
      - env
```
It does get stuck as pending as well. I thought maybe it was related to podman being installed and interfering somehow (the new PKGBUILD mentions podman support), so I ditched it, keeping only docker, and restarted the build with the web UI. Same fate.

Just to mention, I use the `woodpecker.conf` and `woodpecker-agent.conf` I had for RC1 when trying with the new release. RC1 does succeed in building my sample CI def.

Am I the only one in this situation recently ? I'll cross-link to this issue on the AUR to see if Arch users report it as well.

**Comment by relnod** [comment]
I also ran into this issue, with the server and agent running on `arm64` with docker using `v0.15.1-alpine`. Is there a recommended way to debug the issue further?

**Comment by lafleurdeboum** [comment]
I suspect the issue i run into is specific to armv7. I ran the CI script I mentioned on an amd64 platform machine and it succeeded. I think I used precisely the alpine docker image for v0.15.1.

@relnod have you run Woodpecker with debug logs turned on ? Do the logs say that agent and server were connected before launching the CI script ?

Le May 6, 2022 1:29:59 PM UTC, relnod ***@***.***> a écrit :

**Comment by 6543** [comment]
if it's an arm only issue, it will be hard to debug by me atm :/

**Comment by anbraten** [comment]
It could be related to the arch we set for the pipeline and the arch which is set for the agent. If I am correct the arch for the agent is auto detected, but the pipeline arch is currently hard-coded to `linux/amd64` in https://github.com/woodpecker-ci/woodpecker/blob/905350fa1573b39a41ba289b4d4e76b7f652df3b/server/shared/procBuilder.go#L371

**Comment by RensOliemans** [comment]
Thanks for fixing this! If it isn't clear for all, you have to use `next` instead of `v0.15.3` (see https://github.com/woodpecker-ci/woodpecker/pull/902#issuecomment-1204309716)
