### ISSUE TITLE
Use rsa for http signing

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#865]
Using rsa for http would allow us to keep the secret secret :wink:
This will be especially helpful when allowing more extensions in addition to the current configuration service to be settable per repo.
The current lib used for signing doesn't support that but we could try https://github.com/go-fed/httpsig

**Comment by mscherer** [comment]
The [current lib](https://github.com/99designs/httpsignatures-go) seems not maintained (last commit in 2017), but the [new one](https://github.com/go-fed/httpsig) seems also not moving a lot (last commit 1 year ago). But that's indeed better.
