### ISSUE TITLE
Erroneous env var definition in the woodpecker agent Helm chart

### ISSUE THREAD

**Issue by izeau** [woodpecker-ci/woodpecker#866]
### Component

agent

### Describe the bug

In `charts/woodpecker-agent/values.yaml`, `dind.env` variables [are defined](https://github.com/woodpecker-ci/woodpecker/blob/c310363c99d5b1422a9abfeba1a74d8b520a50a0/charts/woodpecker-agent/values.yaml#L12-L14) using a list of `{name,value}` objects. However, the template defined in `woodpecker-agent/templates/deployment.yaml` expects `dind.env` to be a key-value map instead.

This results in the following error when trying to install the chart:

```
Error: INSTALLATION FAILED: Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.SecurityContext: Resources: Name: Image: Env: []v1.EnvVar: v1.EnvVar.Value: Name: ReadString: expects " or n, but found 0, error found in #10 byte of ...|[{"name":0,"value":"|..., bigger context ...|:"/var/run","name":"sock-dir"}]},{"env":[{"name":0,"value":"map[name:DOCKER_DRIVER value:overlay2]"}|...
```

This may be fixed by specifying the default values as a key-value map ([the way the `env` value is defined](https://github.com/woodpecker-ci/woodpecker/blob/c310363c99d5b1422a9abfeba1a74d8b520a50a0/charts/woodpecker-agent/values.yaml#L17-L18)) instead:

```yaml
dind:
  env:
    DOCKER_DRIVER: overlay2
```

I can provide the patch :)

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"0.15.0"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy).

**Comment by IDerr** [comment]
Same issue on my side, add the env to my values fixes the issue, thanks @izeau

**Comment by izeau** [comment]
Thanks!
