### ISSUE TITLE
can we support multi SCM providers at the same time

### ISSUE THREAD

**Issue by xuecanlong** [woodpecker-ci/woodpecker#867]
### Clear and concise description of the problem

can we support multi SCM providers at the same time?  can you support github and gitlab at one server?

### Suggested solution

maybe save the user SCM info into database, and add multi button at web ui login page?

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by anbraten** [comment]
duplicate of #138

**Comment by xuecanlong** [comment]
> duplicate of #138

or, so sorry, will close this and sub the #138
