### ISSUE TITLE
Option to overwrite forge host address

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#891]
If you have different addresses for the user and the internal requests:
 - user access woodpecker and forge via reverse proxy but woodpecker and visa versa talk in private net directly to each other

**Comment by anbraten** [comment]
linking https://github.com/woodpecker-ci/woodpecker/pull/586

**Comment by coredotbin** [comment]
> linking https://github.com/woodpecker-ci/woodpecker/pull/586 `WOODPECKER_DEV_OAUTH_HOST`

I'm trying to understand.. Does this PR provide the requested feature?

**Comment by anbraten** [comment]
should be fixed by #3670
