### ISSUE TITLE
Improve status messages for protected pipelines

### ISSUE THREAD

**Issue by qwerty287** [woodpecker-ci/woodpecker#895]
### Clear and concise description of the problem

Currently, the status sent back to the forge looks like this:

|state|status|message|
|---|---|---|
|pipeline waits for approval|pending|`Pipeline is pending`|
|pipeline is declined|pending|`Pipeline is pending`|

### Suggested solution

It should look like:

|state|status|message|
|---|---|---|
|pipeline waits for approval|pending|`Pipeline waits for approval`|
|pipeline is declined|failed|`Pipeline was declined`|

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by xoxys** [comment]
> pipeline is declined 	failed 	Pipeline was declined

Isn't there a `canceled` state? I would use this for declined pipelines instead of `failed`.
