### ISSUE TITLE
Add Kubernetes backend

### ISSUE THREAD

**Issue by laszlocph** [woodpecker-ci/woodpecker#9]
Add Kubernetes as a backend to Woodpecker to allow running pipelines via the Kubernetes API in a Kubernetes Cluster.

**Comment by laszlocph** [comment]
Work started here: https://github.com/laszlocph/drone-oss-08/compare/kube?expand=1

- [x] Basic pipeline support
- [ ] Proper service support
- [x] Integrate it to drone-server
- [x] RWX volume support with `storageclasses`
- [ ] Deploy it and run builds for 10 repos with it for 2 weeks

**Comment by er1z** [comment]
Any news?

**Comment by 6543** [comment]
> Any news?

https://github.com/woodpecker-ci/woodpecker/pull/552
