### ISSUE TITLE
[CLI] Get repos from git remotes

### ISSUE THREAD

**Issue by qwerty287** [woodpecker-ci/woodpecker#910]
### Clear and concise description of the problem

Instead of having  to add the repo as arguments to every repo-related command, it would be nice if the CLI could determine the repo itself using the git remotes.

### Suggested solution

See above.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by anbraten** [comment]
Do you have something like and autodetect in mind which uses the git remote and searches the woodpecker db by that to know which project you are in?
