### ISSUE TITLE
Warn users for bad-habits and deprecations in configs

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#922]
I think woodpecker should ignore errors etc while `cli lint` should warn you if your config do have strange things ...
- conditions that will never be true
- filters that will never apply (event: tag & branch: main -> branch is ignored in all cases)
- ...

_Originally posted by @6543 in https://github.com/woodpecker-ci/woodpecker/issues/921#issuecomment-1129009258_

**Comment by anbraten** [comment]
Yeah we really need to give some love to the cli especially the lint and exec commands. 

In general I would prefer to be as strict as possible with linting via cli and the server itself and at least be equal in both systems as that solves a lot of headache especially to new users like why is it throwing an error / showing a warning in the cli, but the server doesn't even care about it ...

**Comment by x80486** [comment]
There could be also a UI to accomplish this. A user just paste the pipeline definition and it will tell if there is anything wrong. In subsequent releases could be polished to say exactly where the problem is — if not supported by the CLI.
