### ISSUE TITLE
Pipelines are skipped where they should not

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#931]
#877 did introduce an regression (I did also not notice while reviewing :/ ) 

WP only exec 1 pipeline but should do 2

## Before
https://ci.woodpecker-ci.org/woodpecker-ci/woodpecker/build/2558
## Now :/
https://ci.woodpecker-ci.org/woodpecker-ci/woodpecker/build/2563

**Comment by anbraten** [comment]
Stange its not working for the push event? Skip pipeline shouldn't be touching push at all as it is only enabled for PR in our setup ...

**Comment by 6543** [comment]
closed by e2e094cfda87becedf7a37d6077fabea2c97ebb5 ...  - lets move on at #932 to make it work
