### ISSUE TITLE
Allow to restart declined pipeline

### ISSUE THREAD

**Issue by qwerty287** [woodpecker-ci/woodpecker#935]
### Clear and concise description of the problem

You can't start a pipeline once it's declined.

### Suggested solution

Show the restart button for declined pipelines to allow to start a declined pipeline later.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by 6543** [comment]
duplicate of #300
