### ISSUE TITLE
Tag filter in when is not working

### ISSUE THREAD

**Issue by jeanmichelfischer** [woodpecker-ci/woodpecker#945]
### Component

agent

### Describe the bug

The docs say: https://woodpecker-ci.org/docs/usage/pipeline-syntax#tag

but the filter in a condition is not working for tags:

```
    when:
      event: tag
      tag: v*
```
The step with this condition is executed, even when the tag name is something different e.g. 'x' or 'pre1.2.3'

How to use this feature? 

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"0.15.1"}
```

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy).

**Comment by dvjn** [comment]
I am facing the same issue, the tag glob filter is not working. When event is set to tag, the pipeline always runs.

**Comment by 6543** [comment]
@dvjn that's a `next` feature
