### ISSUE TITLE
Pull default images on agent start

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#947]
to make sure on agent restart to also have the newest default images, we should pull them.

https://github.com/woodpecker-ci/woodpecker/blob/master/shared/constant/constant.go

**Comment by anbraten** [comment]
I would suggest to simply pin the image with its proper version. That way a new (not exiting) git image would just be pulled. Pulling the image on the agent would be quite backend specific (for example that would not work for kubernetes).
