### ISSUE TITLE
Rename build to pipeline in bagde

### ISSUE THREAD

**Issue by x80486** [woodpecker-ci/woodpecker#955]
### Clear and concise description of the problem

This one falls into a very gray area, but I think the `build | status` badge could be more generic and be presented as `pipeline | status`, because `build` is a targeted process within the entire pipeline — if present.

Some pipelines don't have a "build" process, but like I said, it's a grays area, because the word can be used to describe the entire process as well.

### Suggested solution

Badge should be `pipeline | status`.

### Alternative

N/A

### Additional context

N/A

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by anbraten** [comment]
I am a fan of the term pipeline instead of build as well. My plan would be to get rid of the build term completely at some point. 

See https://github.com/woodpecker-ci/woodpecker/pull/949#discussion_r888615393 and https://github.com/woodpecker-ci/woodpecker/issues/745

**Comment by anbraten** [comment]
We can leave it open. Could you create a pull-request to change the naming. Its just the following four lines: https://github.com/woodpecker-ci/woodpecker/blob/master/server/badges/badges.go#L20-L24
