### ISSUE TITLE
Exclude condition for tag pattern

### ISSUE THREAD

**Issue by s00500** [woodpecker-ci/woodpecker#961]
### Clear and concise description of the problem

I am trying to setup a pipeline with several steps, the last two should fire depending on the tag

if the tag follows the pattern vX.X.X i want to execute step A
If the tag follows vX.X.X-preXX i want to execute step B

How can I set this up ? 

Yet another issue I ran into was: How can I make a whole pipeline only run on tags ? and disable pushes ?
Currently I have a event condition on all steps, but it will still trigger the clone step everytime, also it is kinda not elegant to have this condition on all steps, I would prefer a global condition like the one for branches

am I missing something or is this a little more complicated ?

### Suggested solution

When we find  a solution I would update the docs with an example, I think this usecase is not uncommon

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by anbraten** [comment]
The matching of a tag as you describe it should work for a step like that. I think it is a bug.

The filtering on a global level is planned and there is already a PR for it #770. Having just the clone step for empty pipeline is somehow a bug which will be resolved by #932

**Comment by s00500** [comment]
ok, what kind of glob pattern do I need to use in this case ? or it it possible to make exclude and include distictions there ?

I tried this:


    when:
      event: tag
      tag: "*(!-pre)*"
      
      
      and this:
      
     when:
      event: tag
      tag: 
        exclude: "*-pre*"

**Comment by s00500** [comment]
Ok so I found a way to make this work for me now, although it is undocumented and I found out about it by playing the tests in constraint_test.go...

```
    when:
      event: tag
      ref: 
        include: "refs/tags/*-pre*"
```

I can correctly use this with include and exclude

**Comment by anbraten** [comment]
#1213 could help here as well

**Comment by 6543** [comment]
implement via https://github.com/woodpecker-ci/woodpecker/pull/1213 and other condition filters ...
