### ISSUE TITLE
Documentation specifies 'run_on' when it should use 'runs_on'

### ISSUE THREAD

**Issue by fracai** [woodpecker-ci/woodpecker#964]
### Component

other

### Describe the bug

The multi-pipeline [documentation](https://woodpecker-ci.org/docs/usage/multi-pipeline#flow-control) says `run_on` can be used to allow a pipeline to run even if a dependent pipeline has failed:
~~~~
pipeline:
  task2:
    ...
depends_on:
  - task1
run_on: [ success, failure ]
~~~~
While testing this I discovered that the tag is actually `runs_on`.

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"0.15.1"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by fracai** [comment]
I forgot to include a link to the repo where I tested this.

https://github.com/fracai/woodpecker-test

**Comment by 6543** [comment]
thanks for finding this docu bug :+1:
