### ISSUE TITLE
Synchronize status between active view, the right pane, and the top (navigation) bar

### ISSUE THREAD

**Issue by x80486** [woodpecker-ci/woodpecker#971]
### Component

web-ui

### Describe the bug

When a pipeline is triggered, if I browse over the view/screen where the steps are displayed, when the pipeline finishes, the interface "gives the impression" the pipeline is still in progress based on some indicators, specifically, there will still be a section with the `user/repository` (with the blue two-dots animation) and the circle in the top (navigation) bar.

Notice that when it finishes, a section with the `user/repository` is created as well right before the top one with the correct "finished" status.

So it's just a matter of synchronizing some elements and hiding/removing them from the DOM — my guess :thinking:

### System Info

```shell
Codeberg's Woodpecker CI
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by anbraten** [comment]
This is a problem related to the pub-sub system sending kinda "special" events to the UI.
