### ISSUE TITLE
Add linter for editorconfig

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#973]

**Comment by anbraten** [comment]
We actually have a linter / tests for the editorconfig already or do you mean adding it to the linter which checks a config before the pipeline executes it?

**Comment by 6543** [comment]
well i found a wrong intendation:

https://github.com/woodpecker-ci/woodpecker/blob/fe006d9656309cab84c6059f7648ba2c6ee1ca30/.woodpecker/docs.yml#L56-L57

**Comment by 6543** [comment]
```yml
  editor-config:
    image: mstruebing/editorconfig-checker
```
adding this step should do it

**Comment by 6543** [comment]
to exclude stuff create file `.ecrc`

```
{
  "Exclude": ["LICENSE", ".git*"]
}
```
