### ISSUE TITLE
Use UUID for Steps

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#983]
9449b67da9a824747eed2ac860f2f85411937219 do show that we should not rely on a name to identify containers

(https://ci.woodpecker-ci.org/woodpecker-ci/woodpecker/build/2736/8)  
-> `Error response from daemon: Conflict. The container name "/pipeline.build-web" is already in use by container "8b762354d71226969e0b4f87f5244b93c0d0c092fd004362b5d71def5fd63ddc". You have to remove (or rename) that container to be able to reuse that name.`

**Comment by 6543** [comment]
cc @LamaAni

**Comment by LamaAni** [comment]
The new name will be `to_kube_valid(name+'-'s'+[step index])`

**Comment by LamaAni** [comment]
Hum. I dont see the same issue in kubectl... The Specific random run_id I add there resolves this issue. Did you run this in docker?

**Comment by 6543** [comment]
yes

**Comment by 6543** [comment]
I think the run_id is not within the docker backend ...

**Comment by LamaAni** [comment]
Hi, The run_id is not within it. That is way I needed the random number on my executor. 

Which branch lead to the error in the run_id? Did you check if this exists on the original docker backed? I would assume so.

**Comment by 6543** [comment]
-> #1802
